insert into kino (ime, kraj) values ('Fairview', 'Pāvilosta');
insert into kino (ime, kraj) values ('Heffernan', 'Zhongzuiling');
insert into kino (ime, kraj) values ('Kingsford', 'Esperanza');
insert into kino (ime, kraj) values ('Lakeland', 'Saurama');
insert into kino (ime, kraj) values ('Dovetail', 'Ji’an');
insert into kino (ime, kraj) values ('Center', 'Dziergowice');
insert into kino (ime, kraj) values ('Old Shore', 'Nankeng');
insert into kino (ime, kraj) values ('Briar Crest', 'Chvalšiny');
insert into kino (ime, kraj) values ('Texas', 'Pa Tio');
insert into kino (ime, kraj) values ('Johnson', 'La Soledad');
insert into kino (ime, kraj) values ('Barnett', 'Téra');
insert into kino (ime, kraj) values ('Hollow Ridge', 'Kadyy');
insert into kino (ime, kraj) values ('Columbus', 'Tanahmerah');
insert into kino (ime, kraj) values ('Stuart', 'Chisec');
insert into kino (ime, kraj) values ('Shasta', 'Cigagade');
insert into kino (ime, kraj) values ('Esker', 'Xuebu');
insert into kino (ime, kraj) values ('La Follette', 'Vlachovo Březí');
insert into kino (ime, kraj) values ('Waxwing', 'Lopar');
insert into kino (ime, kraj) values ('Fairview', 'Nortelândia');
insert into kino (ime, kraj) values ('Doe Crossing', 'Kishiwada');
insert into kino (ime, kraj) values ('Moose', 'Petauke');
insert into kino (ime, kraj) values ('Surrey', 'El Alamo');
insert into kino (ime, kraj) values ('2nd', 'Goričan');
insert into kino (ime, kraj) values ('Almo', 'Mar’’ina Horka');
insert into kino (ime, kraj) values ('Hoffman', 'Vera Cruz');
insert into kino (ime, kraj) values ('Cordelia', 'Rîbniţa');
insert into kino (ime, kraj) values ('Merrick', 'Bhātpāra Abhaynagar');
insert into kino (ime, kraj) values ('Crescent Oaks', 'Sochi');
insert into kino (ime, kraj) values ('Union', 'Trnovlje pri Celju');
insert into kino (ime, kraj) values ('Forest Dale', 'San Antonio de Los Altos');
insert into kino (ime, kraj) values ('Orin', 'Delong');
insert into kino (ime, kraj) values ('Northridge', 'Rozhdestveno');
insert into kino (ime, kraj) values ('Service', 'Nàng Mau');
insert into kino (ime, kraj) values ('1st', 'Esposende');
insert into kino (ime, kraj) values ('Buena Vista', 'Hudai');
insert into kino (ime, kraj) values ('Blackbird', 'Gobabis');
insert into kino (ime, kraj) values ('Grim', 'Ōtawara');
insert into kino (ime, kraj) values ('Rowland', 'Kolobovo');
insert into kino (ime, kraj) values ('Del Sol', 'Nanzamu');
insert into kino (ime, kraj) values ('Walton', 'Ribeira do Pombal');
insert into kino (ime, kraj) values ('Maywood', 'Akhtopol');
insert into kino (ime, kraj) values ('Cherokee', 'Denton');
insert into kino (ime, kraj) values ('Oneill', 'Fengshan');
insert into kino (ime, kraj) values ('Burning Wood', 'Guoxiang');
insert into kino (ime, kraj) values ('Miller', 'San Jose');
insert into kino (ime, kraj) values ('Hagan', 'Alderetes');
insert into kino (ime, kraj) values ('Fairfield', 'Atlanta');
insert into kino (ime, kraj) values ('Hazelcrest', 'Podgornoye');
insert into kino (ime, kraj) values ('Chinook', 'Nanshi');
insert into kino (ime, kraj) values ('Sutteridge', 'Drochia');
insert into kino (ime, kraj) values ('Londonderry', 'Tiantang');
insert into kino (ime, kraj) values ('Corben', 'Valmiera');
insert into kino (ime, kraj) values ('Butternut', 'Rîbniţa');
insert into kino (ime, kraj) values ('Kinsman', 'Al Judayrah');
insert into kino (ime, kraj) values ('Sunnyside', 'Dindima');
insert into kino (ime, kraj) values ('Lakeland', 'Daitōchō');
insert into kino (ime, kraj) values ('Lawn', 'Cap Malheureux');
insert into kino (ime, kraj) values ('Arizona', 'Luodian');
insert into kino (ime, kraj) values ('Parkside', 'Gunung');
insert into kino (ime, kraj) values ('Sycamore', 'Vales');
insert into kino (ime, kraj) values ('Milwaukee', 'Bayside');
insert into kino (ime, kraj) values ('Surrey', 'Zhoujiaba');
insert into kino (ime, kraj) values ('Thompson', 'Cuijiamatou');
insert into kino (ime, kraj) values ('Ronald Regan', 'Jinhaihu');
insert into kino (ime, kraj) values ('Melvin', 'Cangzhou');
insert into kino (ime, kraj) values ('Kinsman', 'Huayuan');
insert into kino (ime, kraj) values ('Fallview', 'Pakis');
insert into kino (ime, kraj) values ('Springs', 'Vũ Quang');
insert into kino (ime, kraj) values ('Redwing', 'Santa Cruz');
insert into kino (ime, kraj) values ('Bultman', 'El Paso');
insert into kino (ime, kraj) values ('Hollow Ridge', 'Ciomas');
insert into kino (ime, kraj) values ('Rutledge', 'Sobreda');
insert into kino (ime, kraj) values ('Fairview', 'Jōetsu');
insert into kino (ime, kraj) values ('Red Cloud', 'Concepcion');
insert into kino (ime, kraj) values ('Twin Pines', 'Houston');
insert into kino (ime, kraj) values ('Green', 'Šentvid pri Stični');
insert into kino (ime, kraj) values ('Pine View', 'Obollo-Afor');
insert into kino (ime, kraj) values ('Towne', 'Nizhniy Kurkuzhin');
insert into kino (ime, kraj) values ('Golf', 'Malakand');
insert into kino (ime, kraj) values ('Lighthouse Bay', 'Xinmatou');
insert into kino (ime, kraj) values ('Trailsway', 'Bailizhou');
insert into kino (ime, kraj) values ('Comanche', 'Kopen');
insert into kino (ime, kraj) values ('Moland', 'Calvos');
insert into kino (ime, kraj) values ('Donald', 'Mikhaylovsk');
insert into kino (ime, kraj) values ('Clemons', 'Vysočany');
insert into kino (ime, kraj) values ('Homewood', 'Traganón');
insert into kino (ime, kraj) values ('Grasskamp', 'Fasito‘outa');
insert into kino (ime, kraj) values ('Glacier Hill', 'Miracema');
insert into kino (ime, kraj) values ('7th', 'Komsomolets');
insert into kino (ime, kraj) values ('Jenna', 'San Carlos');
insert into kino (ime, kraj) values ('Fulton', 'Mohelno');
insert into kino (ime, kraj) values ('Cambridge', 'Santa Rosa');
insert into kino (ime, kraj) values ('Loomis', 'Nurlat');
insert into kino (ime, kraj) values ('Stoughton', 'San Fernando del Valle de Catamarca');
insert into kino (ime, kraj) values ('Hoepker', 'Moutsamoudou');
insert into kino (ime, kraj) values ('Golf', 'Rouen');
insert into kino (ime, kraj) values ('Thompson', 'Ambato');
insert into kino (ime, kraj) values ('Anthes', 'Boyarka');
insert into kino (ime, kraj) values ('Dawn', 'Williston');
insert into kino (ime, kraj) values ('Messerschmidt', 'Waturoka');
insert into kino (ime, kraj) values ('Sutteridge', 'Jiancheng');
insert into kino (ime, kraj) values ('Green', 'Karangsari');
insert into kino (ime, kraj) values ('Burning Wood', 'Sūrak');
insert into kino (ime, kraj) values ('Hanover', 'Halmstad');
insert into kino (ime, kraj) values ('Logan', 'Mādārīpur');
insert into kino (ime, kraj) values ('Hauk', 'Jõhvi');
insert into kino (ime, kraj) values ('Garrison', 'São Jerônimo');
insert into kino (ime, kraj) values ('Anniversary', 'Llano Largo');
insert into kino (ime, kraj) values ('Weeping Birch', 'Lebak');
insert into kino (ime, kraj) values ('Oak', 'San Francisco');
insert into kino (ime, kraj) values ('Rusk', 'Krosno Odrzańskie');
insert into kino (ime, kraj) values ('Sunfield', 'Meijiahe');
insert into kino (ime, kraj) values ('Monument', 'Vientiane');
insert into kino (ime, kraj) values ('Ilene', 'Zheleznodorozhnyy');
insert into kino (ime, kraj) values ('Jenna', '28 de Noviembre');
insert into kino (ime, kraj) values ('Bellgrove', 'Ekibastuz');
insert into kino (ime, kraj) values ('Moland', 'Frankfurt am Main');
insert into kino (ime, kraj) values ('Blackbird', 'Oslo');
insert into kino (ime, kraj) values ('Autumn Leaf', 'Vitry-le-François');
insert into kino (ime, kraj) values ('Sutherland', 'Timbó');
insert into kino (ime, kraj) values ('Prentice', 'Gaohe');
insert into kino (ime, kraj) values ('Dixon', 'Las Vegas');
insert into kino (ime, kraj) values ('Iowa', 'Tianshan');
insert into kino (ime, kraj) values ('International', 'Ariguaní');
insert into kino (ime, kraj) values ('Gale', 'Loughrea');
insert into kino (ime, kraj) values ('Erie', 'Il’skiy');
insert into kino (ime, kraj) values ('Ludington', 'Hadyach');
insert into kino (ime, kraj) values ('Debs', 'Mikhaylovskoye');
insert into kino (ime, kraj) values ('Pennsylvania', 'Hepu');
insert into kino (ime, kraj) values ('Derek', 'João Pinheiro');
insert into kino (ime, kraj) values ('5th', 'Chahe');
insert into kino (ime, kraj) values ('Merry', 'Chum Phae');
insert into kino (ime, kraj) values ('International', 'Cana Chapetón');
insert into kino (ime, kraj) values ('Logan', 'Kuala Lumpur');
insert into kino (ime, kraj) values ('Maple Wood', 'Nangang');
insert into kino (ime, kraj) values ('Old Gate', 'Vsevolozhsk');
insert into kino (ime, kraj) values ('Fordem', 'Avignon');
insert into kino (ime, kraj) values ('Kensington', 'Izhmorskiy');
insert into kino (ime, kraj) values ('Kennedy', 'Aqtoghay');
insert into kino (ime, kraj) values ('Mccormick', 'Saint-Quentin');
insert into kino (ime, kraj) values ('Stang', 'Al Muwayh');
insert into kino (ime, kraj) values ('Karstens', 'Tulungrejo');
insert into kino (ime, kraj) values ('Waywood', 'Budapest');
insert into kino (ime, kraj) values ('Surrey', 'Yunfu');
insert into kino (ime, kraj) values ('Oak Valley', 'Stockholm');
insert into kino (ime, kraj) values ('Norway Maple', 'Walichnowy');
insert into kino (ime, kraj) values ('Autumn Leaf', 'Shangcunba');
insert into kino (ime, kraj) values ('Kinsman', 'Kaizuka');
insert into kino (ime, kraj) values ('Hermina', 'Drajak');
insert into kino (ime, kraj) values ('Atwood', 'Granada');
insert into kino (ime, kraj) values ('Gale', 'Shuikou');
insert into kino (ime, kraj) values ('Fairfield', 'Araouane');
insert into kino (ime, kraj) values ('Vidon', 'Treinta y Tres');
insert into kino (ime, kraj) values ('Grover', 'Bar');
insert into kino (ime, kraj) values ('Montana', 'Hexi');
insert into kino (ime, kraj) values ('Bultman', 'Bunobogu');
insert into kino (ime, kraj) values ('Weeping Birch', 'Xinxu');
insert into kino (ime, kraj) values ('Arapahoe', 'Digne-les-Bains');
insert into kino (ime, kraj) values ('Paget', 'Linshui');
insert into kino (ime, kraj) values ('Pond', 'Sydney');
insert into kino (ime, kraj) values ('Magdeline', 'Buenaventura');
insert into kino (ime, kraj) values ('Blackbird', 'Tuchlovice');
insert into kino (ime, kraj) values ('Elgar', 'Kesugihan');
insert into kino (ime, kraj) values ('Bunting', 'Pumaqangtang');
insert into kino (ime, kraj) values ('Delladonna', 'Tubuhue');
insert into kino (ime, kraj) values ('Oak', 'Santyoku');
insert into kino (ime, kraj) values ('Oak', 'Cabaiguán');
insert into kino (ime, kraj) values ('Clove', 'Ershilipu');
insert into kino (ime, kraj) values ('Rutledge', 'Daraitan');
insert into kino (ime, kraj) values ('Green Ridge', 'San José');
insert into kino (ime, kraj) values ('Lyons', 'Petro-Slavyanka');
insert into kino (ime, kraj) values ('Meadow Ridge', 'Shangying');
insert into kino (ime, kraj) values ('Monica', 'Zürich');
insert into kino (ime, kraj) values ('Warner', 'Muqi');
insert into kino (ime, kraj) values ('Thompson', 'Guangli');
insert into kino (ime, kraj) values ('Mariners Cove', 'Halinów');
insert into kino (ime, kraj) values ('Bashford', 'Klippan');
insert into kino (ime, kraj) values ('Arizona', 'Dashi');
insert into kino (ime, kraj) values ('Clemons', 'Nîmes');
insert into kino (ime, kraj) values ('Swallow', 'Višňové');
insert into kino (ime, kraj) values ('Sunbrook', 'Monastyryshche');
insert into kino (ime, kraj) values ('Thompson', 'Tartouss');
insert into kino (ime, kraj) values ('Kennedy', 'Qinggang');
insert into kino (ime, kraj) values ('Nova', 'Chōfugaoka');
insert into kino (ime, kraj) values ('Delaware', 'Bangbayang');
insert into kino (ime, kraj) values ('Veith', 'Lashkar Gāh');
insert into kino (ime, kraj) values ('Buena Vista', 'Alivéri');
insert into kino (ime, kraj) values ('Dwight', 'Turku');
insert into kino (ime, kraj) values ('Scott', 'Shujāābād');
insert into kino (ime, kraj) values ('Londonderry', 'Aeka');
insert into kino (ime, kraj) values ('Glendale', 'Mongar');
insert into kino (ime, kraj) values ('Chinook', 'Aytos');
insert into kino (ime, kraj) values ('Rigney', 'Chenārān');
insert into kino (ime, kraj) values ('Westridge', 'Ambarakaraka');
insert into kino (ime, kraj) values ('Gateway', 'Gelap');
insert into kino (ime, kraj) values ('Rutledge', 'Zapod');
insert into kino (ime, kraj) values ('Fallview', 'Shahkot');
insert into kino (ime, kraj) values ('Coolidge', 'Mantes-la-Jolie');
insert into kino (ime, kraj) values ('Shopko', 'Novoye Leushino');
insert into kino (ime, kraj) values ('Arrowood', '‘Attīl');
insert into kino (ime, kraj) values ('Beilfuss', 'Bojong');
insert into kino (ime, kraj) values ('Corscot', 'Tetebatu');
insert into kino (ime, kraj) values ('Carey', 'Ngarus');
insert into kino (ime, kraj) values ('Parkside', 'Nechanice');
insert into kino (ime, kraj) values ('Marcy', 'Lycksele');
insert into kino (ime, kraj) values ('6th', 'El Benque');
insert into kino (ime, kraj) values ('Jana', 'Sagarejo');
insert into kino (ime, kraj) values ('Kinsman', 'Cibinong Satu');
insert into kino (ime, kraj) values ('Glendale', 'Paris 12');
insert into kino (ime, kraj) values ('Macpherson', 'Soio');
insert into kino (ime, kraj) values ('Ryan', 'Songlong');
insert into kino (ime, kraj) values ('Banding', 'Binglincha');
insert into kino (ime, kraj) values ('Surrey', 'Charat');
insert into kino (ime, kraj) values ('Fair Oaks', 'Montréal-Ouest');
insert into kino (ime, kraj) values ('Duke', 'Al Matlīn');
insert into kino (ime, kraj) values ('Myrtle', 'Moose Jaw');
insert into kino (ime, kraj) values ('Tennessee', 'Chefchaouene');
insert into kino (ime, kraj) values ('Lakeland', 'Arco de Baúlhe');
insert into kino (ime, kraj) values ('Di Loreto', 'Figueiras');
insert into kino (ime, kraj) values ('Dayton', 'Shtip');
insert into kino (ime, kraj) values ('Vernon', 'Timrat');
insert into kino (ime, kraj) values ('Arapahoe', 'Zhoutou');
insert into kino (ime, kraj) values ('Golf View', 'Lobatse');
insert into kino (ime, kraj) values ('Welch', 'Talā');
insert into kino (ime, kraj) values ('Farmco', 'Sangkulirang');
insert into kino (ime, kraj) values ('Loeprich', 'Tunzhai');
insert into kino (ime, kraj) values ('Carpenter', 'Hangzhou');
insert into kino (ime, kraj) values ('Vera', 'Sarpsborg');
insert into kino (ime, kraj) values ('Starling', 'Karanganyar');
insert into kino (ime, kraj) values ('Rigney', 'Caojia');
insert into kino (ime, kraj) values ('Mandrake', 'Yeroẖam');
insert into kino (ime, kraj) values ('Acker', 'Formosa');
insert into kino (ime, kraj) values ('Corben', 'Espinal');
insert into kino (ime, kraj) values ('Cardinal', 'Gaplokan');
insert into kino (ime, kraj) values ('Huxley', 'Starominskaya');
insert into kino (ime, kraj) values ('Manley', 'Phitsanulok');
insert into kino (ime, kraj) values ('Hanover', 'Lojigawaran');
insert into kino (ime, kraj) values ('Mallard', 'Zhanggongmiao');
insert into kino (ime, kraj) values ('Amoth', 'Ban Selaphum');
insert into kino (ime, kraj) values ('Cordelia', 'Domampot');
insert into kino (ime, kraj) values ('Loomis', 'Tianxing');
insert into kino (ime, kraj) values ('Almo', 'Biao');
insert into kino (ime, kraj) values ('Tomscot', 'Shiogama');
insert into kino (ime, kraj) values ('Anzinger', 'Topdac');
insert into kino (ime, kraj) values ('Lakewood Gardens', 'Al Judayrah');
insert into kino (ime, kraj) values ('Buena Vista', 'Karadaglije');
insert into kino (ime, kraj) values ('Stoughton', 'Forino');
insert into kino (ime, kraj) values ('Eastlawn', 'Makīnsk');
insert into kino (ime, kraj) values ('Prairieview', 'Paupanda Bawah');
insert into kino (ime, kraj) values ('Cambridge', 'Taozhuang');
insert into kino (ime, kraj) values ('Tony', 'Niitsu-honchō');
insert into kino (ime, kraj) values ('Dixon', 'Kuantan');
insert into kino (ime, kraj) values ('Banding', 'La Uvita');
insert into kino (ime, kraj) values ('Ohio', 'Hongmiao');
insert into kino (ime, kraj) values ('Bonner', 'Ngamba');
insert into kino (ime, kraj) values ('Katie', 'Porvoo');
insert into kino (ime, kraj) values ('Portage', 'Polepy');
insert into kino (ime, kraj) values ('Schlimgen', 'Wangzha');
insert into kino (ime, kraj) values ('Anthes', 'Baabda');
insert into kino (ime, kraj) values ('Barnett', 'Niamey');
insert into kino (ime, kraj) values ('Amoth', 'Sioguí Arriba');
insert into kino (ime, kraj) values ('Bunker Hill', 'Changyanbao');
insert into kino (ime, kraj) values ('Crescent Oaks', 'São Bartolomeu');
insert into kino (ime, kraj) values ('Manley', 'Orly aérogare');
insert into kino (ime, kraj) values ('Lighthouse Bay', 'Örebro');
insert into kino (ime, kraj) values ('Transport', 'Kuragaki-kosugi');
insert into kino (ime, kraj) values ('Spenser', 'Rezé');
insert into kino (ime, kraj) values ('Hudson', 'Spytkowice');
insert into kino (ime, kraj) values ('Mendota', 'Kiiminki');
insert into kino (ime, kraj) values ('Helena', 'Ifanadiana');
insert into kino (ime, kraj) values ('Sundown', 'Mahe');
insert into kino (ime, kraj) values ('Lillian', 'Lyubotyn');
insert into kino (ime, kraj) values ('Hayes', 'Pancol');
insert into kino (ime, kraj) values ('Del Mar', 'Lüxiang');
insert into kino (ime, kraj) values ('Coolidge', 'Al Jumūm');
insert into kino (ime, kraj) values ('Vermont', 'Ōmihachiman');
insert into kino (ime, kraj) values ('West', 'Yuza');
insert into kino (ime, kraj) values ('Dawn', 'Paatan');
insert into kino (ime, kraj) values ('Waywood', 'Muting');
insert into kino (ime, kraj) values ('Roth', 'Paldiski');
insert into kino (ime, kraj) values ('Drewry', 'Nusajaya');
insert into kino (ime, kraj) values ('Pepper Wood', 'Malummaduri');
insert into kino (ime, kraj) values ('Manufacturers', 'Dagar');
insert into kino (ime, kraj) values ('Thompson', 'Šabac');
insert into kino (ime, kraj) values ('Hayes', 'Presidente Prudente');
insert into kino (ime, kraj) values ('Messerschmidt', 'Ad Dawḩah');
insert into kino (ime, kraj) values ('Manley', 'Diourbel');
insert into kino (ime, kraj) values ('Stang', 'Pedreira');
insert into kino (ime, kraj) values ('Mallory', 'Manwakh');
insert into kino (ime, kraj) values ('New Castle', 'Beijós');
insert into kino (ime, kraj) values ('Veith', 'Vil’nyans’k');
insert into kino (ime, kraj) values ('1st', 'Dongzhaogezhuang');
insert into kino (ime, kraj) values ('Amoth', 'Vil’nyans’k');
insert into kino (ime, kraj) values ('Park Meadow', '‘Alīābād-e Katūl');
insert into kino (ime, kraj) values ('Bellgrove', 'Majagual');
insert into kino (ime, kraj) values ('Morning', 'Łopuszna');
insert into kino (ime, kraj) values ('Maryland', 'Kvitok');
insert into kino (ime, kraj) values ('Forest Dale', 'Storozhnytsya');
insert into kino (ime, kraj) values ('Northridge', 'Madruga');
insert into kino (ime, kraj) values ('Mosinee', 'Venëv');
insert into kino (ime, kraj) values ('Hermina', 'Lhoknga');
insert into kino (ime, kraj) values ('Tony', 'Baraya');
insert into kino (ime, kraj) values ('Mitchell', 'Fais');
insert into kino (ime, kraj) values ('Westend', 'Mikrókampos');
insert into kino (ime, kraj) values ('Petterle', 'Chengji');
insert into kino (ime, kraj) values ('Myrtle', 'Praya');
insert into kino (ime, kraj) values ('Gulseth', 'Dongzhang');
insert into kino (ime, kraj) values ('Oneill', 'Žrnovnica');
insert into kino (ime, kraj) values ('Walton', 'Lais');
insert into kino (ime, kraj) values ('High Crossing', 'Saihan Tal');
insert into kino (ime, kraj) values ('Lyons', 'Novopavlovsk');
insert into kino (ime, kraj) values ('8th', 'Kanḏay');
insert into kino (ime, kraj) values ('Carey', 'Dob');
insert into kino (ime, kraj) values ('Washington', 'Klerksdorp');
insert into kino (ime, kraj) values ('Caliangt', 'As Salţ');
insert into kino (ime, kraj) values ('Sage', 'Changfeng');
insert into kino (ime, kraj) values ('Dahle', 'Banjar Dauhpura');
insert into kino (ime, kraj) values ('Mesta', 'Keffi');
insert into kino (ime, kraj) values ('Blaine', 'Chuquitira');
insert into kino (ime, kraj) values ('Garrison', 'Bataiporã');
insert into kino (ime, kraj) values ('Toban', 'Nantou');
insert into kino (ime, kraj) values ('Dennis', 'Anchorage');
insert into kino (ime, kraj) values ('Village Green', 'Tacarigua');
insert into kino (ime, kraj) values ('Anzinger', 'Tiguha');
insert into kino (ime, kraj) values ('Veith', 'Ochobo');
insert into kino (ime, kraj) values ('Stone Corner', 'Muang Sing');
insert into kino (ime, kraj) values ('Evergreen', 'Mugango');
insert into kino (ime, kraj) values ('Morrow', 'Piran');
insert into kino (ime, kraj) values ('Scofield', 'E’erdun Wula');
insert into kino (ime, kraj) values ('Jana', 'Palocabildo');
insert into kino (ime, kraj) values ('Dennis', 'Serra da Boa Viagem');
insert into kino (ime, kraj) values ('International', 'Zhongxin');
insert into kino (ime, kraj) values ('Susan', 'Sinanju');
insert into kino (ime, kraj) values ('Sutherland', 'Panyingkiran');
insert into kino (ime, kraj) values ('Stone Corner', 'Srabah');
insert into kino (ime, kraj) values ('Calypso', 'Nagrog');
insert into kino (ime, kraj) values ('Eliot', 'Karantaba');
insert into kino (ime, kraj) values ('Alpine', 'Kuala Lumpur');
insert into kino (ime, kraj) values ('Ridgeview', 'Izvestkovyy');
insert into kino (ime, kraj) values ('Vermont', 'Henggang');
insert into kino (ime, kraj) values ('Fuller', 'Huangshan');
insert into kino (ime, kraj) values ('Oxford', 'Cruzeiro');
insert into kino (ime, kraj) values ('Blaine', 'Spassk-Dal’niy');
insert into kino (ime, kraj) values ('Cherokee', 'Huangshi');
insert into kino (ime, kraj) values ('Mockingbird', 'Orlu');
insert into kino (ime, kraj) values ('Calypso', 'Daluo');
insert into kino (ime, kraj) values ('Meadow Valley', 'Bururi');
insert into kino (ime, kraj) values ('Thompson', 'Pyskowice');
insert into kino (ime, kraj) values ('Eagle Crest', 'Lagnieu');
insert into kino (ime, kraj) values ('Goodland', 'Ixopo');
insert into kino (ime, kraj) values ('Schurz', 'Slobozia');
insert into kino (ime, kraj) values ('Ridgeview', 'Yingdianjie');
insert into kino (ime, kraj) values ('Hansons', 'Shanmu');
insert into kino (ime, kraj) values ('Bashford', 'Soutelo');
insert into kino (ime, kraj) values ('Clyde Gallagher', 'Untolovo');
insert into kino (ime, kraj) values ('Old Shore', 'Ares Tengah');
insert into kino (ime, kraj) values ('Rutledge', 'Levski');
insert into kino (ime, kraj) values ('Arkansas', 'San Francisco');
insert into kino (ime, kraj) values ('Waubesa', 'Bålsta');
insert into kino (ime, kraj) values ('Bartillon', 'Tucano');
insert into kino (ime, kraj) values ('Nevada', 'Pórto Chéli');
insert into kino (ime, kraj) values ('Lerdahl', 'Västerås');
insert into kino (ime, kraj) values ('South', 'Zwedru');
insert into kino (ime, kraj) values ('Scofield', 'Bantal');
insert into kino (ime, kraj) values ('Kensington', 'Tangfang');
insert into kino (ime, kraj) values ('Lunder', 'Qinghua');
insert into kino (ime, kraj) values ('Forest', 'Penza');
insert into kino (ime, kraj) values ('Randy', 'Jiaozhou');
insert into kino (ime, kraj) values ('Warrior', 'Ust’-Ilimsk');
insert into kino (ime, kraj) values ('Norway Maple', 'Tópaga');
insert into kino (ime, kraj) values ('Lakewood Gardens', 'Huazhou');
insert into kino (ime, kraj) values ('Havey', 'Kisesa');
insert into kino (ime, kraj) values ('Dovetail', 'Gunungkoneng');
insert into kino (ime, kraj) values ('Kingsford', 'Xiaoyi');
insert into kino (ime, kraj) values ('Mesta', 'Bergvliet');
insert into kino (ime, kraj) values ('Pond', 'Sukabumi');
insert into kino (ime, kraj) values ('Myrtle', 'Burrel');
insert into kino (ime, kraj) values ('Fair Oaks', 'Nikkō');
insert into kino (ime, kraj) values ('Scofield', 'Dongbian');
insert into kino (ime, kraj) values ('Grover', 'Gaspra');
insert into kino (ime, kraj) values ('Red Cloud', 'Aba');
insert into kino (ime, kraj) values ('Mesta', 'Jeżów');
insert into kino (ime, kraj) values ('Bluestem', 'Lin’an');
insert into kino (ime, kraj) values ('Manitowish', 'Ōmura');
insert into kino (ime, kraj) values ('Hudson', 'Dalonghua');
insert into kino (ime, kraj) values ('Transport', 'Berber');
insert into kino (ime, kraj) values ('John Wall', 'Middleton');
insert into kino (ime, kraj) values ('Ridge Oak', 'Jiumen');
insert into kino (ime, kraj) values ('Messerschmidt', 'Caraga');
insert into kino (ime, kraj) values ('Burrows', 'Karakol');
insert into kino (ime, kraj) values ('Shoshone', 'Novorossiysk');
insert into kino (ime, kraj) values ('Bluestem', 'Kayakent');
insert into kino (ime, kraj) values ('Rieder', 'Nglego');
insert into kino (ime, kraj) values ('Bunker Hill', 'Giporlos');
insert into kino (ime, kraj) values ('Paget', 'Alasmalang');
insert into kino (ime, kraj) values ('Luster', 'Doksy');
insert into kino (ime, kraj) values ('Northfield', 'Ambositra');
insert into kino (ime, kraj) values ('Victoria', 'Caihe');
insert into kino (ime, kraj) values ('Memorial', 'Buayan');
insert into kino (ime, kraj) values ('Jenna', 'Wuyo');
insert into kino (ime, kraj) values ('Schmedeman', 'Wuping');
insert into kino (ime, kraj) values ('Acker', 'Parchal');
insert into kino (ime, kraj) values ('Fulton', 'Nayoro');
insert into kino (ime, kraj) values ('Duke', 'Al Kiswah');
insert into kino (ime, kraj) values ('Valley Edge', 'Ashgabat');
insert into kino (ime, kraj) values ('Warner', 'Bacong');
insert into kino (ime, kraj) values ('Emmet', 'Xilian');
insert into kino (ime, kraj) values ('Heath', 'Taohua');
insert into kino (ime, kraj) values ('Maple', 'Çlirim');
insert into kino (ime, kraj) values ('Derek', 'Chingas');
insert into kino (ime, kraj) values ('Surrey', 'Colcabamba');
insert into kino (ime, kraj) values ('Pennsylvania', 'Xietang');
insert into kino (ime, kraj) values ('Center', 'Vilca');
insert into kino (ime, kraj) values ('Monterey', 'Longsheng');
insert into kino (ime, kraj) values ('La Follette', 'Idanha-a-Nova');
insert into kino (ime, kraj) values ('Jackson', 'Vatutino');
insert into kino (ime, kraj) values ('Aberg', 'Erími');
insert into kino (ime, kraj) values ('Trailsway', 'Yanguan');
insert into kino (ime, kraj) values ('Jana', 'Pariti');
insert into kino (ime, kraj) values ('Golf', 'La Cesira');
insert into kino (ime, kraj) values ('Westport', 'Xigaoshan');
insert into kino (ime, kraj) values ('Bonner', 'Abuja');
insert into kino (ime, kraj) values ('Bellgrove', 'Kombolcha');
insert into kino (ime, kraj) values ('Messerschmidt', 'Vrtojba');
insert into kino (ime, kraj) values ('Kensington', 'Makedonski Brod');
insert into kino (ime, kraj) values ('Fordem', 'Upton');
insert into kino (ime, kraj) values ('Hagan', 'Newton');
insert into kino (ime, kraj) values ('Shopko', 'Matlang');
insert into kino (ime, kraj) values ('Brown', 'San Vicente');
insert into kino (ime, kraj) values ('Carioca', 'Weifang');
insert into kino (ime, kraj) values ('Lunder', 'Sahline');
insert into kino (ime, kraj) values ('Ramsey', 'P’asanauri');
insert into kino (ime, kraj) values ('Thierer', 'Tundagan');
insert into kino (ime, kraj) values ('Stoughton', 'Kembang');
insert into kino (ime, kraj) values ('Lunder', 'Hrvatini');
insert into kino (ime, kraj) values ('Erie', 'Sawara');
insert into kino (ime, kraj) values ('South', 'La Cueva');
insert into kino (ime, kraj) values ('Upham', 'Luzhi');
insert into kino (ime, kraj) values ('Scoville', 'Tzaneen');
insert into kino (ime, kraj) values ('Troy', 'Xuyong');
insert into kino (ime, kraj) values ('Springs', 'Hartford');
insert into kino (ime, kraj) values ('Sherman', 'Rendian');
insert into kino (ime, kraj) values ('American Ash', 'Tonkino');
insert into kino (ime, kraj) values ('Judy', 'Göteborg');
insert into kino (ime, kraj) values ('Stephen', 'Loncoche');
insert into kino (ime, kraj) values ('Delladonna', 'Cilentung');
insert into kino (ime, kraj) values ('Red Cloud', 'Ta‘izz');
insert into kino (ime, kraj) values ('Sunbrook', 'Francisco I Madero');
insert into kino (ime, kraj) values ('Gateway', 'Campamento');
insert into kino (ime, kraj) values ('Eastwood', 'Pabean');
insert into kino (ime, kraj) values ('Prentice', 'Jiangnan');
insert into kino (ime, kraj) values ('Delladonna', 'Yiyang');
insert into kino (ime, kraj) values ('Jay', 'Monguno');
insert into kino (ime, kraj) values ('Erie', 'Podgornaya');
insert into kino (ime, kraj) values ('7th', 'Gunung Sugih');
insert into kino (ime, kraj) values ('Darwin', 'Houston');
insert into kino (ime, kraj) values ('Badeau', 'Palcamayo');
insert into kino (ime, kraj) values ('Memorial', 'Pueblo Nuevo');
insert into kino (ime, kraj) values ('Oak', 'Duma');
insert into kino (ime, kraj) values ('Del Sol', 'Luis Donaldo Colosio');
insert into kino (ime, kraj) values ('Sutteridge', 'Luoxi');
insert into kino (ime, kraj) values ('West', 'Budzów');
insert into kino (ime, kraj) values ('Warbler', 'Makadi Bay');
insert into kino (ime, kraj) values ('Monica', 'Kukushtan');
insert into kino (ime, kraj) values ('Coleman', 'Uyugan');
insert into kino (ime, kraj) values ('Hanson', 'Blois');
insert into kino (ime, kraj) values ('Butternut', 'Yanghou');
insert into kino (ime, kraj) values ('Moulton', 'Sasayama');
insert into kino (ime, kraj) values ('Paget', 'Kitami');
insert into kino (ime, kraj) values ('Montana', 'Poço Verde');
insert into kino (ime, kraj) values ('Quincy', 'Boca do Acre');
insert into kino (ime, kraj) values ('Shopko', 'Yāsūf');
insert into kino (ime, kraj) values ('Delladonna', 'Yazykovo');
insert into kino (ime, kraj) values ('Delaware', 'Ngandangan');
insert into kino (ime, kraj) values ('7th', 'Auch');
insert into kino (ime, kraj) values ('Prairieview', 'Béziers');
insert into kino (ime, kraj) values ('Fordem', 'Nong Bua Daeng');
insert into kino (ime, kraj) values ('Center', 'Katipunan');
insert into kino (ime, kraj) values ('Evergreen', 'Coronel Vivida');
insert into kino (ime, kraj) values ('Del Mar', 'Kęty');
insert into kino (ime, kraj) values ('Northridge', 'Taocheng');
insert into kino (ime, kraj) values ('Hooker', 'Sunne');
insert into kino (ime, kraj) values ('Fisk', 'Comitancillo');
insert into kino (ime, kraj) values ('Bonner', 'Riđica');
insert into kino (ime, kraj) values ('Northland', 'Quillota');
insert into kino (ime, kraj) values ('Di Loreto', 'Cilangla');
insert into kino (ime, kraj) values ('Chive', 'Tagasilay');
insert into kino (ime, kraj) values ('Gina', 'Cisek');
insert into kino (ime, kraj) values ('Roth', 'Pirava');
insert into kino (ime, kraj) values ('Morning', 'Labuan');
insert into kino (ime, kraj) values ('Aberg', 'Moste');
insert into kino (ime, kraj) values ('Namekagon', 'Pizhma');
insert into kino (ime, kraj) values ('Messerschmidt', 'Kumla');
insert into kino (ime, kraj) values ('Buell', 'Passo');
insert into kino (ime, kraj) values ('Old Gate', 'Kuantan');
insert into kino (ime, kraj) values ('Clyde Gallagher', 'Xijiang');
insert into kino (ime, kraj) values ('Talmadge', 'Kikuchi');
insert into kino (ime, kraj) values ('Harper', 'Oslo');
insert into kino (ime, kraj) values ('Delaware', 'Ibrā’');
insert into kino (ime, kraj) values ('Nova', 'Meitang');
insert into kino (ime, kraj) values ('Myrtle', 'Hai Riêng');
insert into kino (ime, kraj) values ('Marcy', 'Los Angeles');
insert into kino (ime, kraj) values ('Sunfield', 'Ollachea');
insert into kino (ime, kraj) values ('Rockefeller', 'Tangwei');
insert into kino (ime, kraj) values ('Melody', 'Pedome');
insert into kino (ime, kraj) values ('Washington', 'Xumu');
insert into kino (ime, kraj) values ('Northwestern', 'Legionowo');
insert into kino (ime, kraj) values ('Melvin', 'Kudang');
insert into kino (ime, kraj) values ('Spohn', 'Balboa');
insert into kino (ime, kraj) values ('Bowman', 'Sibulan');
insert into kino (ime, kraj) values ('Armistice', 'Dongjiang Matoukou');
insert into kino (ime, kraj) values ('Forster', 'Luojiaping');
insert into kino (ime, kraj) values ('Aberg', 'Futuroscope');
insert into kino (ime, kraj) values ('Waywood', 'Dazhongzhuang');
insert into kino (ime, kraj) values ('Darwin', 'Skillingaryd');
insert into kino (ime, kraj) values ('Onsgard', 'Furong');
insert into kino (ime, kraj) values ('Service', 'Tsubame');
insert into kino (ime, kraj) values ('Truax', 'Quibal');
insert into kino (ime, kraj) values ('Anderson', 'Beslan');
insert into kino (ime, kraj) values ('5th', 'São Domingos do Maranhão');
insert into kino (ime, kraj) values ('Union', 'Gomunice');
insert into kino (ime, kraj) values ('Lake View', 'Huangtu');
insert into kino (ime, kraj) values ('Stephen', 'Augusto Corrêa');
insert into kino (ime, kraj) values ('Talisman', 'Driyorejo');
insert into kino (ime, kraj) values ('Rockefeller', 'Banraeaba Village');
insert into kino (ime, kraj) values ('Darwin', 'Rancabolang');
insert into kino (ime, kraj) values ('Mifflin', 'Kanlagay');
insert into kino (ime, kraj) values ('Mcbride', 'Curahklapa');
insert into kino (ime, kraj) values ('Nelson', 'Wonokromo');
insert into kino (ime, kraj) values ('Waxwing', 'La Cueva');
insert into kino (ime, kraj) values ('Fuller', 'Kuanghe');
insert into kino (ime, kraj) values ('Dayton', 'Turbiv');
insert into kino (ime, kraj) values ('Mccormick', 'Hachiōji');
insert into kino (ime, kraj) values ('Schlimgen', 'Saguiaran');
insert into kino (ime, kraj) values ('Anhalt', 'Shuangtang');
insert into kino (ime, kraj) values ('Rockefeller', 'Granja');
insert into kino (ime, kraj) values ('Clemons', 'Saumur');
insert into kino (ime, kraj) values ('Surrey', 'Biao');
insert into kino (ime, kraj) values ('Pine View', 'Uozu');
insert into kino (ime, kraj) values ('Village Green', 'Xudat');
insert into kino (ime, kraj) values ('Bayside', 'Lopatyn');
insert into kino (ime, kraj) values ('Loftsgordon', 'Longtou');
insert into kino (ime, kraj) values ('Hooker', 'Yelabuga');
insert into kino (ime, kraj) values ('Golf View', 'Imrīsh');
insert into kino (ime, kraj) values ('Huxley', 'Shuimen');
insert into kino (ime, kraj) values ('Victoria', 'Richard-Toll');
insert into kino (ime, kraj) values ('Paget', 'Siekierczyn');
insert into kino (ime, kraj) values ('Sutherland', 'Cigembor');
insert into kino (ime, kraj) values ('Norway Maple', 'Semerak');
insert into kino (ime, kraj) values ('Bartillon', 'Gamovo');
insert into kino (ime, kraj) values ('Northport', 'Moutas');
insert into kino (ime, kraj) values ('Blackbird', 'Saint Petersburg');
insert into kino (ime, kraj) values ('Carioca', 'Kishorganj');
insert into kino (ime, kraj) values ('Johnson', 'Zhenwen');
insert into kino (ime, kraj) values ('Rockefeller', 'Heshan');
insert into kino (ime, kraj) values ('Village Green', 'Mošorin');
insert into kino (ime, kraj) values ('Sommers', 'President Roxas');
insert into kino (ime, kraj) values ('Banding', 'Mikhaylovka');
insert into kino (ime, kraj) values ('Kinsman', 'San Rafael');
insert into kino (ime, kraj) values ('Killdeer', 'Hanau');
insert into kino (ime, kraj) values ('Luster', 'Sobinka');
insert into kino (ime, kraj) values ('Warbler', 'Cruz Alta');
insert into kino (ime, kraj) values ('Shelley', 'Lappeenranta');
insert into kino (ime, kraj) values ('Drewry', 'Paitan Este');
insert into kino (ime, kraj) values ('Autumn Leaf', 'København');
insert into kino (ime, kraj) values ('Orin', 'Nantuo');
insert into kino (ime, kraj) values ('Tennessee', 'Šumice');
insert into kino (ime, kraj) values ('Miller', 'Pongkor');
insert into kino (ime, kraj) values ('East', 'Bagé');
insert into kino (ime, kraj) values ('Gulseth', 'Castlepollard');
insert into kino (ime, kraj) values ('Eastwood', 'Boconó');
insert into kino (ime, kraj) values ('Bowman', 'Kraśnik');
insert into kino (ime, kraj) values ('Northfield', 'Kraaifontein');
insert into kino (ime, kraj) values ('Express', 'Cihambali');
insert into kino (ime, kraj) values ('Nevada', 'Berlín');
insert into kino (ime, kraj) values ('Porter', 'Novo Hamburgo');
insert into kino (ime, kraj) values ('Mayfield', 'Parnaíba');
insert into kino (ime, kraj) values ('Bellgrove', 'Icheon-si');
insert into kino (ime, kraj) values ('Thompson', 'Nuits-Saint-Georges');
insert into kino (ime, kraj) values ('Golf', 'Cetinje');
insert into kino (ime, kraj) values ('Arapahoe', 'Bodzentyn');
insert into kino (ime, kraj) values ('Holy Cross', 'Kajuru');
insert into kino (ime, kraj) values ('Mcguire', 'Doumé');
insert into kino (ime, kraj) values ('Sutteridge', 'Verkhnyaya Toyma');
insert into kino (ime, kraj) values ('Browning', 'Nīca');
insert into kino (ime, kraj) values ('Merry', 'Tsaratanana');
insert into kino (ime, kraj) values ('Westport', 'Choya');
insert into kino (ime, kraj) values ('Burrows', 'Shah Alam');
insert into kino (ime, kraj) values ('8th', 'Olhos de Água');
insert into kino (ime, kraj) values ('Laurel', 'Lyon');
insert into kino (ime, kraj) values ('Gerald', 'Rotunda');
insert into kino (ime, kraj) values ('Bellgrove', 'Lidingö');
insert into kino (ime, kraj) values ('Village', 'Taishihe');
insert into kino (ime, kraj) values ('Lunder', 'Soweto');
insert into kino (ime, kraj) values ('Crownhardt', 'Mingelchaur');
insert into kino (ime, kraj) values ('Stuart', 'Iroquois Falls');
insert into kino (ime, kraj) values ('Portage', 'Kaytitinga');
insert into kino (ime, kraj) values ('Tony', 'Kristinehamn');
insert into kino (ime, kraj) values ('Miller', 'Gaobeijie');
insert into kino (ime, kraj) values ('Harper', 'Arani');
insert into kino (ime, kraj) values ('Trailsway', 'Honghuatao');
insert into kino (ime, kraj) values ('Doe Crossing', 'Nagornyy');
insert into kino (ime, kraj) values ('Hoffman', 'Chahe');
insert into kino (ime, kraj) values ('Kipling', 'Tanjung');
insert into kino (ime, kraj) values ('Thackeray', 'Paris 08');
insert into kino (ime, kraj) values ('Lerdahl', 'Enrile');
insert into kino (ime, kraj) values ('Thackeray', 'Jakusko');
insert into kino (ime, kraj) values ('Transport', 'Mamonit');
insert into kino (ime, kraj) values ('Village', 'Omuo-Ekiti');
insert into kino (ime, kraj) values ('Kipling', 'Moro');
insert into kino (ime, kraj) values ('Cherokee', 'Sochi');
insert into kino (ime, kraj) values ('Hintze', 'Ku‘aydinah');
insert into kino (ime, kraj) values ('Caliangt', 'Pisang');
insert into kino (ime, kraj) values ('Eastlawn', 'Mustvee');
insert into kino (ime, kraj) values ('Esker', 'Curiapo');
insert into kino (ime, kraj) values ('Vahlen', 'Santiago do Cacém');
insert into kino (ime, kraj) values ('Dixon', 'Ngala');
insert into kino (ime, kraj) values ('Huxley', 'Benhao');
insert into kino (ime, kraj) values ('Kropf', 'Kuala Lumpur');
insert into kino (ime, kraj) values ('Autumn Leaf', 'Kekeran');
insert into kino (ime, kraj) values ('Anzinger', 'Juncalito Abajo');
insert into kino (ime, kraj) values ('Granby', 'Chicama');
insert into kino (ime, kraj) values ('Debs', 'Nabire');
insert into kino (ime, kraj) values ('Amoth', 'Krasnorechenskiy');
insert into kino (ime, kraj) values ('Johnson', 'Jeżów');
insert into kino (ime, kraj) values ('International', 'Amagarapati');
insert into kino (ime, kraj) values ('Johnson', 'Daxi');
insert into kino (ime, kraj) values ('Upham', 'Grand Rapids');
insert into kino (ime, kraj) values ('Eastwood', 'Bārkhān');
insert into kino (ime, kraj) values ('Grasskamp', 'San Pedro');
insert into kino (ime, kraj) values ('Hansons', 'Daşoguz');
insert into kino (ime, kraj) values ('Weeping Birch', 'Delft');
insert into kino (ime, kraj) values ('Scott', 'Piracaia');
insert into kino (ime, kraj) values ('Morrow', 'Sergelen');
insert into kino (ime, kraj) values ('Crescent Oaks', 'Kembangarum');
insert into kino (ime, kraj) values ('Pennsylvania', 'Niverville');
insert into kino (ime, kraj) values ('Cottonwood', 'Artur Nogueira');
insert into kino (ime, kraj) values ('Oakridge', 'Welchman Hall');
insert into kino (ime, kraj) values ('Commercial', 'Plast');
insert into kino (ime, kraj) values ('Judy', 'Krajan Siki');
insert into kino (ime, kraj) values ('Scoville', 'Orël');
insert into kino (ime, kraj) values ('Vidon', 'Dongqinggou');
insert into kino (ime, kraj) values ('Heffernan', 'Medovene');
insert into kino (ime, kraj) values ('Pierstorff', 'Fakel');
insert into kino (ime, kraj) values ('Continental', 'Panjakent');
insert into kino (ime, kraj) values ('Everett', 'Alcáçovas');
insert into kino (ime, kraj) values ('Pleasure', 'Fauske');
insert into kino (ime, kraj) values ('Lindbergh', 'Gravataí');
insert into kino (ime, kraj) values ('Rowland', 'Skrunda');
insert into kino (ime, kraj) values ('Mockingbird', 'Mikhaylovsk');
insert into kino (ime, kraj) values ('Fisk', 'Paseyan');
insert into kino (ime, kraj) values ('Toban', 'Prakhon Chai');
insert into kino (ime, kraj) values ('Hudson', 'Camasca');
insert into kino (ime, kraj) values ('Sachtjen', 'Skrzydlna');
insert into kino (ime, kraj) values ('Walton', 'Sóc Sơn');
insert into kino (ime, kraj) values ('Carey', 'Xishan');
insert into kino (ime, kraj) values ('Clyde Gallagher', 'Grand Rapids');
insert into kino (ime, kraj) values ('Lerdahl', 'Rossosh’');
insert into kino (ime, kraj) values ('Merchant', 'Young');
insert into kino (ime, kraj) values ('Hazelcrest', 'Hucheng');
insert into kino (ime, kraj) values ('7th', 'Yōkaichiba');
insert into kino (ime, kraj) values ('Carioca', 'Pangantocan');
insert into kino (ime, kraj) values ('Mesta', 'Suchań');
insert into kino (ime, kraj) values ('Becker', 'Turenki');
insert into kino (ime, kraj) values ('Grover', 'Svirsk');
insert into kino (ime, kraj) values ('Prairie Rose', 'Rakek');
insert into kino (ime, kraj) values ('Luster', 'Saraburi');
insert into kino (ime, kraj) values ('Welch', 'Liqizhuang');
insert into kino (ime, kraj) values ('Sycamore', 'Liancheng');
insert into kino (ime, kraj) values ('Becker', 'Cartagena');
insert into kino (ime, kraj) values ('Kipling', 'La Libertad');
insert into kino (ime, kraj) values ('Manitowish', 'Talhār');
insert into kino (ime, kraj) values ('Sloan', 'Yamada');
insert into kino (ime, kraj) values ('Rusk', 'Uppsala');
insert into kino (ime, kraj) values ('Cascade', 'Oliveiras');
insert into kino (ime, kraj) values ('Mccormick', 'Roissy Charles-de-Gaulle');
insert into kino (ime, kraj) values ('Boyd', 'Babakankalong');
insert into kino (ime, kraj) values ('Cardinal', 'Vällingby');
insert into kino (ime, kraj) values ('Hanover', 'Brudzeń Duży');
insert into kino (ime, kraj) values ('Fair Oaks', 'Pulopaya');
insert into kino (ime, kraj) values ('Steensland', 'Bandar-e Lengeh');
insert into kino (ime, kraj) values ('Heffernan', 'L-Iklin');
insert into kino (ime, kraj) values ('Shelley', 'Hoeyang');
insert into kino (ime, kraj) values ('Helena', 'Junqueiro');
insert into kino (ime, kraj) values ('Northview', 'Kaduseeng');
insert into kino (ime, kraj) values ('Hoepker', 'Ágios Andréas');
insert into kino (ime, kraj) values ('Veith', 'Beizheng');
insert into kino (ime, kraj) values ('Transport', 'Futian');
insert into kino (ime, kraj) values ('Darwin', 'Bonneuil-sur-Marne');
insert into kino (ime, kraj) values ('Lyons', 'Melun');
insert into kino (ime, kraj) values ('Randy', 'Clarines');
insert into kino (ime, kraj) values ('Hayes', 'Qishui');
insert into kino (ime, kraj) values ('Darwin', 'Lanat');
insert into kino (ime, kraj) values ('2nd', 'Shahrīār');
insert into kino (ime, kraj) values ('Corry', 'Hưng Nguyên');
insert into kino (ime, kraj) values ('Sage', 'Cuauhtemoc');
insert into kino (ime, kraj) values ('Upham', 'Ageoshimo');
insert into kino (ime, kraj) values ('East', 'Jinbo');
insert into kino (ime, kraj) values ('Holmberg', 'Rajhrad');
insert into kino (ime, kraj) values ('Welch', 'Judaydah');
insert into kino (ime, kraj) values ('Fuller', 'Zangkaxa');
insert into kino (ime, kraj) values ('Dawn', 'Koryukivka');
insert into kino (ime, kraj) values ('Shoshone', 'Xingxi');
insert into kino (ime, kraj) values ('Transport', 'Muara Dua');
insert into kino (ime, kraj) values ('Iowa', 'Yongfeng');
insert into kino (ime, kraj) values ('Meadow Valley', 'Santo Tomas');
insert into kino (ime, kraj) values ('Hazelcrest', 'Thị Trấn Bắc Yên');
insert into kino (ime, kraj) values ('Fallview', 'Aubagne');
insert into kino (ime, kraj) values ('Schurz', 'Walahir');
insert into kino (ime, kraj) values ('Bashford', 'Bakersfield');
insert into kino (ime, kraj) values ('Ludington', 'Deneysville');
insert into kino (ime, kraj) values ('Crest Line', 'Vratsa');
insert into kino (ime, kraj) values ('Declaration', 'Montluel');
insert into kino (ime, kraj) values ('Cottonwood', 'Entebbe');
insert into kino (ime, kraj) values ('Jenifer', 'Khorramdarreh');
insert into kino (ime, kraj) values ('Porter', 'Paphos');
insert into kino (ime, kraj) values ('Butterfield', 'Lyon');
insert into kino (ime, kraj) values ('Hanson', 'Carmen');
insert into kino (ime, kraj) values ('Mitchell', 'Krasnyy Oktyabr’');
insert into kino (ime, kraj) values ('Florence', 'Hinvi');
insert into kino (ime, kraj) values ('Badeau', 'Laguna Salada');
insert into kino (ime, kraj) values ('Quincy', 'Kenzhe');
insert into kino (ime, kraj) values ('Pankratz', 'Kristinehamn');
insert into kino (ime, kraj) values ('Declaration', 'Sara Kunda');
insert into kino (ime, kraj) values ('Dwight', 'Mabugang');
insert into kino (ime, kraj) values ('Warrior', 'Le Blanc-Mesnil');
insert into kino (ime, kraj) values ('Kropf', 'Noupoort');
insert into kino (ime, kraj) values ('1st', 'Sinazongwe');
insert into kino (ime, kraj) values ('Starling', 'Prámanta');
insert into kino (ime, kraj) values ('Macpherson', 'Naḩḩālīn');
insert into kino (ime, kraj) values ('Leroy', 'Cañete');
insert into kino (ime, kraj) values ('Browning', 'Kota Trieng');
insert into kino (ime, kraj) values ('Carey', 'Sanchahe');
insert into kino (ime, kraj) values ('Upham', 'Stockholm');
insert into kino (ime, kraj) values ('Delladonna', 'Morinville');
insert into kino (ime, kraj) values ('La Follette', 'Sanxi');
insert into kino (ime, kraj) values ('Esch', 'Rekovac');
insert into kino (ime, kraj) values ('Ruskin', 'Täby');
insert into kino (ime, kraj) values ('Lake View', 'Gudja');
insert into kino (ime, kraj) values ('Lunder', 'Listowel');
insert into kino (ime, kraj) values ('Paget', 'Vardablur');
insert into kino (ime, kraj) values ('Spenser', 'Ganxi');
insert into kino (ime, kraj) values ('Gulseth', 'Changning');
insert into kino (ime, kraj) values ('Sugar', 'Plottier');
insert into kino (ime, kraj) values ('Maryland', 'Littleton');
insert into kino (ime, kraj) values ('Dunning', '‘Akko');
insert into kino (ime, kraj) values ('Oakridge', 'Huangzhawan');
insert into kino (ime, kraj) values ('Buena Vista', 'Rawasan');
insert into kino (ime, kraj) values ('Marcy', 'Hitiaa');
insert into kino (ime, kraj) values ('Rutledge', 'Abakaliki');
insert into kino (ime, kraj) values ('Glendale', 'Donji Vakuf');
insert into kino (ime, kraj) values ('Loeprich', 'Bangunsari');
insert into kino (ime, kraj) values ('Lakeland', 'Morazán');
insert into kino (ime, kraj) values ('Anderson', 'Riangblolong');
insert into kino (ime, kraj) values ('Chive', 'San Felipe');
insert into kino (ime, kraj) values ('Warbler', 'Fristad');
insert into kino (ime, kraj) values ('Pine View', 'Xiangtang');
insert into kino (ime, kraj) values ('Maryland', 'Stari Grad');
insert into kino (ime, kraj) values ('Mockingbird', 'Vrtojba');
insert into kino (ime, kraj) values ('Forster', 'Maddela');
insert into kino (ime, kraj) values ('Rockefeller', 'Montilla');
insert into kino (ime, kraj) values ('Comanche', 'Toulon');
insert into kino (ime, kraj) values ('Fuller', 'Merkezköy');
insert into kino (ime, kraj) values ('Fisk', 'Libode');
insert into kino (ime, kraj) values ('Green', 'Ḩammām Damt');
insert into kino (ime, kraj) values ('Rowland', 'Falun');
insert into kino (ime, kraj) values ('Thompson', 'Xuebu');
insert into kino (ime, kraj) values ('Trailsway', 'Shuigou');
insert into kino (ime, kraj) values ('Anniversary', 'Kangani');
insert into kino (ime, kraj) values ('Buhler', 'Pueblo Nuevo');
insert into kino (ime, kraj) values ('Lunder', 'Bataiporã');
insert into kino (ime, kraj) values ('Pepper Wood', 'San Isidro');
insert into kino (ime, kraj) values ('Prairieview', '‘Ābūd');
insert into kino (ime, kraj) values ('Maple Wood', 'Babice');
insert into kino (ime, kraj) values ('Prairieview', 'Qal‘ah-ye Kuhnah');
insert into kino (ime, kraj) values ('Blackbird', 'Gonzalo Pizarro');
insert into kino (ime, kraj) values ('Starling', 'Sete Cidades');
insert into kino (ime, kraj) values ('Main', 'Xagmakajor');
insert into kino (ime, kraj) values ('La Follette', 'Ödeshög');
insert into kino (ime, kraj) values ('Waubesa', 'Barbacena');
insert into kino (ime, kraj) values ('Talmadge', 'Saint-Marcellin');
insert into kino (ime, kraj) values ('Prentice', 'Taourirt');
insert into kino (ime, kraj) values ('Rieder', 'Combita');
insert into kino (ime, kraj) values ('Lerdahl', 'Kaishantun');
insert into kino (ime, kraj) values ('Mitchell', 'Papilawe');
insert into kino (ime, kraj) values ('Talisman', 'Alexandria');
insert into kino (ime, kraj) values ('Londonderry', 'Bowen Island');
insert into kino (ime, kraj) values ('Quincy', 'Potiskum');
insert into kino (ime, kraj) values ('Pepper Wood', 'Qagan Obo');
insert into kino (ime, kraj) values ('Hanover', 'Haramgai');
insert into kino (ime, kraj) values ('Cordelia', 'Chmielno');
insert into kino (ime, kraj) values ('Northport', 'Bemposta');
insert into kino (ime, kraj) values ('Sutherland', 'Lindavista');
insert into kino (ime, kraj) values ('Buhler', 'Osias');
insert into kino (ime, kraj) values ('Talisman', 'Silvares');
insert into kino (ime, kraj) values ('Hayes', 'Bolkhov');
insert into kino (ime, kraj) values ('Fair Oaks', 'Zhuli');
insert into kino (ime, kraj) values ('Sutteridge', 'Jinquan');
insert into kino (ime, kraj) values ('Fairfield', 'Chimboy Shahri');
insert into kino (ime, kraj) values ('Hoffman', 'Yanmenkou');
insert into kino (ime, kraj) values ('American', 'Nueve de Julio');
insert into kino (ime, kraj) values ('Upham', 'Katsuta');
insert into kino (ime, kraj) values ('Pankratz', 'Las Lajas');
insert into kino (ime, kraj) values ('Waywood', 'Darma');
insert into kino (ime, kraj) values ('Algoma', 'Wangjiaping');
insert into kino (ime, kraj) values ('South', 'Lesnoy');
insert into kino (ime, kraj) values ('Washington', 'Kalimati');
insert into kino (ime, kraj) values ('Anzinger', 'Ono');
insert into kino (ime, kraj) values ('Jay', 'Abade de Neiva');
insert into kino (ime, kraj) values ('Moulton', 'Jilong');
insert into kino (ime, kraj) values ('Independence', 'Trinidad');
insert into kino (ime, kraj) values ('Katie', 'El Paso');
insert into kino (ime, kraj) values ('Mockingbird', 'Boden');
insert into kino (ime, kraj) values ('Melrose', 'Kuantan');
insert into kino (ime, kraj) values ('Paget', 'Phrae');
insert into kino (ime, kraj) values ('Maywood', 'Grenoble');
insert into kino (ime, kraj) values ('Tony', 'Périgueux');
insert into kino (ime, kraj) values ('Northridge', 'Baishuitan');
insert into kino (ime, kraj) values ('Farmco', 'Luka nad Jihlavou');
insert into kino (ime, kraj) values ('Rowland', 'Pueblo Nuevo Viñas');
insert into kino (ime, kraj) values ('Ridgeway', 'Checca');
insert into kino (ime, kraj) values ('Meadow Vale', 'Tabatinga');
insert into kino (ime, kraj) values ('Clyde Gallagher', 'Sandakan');
insert into kino (ime, kraj) values ('Butternut', 'Amherst');
insert into kino (ime, kraj) values ('David', 'Duobagou');
insert into kino (ime, kraj) values ('Nobel', 'Wengaingo');
insert into kino (ime, kraj) values ('Shoshone', 'Bistrica ob Sotli');
insert into kino (ime, kraj) values ('Mallard', 'Alurbulu');
insert into kino (ime, kraj) values ('Brown', 'Kokembang');
insert into kino (ime, kraj) values ('Heffernan', 'Houk');
insert into kino (ime, kraj) values ('Golf', 'Muzaffargarh');
insert into kino (ime, kraj) values ('Melvin', 'Faqqū‘ah');
insert into kino (ime, kraj) values ('Village Green', 'Pasar');
insert into kino (ime, kraj) values ('School', 'Kinalansan');
insert into kino (ime, kraj) values ('Fallview', 'Mazeikiai');
insert into kino (ime, kraj) values ('Golf', 'Cambebba');
insert into kino (ime, kraj) values ('Orin', 'Hovås');
insert into kino (ime, kraj) values ('Jenna', 'Ferapontovo');
insert into kino (ime, kraj) values ('Stuart', 'San Juan');
insert into kino (ime, kraj) values ('Bay', 'Jiguaní');
insert into kino (ime, kraj) values ('Sullivan', 'Tyarlevo');
insert into kino (ime, kraj) values ('Continental', 'Ngromo');
insert into kino (ime, kraj) values ('Northridge', 'Buerarema');
insert into kino (ime, kraj) values ('John Wall', 'Brits');
insert into kino (ime, kraj) values ('Grayhawk', 'Holma');
insert into kino (ime, kraj) values ('Pennsylvania', 'Taishihe');
insert into kino (ime, kraj) values ('Bayside', 'Valongo');
insert into kino (ime, kraj) values ('Hanson', 'Aiguo');
insert into kino (ime, kraj) values ('Ohio', 'Tushi');
insert into kino (ime, kraj) values ('Merrick', 'Tuanjie');
insert into kino (ime, kraj) values ('Mosinee', 'Varnsdorf');
insert into kino (ime, kraj) values ('Gina', 'Palebunan');
insert into kino (ime, kraj) values ('Kingsford', 'Kraaifontein');
insert into kino (ime, kraj) values ('Kropf', 'Gonghe');
insert into kino (ime, kraj) values ('2nd', 'Zhenjiang');
insert into kino (ime, kraj) values ('Carey', 'Rongxing');
insert into kino (ime, kraj) values ('Scott', 'Belford Roxo');
insert into kino (ime, kraj) values ('Sycamore', 'Jaguarari');
insert into kino (ime, kraj) values ('Lunder', 'Chamical');
insert into kino (ime, kraj) values ('Harbort', 'Arrepiado');
insert into kino (ime, kraj) values ('Hazelcrest', 'Portela');
insert into kino (ime, kraj) values ('Hintze', 'Llacanora');
insert into kino (ime, kraj) values ('Canary', 'Chulabhorn');
insert into kino (ime, kraj) values ('Knutson', 'Kramat');
insert into kino (ime, kraj) values ('Dapin', 'Bafilo');
insert into kino (ime, kraj) values ('Onsgard', 'Palma De Mallorca');
insert into kino (ime, kraj) values ('Twin Pines', 'Guniushan');
insert into kino (ime, kraj) values ('Morrow', 'Hullo');
insert into kino (ime, kraj) values ('Glendale', 'Naftalan');
insert into kino (ime, kraj) values ('Charing Cross', 'Vällingby');
insert into kino (ime, kraj) values ('Colorado', 'Dizhai');
insert into kino (ime, kraj) values ('Comanche', 'Nāḩiyat as Sab‘ Biyār');
insert into kino (ime, kraj) values ('Schurz', 'Monastyrishche');
insert into kino (ime, kraj) values ('Atwood', 'Yilongyong');
insert into kino (ime, kraj) values ('Sauthoff', 'Moryń');
insert into kino (ime, kraj) values ('Schlimgen', 'Sembon');
insert into kino (ime, kraj) values ('Pawling', 'Ingenio');
insert into kino (ime, kraj) values ('Eastwood', 'Toužim');
insert into kino (ime, kraj) values ('Stang', 'Tiébo');
insert into kino (ime, kraj) values ('Merrick', 'Yakovlevo');
insert into kino (ime, kraj) values ('Tennessee', 'Tubualá');
insert into kino (ime, kraj) values ('Redwing', 'Kabar Utara');
insert into kino (ime, kraj) values ('Shoshone', 'Macaé');
insert into kino (ime, kraj) values ('Scoville', 'Abaeté');
insert into kino (ime, kraj) values ('Sherman', 'Katunayaka');
insert into kino (ime, kraj) values ('Fisk', 'Suba');
insert into kino (ime, kraj) values ('Arapahoe', 'Zhongguan');
insert into kino (ime, kraj) values ('Spohn', 'Bolobo');
insert into kino (ime, kraj) values ('Memorial', 'Gózd');
insert into kino (ime, kraj) values ('Burning Wood', 'Farroupilha');
insert into kino (ime, kraj) values ('8th', 'Åmål');
insert into kino (ime, kraj) values ('Hollow Ridge', 'Catende');
insert into kino (ime, kraj) values ('Meadow Ridge', 'Leninsk');
insert into kino (ime, kraj) values ('Harbort', 'Cernache do Bonjardim');
insert into kino (ime, kraj) values ('Miller', 'Riyadh');
insert into kino (ime, kraj) values ('Reindahl', 'Gao’an');
insert into kino (ime, kraj) values ('Little Fleur', 'Vigo');
insert into kino (ime, kraj) values ('Grim', 'Североморск-3');
insert into kino (ime, kraj) values ('Little Fleur', 'Petropavlovka');
insert into kino (ime, kraj) values ('Orin', 'Pewel Wielka');
insert into kino (ime, kraj) values ('Morning', 'Berkovitsa');
insert into kino (ime, kraj) values ('Bay', 'Petit Valley');
insert into kino (ime, kraj) values ('Springs', 'Linëvo');
insert into kino (ime, kraj) values ('Meadow Ridge', 'Xiaoyang');
insert into kino (ime, kraj) values ('Fuller', 'Chikwawa');
insert into kino (ime, kraj) values ('Oneill', 'Sadao');
insert into kino (ime, kraj) values ('Surrey', 'Rokytnice');
insert into kino (ime, kraj) values ('Utah', 'Troitsk');
insert into kino (ime, kraj) values ('Victoria', 'Xigangzi');
insert into kino (ime, kraj) values ('Kedzie', 'Kumla');
insert into kino (ime, kraj) values ('Dexter', 'Gerelayang');
insert into kino (ime, kraj) values ('East', 'Jembayan Hitam');
insert into kino (ime, kraj) values ('Monterey', 'Mīr Bachah Kōṯ');
insert into kino (ime, kraj) values ('Pleasure', 'Blantyre');
insert into kino (ime, kraj) values ('Marquette', 'Xinzhan');
insert into kino (ime, kraj) values ('Lunder', 'Ḩalabjah');
insert into kino (ime, kraj) values ('Packers', 'Longsheng');
insert into kino (ime, kraj) values ('Amoth', 'Varge Mondar');
insert into kino (ime, kraj) values ('Tennyson', 'Tiaong');
insert into kino (ime, kraj) values ('Bluestem', 'Frederico Westphalen');
insert into kino (ime, kraj) values ('Eastlawn', 'San Pedro Masahuat');
insert into kino (ime, kraj) values ('Anderson', 'Bodzentyn');
insert into kino (ime, kraj) values ('Harbort', 'Guéret');
insert into kino (ime, kraj) values ('Center', 'Manhumirim');
insert into kino (ime, kraj) values ('Cherokee', 'Widuchowa');
insert into kino (ime, kraj) values ('Linden', 'Negotin');
insert into kino (ime, kraj) values ('Brentwood', 'Kutamandarakan');
insert into kino (ime, kraj) values ('Dryden', 'Tambopata');
insert into kino (ime, kraj) values ('Badeau', 'Shanhou');
insert into kino (ime, kraj) values ('Twin Pines', 'Étampes');
insert into kino (ime, kraj) values ('Butterfield', 'Santi Suk');
insert into kino (ime, kraj) values ('Talmadge', 'Guilhabreu');
insert into kino (ime, kraj) values ('Columbus', 'Kontagora');
insert into kino (ime, kraj) values ('Mcbride', 'Łękawica');
insert into kino (ime, kraj) values ('Northland', 'Chisec');
insert into kino (ime, kraj) values ('Namekagon', 'Sosnovka');
insert into kino (ime, kraj) values ('Meadow Ridge', 'Biasong');
insert into kino (ime, kraj) values ('Hollow Ridge', 'Smithers');
insert into kino (ime, kraj) values ('Fulton', 'Muarabadak');
insert into kino (ime, kraj) values ('Morrow', 'Čerčany');
insert into kino (ime, kraj) values ('Rowland', 'Mahates');
insert into kino (ime, kraj) values ('Fremont', 'Tiaodeng');
insert into kino (ime, kraj) values ('Rigney', 'Puerto de Nutrias');
insert into kino (ime, kraj) values ('Chinook', 'Zhucun');
insert into kino (ime, kraj) values ('David', 'Zhuangtou');
insert into kino (ime, kraj) values ('Bluestem', 'Ijuí');
insert into kino (ime, kraj) values ('Manley', 'Hato Mayor del Rey');
insert into kino (ime, kraj) values ('Sloan', 'Retkovci');
insert into kino (ime, kraj) values ('Trailsway', 'Jeżów');
insert into kino (ime, kraj) values ('Valley Edge', 'Penamacor');
insert into kino (ime, kraj) values ('David', 'Obolo-Eke (1)');
insert into kino (ime, kraj) values ('Bultman', 'Bodø');
insert into kino (ime, kraj) values ('Buhler', 'Tver');
insert into kino (ime, kraj) values ('Beilfuss', 'Nacka');
insert into kino (ime, kraj) values ('Heffernan', 'Jincun');
insert into kino (ime, kraj) values ('Lyons', 'Veghel');
insert into kino (ime, kraj) values ('Sutherland', 'Shuyuan Zhen');
insert into kino (ime, kraj) values ('Pepper Wood', 'Marseille');
insert into kino (ime, kraj) values ('Monica', 'Kocēni');
insert into kino (ime, kraj) values ('Schmedeman', 'Sande São Martinho');
insert into kino (ime, kraj) values ('Emmet', 'Lyaskovets');
insert into kino (ime, kraj) values ('Tomscot', 'Al Ma‘baţlī');
insert into kino (ime, kraj) values ('Maple', 'Sahnaiya');
insert into kino (ime, kraj) values ('Sugar', 'Bilbays');
insert into kino (ime, kraj) values ('Pennsylvania', 'Marataizes');
insert into kino (ime, kraj) values ('Fair Oaks', 'Malway');
insert into kino (ime, kraj) values ('Mayer', 'Qırmızı Samux');
insert into kino (ime, kraj) values ('Carpenter', 'Karlstad');
insert into kino (ime, kraj) values ('Duke', 'Lolak');
insert into kino (ime, kraj) values ('Buell', 'Pontevedra');
insert into kino (ime, kraj) values ('Rusk', 'Serh');
insert into kino (ime, kraj) values ('Bluestem', 'Vavozh');
insert into kino (ime, kraj) values ('Hansons', 'Chai Badan');
insert into kino (ime, kraj) values ('Aberg', 'Salto');
insert into kino (ime, kraj) values ('Thompson', 'Starokorsunskaya');
insert into kino (ime, kraj) values ('Esch', 'Belo Oriente');
insert into kino (ime, kraj) values ('Rigney', 'Potosí');
insert into kino (ime, kraj) values ('Oxford', 'Idenao');
insert into kino (ime, kraj) values ('Sundown', 'Wiset Chaichan');
insert into kino (ime, kraj) values ('Hayes', 'Presa');
insert into kino (ime, kraj) values ('Forest Dale', 'Masipi West');
insert into kino (ime, kraj) values ('Maywood', 'Krajan');
insert into kino (ime, kraj) values ('Hoffman', 'Madang');
insert into kino (ime, kraj) values ('Eggendart', 'Księżpol');
insert into kino (ime, kraj) values ('Linden', 'Jakubów');
insert into kino (ime, kraj) values ('Ridgeview', 'Baih');
insert into kino (ime, kraj) values ('Talmadge', 'Uddevalla');
insert into kino (ime, kraj) values ('High Crossing', 'Zhaozhen');
insert into kino (ime, kraj) values ('Northview', 'Henglu');
insert into kino (ime, kraj) values ('Melody', 'Baabda');
insert into kino (ime, kraj) values ('Sheridan', 'Kalpin');
insert into kino (ime, kraj) values ('Glendale', 'Saint-Jean-de-Védas');
insert into kino (ime, kraj) values ('Mifflin', 'Ocampo');
insert into kino (ime, kraj) values ('Loeprich', 'Gwio Kura');
insert into kino (ime, kraj) values ('Stuart', 'Sacapulas');
insert into kino (ime, kraj) values ('Gale', 'Mariestad');
insert into kino (ime, kraj) values ('Delladonna', 'Krajenka');
insert into kino (ime, kraj) values ('Independence', 'Touguinha');
insert into kino (ime, kraj) values ('Di Loreto', 'Ikey');
insert into kino (ime, kraj) values ('Upham', 'Caeté');
