insert into kino (ime, kraj) values ('Browning', 'Ershilipu');
insert into kino (ime, kraj) values ('Towne', 'Goragorskiy');
insert into kino (ime, kraj) values ('Killdeer', 'Shisandaogou');
insert into kino (ime, kraj) values ('Wayridge', 'Carolina');
insert into kino (ime, kraj) values ('Rusk', 'Lenart v Slov. Goricah');
insert into kino (ime, kraj) values ('Service', 'Sukaratu');
insert into kino (ime, kraj) values ('Lighthouse Bay', 'Agudos');
insert into kino (ime, kraj) values ('Tennyson', 'Pedrogão');
insert into kino (ime, kraj) values ('Steensland', 'Darovskoy');
insert into kino (ime, kraj) values ('Main', 'Jerez');
insert into kino (ime, kraj) values ('Morningstar', 'Escada');
insert into kino (ime, kraj) values ('Prairieview', 'Palaiópyrgos');
insert into kino (ime, kraj) values ('Hoffman', 'Blois');
insert into kino (ime, kraj) values ('Cottonwood', 'Pacar');
insert into kino (ime, kraj) values ('Anthes', 'Huangshi');
insert into kino (ime, kraj) values ('Lakewood', 'Silver Spring');
insert into kino (ime, kraj) values ('Judy', 'Paris 19');
insert into kino (ime, kraj) values ('Coleman', 'Aso');
insert into kino (ime, kraj) values ('Ohio', 'Allen');
insert into kino (ime, kraj) values ('Emmet', 'Klemunan');
insert into kino (ime, kraj) values ('Linden', 'Panzhou');
insert into kino (ime, kraj) values ('Carioca', 'Ban Phai');
insert into kino (ime, kraj) values ('Spohn', 'Ćmielów');
insert into kino (ime, kraj) values ('Grim', '''Ali Sabieh');
insert into kino (ime, kraj) values ('Vermont', 'Ash Shuqayrah');
insert into kino (ime, kraj) values ('Ruskin', 'Amboise');
insert into kino (ime, kraj) values ('Birchwood', 'Dolní Studénky');
insert into kino (ime, kraj) values ('Village Green', 'Sumberrejo');
insert into kino (ime, kraj) values ('Village Green', 'Clichy');
insert into kino (ime, kraj) values ('Hooker', 'Prosperous');
insert into kino (ime, kraj) values ('Sugar', 'Borbon');
insert into kino (ime, kraj) values ('Dawn', 'Zürich');
insert into kino (ime, kraj) values ('Esch', 'Vilkaviskis');
insert into kino (ime, kraj) values ('Carioca', 'Detupia');
insert into kino (ime, kraj) values ('Gulseth', 'Gwangjeok');
insert into kino (ime, kraj) values ('Canary', 'Dongqu');
insert into kino (ime, kraj) values ('Bartelt', 'Zhamao');
insert into kino (ime, kraj) values ('Calypso', 'Sioguí Abajo');
insert into kino (ime, kraj) values ('Northland', 'Salto');
insert into kino (ime, kraj) values ('Badeau', 'Nueva Manoa');
insert into kino (ime, kraj) values ('Waxwing', 'Somita');
insert into kino (ime, kraj) values ('Lakewood Gardens', 'Prozor');
insert into kino (ime, kraj) values ('Eagle Crest', 'Henghe');
insert into kino (ime, kraj) values ('Fairfield', 'Waru');
insert into kino (ime, kraj) values ('Moose', 'Pagelaran');
insert into kino (ime, kraj) values ('Autumn Leaf', 'Paris 15');
insert into kino (ime, kraj) values ('Pine View', 'Bourges');
insert into kino (ime, kraj) values ('Golden Leaf', 'Companhia de Baixo');
insert into kino (ime, kraj) values ('Holmberg', 'Beppu');
insert into kino (ime, kraj) values ('Eastlawn', 'Kermānshāh');
insert into kino (ime, kraj) values ('Mayfield', 'Maskinongé');
insert into kino (ime, kraj) values ('Knutson', 'Nanshan');
insert into kino (ime, kraj) values ('Columbus', 'Banjar Asahduren');
insert into kino (ime, kraj) values ('Springs', 'Bugojno');
insert into kino (ime, kraj) values ('Maryland', 'Kuching');
insert into kino (ime, kraj) values ('Myrtle', 'Koshki');
insert into kino (ime, kraj) values ('Oakridge', 'Beaverton');
insert into kino (ime, kraj) values ('Bluestem', 'Shangma');
insert into kino (ime, kraj) values ('Warner', 'Liancheng');
insert into kino (ime, kraj) values ('Dorton', 'Wuci');
insert into kino (ime, kraj) values ('Scott', 'Cirumput');
insert into kino (ime, kraj) values ('East', 'Caburan');
insert into kino (ime, kraj) values ('Darwin', 'Braga');
insert into kino (ime, kraj) values ('Heffernan', 'Atlanta');
insert into kino (ime, kraj) values ('Bashford', 'Linoan');
insert into kino (ime, kraj) values ('Kinsman', 'Haoxinying');
insert into kino (ime, kraj) values ('Helena', 'Tampakan');
insert into kino (ime, kraj) values ('Atwood', 'Dorupare');
insert into kino (ime, kraj) values ('Oak', 'Hospitalet De Llobregat, L''');
insert into kino (ime, kraj) values ('Maple', 'Divjakë');
insert into kino (ime, kraj) values ('Shelley', 'Brataj');
insert into kino (ime, kraj) values ('Petterle', 'Zalesnoye');
insert into kino (ime, kraj) values ('Maple', 'Salinungan Proper');
insert into kino (ime, kraj) values ('Lakewood Gardens', 'Hashimoto');
insert into kino (ime, kraj) values ('Vahlen', 'Takehara');
insert into kino (ime, kraj) values ('Marcy', 'Queimados');
insert into kino (ime, kraj) values ('Montana', 'Hyesan-dong');
insert into kino (ime, kraj) values ('Darwin', 'Kuytun');
insert into kino (ime, kraj) values ('Fremont', 'Huangge');
insert into kino (ime, kraj) values ('Monument', 'Aş Şaff');
insert into kino (ime, kraj) values ('Independence', 'Vitebsk');
insert into kino (ime, kraj) values ('Granby', 'Marseille');
insert into kino (ime, kraj) values ('Morningstar', 'Kliteh');
insert into kino (ime, kraj) values ('Burrows', 'Achada');
insert into kino (ime, kraj) values ('Merrick', 'Gulao');
insert into kino (ime, kraj) values ('Hollow Ridge', 'Belawang');
insert into kino (ime, kraj) values ('Marquette', 'Xo’jayli Shahri');
insert into kino (ime, kraj) values ('Truax', 'Huashan');
insert into kino (ime, kraj) values ('Nevada', 'Bandar Seri Begawan');
insert into kino (ime, kraj) values ('Lakeland', 'Bun Barat');
insert into kino (ime, kraj) values ('Namekagon', 'Ithari');
insert into kino (ime, kraj) values ('Huxley', 'Núi Đối');
insert into kino (ime, kraj) values ('Bayside', 'Ituiutaba');
insert into kino (ime, kraj) values ('Memorial', 'Mascouche');
insert into kino (ime, kraj) values ('Luster', 'Gorzkowice');
insert into kino (ime, kraj) values ('Elmside', 'Zhangdiyingzi');
insert into kino (ime, kraj) values ('Farwell', 'Asopós');
insert into kino (ime, kraj) values ('Gateway', 'Moundou');
insert into kino (ime, kraj) values ('Delaware', 'Båstad');
insert into kino (ime, kraj) values ('Northport', 'Clearwater');
insert into kino (ime, kraj) values ('Westport', 'Triolet');
insert into kino (ime, kraj) values ('Larry', 'Sol’-Iletsk');
insert into kino (ime, kraj) values ('Bowman', 'Krasnyy Oktyabr’');
insert into kino (ime, kraj) values ('Shelley', 'Guanzhou');
insert into kino (ime, kraj) values ('Northland', 'Kedrovoye');
insert into kino (ime, kraj) values ('Reinke', 'Juncalito Abajo');
insert into kino (ime, kraj) values ('Anzinger', 'Schirmeck');
insert into kino (ime, kraj) values ('Oneill', 'Lennec');
insert into kino (ime, kraj) values ('Katie', 'Lafayette');
insert into kino (ime, kraj) values ('Leroy', 'Quintães');
insert into kino (ime, kraj) values ('Lakeland', 'Newark');
insert into kino (ime, kraj) values ('Arrowood', 'Xixi');
insert into kino (ime, kraj) values ('Riverside', 'Baligród');
insert into kino (ime, kraj) values ('Parkside', 'Kučevo');
insert into kino (ime, kraj) values ('Mariners Cove', 'Marcabamba');
insert into kino (ime, kraj) values ('Hauk', 'Turiys’k');
insert into kino (ime, kraj) values ('Maryland', 'Massy');
insert into kino (ime, kraj) values ('Sheridan', 'Satinka');
insert into kino (ime, kraj) values ('Express', 'Pīshvā');
insert into kino (ime, kraj) values ('Drewry', 'Cabanbanan');
insert into kino (ime, kraj) values ('Chinook', 'Tsukuba');
insert into kino (ime, kraj) values ('Superior', 'Staromyshastovskaya');
insert into kino (ime, kraj) values ('Mallory', 'San Francisco');
insert into kino (ime, kraj) values ('Pearson', 'Turku');
insert into kino (ime, kraj) values ('Darwin', 'Asan Kumbang');
insert into kino (ime, kraj) values ('Bluejay', 'Luofang');
insert into kino (ime, kraj) values ('Nobel', 'Pau');
insert into kino (ime, kraj) values ('Loomis', 'Dongshangen');
insert into kino (ime, kraj) values ('Schiller', 'Panyuran');
insert into kino (ime, kraj) values ('Browning', 'Wakapuken');
insert into kino (ime, kraj) values ('Kenwood', 'Manacapuru');
insert into kino (ime, kraj) values ('David', 'Boshof');
insert into kino (ime, kraj) values ('Mesta', 'Rizal');
insert into kino (ime, kraj) values ('Thackeray', 'Maslovka');
insert into kino (ime, kraj) values ('American', 'Youlan');
insert into kino (ime, kraj) values ('Briar Crest', 'Alcaldedíaz');
insert into kino (ime, kraj) values ('Kenwood', 'Wolanów');
insert into kino (ime, kraj) values ('Heffernan', 'Hutang');
insert into kino (ime, kraj) values ('Graedel', 'Changwon');
insert into kino (ime, kraj) values ('Dayton', 'Paris 17');
insert into kino (ime, kraj) values ('Pankratz', 'Besançon');
insert into kino (ime, kraj) values ('Sloan', 'Blagoevgrad');
insert into kino (ime, kraj) values ('Oriole', 'Beiling');
insert into kino (ime, kraj) values ('Carpenter', 'Tuusula');
insert into kino (ime, kraj) values ('Sloan', 'Nový Knín');
insert into kino (ime, kraj) values ('Londonderry', 'San Calixto');
insert into kino (ime, kraj) values ('Barby', 'Natarleba');
insert into kino (ime, kraj) values ('Blue Bill Park', 'Sarandi');
insert into kino (ime, kraj) values ('Memorial', 'Arboga');
insert into kino (ime, kraj) values ('Jackson', 'Plandi');
insert into kino (ime, kraj) values ('Bowman', 'Gunung');
insert into kino (ime, kraj) values ('Dottie', 'Lũng Hồ');
insert into kino (ime, kraj) values ('Northridge', 'Ilovka');
insert into kino (ime, kraj) values ('Superior', 'Cherëmushki');
insert into kino (ime, kraj) values ('Westerfield', 'Baranusa');
insert into kino (ime, kraj) values ('Golf Course', 'Yokohama');
insert into kino (ime, kraj) values ('Holmberg', 'Krosno');
insert into kino (ime, kraj) values ('Bunker Hill', 'Brakas');
insert into kino (ime, kraj) values ('Larry', 'Bāft');
insert into kino (ime, kraj) values ('Swallow', 'Alburitel');
insert into kino (ime, kraj) values ('Monument', 'Singida');
insert into kino (ime, kraj) values ('Doe Crossing', 'Horad Barysaw');
insert into kino (ime, kraj) values ('International', 'Lakeland');
insert into kino (ime, kraj) values ('Thierer', 'Rokiškis');
insert into kino (ime, kraj) values ('Marcy', 'Paris 01');
insert into kino (ime, kraj) values ('Merchant', 'Velykyy Klyuchiv');
insert into kino (ime, kraj) values ('Gulseth', 'Ożarowice');
insert into kino (ime, kraj) values ('Donald', 'Roermond');
insert into kino (ime, kraj) values ('Bluejay', 'Partizansk');
insert into kino (ime, kraj) values ('Kingsford', 'Koronganayam');
insert into kino (ime, kraj) values ('Washington', 'Sakerta Timur');
insert into kino (ime, kraj) values ('Anderson', 'Krajan');
insert into kino (ime, kraj) values ('Rowland', 'Arras');
insert into kino (ime, kraj) values ('Westend', 'Samamiya');
insert into kino (ime, kraj) values ('Bellgrove', 'Il’inskiy');
insert into kino (ime, kraj) values ('Milwaukee', 'Sịa');
insert into kino (ime, kraj) values ('8th', 'Shuanggang');
insert into kino (ime, kraj) values ('Monument', 'Kaliwates');
insert into kino (ime, kraj) values ('Aberg', 'Plaeng Yao');
insert into kino (ime, kraj) values ('Cherokee', 'Dzerzhinsk');
insert into kino (ime, kraj) values ('Knutson', 'Hanau');
insert into kino (ime, kraj) values ('Hanson', 'Senanga');
insert into kino (ime, kraj) values ('Chinook', 'Chengdong');
insert into kino (ime, kraj) values ('Acker', 'Cut-cut Primero');
insert into kino (ime, kraj) values ('Dorton', 'La Condamine');
insert into kino (ime, kraj) values ('Talmadge', 'Rosignol');
insert into kino (ime, kraj) values ('Golf Course', 'Mendeleyevo');
insert into kino (ime, kraj) values ('Dovetail', 'Gusong');
insert into kino (ime, kraj) values ('Scoville', 'San Juan');
insert into kino (ime, kraj) values ('Luster', 'Calasgasan');
insert into kino (ime, kraj) values ('Pearson', 'Poctol');
insert into kino (ime, kraj) values ('Forest Run', 'Aizkraukle');
insert into kino (ime, kraj) values ('Dovetail', 'Gaofeng');
insert into kino (ime, kraj) values ('Pearson', 'Faruka');
insert into kino (ime, kraj) values ('Laurel', 'Raejeru');
insert into kino (ime, kraj) values ('Evergreen', 'Tatsunochō-tominaga');
insert into kino (ime, kraj) values ('Sage', 'Chonghe');
insert into kino (ime, kraj) values ('Tony', 'Lófos');
insert into kino (ime, kraj) values ('Merrick', 'Indianapolis');
insert into kino (ime, kraj) values ('Eggendart', 'Goléré');
insert into kino (ime, kraj) values ('Garrison', 'Paris La Défense');
insert into kino (ime, kraj) values ('Farmco', 'Batulawang');
insert into kino (ime, kraj) values ('Monument', 'Verbilki');
insert into kino (ime, kraj) values ('Vernon', 'Vạn Giã');
insert into kino (ime, kraj) values ('Huxley', 'Burrel');
insert into kino (ime, kraj) values ('Eagan', 'Yanas');
insert into kino (ime, kraj) values ('Shelley', 'Biruinţa');
insert into kino (ime, kraj) values ('Jackson', 'Gorbunki');
insert into kino (ime, kraj) values ('Steensland', 'Patrocínio');
insert into kino (ime, kraj) values ('Burrows', 'Paris 14');
insert into kino (ime, kraj) values ('Jackson', 'Stockholm');
insert into kino (ime, kraj) values ('Gulseth', 'Daqingshan');
insert into kino (ime, kraj) values ('Dwight', 'Tash-Kumyr');
insert into kino (ime, kraj) values ('Transport', 'Khŭjand');
insert into kino (ime, kraj) values ('Southridge', 'Tieling');
insert into kino (ime, kraj) values ('Helena', 'Topola');
insert into kino (ime, kraj) values ('Hagan', 'Ljupina');
insert into kino (ime, kraj) values ('Northland', 'Montpellier');
insert into kino (ime, kraj) values ('Summerview', 'Longtian');
insert into kino (ime, kraj) values ('Mandrake', 'Egvekinot');
insert into kino (ime, kraj) values ('Ridgeway', 'Futuroscope');
insert into kino (ime, kraj) values ('Hanover', 'Leninogorsk');
insert into kino (ime, kraj) values ('Colorado', 'Quinta');
insert into kino (ime, kraj) values ('Springview', 'Mimbaan Timur');
insert into kino (ime, kraj) values ('Upham', 'Ambato Boeny');
insert into kino (ime, kraj) values ('Annamark', 'Caherconlish');
insert into kino (ime, kraj) values ('Mallory', 'Dadong');
insert into kino (ime, kraj) values ('Badeau', 'Huang’ao');
insert into kino (ime, kraj) values ('Tennessee', 'Žlutava');
insert into kino (ime, kraj) values ('Farmco', 'Ruše');
insert into kino (ime, kraj) values ('4th', 'La Paz');
insert into kino (ime, kraj) values ('Hayes', 'Amadeo');
insert into kino (ime, kraj) values ('West', 'Manūjān');
insert into kino (ime, kraj) values ('Beilfuss', 'Labao');
insert into kino (ime, kraj) values ('Manley', 'Bokoro');
insert into kino (ime, kraj) values ('Morningstar', 'Sidi Yahia el Gharb');
insert into kino (ime, kraj) values ('Dunning', 'Bilohirs’k');
insert into kino (ime, kraj) values ('Eggendart', 'Mýki');
insert into kino (ime, kraj) values ('Cardinal', 'Arish');
insert into kino (ime, kraj) values ('Mayer', 'Västerås');
insert into kino (ime, kraj) values ('Canary', 'Loures');
insert into kino (ime, kraj) values ('Kim', 'Esperanza');
insert into kino (ime, kraj) values ('Ridgeview', 'Zaragoza');
insert into kino (ime, kraj) values ('Armistice', 'Bida');
insert into kino (ime, kraj) values ('6th', 'La Sebala du Mornag');
insert into kino (ime, kraj) values ('Dakota', 'Madagali');
insert into kino (ime, kraj) values ('Redwing', 'Amsterdam');
insert into kino (ime, kraj) values ('Arrowood', 'Tebon');
insert into kino (ime, kraj) values ('Transport', 'Göteborg');
insert into kino (ime, kraj) values ('Esch', 'Paurito');
insert into kino (ime, kraj) values ('Montana', 'Kalaxilike');
insert into kino (ime, kraj) values ('Sycamore', 'Kara Suu');
insert into kino (ime, kraj) values ('Eagan', 'Caoxi');
insert into kino (ime, kraj) values ('Tony', 'Jianzhatan');
insert into kino (ime, kraj) values ('Towne', 'Jialai');
insert into kino (ime, kraj) values ('Clyde Gallagher', 'Ban Talat Nua');
insert into kino (ime, kraj) values ('David', 'Bahía Blanca');
insert into kino (ime, kraj) values ('Melby', 'Ban Takhun');
insert into kino (ime, kraj) values ('New Castle', 'Sukacai');
insert into kino (ime, kraj) values ('Drewry', 'Savannakhét');
insert into kino (ime, kraj) values ('Lakewood', 'Kota Bharu');
insert into kino (ime, kraj) values ('Talisman', 'Vlachovo Březí');
insert into kino (ime, kraj) values ('Waywood', 'Piedrancha');
insert into kino (ime, kraj) values ('Northview', 'Cigintung');
insert into kino (ime, kraj) values ('Lien', 'Somié');
insert into kino (ime, kraj) values ('Nova', 'Taisen-ri');
insert into kino (ime, kraj) values ('Rigney', 'Narsingdi');
insert into kino (ime, kraj) values ('Trailsway', 'Shibajiazi');
insert into kino (ime, kraj) values ('Cordelia', 'Denov');
insert into kino (ime, kraj) values ('Paget', 'San Vicente de Bique');
insert into kino (ime, kraj) values ('2nd', 'Pandansari');
insert into kino (ime, kraj) values ('Coolidge', 'Bahía Blanca');
insert into kino (ime, kraj) values ('Badeau', 'Beijie');
insert into kino (ime, kraj) values ('New Castle', 'Nilanapo');
insert into kino (ime, kraj) values ('Loomis', 'Miřetice');
insert into kino (ime, kraj) values ('Surrey', 'Baidian');
insert into kino (ime, kraj) values ('Eliot', 'South Tangerang');
insert into kino (ime, kraj) values ('Nancy', 'Honghai');
insert into kino (ime, kraj) values ('Grover', 'Cartago');
insert into kino (ime, kraj) values ('Debra', 'São José de Mipibu');
insert into kino (ime, kraj) values ('Marquette', 'Genet');
insert into kino (ime, kraj) values ('Thackeray', 'Sioux Falls');
insert into kino (ime, kraj) values ('Commercial', 'Ampasimanolotra');
insert into kino (ime, kraj) values ('Straubel', '‘Afula ‘Illit');
insert into kino (ime, kraj) values ('Becker', 'Sogod');
insert into kino (ime, kraj) values ('Ohio', 'Corupá');
insert into kino (ime, kraj) values ('Crest Line', 'Bagumbayan');
insert into kino (ime, kraj) values ('Jenna', 'Chipoka');
insert into kino (ime, kraj) values ('Park Meadow', 'Candelaria');
insert into kino (ime, kraj) values ('Miller', 'Villa Nueva');
insert into kino (ime, kraj) values ('Dennis', 'Anjani Barat');
insert into kino (ime, kraj) values ('Hollow Ridge', 'Lenīnskīy');
insert into kino (ime, kraj) values ('Sullivan', 'Sanyang');
insert into kino (ime, kraj) values ('Riverside', 'Anastácio');
insert into kino (ime, kraj) values ('Lindbergh', 'Bryansk');
insert into kino (ime, kraj) values ('Northview', 'Burayevo');
insert into kino (ime, kraj) values ('Hazelcrest', 'Zigong');
insert into kino (ime, kraj) values ('Dixon', 'Hořice');
insert into kino (ime, kraj) values ('Vernon', 'Los Rastrojos');
insert into kino (ime, kraj) values ('Golden Leaf', 'Pruszcz');
insert into kino (ime, kraj) values ('International', 'Vavozh');
insert into kino (ime, kraj) values ('Monica', 'Leleque');
insert into kino (ime, kraj) values ('Spaight', 'Suibara');
insert into kino (ime, kraj) values ('Village', 'Darong');
insert into kino (ime, kraj) values ('Meadow Valley', 'Fenjie');
insert into kino (ime, kraj) values ('Cottonwood', 'Częstochowa');
insert into kino (ime, kraj) values ('Anzinger', 'Huansheng');
insert into kino (ime, kraj) values ('Del Mar', 'Pignon');
insert into kino (ime, kraj) values ('Corscot', 'Nazaré');
insert into kino (ime, kraj) values ('Jenna', 'Maradi');
insert into kino (ime, kraj) values ('Old Shore', 'Boa Esperança');
insert into kino (ime, kraj) values ('Morningstar', 'Fengshan');
insert into kino (ime, kraj) values ('Orin', 'Předměřice nad Labem');
insert into kino (ime, kraj) values ('Kropf', 'Saint-Lambert-de-Lauzon');
insert into kino (ime, kraj) values ('Mifflin', 'Přibyslav');
insert into kino (ime, kraj) values ('Surrey', 'Jianshe');
insert into kino (ime, kraj) values ('Bellgrove', 'Fátima');
insert into kino (ime, kraj) values ('Garrison', 'Irahuan');
insert into kino (ime, kraj) values ('Springs', 'Borok');
insert into kino (ime, kraj) values ('Karstens', 'Masinloc');
insert into kino (ime, kraj) values ('Oxford', 'Palaran');
insert into kino (ime, kraj) values ('Debs', 'Tsaghkahovit');
insert into kino (ime, kraj) values ('Ridgeway', 'Inozemtsevo');
insert into kino (ime, kraj) values ('Oxford', 'Bandaran');
insert into kino (ime, kraj) values ('Atwood', 'Laleng');
insert into kino (ime, kraj) values ('Logan', 'Gaomiaoji');
insert into kino (ime, kraj) values ('Mallory', 'Moba');
insert into kino (ime, kraj) values ('Knutson', 'Eséka');
insert into kino (ime, kraj) values ('Blue Bill Park', 'Delft');
insert into kino (ime, kraj) values ('Paget', 'Somba');
insert into kino (ime, kraj) values ('Hallows', 'Girsereng');
insert into kino (ime, kraj) values ('John Wall', 'Mashtūl as Sūq');
insert into kino (ime, kraj) values ('Oneill', 'Banhā');
insert into kino (ime, kraj) values ('Golf Course', 'Xinan');
insert into kino (ime, kraj) values ('Continental', 'Jiangkou');
insert into kino (ime, kraj) values ('North', 'Payao');
insert into kino (ime, kraj) values ('Lillian', 'Ţayyibat al Imām');
insert into kino (ime, kraj) values ('Vermont', 'Koton Karifi');
insert into kino (ime, kraj) values ('David', 'Upernavik');
insert into kino (ime, kraj) values ('Sullivan', 'Pergan');
insert into kino (ime, kraj) values ('Graedel', 'Chanthaburi');
insert into kino (ime, kraj) values ('Longview', 'Baiqi');
insert into kino (ime, kraj) values ('Oneill', 'Cortiçóis');
insert into kino (ime, kraj) values ('Glacier Hill', 'Diaofeng');
insert into kino (ime, kraj) values ('Crownhardt', 'Żarki');
insert into kino (ime, kraj) values ('Rieder', 'Armenia');
insert into kino (ime, kraj) values ('Spenser', 'Meilin');
insert into kino (ime, kraj) values ('Mosinee', 'Bago');
insert into kino (ime, kraj) values ('Burrows', 'Manakara');
insert into kino (ime, kraj) values ('Straubel', 'Komatsushimachō');
insert into kino (ime, kraj) values ('Blue Bill Park', 'Vaiusu');
insert into kino (ime, kraj) values ('Clarendon', 'Levski');
insert into kino (ime, kraj) values ('Claremont', 'Rosebank');
insert into kino (ime, kraj) values ('Bayside', 'Fukiage-fujimi');
insert into kino (ime, kraj) values ('Spenser', 'Esperantina');
insert into kino (ime, kraj) values ('Randy', 'Rancamaya');
insert into kino (ime, kraj) values ('Ramsey', 'Zabierzów');
insert into kino (ime, kraj) values ('Autumn Leaf', 'Zhuangxing');
insert into kino (ime, kraj) values ('Brown', 'Heka');
insert into kino (ime, kraj) values ('Shopko', 'Gunungsari');
insert into kino (ime, kraj) values ('Forest', 'Sundbyberg');
insert into kino (ime, kraj) values ('Alpine', 'Gaoling');
insert into kino (ime, kraj) values ('Service', 'Ağdaş');
insert into kino (ime, kraj) values ('Pierstorff', 'Dailekh');
insert into kino (ime, kraj) values ('Coolidge', 'Shantou');
insert into kino (ime, kraj) values ('Montana', 'Nanfeng');
insert into kino (ime, kraj) values ('Dakota', 'Calabugao');
insert into kino (ime, kraj) values ('Vidon', 'Bulu');
insert into kino (ime, kraj) values ('Hallows', 'Dailing');
insert into kino (ime, kraj) values ('Fisk', 'Massaranduba');
insert into kino (ime, kraj) values ('Carioca', 'Sahavato');
insert into kino (ime, kraj) values ('Nancy', 'Bloemfontein');
insert into kino (ime, kraj) values ('Blaine', 'Matão');
insert into kino (ime, kraj) values ('Badeau', 'Videira');
insert into kino (ime, kraj) values ('Veith', 'Poniatowa');
insert into kino (ime, kraj) values ('Tennessee', 'Vratsa');
insert into kino (ime, kraj) values ('Surrey', 'Luodian');
insert into kino (ime, kraj) values ('7th', 'Pasembon');
insert into kino (ime, kraj) values ('East', 'Stryszawa');
insert into kino (ime, kraj) values ('Forest Dale', 'Den Chai');
insert into kino (ime, kraj) values ('Vernon', 'Issa');
insert into kino (ime, kraj) values ('Goodland', 'Jiancha');
insert into kino (ime, kraj) values ('Talisman', 'Leksand');
insert into kino (ime, kraj) values ('Pawling', 'Chervonohryhorivka');
insert into kino (ime, kraj) values ('Meadow Valley', 'Souran');
insert into kino (ime, kraj) values ('Tony', 'Nowy Sącz');
insert into kino (ime, kraj) values ('Steensland', 'Oslo');
insert into kino (ime, kraj) values ('Nobel', 'Sigiriya');
insert into kino (ime, kraj) values ('Commercial', 'Port-Gentil');
insert into kino (ime, kraj) values ('Summer Ridge', 'Sahnaiya');
insert into kino (ime, kraj) values ('Killdeer', 'San Miguel');
insert into kino (ime, kraj) values ('Esch', 'Strömsund');
insert into kino (ime, kraj) values ('Sachtjen', 'Olavarría');
insert into kino (ime, kraj) values ('Maple', 'Jitan');
insert into kino (ime, kraj) values ('Loeprich', 'Arras');
insert into kino (ime, kraj) values ('Sunfield', 'Moch');
insert into kino (ime, kraj) values ('Sutherland', 'Panjgūr');
insert into kino (ime, kraj) values ('Ohio', 'Gwangjeok');
insert into kino (ime, kraj) values ('Porter', 'Yandian');
insert into kino (ime, kraj) values ('Carioca', 'Carvoeira');
insert into kino (ime, kraj) values ('Raven', 'Gachancipá');
insert into kino (ime, kraj) values ('Hansons', 'Paraty');
insert into kino (ime, kraj) values ('Gateway', 'Kobarid');
insert into kino (ime, kraj) values ('Morningstar', 'Wonokerto');
insert into kino (ime, kraj) values ('Dapin', 'Teutônia');
insert into kino (ime, kraj) values ('Goodland', 'Drien Rampak');
insert into kino (ime, kraj) values ('Bay', 'Bureng');
insert into kino (ime, kraj) values ('Carberry', 'Yingwusitang');
insert into kino (ime, kraj) values ('La Follette', 'Pittsburgh');
insert into kino (ime, kraj) values ('Gale', 'Santa Cruz de El Seibo');
insert into kino (ime, kraj) values ('Dennis', 'Vojnić');
insert into kino (ime, kraj) values ('Lillian', 'Nosy Varika');
insert into kino (ime, kraj) values ('Mesta', 'Litian');
insert into kino (ime, kraj) values ('Hazelcrest', 'Leipsoí');
insert into kino (ime, kraj) values ('Ruskin', 'Wolbrom');
insert into kino (ime, kraj) values ('Schiller', 'Irbit');
insert into kino (ime, kraj) values ('Dorton', 'Togur');
insert into kino (ime, kraj) values ('Starling', 'Iqaluit');
insert into kino (ime, kraj) values ('Blue Bill Park', 'Gazanjyk');
insert into kino (ime, kraj) values ('Eastwood', 'Ganta');
insert into kino (ime, kraj) values ('Petterle', 'Santa Luzia');
insert into kino (ime, kraj) values ('Loomis', 'Åhus');
insert into kino (ime, kraj) values ('Barnett', 'Duayaw Nkwanta');
insert into kino (ime, kraj) values ('Pawling', 'Wangong');
insert into kino (ime, kraj) values ('Gale', 'Dallas');
insert into kino (ime, kraj) values ('Portage', 'Sanguansi');
insert into kino (ime, kraj) values ('Bartelt', 'Hellevoetsluis');
insert into kino (ime, kraj) values ('Eggendart', 'Lérida');
insert into kino (ime, kraj) values ('Gale', 'HanHuang');
insert into kino (ime, kraj) values ('Vernon', 'Las Vegas');
insert into kino (ime, kraj) values ('Manley', 'Imus');
insert into kino (ime, kraj) values ('Lotheville', 'Pionerskiy');
insert into kino (ime, kraj) values ('Hanson', 'Szczecin');
insert into kino (ime, kraj) values ('Division', 'Masty');
insert into kino (ime, kraj) values ('Hallows', 'Vetluzhskiy');
insert into kino (ime, kraj) values ('Utah', 'Brasília de Minas');
insert into kino (ime, kraj) values ('Doe Crossing', 'Tōkamachi');
insert into kino (ime, kraj) values ('Dunning', 'Karata');
insert into kino (ime, kraj) values ('Farmco', 'Hirara');
insert into kino (ime, kraj) values ('Shelley', 'Lokavec');
insert into kino (ime, kraj) values ('Colorado', 'Pereira');
insert into kino (ime, kraj) values ('Fuller', 'Benito Juarez');
insert into kino (ime, kraj) values ('Hansons', 'Maykopskoye');
insert into kino (ime, kraj) values ('Hauk', 'Suya');
insert into kino (ime, kraj) values ('Prairieview', 'Naga');
insert into kino (ime, kraj) values ('Bartillon', 'Yujing');
insert into kino (ime, kraj) values ('Ramsey', 'Hobart');
insert into kino (ime, kraj) values ('Little Fleur', 'Santa Maria');
insert into kino (ime, kraj) values ('Barnett', 'Baiguo');
insert into kino (ime, kraj) values ('Kedzie', 'Shiogama');
insert into kino (ime, kraj) values ('Tomscot', 'Czechowice-Dziedzice');
insert into kino (ime, kraj) values ('Anthes', 'Birinci Aşıqlı');
insert into kino (ime, kraj) values ('Walton', 'Belas');
insert into kino (ime, kraj) values ('Brickson Park', 'Tigbaw');
insert into kino (ime, kraj) values ('Delaware', 'Andir');
insert into kino (ime, kraj) values ('Sachs', 'Arnoia');
insert into kino (ime, kraj) values ('Cottonwood', 'Grębów');
insert into kino (ime, kraj) values ('Buena Vista', 'Bunog');
insert into kino (ime, kraj) values ('Sutherland', 'Jingyang');
insert into kino (ime, kraj) values ('Scott', 'Kolo');
insert into kino (ime, kraj) values ('Oneill', 'Benito Juarez');
insert into kino (ime, kraj) values ('Johnson', 'Toktogul');
insert into kino (ime, kraj) values ('Lindbergh', 'Voiron');
insert into kino (ime, kraj) values ('Rockefeller', 'Limbaži');
insert into kino (ime, kraj) values ('Arapahoe', 'Bol’shoy Kamen’');
insert into kino (ime, kraj) values ('Schmedeman', 'Uva');
insert into kino (ime, kraj) values ('Ramsey', 'Uarini');
insert into kino (ime, kraj) values ('Oakridge', 'Wenfang');
insert into kino (ime, kraj) values ('Springview', 'Sydney');
insert into kino (ime, kraj) values ('Heath', 'Boulsa');
insert into kino (ime, kraj) values ('Logan', 'Caaguazú');
insert into kino (ime, kraj) values ('Coleman', 'Lysyanka');
insert into kino (ime, kraj) values ('Farragut', 'Kota Kinabalu');
insert into kino (ime, kraj) values ('Granby', 'Rattanaburi');
insert into kino (ime, kraj) values ('Bartelt', 'Tyazhinskiy');
insert into kino (ime, kraj) values ('Carberry', 'Shtip');
insert into kino (ime, kraj) values ('Katie', 'Bojongsarung');
insert into kino (ime, kraj) values ('Charing Cross', 'Dois Portos');
insert into kino (ime, kraj) values ('Iowa', 'Babura');
insert into kino (ime, kraj) values ('Stone Corner', 'Hexi');
insert into kino (ime, kraj) values ('School', 'San Miguel');
insert into kino (ime, kraj) values ('Oneill', 'Zásmuky');
insert into kino (ime, kraj) values ('Ilene', 'Kuanfatu');
insert into kino (ime, kraj) values ('Gulseth', 'Lucan');
insert into kino (ime, kraj) values ('Milwaukee', 'Zwolle');
insert into kino (ime, kraj) values ('Quincy', 'Xilian');
insert into kino (ime, kraj) values ('Sauthoff', 'Malino');
insert into kino (ime, kraj) values ('Vahlen', 'Novoselec');
insert into kino (ime, kraj) values ('Caliangt', 'Sancha');
insert into kino (ime, kraj) values ('International', 'Pindobaçu');
insert into kino (ime, kraj) values ('Fuller', 'Arys');
insert into kino (ime, kraj) values ('Manitowish', 'Gucheng');
insert into kino (ime, kraj) values ('Harper', 'Eastern Suburbs Mc');
insert into kino (ime, kraj) values ('Service', 'Duifang');
insert into kino (ime, kraj) values ('7th', 'Carmen de Viboral');
insert into kino (ime, kraj) values ('Morning', 'Nagaoka');
insert into kino (ime, kraj) values ('Mitchell', 'Nioumamilima');
insert into kino (ime, kraj) values ('6th', 'Semboropasar');
insert into kino (ime, kraj) values ('Thierer', 'Rosthern');
insert into kino (ime, kraj) values ('Banding', 'Ar Rubū‘');
insert into kino (ime, kraj) values ('Hovde', 'Borucin');
insert into kino (ime, kraj) values ('Gina', 'Luotuo');
insert into kino (ime, kraj) values ('David', 'Binuangan');
insert into kino (ime, kraj) values ('Doe Crossing', 'Kaffrine');
insert into kino (ime, kraj) values ('Thierer', 'Huibu');
insert into kino (ime, kraj) values ('Tennyson', 'Vårby');
insert into kino (ime, kraj) values ('Nova', 'Los Boquerones');
insert into kino (ime, kraj) values ('Kings', 'Dijon');
insert into kino (ime, kraj) values ('Talisman', 'Laško');
insert into kino (ime, kraj) values ('Springs', 'Xiaopingba');
insert into kino (ime, kraj) values ('Bunting', 'Guanxi');
insert into kino (ime, kraj) values ('Debs', 'Dula’er Ewenke Minzu');
insert into kino (ime, kraj) values ('Pennsylvania', 'Hutang');
insert into kino (ime, kraj) values ('Springs', 'Huolu');
insert into kino (ime, kraj) values ('Jenna', 'Ostrów Lubelski');
insert into kino (ime, kraj) values ('Bowman', 'Mlonggo');
insert into kino (ime, kraj) values ('Saint Paul', 'Bordeaux');
insert into kino (ime, kraj) values ('Browning', 'Norrköping');
insert into kino (ime, kraj) values ('Morrow', 'Jardín América');
insert into kino (ime, kraj) values ('Kropf', 'Itamarandiba');
insert into kino (ime, kraj) values ('Valley Edge', 'Businovo');
insert into kino (ime, kraj) values ('Kennedy', 'La Dorada');
insert into kino (ime, kraj) values ('Sullivan', 'Fada N''gourma');
insert into kino (ime, kraj) values ('Luster', 'Mosoc Llacta');
insert into kino (ime, kraj) values ('Clyde Gallagher', 'Szczytno');
insert into kino (ime, kraj) values ('Bayside', 'Hengfan');
insert into kino (ime, kraj) values ('Drewry', 'Kyosai');
insert into kino (ime, kraj) values ('Carey', 'Trà Ôn');
insert into kino (ime, kraj) values ('Cottonwood', 'Luoshan');
insert into kino (ime, kraj) values ('Nelson', 'Belomorsk');
insert into kino (ime, kraj) values ('Morningstar', 'Kratié');
insert into kino (ime, kraj) values ('Burning Wood', 'Großklein');
insert into kino (ime, kraj) values ('Weeping Birch', 'Ferreñafe');
insert into kino (ime, kraj) values ('Emmet', 'Zlonice');
insert into kino (ime, kraj) values ('Rigney', 'Mytishchi');
insert into kino (ime, kraj) values ('Vera', 'Kansas City');
insert into kino (ime, kraj) values ('Farragut', 'Karangsari');
insert into kino (ime, kraj) values ('Muir', 'Orleans');
insert into kino (ime, kraj) values ('Blaine', 'Baranovichi');
insert into kino (ime, kraj) values ('Schiller', 'Anyuan');
insert into kino (ime, kraj) values ('Golf', 'Ropa');
insert into kino (ime, kraj) values ('Hintze', 'Rokitno');
insert into kino (ime, kraj) values ('Mallard', 'Lianxia');
insert into kino (ime, kraj) values ('Vernon', 'Arzakan');
insert into kino (ime, kraj) values ('Eastlawn', 'Nicoya');
insert into kino (ime, kraj) values ('Leroy', 'Buenavista');
insert into kino (ime, kraj) values ('Hallows', 'Khanabad');
insert into kino (ime, kraj) values ('Shelley', 'Kadoma');
insert into kino (ime, kraj) values ('Stang', 'Firá');
insert into kino (ime, kraj) values ('Barnett', 'Francisco I Madero');
insert into kino (ime, kraj) values ('Cambridge', 'Zoumi');
insert into kino (ime, kraj) values ('Eagan', 'Zabrušany');
insert into kino (ime, kraj) values ('Moose', 'Portland');
insert into kino (ime, kraj) values ('Lakeland', 'Kainantu');
insert into kino (ime, kraj) values ('Anniversary', 'Lancaster');
insert into kino (ime, kraj) values ('Fremont', 'Atalhada');
insert into kino (ime, kraj) values ('Saint Paul', 'Montpellier');
insert into kino (ime, kraj) values ('Prairieview', 'Berezniki');
insert into kino (ime, kraj) values ('Monument', 'Xinjia');
insert into kino (ime, kraj) values ('Sloan', 'Kongsvinger');
insert into kino (ime, kraj) values ('Dorton', 'Lebao');
insert into kino (ime, kraj) values ('Commercial', 'Villeneuve-d''Ascq');
insert into kino (ime, kraj) values ('Summerview', 'Huaping');
insert into kino (ime, kraj) values ('Hazelcrest', 'Hegeng');
insert into kino (ime, kraj) values ('Mallard', 'San Antonio');
insert into kino (ime, kraj) values ('Hauk', 'Tenggong');
insert into kino (ime, kraj) values ('Clove', 'Almalaguês');
insert into kino (ime, kraj) values ('Thackeray', 'Cinyawar');
insert into kino (ime, kraj) values ('Warner', 'Kamionka Wielka');
insert into kino (ime, kraj) values ('Scofield', 'Kaliuling');
insert into kino (ime, kraj) values ('Pond', 'Sigaboy');
insert into kino (ime, kraj) values ('Atwood', 'Cabano');
insert into kino (ime, kraj) values ('Dawn', 'Anju');
insert into kino (ime, kraj) values ('Crownhardt', 'Labuan');
insert into kino (ime, kraj) values ('Nevada', 'Xinshiba');
insert into kino (ime, kraj) values ('Summerview', 'Emnambithi-Ladysmith');
insert into kino (ime, kraj) values ('Northridge', 'São José do Egito');
insert into kino (ime, kraj) values ('Delaware', 'Longchiqiao');
insert into kino (ime, kraj) values ('Dixon', 'Cam Lộ');
insert into kino (ime, kraj) values ('Golf View', 'Falun');
insert into kino (ime, kraj) values ('Artisan', 'Cortinhas');
insert into kino (ime, kraj) values ('Onsgard', 'Mahe');
insert into kino (ime, kraj) values ('Dorton', 'Nový Bydžov');
insert into kino (ime, kraj) values ('Algoma', 'Iwata');
insert into kino (ime, kraj) values ('Mallory', 'Huimin');
insert into kino (ime, kraj) values ('Hayes', 'Itarana');
insert into kino (ime, kraj) values ('Elmside', 'De la Paz');
insert into kino (ime, kraj) values ('Kingsford', 'Itapetinga');
insert into kino (ime, kraj) values ('Merrick', 'Baniachang');
insert into kino (ime, kraj) values ('Hauk', 'Rio do Sul');
insert into kino (ime, kraj) values ('Linden', 'Ziniaré');
insert into kino (ime, kraj) values ('Talisman', 'Karlstad');
insert into kino (ime, kraj) values ('Darwin', 'Mitrofanovka');
insert into kino (ime, kraj) values ('Mcguire', 'Xinmatou');
insert into kino (ime, kraj) values ('Elgar', 'Brändö');
insert into kino (ime, kraj) values ('Forster', 'Burgersdorp');
insert into kino (ime, kraj) values ('Prentice', 'Taza');
insert into kino (ime, kraj) values ('Rowland', 'Hai’an');
insert into kino (ime, kraj) values ('Heath', 'Meilong');
insert into kino (ime, kraj) values ('Merrick', 'Jendouba');
insert into kino (ime, kraj) values ('Summer Ridge', 'Hernani');
insert into kino (ime, kraj) values ('Corscot', 'Yeniköy');
insert into kino (ime, kraj) values ('Maple', 'Diébougou');
insert into kino (ime, kraj) values ('American Ash', 'Quetigny');
insert into kino (ime, kraj) values ('Sherman', 'Garland');
insert into kino (ime, kraj) values ('Prentice', 'Kafr Nubl');
insert into kino (ime, kraj) values ('Grayhawk', 'Taldykorgan');
insert into kino (ime, kraj) values ('Golf View', 'Águas Belas');
insert into kino (ime, kraj) values ('School', 'Yitulihe');
insert into kino (ime, kraj) values ('Nobel', 'Limoges');
insert into kino (ime, kraj) values ('Steensland', 'Huangling');
insert into kino (ime, kraj) values ('Saint Paul', 'Guangping');
insert into kino (ime, kraj) values ('Rockefeller', 'São Francisco');
insert into kino (ime, kraj) values ('Gina', 'La Paz Centro');
insert into kino (ime, kraj) values ('Butternut', 'Talata Mafara');
insert into kino (ime, kraj) values ('Norway Maple', 'Peskovka');
insert into kino (ime, kraj) values ('Schmedeman', 'Ibeto');
insert into kino (ime, kraj) values ('Dryden', 'Qarāwat Banī Zayd');
insert into kino (ime, kraj) values ('Northport', 'Fichē');
insert into kino (ime, kraj) values ('Kenwood', 'Galapa');
insert into kino (ime, kraj) values ('Colorado', 'Pujijie');
insert into kino (ime, kraj) values ('Magdeline', 'Huangcai');
insert into kino (ime, kraj) values ('Carberry', 'Enschede');
insert into kino (ime, kraj) values ('Eastwood', 'Hulu');
insert into kino (ime, kraj) values ('Wayridge', 'Elias Fausto');
insert into kino (ime, kraj) values ('Hintze', 'Las Piñas');
insert into kino (ime, kraj) values ('Anhalt', 'Jūrīsh');
insert into kino (ime, kraj) values ('Pierstorff', 'Zhuhu');
insert into kino (ime, kraj) values ('Sachs', 'Sremska Mitrovica');
insert into kino (ime, kraj) values ('Warbler', 'Berģi');
insert into kino (ime, kraj) values ('Lakeland', 'Nanjing');
insert into kino (ime, kraj) values ('Melody', 'Lappajärvi');
insert into kino (ime, kraj) values ('Kedzie', 'Tygda');
insert into kino (ime, kraj) values ('Shelley', 'Louiseville');
insert into kino (ime, kraj) values ('Elmside', 'Wakefield');
insert into kino (ime, kraj) values ('Park Meadow', 'Preiļi');
insert into kino (ime, kraj) values ('Northridge', 'Guantou');
insert into kino (ime, kraj) values ('Melvin', 'Luxi');
insert into kino (ime, kraj) values ('Hanover', 'Chonogol');
insert into kino (ime, kraj) values ('Green', 'Dalong');
insert into kino (ime, kraj) values ('Anhalt', 'Libertad');
insert into kino (ime, kraj) values ('High Crossing', 'Sinfra');
insert into kino (ime, kraj) values ('Blaine', 'Maduao');
insert into kino (ime, kraj) values ('Dapin', 'Dayr Dibwān');
insert into kino (ime, kraj) values ('Crescent Oaks', 'Ntungamo');
insert into kino (ime, kraj) values ('La Follette', 'Ngunguru');
insert into kino (ime, kraj) values ('Tennessee', 'Bačka Topola');
insert into kino (ime, kraj) values ('Declaration', 'Smach Mean Chey');
insert into kino (ime, kraj) values ('Mendota', 'Anmore');
insert into kino (ime, kraj) values ('Aberg', 'Staroutkinsk');
insert into kino (ime, kraj) values ('Bowman', 'Bystra');
insert into kino (ime, kraj) values ('Warner', 'Kulun');
insert into kino (ime, kraj) values ('Cody', 'Peski');
insert into kino (ime, kraj) values ('Riverside', 'Betim');
insert into kino (ime, kraj) values ('Loftsgordon', 'Cipunglu');
insert into kino (ime, kraj) values ('Eagle Crest', 'Fenglai');
insert into kino (ime, kraj) values ('Fairview', 'Água de Pau');
insert into kino (ime, kraj) values ('Surrey', 'Hot');
insert into kino (ime, kraj) values ('Meadow Ridge', 'Henghe');
insert into kino (ime, kraj) values ('Bunting', 'Soraya');
insert into kino (ime, kraj) values ('Jackson', 'Salavat');
insert into kino (ime, kraj) values ('Lakeland', 'Patapan');
insert into kino (ime, kraj) values ('Fair Oaks', 'Zhaozhen');
insert into kino (ime, kraj) values ('Pawling', 'Caratinga');
insert into kino (ime, kraj) values ('Old Gate', 'Pio');
insert into kino (ime, kraj) values ('Sunnyside', 'Bombu');
insert into kino (ime, kraj) values ('Manitowish', 'Nara');
insert into kino (ime, kraj) values ('Forster', 'Koa');
insert into kino (ime, kraj) values ('Prairie Rose', 'Cimuncang');
insert into kino (ime, kraj) values ('Anderson', 'Laiponda');
insert into kino (ime, kraj) values ('Redwing', 'Fort Myers');
insert into kino (ime, kraj) values ('Sheridan', 'Dianzi');
insert into kino (ime, kraj) values ('Cottonwood', 'Gorzyce');
insert into kino (ime, kraj) values ('Mcguire', 'Pita Kotte');
insert into kino (ime, kraj) values ('Loomis', 'Kafr Mandā');
insert into kino (ime, kraj) values ('Westridge', 'Youfang');
insert into kino (ime, kraj) values ('Nelson', 'Sandwīp');
insert into kino (ime, kraj) values ('Chinook', 'Buluangan');
insert into kino (ime, kraj) values ('Delladonna', 'Tielou');
insert into kino (ime, kraj) values ('8th', 'Kafir Qala');
insert into kino (ime, kraj) values ('Beilfuss', 'Olofström');
insert into kino (ime, kraj) values ('Russell', 'Rungis');
insert into kino (ime, kraj) values ('Upham', 'Hetou');
insert into kino (ime, kraj) values ('Prairieview', 'Köyliö');
insert into kino (ime, kraj) values ('Basil', 'Warin Chamrap');
insert into kino (ime, kraj) values ('Loeprich', 'Quipot');
insert into kino (ime, kraj) values ('Laurel', 'Wenhe');
insert into kino (ime, kraj) values ('Nobel', 'Taiping');
insert into kino (ime, kraj) values ('Tennyson', 'Kyzylzhar');
insert into kino (ime, kraj) values ('Dorton', 'Nikolayevka');
insert into kino (ime, kraj) values ('Vermont', 'Burevestnik');
insert into kino (ime, kraj) values ('Vahlen', 'Sumberdadi');
insert into kino (ime, kraj) values ('Prentice', 'Södertälje');
insert into kino (ime, kraj) values ('Gale', 'Ipoh');
insert into kino (ime, kraj) values ('Hauk', 'Victoria');
insert into kino (ime, kraj) values ('Transport', 'Bastak');
insert into kino (ime, kraj) values ('Sullivan', 'Daze');
insert into kino (ime, kraj) values ('Milwaukee', 'Nanjie');
insert into kino (ime, kraj) values ('Hazelcrest', 'Kikinda');
insert into kino (ime, kraj) values ('Spenser', 'Radzanów');
insert into kino (ime, kraj) values ('Welch', 'Chybie');
insert into kino (ime, kraj) values ('Veith', 'Kavār');
insert into kino (ime, kraj) values ('Burrows', 'Novovolyns’k');
insert into kino (ime, kraj) values ('Golf Course', 'Hobor');
insert into kino (ime, kraj) values ('Mccormick', 'Stęszew');
insert into kino (ime, kraj) values ('Fairfield', 'Saint-Quentin');
insert into kino (ime, kraj) values ('Grover', 'San Antonio');
insert into kino (ime, kraj) values ('Del Sol', 'Kulase');
insert into kino (ime, kraj) values ('Novick', 'Strenči');
insert into kino (ime, kraj) values ('Brown', 'Sunampe');
insert into kino (ime, kraj) values ('Shasta', 'Yên Lập');
insert into kino (ime, kraj) values ('Dryden', 'Seraya');
insert into kino (ime, kraj) values ('Corry', 'Jichang');
insert into kino (ime, kraj) values ('Village Green', 'Koua');
insert into kino (ime, kraj) values ('Amoth', 'Shewopo');
insert into kino (ime, kraj) values ('Goodland', 'Lapa do Lobo');
insert into kino (ime, kraj) values ('Bluejay', 'Changlong');
insert into kino (ime, kraj) values ('Menomonie', 'Fradelos');
insert into kino (ime, kraj) values ('Clyde Gallagher', 'Banjar Kelodan');
insert into kino (ime, kraj) values ('Mayfield', 'Shuangtian');
insert into kino (ime, kraj) values ('Menomonie', 'Nahariya');
insert into kino (ime, kraj) values ('Banding', 'Cairani');
insert into kino (ime, kraj) values ('Lerdahl', 'Lonya Chico');
insert into kino (ime, kraj) values ('Fremont', 'Arāk');
insert into kino (ime, kraj) values ('Moulton', 'Langkapcaang Hilir');
insert into kino (ime, kraj) values ('Northfield', 'Matanog');
insert into kino (ime, kraj) values ('Stephen', 'Sam Roi Yot');
insert into kino (ime, kraj) values ('Basil', 'Norak');
insert into kino (ime, kraj) values ('Mallory', 'Astara');
insert into kino (ime, kraj) values ('Lillian', 'Huachos');
insert into kino (ime, kraj) values ('Fair Oaks', 'Waitara');
insert into kino (ime, kraj) values ('Karstens', 'Weiyanggong');
insert into kino (ime, kraj) values ('Holy Cross', 'Chahe');
insert into kino (ime, kraj) values ('Raven', 'Yaizu');
insert into kino (ime, kraj) values ('Mayer', 'Palmito');
insert into kino (ime, kraj) values ('Gateway', 'Sandaotong');
insert into kino (ime, kraj) values ('Gina', 'Sepīdān');
insert into kino (ime, kraj) values ('Gulseth', 'Sens');
insert into kino (ime, kraj) values ('Duke', 'Jiawu');
insert into kino (ime, kraj) values ('Mitchell', 'Digne-les-Bains');
insert into kino (ime, kraj) values ('Fairfield', 'Kavadarci');
insert into kino (ime, kraj) values ('Muir', 'Xinqiaohe');
insert into kino (ime, kraj) values ('Coleman', 'Ziyang Chengguanzhen');
insert into kino (ime, kraj) values ('Menomonie', 'Sé');
insert into kino (ime, kraj) values ('Rigney', 'Skołyszyn');
insert into kino (ime, kraj) values ('Haas', 'Lailunggi');
insert into kino (ime, kraj) values ('Monterey', 'Changzhi');
insert into kino (ime, kraj) values ('Brentwood', 'Sūq Sibāḩ');
insert into kino (ime, kraj) values ('Moose', 'Ilha de Moçambique');
insert into kino (ime, kraj) values ('Duke', 'Morgados');
insert into kino (ime, kraj) values ('Golden Leaf', 'Caratinga');
insert into kino (ime, kraj) values ('Del Sol', 'Clearwater');
insert into kino (ime, kraj) values ('Emmet', 'Malway');
insert into kino (ime, kraj) values ('Park Meadow', 'Hats’avan');
insert into kino (ime, kraj) values ('Holy Cross', 'Bei’an');
insert into kino (ime, kraj) values ('Westerfield', 'Rambouillet');
insert into kino (ime, kraj) values ('Anderson', 'Xunzhong');
insert into kino (ime, kraj) values ('1st', 'Madrid');
insert into kino (ime, kraj) values ('Sloan', 'Pandan');
insert into kino (ime, kraj) values ('Browning', 'Souto da Casa');
insert into kino (ime, kraj) values ('Coolidge', 'Abastumani');
insert into kino (ime, kraj) values ('School', 'Dhrosiá');
insert into kino (ime, kraj) values ('Columbus', 'Menzel Jemil');
insert into kino (ime, kraj) values ('Erie', 'Terrugem');
insert into kino (ime, kraj) values ('Mendota', 'Kamenka');
insert into kino (ime, kraj) values ('Hansons', 'Congkar');
insert into kino (ime, kraj) values ('Shoshone', 'Dawan');
insert into kino (ime, kraj) values ('Pepper Wood', 'Dongchong');
insert into kino (ime, kraj) values ('Starling', 'Suka Makmue');
insert into kino (ime, kraj) values ('Warbler', 'Bayanhoshuu');
insert into kino (ime, kraj) values ('Kings', 'Charenton-le-Pont');
insert into kino (ime, kraj) values ('Springs', 'Dob');
insert into kino (ime, kraj) values ('Lillian', 'Rocky Mountain House');
insert into kino (ime, kraj) values ('Meadow Ridge', 'Hechuan');
insert into kino (ime, kraj) values ('Grasskamp', 'Taohua');
insert into kino (ime, kraj) values ('Butternut', 'Rancageneng Satu');
insert into kino (ime, kraj) values ('Eliot', 'Paloh');
insert into kino (ime, kraj) values ('Grasskamp', 'Lugu');
insert into kino (ime, kraj) values ('Milwaukee', 'Mucurapo');
insert into kino (ime, kraj) values ('Schmedeman', 'Luleå');
insert into kino (ime, kraj) values ('Dovetail', 'Sviadnov');
insert into kino (ime, kraj) values ('Forest', 'General Cabrera');
insert into kino (ime, kraj) values ('Little Fleur', 'Loudun');
insert into kino (ime, kraj) values ('Homewood', 'Izobil’nyy');
insert into kino (ime, kraj) values ('Golden Leaf', 'Qalqīlyah');
insert into kino (ime, kraj) values ('High Crossing', 'Tamianglayang');
insert into kino (ime, kraj) values ('Wayridge', 'Guishan');
insert into kino (ime, kraj) values ('Vernon', 'Pandean');
insert into kino (ime, kraj) values ('Sullivan', 'Vodnjan');
insert into kino (ime, kraj) values ('Declaration', 'Cikadondongdesa');
insert into kino (ime, kraj) values ('Warbler', 'Kilafors');
insert into kino (ime, kraj) values ('Merry', 'Abejorral');
insert into kino (ime, kraj) values ('Cambridge', 'Ārt Khwājah');
insert into kino (ime, kraj) values ('Hoepker', 'Almere Haven');
insert into kino (ime, kraj) values ('Shelley', 'Lubniewice');
insert into kino (ime, kraj) values ('Macpherson', 'Noeltoko');
insert into kino (ime, kraj) values ('Summer Ridge', 'Kuusjoki');
insert into kino (ime, kraj) values ('Ilene', 'Huanggang');
insert into kino (ime, kraj) values ('Merry', 'Mingyue');
insert into kino (ime, kraj) values ('Fairview', 'Bolhos');
insert into kino (ime, kraj) values ('Florence', 'Sumberrejo');
insert into kino (ime, kraj) values ('Goodland', 'Korenëvo');
insert into kino (ime, kraj) values ('Forster', 'Pingtian');
insert into kino (ime, kraj) values ('Claremont', 'Fuquan');
insert into kino (ime, kraj) values ('Arkansas', 'Gornyy');
insert into kino (ime, kraj) values ('Weeping Birch', 'Molo');
insert into kino (ime, kraj) values ('Ramsey', 'Bidbid');
insert into kino (ime, kraj) values ('Gerald', 'Dahewan');
insert into kino (ime, kraj) values ('Lunder', 'Watuagung');
insert into kino (ime, kraj) values ('Lakeland', 'Gongjiahe');
insert into kino (ime, kraj) values ('Hoepker', 'Lille');
insert into kino (ime, kraj) values ('Forest', 'Lolodorf');
insert into kino (ime, kraj) values ('Truax', 'Capitán Bado');
insert into kino (ime, kraj) values ('Rutledge', 'Kamogatachō-kamogata');
insert into kino (ime, kraj) values ('Shelley', 'Changshan');
insert into kino (ime, kraj) values ('Crownhardt', 'Épinal');
insert into kino (ime, kraj) values ('Londonderry', 'Przybyszówka');
insert into kino (ime, kraj) values ('Sachs', 'Orlando');
insert into kino (ime, kraj) values ('Red Cloud', 'Kotikawatta');
insert into kino (ime, kraj) values ('Reindahl', 'Tây Đằng');
insert into kino (ime, kraj) values ('Sutherland', 'Huntington');
insert into kino (ime, kraj) values ('Old Gate', 'Duri');
insert into kino (ime, kraj) values ('Meadow Valley', 'Duanjia');
insert into kino (ime, kraj) values ('Dovetail', 'Sabon Gari-Nangere');
insert into kino (ime, kraj) values ('Southridge', 'Petkovci');
insert into kino (ime, kraj) values ('Northwestern', 'Condado');
insert into kino (ime, kraj) values ('Farragut', 'Khombole');
insert into kino (ime, kraj) values ('South', 'Shanghuang');
insert into kino (ime, kraj) values ('Eagan', 'Nong Khai');
insert into kino (ime, kraj) values ('Hooker', 'Freiria');
insert into kino (ime, kraj) values ('Drewry', 'Francisco Sarabia');
insert into kino (ime, kraj) values ('Sachtjen', 'Arrën');
insert into kino (ime, kraj) values ('Dorton', 'Zaña');
insert into kino (ime, kraj) values ('Fremont', 'Thị Trấn Mù Cang Chải');
insert into kino (ime, kraj) values ('2nd', 'Puyuan');
insert into kino (ime, kraj) values ('Heffernan', 'Quinta do Sobrado');
insert into kino (ime, kraj) values ('Debra', 'Sonder');
insert into kino (ime, kraj) values ('Manufacturers', 'Santa Rosa');
insert into kino (ime, kraj) values ('Stephen', 'Bluri');
insert into kino (ime, kraj) values ('Karstens', 'Jiangpu');
insert into kino (ime, kraj) values ('Clove', 'Gongpo');
insert into kino (ime, kraj) values ('Randy', 'Strängnäs');
insert into kino (ime, kraj) values ('Jenifer', 'Pulosari');
insert into kino (ime, kraj) values ('New Castle', 'Yablochnyy');
insert into kino (ime, kraj) values ('Lillian', 'Fortuna');
insert into kino (ime, kraj) values ('Anderson', 'Dadiharja');
insert into kino (ime, kraj) values ('Rowland', 'Kivijärvi');
insert into kino (ime, kraj) values ('Elmside', 'Stockholm');
insert into kino (ime, kraj) values ('Bartillon', 'Bujumbura');
insert into kino (ime, kraj) values ('Trailsway', 'Gusau');
insert into kino (ime, kraj) values ('Carioca', 'Praia das Maçãs');
insert into kino (ime, kraj) values ('Northview', 'Łubniany');
insert into kino (ime, kraj) values ('Anthes', 'Norrtälje');
insert into kino (ime, kraj) values ('Jackson', 'Uripa');
insert into kino (ime, kraj) values ('Lake View', 'Duwe');
insert into kino (ime, kraj) values ('Nevada', 'Halimpu');
insert into kino (ime, kraj) values ('Delladonna', 'Čejkovice');
insert into kino (ime, kraj) values ('American Ash', 'Prawdzinski');
insert into kino (ime, kraj) values ('Pierstorff', 'Sumberkertokrajan');
insert into kino (ime, kraj) values ('Ramsey', 'Huangzhai');
insert into kino (ime, kraj) values ('Rigney', 'Chikushino-shi');
insert into kino (ime, kraj) values ('Reindahl', 'Taiyangling');
insert into kino (ime, kraj) values ('Algoma', 'Floresta');
insert into kino (ime, kraj) values ('Dawn', 'Lubomierz');
insert into kino (ime, kraj) values ('Barnett', 'Lilin Satu');
insert into kino (ime, kraj) values ('Ohio', 'Prroshyan');
insert into kino (ime, kraj) values ('Quincy', 'Heyou');
insert into kino (ime, kraj) values ('Trailsway', 'Gibbons');
insert into kino (ime, kraj) values ('Sachs', 'Kubangwaru');
insert into kino (ime, kraj) values ('Johnson', 'Évry');
insert into kino (ime, kraj) values ('Reinke', 'Yugawara');
insert into kino (ime, kraj) values ('Rigney', 'Zhougao');
insert into kino (ime, kraj) values ('Cody', 'Longjumeau');
insert into kino (ime, kraj) values ('Lukken', 'Crossfield');
insert into kino (ime, kraj) values ('Lakewood Gardens', 'Sievi');
insert into kino (ime, kraj) values ('Kedzie', 'Dobryanka');
insert into kino (ime, kraj) values ('Eggendart', 'Bimbo');
insert into kino (ime, kraj) values ('Spenser', 'Frýdlant');
insert into kino (ime, kraj) values ('Portage', 'Salmi');
insert into kino (ime, kraj) values ('Meadow Ridge', 'Issy-les-Moulineaux');
insert into kino (ime, kraj) values ('Brickson Park', 'Oefau');
insert into kino (ime, kraj) values ('Warner', 'Cruzeiro');
insert into kino (ime, kraj) values ('Pepper Wood', 'Cái Nhum');
insert into kino (ime, kraj) values ('Golf Course', 'Saint-Rémy-de-Provence');
insert into kino (ime, kraj) values ('Blue Bill Park', 'Rosario');
insert into kino (ime, kraj) values ('Riverside', 'Laolong');
insert into kino (ime, kraj) values ('Mendota', 'Kochenëvo');
insert into kino (ime, kraj) values ('Delaware', 'Ndofane');
insert into kino (ime, kraj) values ('Bartillon', 'Sidomekar');
insert into kino (ime, kraj) values ('1st', 'Paraćin');
insert into kino (ime, kraj) values ('Morrow', 'Baisha');
insert into kino (ime, kraj) values ('Spaight', 'Tārūt');
insert into kino (ime, kraj) values ('International', 'Wenshui');
insert into kino (ime, kraj) values ('Corben', 'Annecy-le-Vieux');
insert into kino (ime, kraj) values ('Lillian', 'Ambato Boeny');
insert into kino (ime, kraj) values ('Dexter', 'Baiyangwan');
insert into kino (ime, kraj) values ('Laurel', 'Wołczyn');
insert into kino (ime, kraj) values ('Montana', 'Ambositra');
insert into kino (ime, kraj) values ('Crescent Oaks', 'Boussé');
insert into kino (ime, kraj) values ('Schlimgen', 'Emiliano Zapata');
insert into kino (ime, kraj) values ('Larry', 'Huandiqiao');
insert into kino (ime, kraj) values ('Raven', 'Weixin');
insert into kino (ime, kraj) values ('Nancy', 'Wongaya Kaja');
insert into kino (ime, kraj) values ('Morning', 'Sunja');
insert into kino (ime, kraj) values ('Hermina', 'Argelia');
insert into kino (ime, kraj) values ('Pearson', 'Lubomierz');
insert into kino (ime, kraj) values ('Doe Crossing', 'Tilang');
insert into kino (ime, kraj) values ('Jay', 'Adelaide Mail Centre');
insert into kino (ime, kraj) values ('Golf', 'Angered');
insert into kino (ime, kraj) values ('Knutson', 'Neyagawa');
insert into kino (ime, kraj) values ('Dwight', 'Kåge');
insert into kino (ime, kraj) values ('Larry', 'San Ramon');
insert into kino (ime, kraj) values ('Straubel', 'Medan');
insert into kino (ime, kraj) values ('Ramsey', 'Sandakan');
insert into kino (ime, kraj) values ('Vernon', 'Guandi');
insert into kino (ime, kraj) values ('Bobwhite', 'Sherbrooke');
insert into kino (ime, kraj) values ('Loeprich', 'Moju');
insert into kino (ime, kraj) values ('Oakridge', 'Saint-Tite');
insert into kino (ime, kraj) values ('Gulseth', 'Wantan');
insert into kino (ime, kraj) values ('Northview', 'Houston');
insert into kino (ime, kraj) values ('Fordem', 'Campos Belos');
insert into kino (ime, kraj) values ('Birchwood', 'Guazacapán');
insert into kino (ime, kraj) values ('Chive', 'Mombetsu');
insert into kino (ime, kraj) values ('Upham', 'Sarāvān');
insert into kino (ime, kraj) values ('Waywood', 'Abonnema');
insert into kino (ime, kraj) values ('Red Cloud', 'Innisfil');
insert into kino (ime, kraj) values ('Fuller', 'Nanzhao Chengguanzhen');
insert into kino (ime, kraj) values ('Homewood', 'New Orleans');
insert into kino (ime, kraj) values ('Crowley', 'Thị Trấn Thất Khê');
insert into kino (ime, kraj) values ('Nevada', 'Roanoke');
insert into kino (ime, kraj) values ('Manufacturers', 'Caen');
insert into kino (ime, kraj) values ('Red Cloud', 'Babakan Baru');
insert into kino (ime, kraj) values ('Elmside', 'Mętków');
insert into kino (ime, kraj) values ('Marcy', 'Oinoússes');
insert into kino (ime, kraj) values ('Spohn', 'Ljutomer');
insert into kino (ime, kraj) values ('Beilfuss', 'Międzyzdroje');
insert into kino (ime, kraj) values ('Vernon', 'Straszydle');
insert into kino (ime, kraj) values ('Holy Cross', 'Payao');
insert into kino (ime, kraj) values ('Summit', 'Nowa Sarzyna');
insert into kino (ime, kraj) values ('Vahlen', 'São Pedro de Trafaria');
insert into kino (ime, kraj) values ('Sheridan', 'Jinjiang');
insert into kino (ime, kraj) values ('Arrowood', 'Estância');
insert into kino (ime, kraj) values ('Westridge', 'Xinglong');
insert into kino (ime, kraj) values ('Nelson', 'Bapska');
insert into kino (ime, kraj) values ('Surrey', 'Sakākā');
insert into kino (ime, kraj) values ('Troy', 'Samobor');
insert into kino (ime, kraj) values ('Blackbird', 'Juai');
insert into kino (ime, kraj) values ('Crowley', 'Zerkten');
insert into kino (ime, kraj) values ('Toban', 'Tashanta');
insert into kino (ime, kraj) values ('Debs', 'Al ‘Āliyah');
insert into kino (ime, kraj) values ('Summit', 'Keda');
insert into kino (ime, kraj) values ('Thackeray', 'Salvacion');
insert into kino (ime, kraj) values ('Gale', 'Seseng');
insert into kino (ime, kraj) values ('Ohio', 'Sanxing');
insert into kino (ime, kraj) values ('Barby', 'Sumberan');
insert into kino (ime, kraj) values ('Orin', 'Sadahayu');
insert into kino (ime, kraj) values ('Stone Corner', 'Marihatag');
insert into kino (ime, kraj) values ('Bobwhite', 'Ciudad Ojeda');
insert into kino (ime, kraj) values ('Paget', 'Wanasari Baleran');
insert into kino (ime, kraj) values ('Macpherson', 'Beijiang');
insert into kino (ime, kraj) values ('Hoard', 'Tak');
insert into kino (ime, kraj) values ('Parkside', 'Junliangcheng');
insert into kino (ime, kraj) values ('Rowland', 'Geidam');
insert into kino (ime, kraj) values ('Vidon', 'Vavozh');
insert into kino (ime, kraj) values ('Ilene', 'Brudzew');
insert into kino (ime, kraj) values ('Texas', 'Menampukrajan');
insert into kino (ime, kraj) values ('Cordelia', 'Ekibastuz');
insert into kino (ime, kraj) values ('Oneill', 'Leiden');
insert into kino (ime, kraj) values ('Dorton', 'Angelochóri');
insert into kino (ime, kraj) values ('Tennyson', 'Toutai');
insert into kino (ime, kraj) values ('Lighthouse Bay', 'Denver');
insert into kino (ime, kraj) values ('Express', 'Hushan');
insert into kino (ime, kraj) values ('Eliot', 'Buenavista');
insert into kino (ime, kraj) values ('Mifflin', 'Las Palmas');
insert into kino (ime, kraj) values ('Waubesa', 'Helsingborg');
insert into kino (ime, kraj) values ('Grover', 'Smarhon’');
insert into kino (ime, kraj) values ('Lighthouse Bay', 'Tongshanxiang');
insert into kino (ime, kraj) values ('Twin Pines', 'Neftçala');
insert into kino (ime, kraj) values ('Waywood', 'Kosai-shi');
insert into kino (ime, kraj) values ('Forest', 'Amnat Charoen');
insert into kino (ime, kraj) values ('Tennyson', 'Přibyslav');
insert into kino (ime, kraj) values ('Dorton', 'Auch');
insert into kino (ime, kraj) values ('Starling', 'Ticrapo');
insert into kino (ime, kraj) values ('Porter', 'Illkirch-Graffenstaden');
insert into kino (ime, kraj) values ('Elmside', 'Gabao');
insert into kino (ime, kraj) values ('Mariners Cove', 'Huxingshan');
insert into kino (ime, kraj) values ('Mallard', 'Sop Pong');
insert into kino (ime, kraj) values ('Grayhawk', 'Isla Verde');
insert into kino (ime, kraj) values ('Shasta', 'Yongxing');
insert into kino (ime, kraj) values ('Twin Pines', 'Amsterdam Oud Zuid en Rivierenbuurt');
insert into kino (ime, kraj) values ('Ohio', 'Sredno Konjare');
insert into kino (ime, kraj) values ('Surrey', 'Yizhivtsi');
insert into kino (ime, kraj) values ('Armistice', 'Buda-Kashalyova');
insert into kino (ime, kraj) values ('Forest Dale', 'Ganjiang');
insert into kino (ime, kraj) values ('Aberg', 'Makui');
insert into kino (ime, kraj) values ('Bultman', 'Spånga');
insert into kino (ime, kraj) values ('Hallows', 'Giemdiem');
insert into kino (ime, kraj) values ('Aberg', 'Nakhchivan');
insert into kino (ime, kraj) values ('Towne', 'Szprotawa');
insert into kino (ime, kraj) values ('Corben', 'Lutoryż');
