insert into kino (ime, kraj) values ('Pearson', 'Žirovnice');
insert into kino (ime, kraj) values ('Hudson', 'Futang');
insert into kino (ime, kraj) values ('Kropf', 'Covas');
insert into kino (ime, kraj) values ('Gina', 'Rožna Dolina');
insert into kino (ime, kraj) values ('Kenwood', 'Xiawuqi');
insert into kino (ime, kraj) values ('Garrison', 'Hwangju-ŭp');
insert into kino (ime, kraj) values ('Thackeray', 'El Mirador');
insert into kino (ime, kraj) values ('Magdeline', 'Tocumen');
insert into kino (ime, kraj) values ('Superior', 'Xilópolis');
insert into kino (ime, kraj) values ('Susan', 'Umeå');
insert into kino (ime, kraj) values ('Fairview', 'Killumney');
insert into kino (ime, kraj) values ('Ridgeview', 'Grand Junction');
insert into kino (ime, kraj) values ('Parkside', 'Shibli');
insert into kino (ime, kraj) values ('Service', 'Reims');
insert into kino (ime, kraj) values ('Vahlen', 'Javhlant');
insert into kino (ime, kraj) values ('David', 'Blois');
insert into kino (ime, kraj) values ('Mallard', 'Palmeira');
insert into kino (ime, kraj) values ('Nobel', 'Marau');
insert into kino (ime, kraj) values ('Crownhardt', 'Kamieniec Wrocławski');
insert into kino (ime, kraj) values ('Tennessee', 'Monywa');
insert into kino (ime, kraj) values ('Old Gate', 'Kaiama');
insert into kino (ime, kraj) values ('Cardinal', 'Sibayo');
insert into kino (ime, kraj) values ('Stuart', 'Jiujiang');
insert into kino (ime, kraj) values ('Prairieview', 'Azeitão');
insert into kino (ime, kraj) values ('Division', 'Horqueta');
insert into kino (ime, kraj) values ('Shasta', 'København');
insert into kino (ime, kraj) values ('Mallory', 'Ostankinskiy');
insert into kino (ime, kraj) values ('Orin', 'Poste du Lac');
insert into kino (ime, kraj) values ('New Castle', 'Kiili');
insert into kino (ime, kraj) values ('Schlimgen', 'Banamba');
insert into kino (ime, kraj) values ('Claremont', 'Pueblo Viejo');
insert into kino (ime, kraj) values ('Golf', 'Macapsing');
insert into kino (ime, kraj) values ('Fallview', 'Sydney');
insert into kino (ime, kraj) values ('Anthes', 'Pedra Furada');
insert into kino (ime, kraj) values ('Ridge Oak', 'Chaoyangdong');
insert into kino (ime, kraj) values ('Packers', 'Nairobi');
insert into kino (ime, kraj) values ('Mandrake', 'Belajen');
insert into kino (ime, kraj) values ('Prairieview', 'El Coco');
insert into kino (ime, kraj) values ('Cascade', 'Zhangjiafang');
insert into kino (ime, kraj) values ('Westerfield', 'Quy Đạt');
insert into kino (ime, kraj) values ('Anhalt', 'Przystajń');
insert into kino (ime, kraj) values ('Shelley', 'Orekhovo-Borisovo Severnoye');
insert into kino (ime, kraj) values ('Mayfield', 'Caringin');
insert into kino (ime, kraj) values ('Esker', 'Yuanqiao');
insert into kino (ime, kraj) values ('Milwaukee', 'Changbu');
insert into kino (ime, kraj) values ('Fair Oaks', 'Otavalo');
insert into kino (ime, kraj) values ('Oneill', 'Yablochnyy');
insert into kino (ime, kraj) values ('Lyons', 'Kyosai');
insert into kino (ime, kraj) values ('Waubesa', 'Tangwāni');
insert into kino (ime, kraj) values ('Superior', 'Kadubadak');
insert into kino (ime, kraj) values ('Lyons', 'San Juan');
insert into kino (ime, kraj) values ('Mallard', 'Nkurenkuru');
insert into kino (ime, kraj) values ('Duke', 'Al Manqaf');
insert into kino (ime, kraj) values ('Blaine', 'Jega');
insert into kino (ime, kraj) values ('Muir', 'Sel’tso');
insert into kino (ime, kraj) values ('Lukken', 'Nieying');
insert into kino (ime, kraj) values ('Corry', 'Vespasiano');
insert into kino (ime, kraj) values ('Gina', 'Yangxunqiao');
insert into kino (ime, kraj) values ('Northport', 'Komorniki');
insert into kino (ime, kraj) values ('Hollow Ridge', 'Manis Mekarwangi');
insert into kino (ime, kraj) values ('Mosinee', 'Sanhe');
insert into kino (ime, kraj) values ('Birchwood', 'Lugu');
insert into kino (ime, kraj) values ('Melvin', 'Duwakkandung');
insert into kino (ime, kraj) values ('Summer Ridge', 'Tangdukou');
insert into kino (ime, kraj) values ('Park Meadow', 'Yecun');
insert into kino (ime, kraj) values ('Cottonwood', 'Contraalmirante Cordero');
insert into kino (ime, kraj) values ('Bluestem', 'Labuhanlalar');
insert into kino (ime, kraj) values ('Lerdahl', 'Jinchuan');
insert into kino (ime, kraj) values ('Onsgard', 'El Mirador');
insert into kino (ime, kraj) values ('Orin', 'Bokor');
insert into kino (ime, kraj) values ('Mendota', 'Hino');
insert into kino (ime, kraj) values ('Vernon', 'Maojiadian');
insert into kino (ime, kraj) values ('Mallory', 'Radzanów');
insert into kino (ime, kraj) values ('Lakeland', 'Ozubulu');
insert into kino (ime, kraj) values ('Colorado', 'Si Ma Cai');
insert into kino (ime, kraj) values ('Mccormick', 'Ampelákia');
insert into kino (ime, kraj) values ('Hoepker', 'Zhongzhai');
insert into kino (ime, kraj) values ('Bashford', 'Mahaplag');
insert into kino (ime, kraj) values ('Stephen', 'Hino');
insert into kino (ime, kraj) values ('Park Meadow', 'Tiwi');
insert into kino (ime, kraj) values ('Loftsgordon', 'Huafeng');
insert into kino (ime, kraj) values ('Northport', 'Lopez Jaena');
insert into kino (ime, kraj) values ('Petterle', 'Berlin');
insert into kino (ime, kraj) values ('Express', 'Feyẕābād');
insert into kino (ime, kraj) values ('Merrick', 'Camabatela');
insert into kino (ime, kraj) values ('Blackbird', 'Kthella e Epërme');
insert into kino (ime, kraj) values ('Mosinee', 'Tochio-honchō');
insert into kino (ime, kraj) values ('Reindahl', 'Guinabsan');
insert into kino (ime, kraj) values ('Bay', 'Dzüyl');
insert into kino (ime, kraj) values ('Loeprich', 'Vladivostok');
insert into kino (ime, kraj) values ('Farragut', 'Chahe');
insert into kino (ime, kraj) values ('Old Shore', 'Yanjiang');
insert into kino (ime, kraj) values ('Cody', 'Shabo');
insert into kino (ime, kraj) values ('Knutson', 'Chợ Lầu');
insert into kino (ime, kraj) values ('Lotheville', 'Jingzhou');
insert into kino (ime, kraj) values ('Onsgard', 'Parenggan');
insert into kino (ime, kraj) values ('Roxbury', 'Cetinje');
insert into kino (ime, kraj) values ('Declaration', 'Singosari');
insert into kino (ime, kraj) values ('Dunning', 'Passos');
insert into kino (ime, kraj) values ('Bluejay', 'Asunción');
insert into kino (ime, kraj) values ('Birchwood', 'Hobscheid');
insert into kino (ime, kraj) values ('Transport', 'Volgograd');
insert into kino (ime, kraj) values ('Monterey', 'Panggung');
insert into kino (ime, kraj) values ('Stuart', 'Dungang');
insert into kino (ime, kraj) values ('Redwing', 'Maia');
insert into kino (ime, kraj) values ('Mesta', 'Sumberngerjat');
insert into kino (ime, kraj) values ('Knutson', 'Faeanak Dua');
insert into kino (ime, kraj) values ('Mockingbird', 'Alīābad');
insert into kino (ime, kraj) values ('Randy', 'Guinsadan');
insert into kino (ime, kraj) values ('Randy', 'Buang');
insert into kino (ime, kraj) values ('Raven', 'Guaporé');
insert into kino (ime, kraj) values ('Washington', 'Ndom');
insert into kino (ime, kraj) values ('Helena', 'Lebak');
insert into kino (ime, kraj) values ('Arrowood', 'Saraburi');
insert into kino (ime, kraj) values ('Hallows', 'Disūq');
insert into kino (ime, kraj) values ('Bluejay', 'Shilovo');
insert into kino (ime, kraj) values ('Hoard', 'Kaura Namoda');
insert into kino (ime, kraj) values ('John Wall', 'Plavsk');
insert into kino (ime, kraj) values ('Northport', 'Mólos');
insert into kino (ime, kraj) values ('Montana', 'Slavonice');
insert into kino (ime, kraj) values ('Prentice', 'Parral');
insert into kino (ime, kraj) values ('Paget', 'Nyala');
insert into kino (ime, kraj) values ('Oak Valley', 'Chengnan');
insert into kino (ime, kraj) values ('Oneill', 'Cilolongokan');
insert into kino (ime, kraj) values ('Maryland', 'Bavorov');
insert into kino (ime, kraj) values ('Pennsylvania', 'San Diego');
insert into kino (ime, kraj) values ('Crescent Oaks', 'Sinarwangi');
insert into kino (ime, kraj) values ('Pepper Wood', 'Svatava');
insert into kino (ime, kraj) values ('Surrey', 'Semang');
insert into kino (ime, kraj) values ('Moose', 'Mbala');
insert into kino (ime, kraj) values ('Continental', 'Andongsari');
insert into kino (ime, kraj) values ('Vermont', 'Sitajara');
insert into kino (ime, kraj) values ('Meadow Vale', 'Seupakat');
insert into kino (ime, kraj) values ('Jenna', 'Dugongan');
insert into kino (ime, kraj) values ('Merry', 'Wuqu');
insert into kino (ime, kraj) values ('Marquette', 'Suç');
insert into kino (ime, kraj) values ('Anzinger', 'Yenangyaung');
insert into kino (ime, kraj) values ('Bayside', 'Wasquehal');
insert into kino (ime, kraj) values ('Veith', 'Wangwu');
insert into kino (ime, kraj) values ('Pepper Wood', 'Cimanglid');
insert into kino (ime, kraj) values ('Mitchell', 'Yangkou');
insert into kino (ime, kraj) values ('Donald', 'Blois');
insert into kino (ime, kraj) values ('Kenwood', 'Lanipao');
insert into kino (ime, kraj) values ('Montana', 'Magdeburg');
insert into kino (ime, kraj) values ('Buhler', 'Dadong’ao');
insert into kino (ime, kraj) values ('Birchwood', 'Chengdong');
insert into kino (ime, kraj) values ('Rowland', 'Ulcinj');
insert into kino (ime, kraj) values ('Barnett', 'Lamawan');
insert into kino (ime, kraj) values ('Maple', 'Ngoc Hon Doc');
insert into kino (ime, kraj) values ('Rowland', 'Jiangfeng');
insert into kino (ime, kraj) values ('Ridgeway', 'Alilem');
insert into kino (ime, kraj) values ('Hagan', 'Jaworzyna Śląska');
insert into kino (ime, kraj) values ('Orin', 'Masatepe');
insert into kino (ime, kraj) values ('Sycamore', 'As Saddah');
insert into kino (ime, kraj) values ('Buena Vista', 'Caihe');
insert into kino (ime, kraj) values ('Di Loreto', 'Gandiaye');
insert into kino (ime, kraj) values ('Ridgeway', 'Chengmen');
insert into kino (ime, kraj) values ('Old Shore', 'Pueblo Nuevo');
insert into kino (ime, kraj) values ('Pankratz', 'Antanhol');
insert into kino (ime, kraj) values ('Manley', 'Yongning');
insert into kino (ime, kraj) values ('Ramsey', 'Itabuna');
insert into kino (ime, kraj) values ('Helena', 'Korba');
insert into kino (ime, kraj) values ('Mockingbird', 'Mariefred');
insert into kino (ime, kraj) values ('Schurz', 'Uzgen');
insert into kino (ime, kraj) values ('Kensington', 'Gayam');
insert into kino (ime, kraj) values ('Dixon', 'Tacheng');
insert into kino (ime, kraj) values ('Hallows', 'Łaziska Górne');
insert into kino (ime, kraj) values ('Longview', 'Panalanoy');
insert into kino (ime, kraj) values ('Glacier Hill', 'Bieniewice');
insert into kino (ime, kraj) values ('Surrey', '‘Eilabun');
insert into kino (ime, kraj) values ('Hanover', 'Bordeaux');
insert into kino (ime, kraj) values ('Doe Crossing', 'Novo-Peredelkino');
insert into kino (ime, kraj) values ('Linden', 'Wenquan');
insert into kino (ime, kraj) values ('Jenna', 'Uyen Hung');
insert into kino (ime, kraj) values ('Mockingbird', 'Kislovodsk');
insert into kino (ime, kraj) values ('Mifflin', 'Marseille');
insert into kino (ime, kraj) values ('Forest Run', 'Ziyang');
insert into kino (ime, kraj) values ('Monterey', 'Otrado-Kubanskoye');
insert into kino (ime, kraj) values ('Amoth', 'Tambo');
insert into kino (ime, kraj) values ('Hollow Ridge', 'Illintsi');
insert into kino (ime, kraj) values ('Menomonie', 'Kebonkaret');
insert into kino (ime, kraj) values ('Little Fleur', 'Kolodenka');
insert into kino (ime, kraj) values ('Westridge', 'Wuyang');
insert into kino (ime, kraj) values ('Hermina', 'Barra');
insert into kino (ime, kraj) values ('Eastwood', 'Hammam Sousse');
insert into kino (ime, kraj) values ('Main', 'Osiek');
insert into kino (ime, kraj) values ('Schlimgen', 'Kowale');
insert into kino (ime, kraj) values ('Kenwood', 'Rustam jo Goth');
insert into kino (ime, kraj) values ('Hayes', 'Shchukino');
insert into kino (ime, kraj) values ('Union', 'Göteborg');
insert into kino (ime, kraj) values ('Northview', 'Artur Nogueira');
insert into kino (ime, kraj) values ('Esch', 'Rayevskiy');
insert into kino (ime, kraj) values ('Hanson', 'Puncakwangi');
insert into kino (ime, kraj) values ('Morning', 'Lanyi');
insert into kino (ime, kraj) values ('Waubesa', 'Gaoyan');
insert into kino (ime, kraj) values ('Autumn Leaf', 'Talangbetutu');
insert into kino (ime, kraj) values ('Nelson', 'Kuragaki-kosugi');
insert into kino (ime, kraj) values ('Bartelt', 'New York City');
insert into kino (ime, kraj) values ('Linden', 'Älvsjö');
insert into kino (ime, kraj) values ('Esker', 'San Cristóbal');
insert into kino (ime, kraj) values ('Darwin', 'Brześć Kujawski');
insert into kino (ime, kraj) values ('Bay', 'Bang Rak');
insert into kino (ime, kraj) values ('Gateway', 'Mosjøen');
insert into kino (ime, kraj) values ('Fallview', 'El Pino');
insert into kino (ime, kraj) values ('Cambridge', 'La Habana Vieja');
insert into kino (ime, kraj) values ('Buhler', 'Ovsyanka');
insert into kino (ime, kraj) values ('Browning', 'Beisijia');
insert into kino (ime, kraj) values ('Northridge', 'Soure');
insert into kino (ime, kraj) values ('Eggendart', 'Chiriguaná');
insert into kino (ime, kraj) values ('Rowland', 'Mongaguá');
insert into kino (ime, kraj) values ('Dahle', 'Oslo');
insert into kino (ime, kraj) values ('Laurel', 'Pukou');
insert into kino (ime, kraj) values ('Chive', 'Ketanggi');
insert into kino (ime, kraj) values ('Kinsman', 'Durazno');
insert into kino (ime, kraj) values ('Meadow Valley', 'Gogaran');
insert into kino (ime, kraj) values ('Vahlen', 'Jiazhi');
insert into kino (ime, kraj) values ('Chinook', 'Shireet');
insert into kino (ime, kraj) values ('Maple', 'Lomba');
insert into kino (ime, kraj) values ('New Castle', 'Seseng');
insert into kino (ime, kraj) values ('Arizona', 'Ordem');
insert into kino (ime, kraj) values ('Roth', 'Zougang');
insert into kino (ime, kraj) values ('Bowman', 'Abaza');
insert into kino (ime, kraj) values ('Talmadge', 'Lingdi');
insert into kino (ime, kraj) values ('Autumn Leaf', 'Zebrzydowice');
insert into kino (ime, kraj) values ('Meadow Vale', 'La Paz');
insert into kino (ime, kraj) values ('2nd', 'Solina');
insert into kino (ime, kraj) values ('Autumn Leaf', 'Meukek');
insert into kino (ime, kraj) values ('Kedzie', 'Lingqian');
insert into kino (ime, kraj) values ('Granby', 'Gangsha');
insert into kino (ime, kraj) values ('Sutteridge', 'Gorna Oryakhovitsa');
insert into kino (ime, kraj) values ('High Crossing', 'Bajiazi');
insert into kino (ime, kraj) values ('Petterle', 'Shiwan');
insert into kino (ime, kraj) values ('Ilene', 'El Salitre');
insert into kino (ime, kraj) values ('Garrison', 'Dangcalan');
insert into kino (ime, kraj) values ('Lakewood', 'Centenario');
insert into kino (ime, kraj) values ('Lakewood Gardens', 'Nyalindung');
insert into kino (ime, kraj) values ('Melby', 'San José El Ídolo');
insert into kino (ime, kraj) values ('Ilene', 'Puerto Iguazú');
insert into kino (ime, kraj) values ('Burning Wood', 'Buíque');
insert into kino (ime, kraj) values ('Corscot', 'Iturama');
insert into kino (ime, kraj) values ('Dahle', 'Huangjingba');
insert into kino (ime, kraj) values ('Birchwood', 'Tonghong');
insert into kino (ime, kraj) values ('Schurz', 'Vavuniya');
insert into kino (ime, kraj) values ('Lerdahl', 'Santa Rosa');
insert into kino (ime, kraj) values ('Mockingbird', 'Kototujuh');
insert into kino (ime, kraj) values ('Ilene', 'Qianjia');
insert into kino (ime, kraj) values ('Milwaukee', 'La Seyne-sur-Mer');
insert into kino (ime, kraj) values ('Maple Wood', 'Wenquan');
insert into kino (ime, kraj) values ('Clyde Gallagher', 'Srunikrajan');
insert into kino (ime, kraj) values ('Pawling', 'Ad Dimnah');
insert into kino (ime, kraj) values ('Raven', 'Tunggaoen Timur');
insert into kino (ime, kraj) values ('Mallory', 'Daraitan');
insert into kino (ime, kraj) values ('Toban', 'Blokdesa Situgede');
insert into kino (ime, kraj) values ('Morningstar', 'Cikupa');
insert into kino (ime, kraj) values ('Schmedeman', 'Gigant');
insert into kino (ime, kraj) values ('Vermont', 'Maldonado');
insert into kino (ime, kraj) values ('Sundown', 'Yelets');
insert into kino (ime, kraj) values ('Onsgard', 'Enjitsu');
insert into kino (ime, kraj) values ('Hallows', 'Chayek');
insert into kino (ime, kraj) values ('7th', 'Mariara');
insert into kino (ime, kraj) values ('Londonderry', 'Agbor');
insert into kino (ime, kraj) values ('Mendota', 'Cuenca');
insert into kino (ime, kraj) values ('Vidon', 'Sobue');
insert into kino (ime, kraj) values ('Warrior', 'Rueil-Malmaison');
insert into kino (ime, kraj) values ('Loeprich', 'Quivilla');
insert into kino (ime, kraj) values ('Mallory', 'Hispania');
insert into kino (ime, kraj) values ('Upham', 'Forninho');
insert into kino (ime, kraj) values ('Main', 'Ḩabbān');
insert into kino (ime, kraj) values ('Main', 'Shepetivka');
insert into kino (ime, kraj) values ('Redwing', 'Ta`ū');
insert into kino (ime, kraj) values ('Glendale', 'Lahan Sai');
insert into kino (ime, kraj) values ('Graedel', 'Juàzeirinho');
insert into kino (ime, kraj) values ('Cascade', 'Canavieiras');
insert into kino (ime, kraj) values ('Clarendon', 'Khoronk’');
insert into kino (ime, kraj) values ('Maple', 'Roches Noire');
insert into kino (ime, kraj) values ('Declaration', 'Luka nad Jihlavou');
insert into kino (ime, kraj) values ('Hayes', 'Fort Smith');
insert into kino (ime, kraj) values ('Independence', 'Shepetivka');
insert into kino (ime, kraj) values ('Upham', 'Karlskrona');
insert into kino (ime, kraj) values ('Shasta', 'Ntungamo');
insert into kino (ime, kraj) values ('Jenifer', 'Pawłowiczki');
insert into kino (ime, kraj) values ('Mcguire', 'Al Misrākh');
insert into kino (ime, kraj) values ('East', 'Ajman');
insert into kino (ime, kraj) values ('Michigan', 'Ljungby');
insert into kino (ime, kraj) values ('Di Loreto', 'Lin’an');
insert into kino (ime, kraj) values ('Starling', 'Shicheng');
insert into kino (ime, kraj) values ('Arizona', 'Al Khāniq');
insert into kino (ime, kraj) values ('Summerview', 'Guangli');
insert into kino (ime, kraj) values ('Darwin', 'Baoshi');
insert into kino (ime, kraj) values ('Paget', 'Revda');
insert into kino (ime, kraj) values ('Delaware', 'Kresek');
insert into kino (ime, kraj) values ('Crowley', 'Solna');
insert into kino (ime, kraj) values ('Milwaukee', 'Pidigan');
insert into kino (ime, kraj) values ('Hoard', 'Changmaoling');
insert into kino (ime, kraj) values ('Katie', 'Lutun');
insert into kino (ime, kraj) values ('Maywood', 'Yumbel');
insert into kino (ime, kraj) values ('Mayfield', 'Shatian');
insert into kino (ime, kraj) values ('Raven', 'Daying');
insert into kino (ime, kraj) values ('Basil', 'Liuji');
insert into kino (ime, kraj) values ('Village Green', 'El Carmen');
insert into kino (ime, kraj) values ('Prentice', 'Menuma');
insert into kino (ime, kraj) values ('Superior', 'Montalegre');
insert into kino (ime, kraj) values ('Norway Maple', 'Nyzhnya Krynka');
insert into kino (ime, kraj) values ('Onsgard', 'Batakte');
insert into kino (ime, kraj) values ('Lakewood Gardens', 'Xiaoruo');
insert into kino (ime, kraj) values ('Judy', 'Albuquerque');
insert into kino (ime, kraj) values ('Valley Edge', 'Sotouboua');
insert into kino (ime, kraj) values ('Del Mar', 'Sunjia');
insert into kino (ime, kraj) values ('Daystar', 'Świnna');
insert into kino (ime, kraj) values ('7th', 'Masumbwe');
insert into kino (ime, kraj) values ('Buell', 'Lanxi');
insert into kino (ime, kraj) values ('Sutherland', 'Dessalines');
insert into kino (ime, kraj) values ('Meadow Vale', 'Enschede');
insert into kino (ime, kraj) values ('Monica', 'New Orleans');
insert into kino (ime, kraj) values ('Union', 'Batanovtsi');
insert into kino (ime, kraj) values ('Arrowood', 'Chignayhua');
insert into kino (ime, kraj) values ('Melvin', 'Yejia');
insert into kino (ime, kraj) values ('Rieder', 'Rönninge');
insert into kino (ime, kraj) values ('Scoville', 'Peuhaq');
insert into kino (ime, kraj) values ('Messerschmidt', 'Rybarzowice');
insert into kino (ime, kraj) values ('Utah', 'Třemošnice');
insert into kino (ime, kraj) values ('Green', 'Langgapayung');
insert into kino (ime, kraj) values ('Fallview', 'El Progreso');
insert into kino (ime, kraj) values ('Kings', 'Duwayr Raslān');
insert into kino (ime, kraj) values ('Schurz', 'Baiyin');
insert into kino (ime, kraj) values ('Cordelia', 'Ipameri');
insert into kino (ime, kraj) values ('Karstens', 'Hake');
insert into kino (ime, kraj) values ('Mallard', 'Stockholm');
insert into kino (ime, kraj) values ('Carberry', 'Vitry-le-François');
insert into kino (ime, kraj) values ('Gale', 'Mayhan');
insert into kino (ime, kraj) values ('Comanche', 'Luleå');
insert into kino (ime, kraj) values ('Pleasure', 'Toledo');
insert into kino (ime, kraj) values ('Michigan', 'Cibingbin');
insert into kino (ime, kraj) values ('Thompson', 'Chavárion');
insert into kino (ime, kraj) values ('John Wall', 'Nāḩīyat Saddat al Hindīyah');
insert into kino (ime, kraj) values ('Pankratz', 'Da Nang');
insert into kino (ime, kraj) values ('Larry', 'Ambelón');
insert into kino (ime, kraj) values ('Mitchell', 'Yataity del Norte');
insert into kino (ime, kraj) values ('Oneill', 'Nikolayevskaya');
insert into kino (ime, kraj) values ('Sycamore', 'Roshal’');
insert into kino (ime, kraj) values ('Bellgrove', 'Tinumpuk');
insert into kino (ime, kraj) values ('Moulton', 'Katipunan');
insert into kino (ime, kraj) values ('Luster', 'Zarechnyy');
insert into kino (ime, kraj) values ('Spohn', 'Buenavista');
insert into kino (ime, kraj) values ('Rowland', 'Ban Phai');
insert into kino (ime, kraj) values ('Dahle', 'Namibe');
insert into kino (ime, kraj) values ('Montana', 'Timrå');
insert into kino (ime, kraj) values ('Artisan', 'Gonghe');
insert into kino (ime, kraj) values ('Fairfield', 'Saint-Maurice-l''Exil');
insert into kino (ime, kraj) values ('American Ash', 'Hekou');
insert into kino (ime, kraj) values ('Stephen', 'Shahrud');
insert into kino (ime, kraj) values ('Petterle', 'Balad');
insert into kino (ime, kraj) values ('Rieder', 'Mulchén');
insert into kino (ime, kraj) values ('Loftsgordon', 'Faḩmah');
insert into kino (ime, kraj) values ('Delladonna', 'Chicago');
insert into kino (ime, kraj) values ('Stone Corner', 'Kandangsapi');
insert into kino (ime, kraj) values ('Jana', 'Luxor');
insert into kino (ime, kraj) values ('Northfield', 'Pont Cassé');
insert into kino (ime, kraj) values ('Armistice', 'Zürich');
insert into kino (ime, kraj) values ('Hauk', 'Shikou');
insert into kino (ime, kraj) values ('Utah', 'Wan’an');
insert into kino (ime, kraj) values ('Doe Crossing', 'Yuecheng');
insert into kino (ime, kraj) values ('Bobwhite', 'Baranowo');
insert into kino (ime, kraj) values ('Kenwood', 'Dawe');
insert into kino (ime, kraj) values ('Fairview', 'Pasirlaja');
insert into kino (ime, kraj) values ('Arkansas', 'Konibodom');
insert into kino (ime, kraj) values ('Village Green', 'Timurlorong');
insert into kino (ime, kraj) values ('Dunning', 'Yinyang');
insert into kino (ime, kraj) values ('Fallview', 'Rujewa');
insert into kino (ime, kraj) values ('Farwell', 'Uzda');
insert into kino (ime, kraj) values ('Village Green', 'Mizunami');
insert into kino (ime, kraj) values ('Maple', 'Kherson');
insert into kino (ime, kraj) values ('Holy Cross', 'Tucheng');
insert into kino (ime, kraj) values ('Bellgrove', 'Padaimut');
insert into kino (ime, kraj) values ('Portage', 'Agía Varvára');
insert into kino (ime, kraj) values ('Fieldstone', 'Guayabo Dulce');
insert into kino (ime, kraj) values ('Iowa', 'Kalisabuk');
insert into kino (ime, kraj) values ('Jana', 'Charlottenberg');
insert into kino (ime, kraj) values ('Gerald', 'Asahi');
insert into kino (ime, kraj) values ('Mifflin', 'Kungsbacka');
insert into kino (ime, kraj) values ('Loomis', 'Omboué');
insert into kino (ime, kraj) values ('Vermont', 'Jiangguanchi');
insert into kino (ime, kraj) values ('Oak Valley', 'Gunan');
insert into kino (ime, kraj) values ('Maple Wood', 'P’yŏngsŏng');
insert into kino (ime, kraj) values ('Bartelt', 'Huaqiu');
insert into kino (ime, kraj) values ('Kropf', 'Galubakul');
insert into kino (ime, kraj) values ('Bobwhite', 'Owerri');
insert into kino (ime, kraj) values ('Truax', 'Bohai');
insert into kino (ime, kraj) values ('Portage', 'Reuleuet');
insert into kino (ime, kraj) values ('5th', 'Halmstad');
insert into kino (ime, kraj) values ('Portage', 'San Vicente');
insert into kino (ime, kraj) values ('Pearson', 'Kamimaruko');
insert into kino (ime, kraj) values ('Warbler', 'Parachinar');
insert into kino (ime, kraj) values ('Bonner', 'Dziemiany');
insert into kino (ime, kraj) values ('Karstens', 'Nové Město pod Smrkem');
insert into kino (ime, kraj) values ('Kedzie', 'Corral de Bustos');
insert into kino (ime, kraj) values ('Clarendon', '‘Aşīrah ash Shamālīyah');
insert into kino (ime, kraj) values ('Towne', 'Dongzhang');
insert into kino (ime, kraj) values ('Messerschmidt', 'Szeged');
insert into kino (ime, kraj) values ('Badeau', 'Boršice');
insert into kino (ime, kraj) values ('Delaware', 'Tangjiapo');
insert into kino (ime, kraj) values ('Shopko', 'Charleston');
insert into kino (ime, kraj) values ('Blaine', 'Astana');
insert into kino (ime, kraj) values ('Canary', 'Arkalyk');
insert into kino (ime, kraj) values ('Esker', 'Venilale');
insert into kino (ime, kraj) values ('Washington', 'Pochayiv');
insert into kino (ime, kraj) values ('Marquette', 'Balatero');
insert into kino (ime, kraj) values ('Vernon', 'Kabare');
insert into kino (ime, kraj) values ('Schurz', 'Altavista');
insert into kino (ime, kraj) values ('Forest Run', 'Bankaw');
insert into kino (ime, kraj) values ('Sherman', 'Yushan');
insert into kino (ime, kraj) values ('Arapahoe', 'San Guillermo');
insert into kino (ime, kraj) values ('Summerview', 'Viñac');
insert into kino (ime, kraj) values ('Rigney', 'Abdurahmoni Jomí');
insert into kino (ime, kraj) values ('Rieder', 'Chelbasskaya');
insert into kino (ime, kraj) values ('Jenifer', 'Huolianpo');
insert into kino (ime, kraj) values ('Pleasure', 'Phanat Nikhom');
insert into kino (ime, kraj) values ('Westport', 'Wageningen');
insert into kino (ime, kraj) values ('Alpine', 'Oświęcim');
insert into kino (ime, kraj) values ('Holmberg', 'Raga');
insert into kino (ime, kraj) values ('Trailsway', 'Mirimire');
insert into kino (ime, kraj) values ('Fulton', 'Yichun');
insert into kino (ime, kraj) values ('Dakota', 'Yasinya');
insert into kino (ime, kraj) values ('Killdeer', 'Xarag');
insert into kino (ime, kraj) values ('Mccormick', 'Krmelín');
insert into kino (ime, kraj) values ('Maywood', 'Yangsha');
insert into kino (ime, kraj) values ('Barnett', 'Aygeshat');
insert into kino (ime, kraj) values ('Gateway', 'Jirjā');
insert into kino (ime, kraj) values ('Forest', 'Zhangdun');
insert into kino (ime, kraj) values ('Granby', 'Mosquée');
insert into kino (ime, kraj) values ('Lotheville', 'Santa Maria');
insert into kino (ime, kraj) values ('Algoma', 'Valencia');
insert into kino (ime, kraj) values ('Di Loreto', 'Lerrnanist');
insert into kino (ime, kraj) values ('Loeprich', 'Lahad Datu');
insert into kino (ime, kraj) values ('Lillian', 'Nagano-shi');
insert into kino (ime, kraj) values ('Sutherland', 'Silodakon');
insert into kino (ime, kraj) values ('Mccormick', 'Dongshan');
insert into kino (ime, kraj) values ('Oriole', 'Khromtau');
insert into kino (ime, kraj) values ('Springview', 'Säffle');
insert into kino (ime, kraj) values ('Boyd', 'Weda');
insert into kino (ime, kraj) values ('Banding', 'Fatufaun');
insert into kino (ime, kraj) values ('Muir', 'Al Qurayn');
insert into kino (ime, kraj) values ('Wayridge', 'Fátima');
insert into kino (ime, kraj) values ('Portage', 'Chinju');
insert into kino (ime, kraj) values ('Garrison', 'Mizdah');
insert into kino (ime, kraj) values ('Swallow', 'Ibaraki');
insert into kino (ime, kraj) values ('Ridgeview', 'Viļāni');
insert into kino (ime, kraj) values ('Roxbury', 'Shuanggang');
insert into kino (ime, kraj) values ('Sycamore', 'Markaz-e Ḩukūmat-e Darwēshān');
insert into kino (ime, kraj) values ('Forster', 'Zhangdan');
insert into kino (ime, kraj) values ('Thackeray', 'Norcasia');
insert into kino (ime, kraj) values ('Anzinger', 'Prinza');
insert into kino (ime, kraj) values ('Holmberg', 'Fāraskūr');
insert into kino (ime, kraj) values ('Monica', 'Baise City');
insert into kino (ime, kraj) values ('Sloan', 'Chóra');
insert into kino (ime, kraj) values ('Thompson', 'Quinta de Valadares');
insert into kino (ime, kraj) values ('Northview', 'Bojonghaur');
insert into kino (ime, kraj) values ('Cherokee', 'Gémeos');
insert into kino (ime, kraj) values ('David', 'Starcevica');
insert into kino (ime, kraj) values ('John Wall', 'Pretoria');
insert into kino (ime, kraj) values ('Green Ridge', 'Caijiapu');
insert into kino (ime, kraj) values ('Corscot', 'Janeng');
insert into kino (ime, kraj) values ('Northwestern', 'Primero de Mayo');
insert into kino (ime, kraj) values ('Anderson', 'Mmathubudukwane');
insert into kino (ime, kraj) values ('Nancy', 'Kelīshād va Sūdarjān');
insert into kino (ime, kraj) values ('Lakewood Gardens', 'Salerno');
insert into kino (ime, kraj) values ('Norway Maple', 'Barueri');
insert into kino (ime, kraj) values ('Talisman', 'Steblevë');
insert into kino (ime, kraj) values ('Mendota', 'Pateh Sam');
insert into kino (ime, kraj) values ('Veith', 'Anxi');
insert into kino (ime, kraj) values ('Hayes', 'Shangwuzhuang');
insert into kino (ime, kraj) values ('Forest Dale', 'Lengkongsari');
insert into kino (ime, kraj) values ('Graceland', 'Helixi');
insert into kino (ime, kraj) values ('Warner', 'Ögöömör');
insert into kino (ime, kraj) values ('Roth', 'Mukhen');
insert into kino (ime, kraj) values ('Cordelia', 'Alajuela');
insert into kino (ime, kraj) values ('Harper', 'Cemplang');
insert into kino (ime, kraj) values ('Stoughton', 'Hongmiao');
insert into kino (ime, kraj) values ('Sherman', 'Qing’an');
insert into kino (ime, kraj) values ('Dakota', 'Vacenovice');
insert into kino (ime, kraj) values ('Clarendon', 'Dartang');
insert into kino (ime, kraj) values ('Melby', 'Vista Hermosa');
insert into kino (ime, kraj) values ('Pond', 'Konggar');
insert into kino (ime, kraj) values ('Mcguire', 'Veiga');
insert into kino (ime, kraj) values ('Stoughton', 'Huacrapuquio');
insert into kino (ime, kraj) values ('Bayside', 'Marumori');
insert into kino (ime, kraj) values ('Manitowish', 'Yangtan');
insert into kino (ime, kraj) values ('Chive', 'Jiushe');
insert into kino (ime, kraj) values ('Melody', 'Araruama');
insert into kino (ime, kraj) values ('Luster', 'Metz');
insert into kino (ime, kraj) values ('Nova', 'Ivanec');
insert into kino (ime, kraj) values ('Service', 'Cigoong');
insert into kino (ime, kraj) values ('Buhler', 'Sergio Osmeña Sr');
insert into kino (ime, kraj) values ('Morningstar', 'Ulaan-Uul');
insert into kino (ime, kraj) values ('4th', 'Gelang');
insert into kino (ime, kraj) values ('Hazelcrest', 'Viedma');
insert into kino (ime, kraj) values ('1st', 'Arklow');
insert into kino (ime, kraj) values ('Weeping Birch', 'Desa Gegempalan');
insert into kino (ime, kraj) values ('Hanson', 'Banyumas');
insert into kino (ime, kraj) values ('Lotheville', 'Capela');
insert into kino (ime, kraj) values ('Brown', 'Brescia');
insert into kino (ime, kraj) values ('Dexter', 'Karlstad');
insert into kino (ime, kraj) values ('Linden', 'Jednorożec');
insert into kino (ime, kraj) values ('Jenna', 'Bergville');
insert into kino (ime, kraj) values ('American Ash', 'Mangga Dua');
insert into kino (ime, kraj) values ('Ronald Regan', 'Ruma');
insert into kino (ime, kraj) values ('Twin Pines', 'Cibebek');
insert into kino (ime, kraj) values ('Golden Leaf', 'Zaojiacheng');
insert into kino (ime, kraj) values ('Warrior', 'Newtown');
insert into kino (ime, kraj) values ('Warner', 'Tiyuguan');
insert into kino (ime, kraj) values ('Lakewood', 'San Francisco');
insert into kino (ime, kraj) values ('Mayer', 'Bīr Nabālā');
insert into kino (ime, kraj) values ('Kipling', 'Wuppertal');
insert into kino (ime, kraj) values ('Kim', 'Poja');
insert into kino (ime, kraj) values ('Corben', 'Matou');
insert into kino (ime, kraj) values ('Pennsylvania', 'Naḩḩālīn');
insert into kino (ime, kraj) values ('Mendota', 'Nangong');
insert into kino (ime, kraj) values ('Loftsgordon', 'Ipoh');
insert into kino (ime, kraj) values ('Green Ridge', 'Sheksna');
insert into kino (ime, kraj) values ('Starling', 'Zhenziliang');
insert into kino (ime, kraj) values ('Grasskamp', 'Pagelaran');
insert into kino (ime, kraj) values ('Graedel', 'Wafang');
insert into kino (ime, kraj) values ('Acker', 'Xin’an');
insert into kino (ime, kraj) values ('Maywood', 'Kuhmalahti');
insert into kino (ime, kraj) values ('Jana', 'Oleiros');
insert into kino (ime, kraj) values ('Calypso', 'Kozy');
insert into kino (ime, kraj) values ('Carberry', 'Cao Thượng');
insert into kino (ime, kraj) values ('Portage', 'Amagarapati');
insert into kino (ime, kraj) values ('Atwood', 'Zumarraga');
insert into kino (ime, kraj) values ('Colorado', 'Luzhuangzi');
insert into kino (ime, kraj) values ('Northview', 'Dong’ao');
insert into kino (ime, kraj) values ('Artisan', 'Kostanay');
insert into kino (ime, kraj) values ('Marcy', 'Huangtan');
insert into kino (ime, kraj) values ('Hoepker', 'Vacoas');
insert into kino (ime, kraj) values ('Stuart', 'Miaoxi');
insert into kino (ime, kraj) values ('Straubel', 'Mattaldi');
insert into kino (ime, kraj) values ('Texas', 'Mahuta');
insert into kino (ime, kraj) values ('Brown', 'Al Jamīmah');
insert into kino (ime, kraj) values ('Derek', 'Cibenda');
insert into kino (ime, kraj) values ('Grasskamp', 'Shenshan');
insert into kino (ime, kraj) values ('Lakewood Gardens', 'Pigí');
insert into kino (ime, kraj) values ('Becker', 'Wudangshan');
insert into kino (ime, kraj) values ('Atwood', 'Murfreesboro');
insert into kino (ime, kraj) values ('Del Mar', 'Lisewo Malborskie');
insert into kino (ime, kraj) values ('Leroy', 'Stare Pole');
insert into kino (ime, kraj) values ('Mcguire', 'Marseille');
insert into kino (ime, kraj) values ('Redwing', 'Grande Rivière Noire');
insert into kino (ime, kraj) values ('Becker', 'Oranmore');
insert into kino (ime, kraj) values ('Forest Dale', 'Jiaocheng');
insert into kino (ime, kraj) values ('Mitchell', 'Pingyi');
insert into kino (ime, kraj) values ('Grover', 'Myronivka');
insert into kino (ime, kraj) values ('Shopko', 'São José do Rio Preto');
insert into kino (ime, kraj) values ('Randy', 'Panagyurishte');
insert into kino (ime, kraj) values ('Arkansas', 'Jintian');
insert into kino (ime, kraj) values ('Truax', 'Dededo Village');
insert into kino (ime, kraj) values ('Bluejay', 'Castlebridge');
insert into kino (ime, kraj) values ('Glendale', 'Bebandem');
insert into kino (ime, kraj) values ('Susan', 'Zarumilla');
insert into kino (ime, kraj) values ('Straubel', 'Burgas');
insert into kino (ime, kraj) values ('Lunder', 'Beiquan');
insert into kino (ime, kraj) values ('Tony', 'Mehar');
insert into kino (ime, kraj) values ('Hoard', 'Kirovgrad');
insert into kino (ime, kraj) values ('Paget', 'Sam Roi Yot');
insert into kino (ime, kraj) values ('Stoughton', 'Wiązownica');
insert into kino (ime, kraj) values ('Southridge', 'Dobrzeń Wielki');
insert into kino (ime, kraj) values ('Montana', 'Taiping');
insert into kino (ime, kraj) values ('Northwestern', 'Tomé');
insert into kino (ime, kraj) values ('Kipling', 'Bartsrashen');
insert into kino (ime, kraj) values ('Sheridan', 'Karabash');
insert into kino (ime, kraj) values ('Fulton', 'Balading');
insert into kino (ime, kraj) values ('2nd', 'Dazuo');
insert into kino (ime, kraj) values ('Old Shore', 'Marinhais');
insert into kino (ime, kraj) values ('Doe Crossing', 'Nanhuang');
insert into kino (ime, kraj) values ('Lunder', 'Castro');
insert into kino (ime, kraj) values ('Cardinal', 'Majur');
insert into kino (ime, kraj) values ('Stang', 'Kamakura');
insert into kino (ime, kraj) values ('Fair Oaks', 'Kosino');
insert into kino (ime, kraj) values ('Lotheville', 'Meringkik');
insert into kino (ime, kraj) values ('Russell', 'Xêgar');
insert into kino (ime, kraj) values ('Spaight', 'Al Abyār');
insert into kino (ime, kraj) values ('Mesta', 'Donggu');
insert into kino (ime, kraj) values ('Jackson', 'Velestíno');
insert into kino (ime, kraj) values ('Glacier Hill', 'Berehomet');
insert into kino (ime, kraj) values ('Crescent Oaks', 'Labrang');
insert into kino (ime, kraj) values ('Merry', 'Siepraw');
insert into kino (ime, kraj) values ('Tony', 'Hrvatska Kostajnica');
insert into kino (ime, kraj) values ('Anderson', 'Nankou');
insert into kino (ime, kraj) values ('Doe Crossing', 'Ximafang');
insert into kino (ime, kraj) values ('Chive', 'Lanos');
insert into kino (ime, kraj) values ('Farwell', 'Hanfeng');
insert into kino (ime, kraj) values ('Sutteridge', 'Bagahanlad');
insert into kino (ime, kraj) values ('Kenwood', 'Huadian');
insert into kino (ime, kraj) values ('Mockingbird', 'Ranilug');
insert into kino (ime, kraj) values ('Lotheville', 'Baunu-Timbangan');
insert into kino (ime, kraj) values ('Kipling', 'San Simon');
insert into kino (ime, kraj) values ('Debs', 'Chelgard');
insert into kino (ime, kraj) values ('Judy', 'Kula');
insert into kino (ime, kraj) values ('Oxford', 'Ulricehamn');
insert into kino (ime, kraj) values ('Gateway', 'Río Blanquito');
insert into kino (ime, kraj) values ('Redwing', 'Jiahe');
insert into kino (ime, kraj) values ('Sherman', 'Marugame');
insert into kino (ime, kraj) values ('Carey', 'Babakankadu');
insert into kino (ime, kraj) values ('Magdeline', 'Donghoufang');
insert into kino (ime, kraj) values ('Bayside', 'Chetian');
insert into kino (ime, kraj) values ('Maple', 'Visby');
insert into kino (ime, kraj) values ('Bunting', 'Charras');
insert into kino (ime, kraj) values ('Riverside', 'Contramaestre');
insert into kino (ime, kraj) values ('Longview', 'Kozje');
insert into kino (ime, kraj) values ('Stuart', 'Jiblah');
insert into kino (ime, kraj) values ('Victoria', 'Estoril');
insert into kino (ime, kraj) values ('Jana', 'Leiyang');
insert into kino (ime, kraj) values ('3rd', 'Sanshui');
insert into kino (ime, kraj) values ('Straubel', 'Presidente Médici');
insert into kino (ime, kraj) values ('Golf Course', 'Guanagazapa');
insert into kino (ime, kraj) values ('Blackbird', 'Shazikou');
insert into kino (ime, kraj) values ('Corscot', 'Al Qardāḩah');
insert into kino (ime, kraj) values ('Sutherland', 'Xinxikou');
insert into kino (ime, kraj) values ('Melvin', 'Goundi');
insert into kino (ime, kraj) values ('Eagan', 'Bairro dos Marinheiros');
insert into kino (ime, kraj) values ('Texas', 'Fuji');
insert into kino (ime, kraj) values ('Hovde', 'Kampungsusah');
insert into kino (ime, kraj) values ('Anhalt', 'Ülken');
insert into kino (ime, kraj) values ('Claremont', 'Funan Chengguanzhen');
insert into kino (ime, kraj) values ('Montana', 'Laau');
insert into kino (ime, kraj) values ('Dixon', 'Mardakyany');
insert into kino (ime, kraj) values ('Briar Crest', 'Saint-Sauveur');
insert into kino (ime, kraj) values ('Carey', 'Vila Chã do Monte');
insert into kino (ime, kraj) values ('Porter', 'Beixinjie');
insert into kino (ime, kraj) values ('Roxbury', 'Hekou');
insert into kino (ime, kraj) values ('Florence', 'Longjumeau');
insert into kino (ime, kraj) values ('Michigan', 'Novorozhdestvenskaya');
insert into kino (ime, kraj) values ('Shoshone', 'Xiaoqi');
insert into kino (ime, kraj) values ('Darwin', 'Las Mercedes');
insert into kino (ime, kraj) values ('Mcguire', 'Murtajih');
insert into kino (ime, kraj) values ('Blue Bill Park', 'Huainan');
insert into kino (ime, kraj) values ('Pankratz', 'Peruc');
insert into kino (ime, kraj) values ('Crest Line', 'San Gregorio');
insert into kino (ime, kraj) values ('Continental', 'Royan');
insert into kino (ime, kraj) values ('Duke', 'San Bautista');
insert into kino (ime, kraj) values ('Hintze', 'Vynohradivka');
insert into kino (ime, kraj) values ('Texas', 'Bergem');
insert into kino (ime, kraj) values ('Becker', 'Duanshen');
insert into kino (ime, kraj) values ('Northport', 'Heshang');
insert into kino (ime, kraj) values ('Buell', 'Jining');
insert into kino (ime, kraj) values ('Cordelia', 'Xinfeng');
insert into kino (ime, kraj) values ('Moose', 'Rassvet');
insert into kino (ime, kraj) values ('Eggendart', 'Nekhayevskiy');
insert into kino (ime, kraj) values ('Londonderry', 'Rajhrad');
insert into kino (ime, kraj) values ('Cambridge', 'Oliveira');
insert into kino (ime, kraj) values ('International', 'Cacoal');
insert into kino (ime, kraj) values ('Manitowish', 'Morazán');
insert into kino (ime, kraj) values ('2nd', 'Mlangali');
insert into kino (ime, kraj) values ('Melody', 'Tayuan');
insert into kino (ime, kraj) values ('Hoffman', 'Paclolo');
insert into kino (ime, kraj) values ('Larry', 'Canmore');
insert into kino (ime, kraj) values ('Thackeray', 'Campos');
insert into kino (ime, kraj) values ('Hoffman', 'Aksarka');
insert into kino (ime, kraj) values ('Buena Vista', 'Corroios');
insert into kino (ime, kraj) values ('Schlimgen', 'Faranah');
insert into kino (ime, kraj) values ('Butternut', 'Tomaszów Mazowiecki');
insert into kino (ime, kraj) values ('Mccormick', 'Zhangjiafang');
insert into kino (ime, kraj) values ('Sauthoff', 'Cikajang');
insert into kino (ime, kraj) values ('Dakota', 'Yangqiaodian');
insert into kino (ime, kraj) values ('Manitowish', 'Kosonsoy Shahri');
insert into kino (ime, kraj) values ('Blue Bill Park', 'Rawawilis');
insert into kino (ime, kraj) values ('Barnett', 'Los Angeles');
insert into kino (ime, kraj) values ('Melody', 'Yaviza');
insert into kino (ime, kraj) values ('Maple', 'Headlands');
insert into kino (ime, kraj) values ('Bowman', 'Huyang');
insert into kino (ime, kraj) values ('Truax', 'Krasnoarmiys’k');
insert into kino (ime, kraj) values ('Northview', 'Ryūgasaki');
insert into kino (ime, kraj) values ('School', 'Easington');
insert into kino (ime, kraj) values ('Redwing', 'Verblyany');
insert into kino (ime, kraj) values ('Springview', 'Yonago');
insert into kino (ime, kraj) values ('Columbus', 'Xiachengzi');
insert into kino (ime, kraj) values ('Stone Corner', 'Naberera');
insert into kino (ime, kraj) values ('Mariners Cove', 'Qīr Moāv');
insert into kino (ime, kraj) values ('Petterle', 'Qinggang');
insert into kino (ime, kraj) values ('Straubel', 'Bryansk');
insert into kino (ime, kraj) values ('Calypso', 'Guzhu');
insert into kino (ime, kraj) values ('Shoshone', 'Swan Hills');
insert into kino (ime, kraj) values ('Hintze', 'Passo');
insert into kino (ime, kraj) values ('Stone Corner', 'Wukang');
insert into kino (ime, kraj) values ('Buhler', 'Paterson');
insert into kino (ime, kraj) values ('Del Sol', 'Badajoz');
insert into kino (ime, kraj) values ('Monica', 'Simrishamn');
insert into kino (ime, kraj) values ('Norway Maple', 'Shijiazhuang');
insert into kino (ime, kraj) values ('Granby', 'San Carlos');
insert into kino (ime, kraj) values ('Dottie', 'Várzea');
insert into kino (ime, kraj) values ('Eastlawn', 'Nong Ki');
insert into kino (ime, kraj) values ('Armistice', 'Quebradas');
insert into kino (ime, kraj) values ('Lakewood', 'Glyadyanskoye');
insert into kino (ime, kraj) values ('Sullivan', 'Gaocun');
insert into kino (ime, kraj) values ('Lakewood Gardens', 'Futtsu');
insert into kino (ime, kraj) values ('Hooker', 'Andkhōy');
insert into kino (ime, kraj) values ('Lyons', 'Bhamo');
insert into kino (ime, kraj) values ('Walton', 'Black River');
insert into kino (ime, kraj) values ('Service', 'Héroumbili');
insert into kino (ime, kraj) values ('Loftsgordon', 'Loujiadian');
insert into kino (ime, kraj) values ('Briar Crest', 'Tenja');
insert into kino (ime, kraj) values ('Evergreen', 'Oula Xiuma');
insert into kino (ime, kraj) values ('Saint Paul', 'Baoshan');
insert into kino (ime, kraj) values ('Maple Wood', 'Bintawan');
insert into kino (ime, kraj) values ('Clarendon', 'Shangcun');
insert into kino (ime, kraj) values ('Sutteridge', 'Longshan');
insert into kino (ime, kraj) values ('Ryan', 'Pesisir');
insert into kino (ime, kraj) values ('Montana', 'Lages');
insert into kino (ime, kraj) values ('Dovetail', 'Sanlidian');
insert into kino (ime, kraj) values ('Almo', 'Pedra Azul');
insert into kino (ime, kraj) values ('Almo', 'Sukasenang');
insert into kino (ime, kraj) values ('Bartillon', 'Corujeira');
insert into kino (ime, kraj) values ('Kinsman', 'Paris 01');
insert into kino (ime, kraj) values ('Cordelia', 'Peliyagoda');
insert into kino (ime, kraj) values ('Warbler', 'Jiuchenggong');
insert into kino (ime, kraj) values ('Warner', 'Kimhae');
insert into kino (ime, kraj) values ('Forest Dale', 'Ikoma');
insert into kino (ime, kraj) values ('Scott', 'Ariquemes');
insert into kino (ime, kraj) values ('Jay', 'Cashel');
insert into kino (ime, kraj) values ('Trailsway', 'Arys');
insert into kino (ime, kraj) values ('Westridge', 'Tessaoua');
insert into kino (ime, kraj) values ('3rd', 'Jiazhuang');
insert into kino (ime, kraj) values ('Trailsway', 'Malaga');
insert into kino (ime, kraj) values ('Pankratz', 'Jiaqu');
insert into kino (ime, kraj) values ('Elmside', 'Yŏnan-ŭp');
insert into kino (ime, kraj) values ('Lyons', 'Yablochnyy');
insert into kino (ime, kraj) values ('Old Shore', 'Weiguo');
insert into kino (ime, kraj) values ('Express', 'Kushchëvskaya');
insert into kino (ime, kraj) values ('Troy', 'Jitian');
insert into kino (ime, kraj) values ('Southridge', 'Pingshan');
insert into kino (ime, kraj) values ('Village', 'Kotor');
insert into kino (ime, kraj) values ('Kipling', 'Zhoutou');
insert into kino (ime, kraj) values ('Merchant', 'Cikalaces');
insert into kino (ime, kraj) values ('Killdeer', 'Volodarka');
insert into kino (ime, kraj) values ('Lyons', 'Ar Rawḑah');
insert into kino (ime, kraj) values ('Debra', 'Cibaregbeg');
insert into kino (ime, kraj) values ('Warbler', 'Peimei');
insert into kino (ime, kraj) values ('Meadow Valley', 'Maukaro');
insert into kino (ime, kraj) values ('Roth', 'Bayshint');
insert into kino (ime, kraj) values ('Holy Cross', 'Venustiano Carranza');
insert into kino (ime, kraj) values ('Declaration', 'Ganjaran');
insert into kino (ime, kraj) values ('Crowley', 'Itaúna');
insert into kino (ime, kraj) values ('Anthes', 'Xingbin');
insert into kino (ime, kraj) values ('Beilfuss', 'Pensacola');
insert into kino (ime, kraj) values ('Fallview', 'Jingchuan Chengguanzhen');
insert into kino (ime, kraj) values ('Lakewood Gardens', 'Neochórion');
insert into kino (ime, kraj) values ('Lindbergh', 'Magugu');
insert into kino (ime, kraj) values ('Rutledge', 'Karang Daye');
insert into kino (ime, kraj) values ('West', 'Dingtao');
insert into kino (ime, kraj) values ('Canary', 'Qingquan');
insert into kino (ime, kraj) values ('Red Cloud', 'Gangbian');
insert into kino (ime, kraj) values ('Columbus', 'Minamata');
insert into kino (ime, kraj) values ('Ramsey', 'Anningqu');
insert into kino (ime, kraj) values ('Valley Edge', 'Paris 15');
insert into kino (ime, kraj) values ('Canary', 'San Andres');
insert into kino (ime, kraj) values ('Mifflin', 'Chitose');
insert into kino (ime, kraj) values ('Reinke', 'Lalībela');
insert into kino (ime, kraj) values ('Green', 'Pršovce');
insert into kino (ime, kraj) values ('Blackbird', 'San Vicente');
insert into kino (ime, kraj) values ('Anzinger', 'Jianchang');
insert into kino (ime, kraj) values ('Gina', 'Sergelen');
insert into kino (ime, kraj) values ('Huxley', 'Vällingby');
insert into kino (ime, kraj) values ('Onsgard', 'Sunne');
insert into kino (ime, kraj) values ('Autumn Leaf', 'Brejoeira');
insert into kino (ime, kraj) values ('Northport', 'Krandil');
insert into kino (ime, kraj) values ('Cambridge', 'Hondo');
insert into kino (ime, kraj) values ('Tennyson', 'Saransk');
insert into kino (ime, kraj) values ('Ruskin', 'Naperville');
insert into kino (ime, kraj) values ('Basil', 'Wulong');
insert into kino (ime, kraj) values ('Carey', 'Yasenevo');
insert into kino (ime, kraj) values ('Blackbird', 'Pukkila');
insert into kino (ime, kraj) values ('Logan', 'Sandia');
insert into kino (ime, kraj) values ('Spaight', 'Gainesville');
insert into kino (ime, kraj) values ('Pennsylvania', 'Gechuan');
insert into kino (ime, kraj) values ('Shoshone', 'Mamboma');
insert into kino (ime, kraj) values ('Rowland', 'Nanhai');
insert into kino (ime, kraj) values ('Upham', 'Pasirjaya');
insert into kino (ime, kraj) values ('Eggendart', 'Rizokárpaso');
insert into kino (ime, kraj) values ('Columbus', 'Xiniu');
insert into kino (ime, kraj) values ('Westport', 'Ōmura');
insert into kino (ime, kraj) values ('Northland', 'Khudāydād Khēl');
insert into kino (ime, kraj) values ('Dahle', 'Palmar de Varela');
insert into kino (ime, kraj) values ('Starling', 'Mtambile');
insert into kino (ime, kraj) values ('Waubesa', 'Auas');
insert into kino (ime, kraj) values ('Dahle', 'Lleida');
insert into kino (ime, kraj) values ('Redwing', 'Matiao');
insert into kino (ime, kraj) values ('Grasskamp', 'Jatiklampok');
insert into kino (ime, kraj) values ('Maywood', 'Prachamtakham');
insert into kino (ime, kraj) values ('Eagan', 'Lushnjë');
insert into kino (ime, kraj) values ('Thierer', 'Ko Si Chang');
insert into kino (ime, kraj) values ('Melby', 'Dukuhsawah');
insert into kino (ime, kraj) values ('Mitchell', 'Kodinsk');
insert into kino (ime, kraj) values ('Cascade', 'Kohlu');
insert into kino (ime, kraj) values ('Lillian', 'Győr');
insert into kino (ime, kraj) values ('Anhalt', 'Glinka');
insert into kino (ime, kraj) values ('Mosinee', 'Bama');
insert into kino (ime, kraj) values ('Farwell', 'Diapaga');
insert into kino (ime, kraj) values ('Mariners Cove', 'Emiliano Zapata');
insert into kino (ime, kraj) values ('Hollow Ridge', 'Almaty');
insert into kino (ime, kraj) values ('Shasta', 'Mizunami');
insert into kino (ime, kraj) values ('Namekagon', 'Pułtusk');
insert into kino (ime, kraj) values ('Jenna', 'Komsomolets');
insert into kino (ime, kraj) values ('Canary', 'Palmito');
insert into kino (ime, kraj) values ('Anniversary', 'Lanjaghbyur');
insert into kino (ime, kraj) values ('Northland', 'Chouto');
insert into kino (ime, kraj) values ('Hansons', 'Guilherand-Granges');
insert into kino (ime, kraj) values ('Old Shore', 'Libertad');
insert into kino (ime, kraj) values ('Spohn', 'Krajan Rowokangkung');
insert into kino (ime, kraj) values ('Clyde Gallagher', 'Luojiaping');
insert into kino (ime, kraj) values ('Washington', 'Sorong');
insert into kino (ime, kraj) values ('Kings', 'Paso de Carrasco');
insert into kino (ime, kraj) values ('Farmco', 'Thanatpin');
insert into kino (ime, kraj) values ('West', 'Reims');
insert into kino (ime, kraj) values ('Fallview', 'Tobias Barreto');
insert into kino (ime, kraj) values ('Jackson', 'Bunutan');
insert into kino (ime, kraj) values ('Village Green', 'Budy');
insert into kino (ime, kraj) values ('Summerview', 'Santana do Paraíso');
insert into kino (ime, kraj) values ('Blackbird', 'Keffi');
insert into kino (ime, kraj) values ('Forest', 'Chigan');
insert into kino (ime, kraj) values ('Stephen', 'Trstenik');
insert into kino (ime, kraj) values ('Del Mar', 'El Valle del Espíritu Santo');
insert into kino (ime, kraj) values ('Arkansas', 'Pojok');
insert into kino (ime, kraj) values ('Homewood', 'Donduşeni');
insert into kino (ime, kraj) values ('Westport', 'Cibalieur');
insert into kino (ime, kraj) values ('Twin Pines', 'Bardīyah');
insert into kino (ime, kraj) values ('Pepper Wood', 'Tian’an');
insert into kino (ime, kraj) values ('Brentwood', 'Soa');
insert into kino (ime, kraj) values ('Hoffman', 'Gan Yavne');
insert into kino (ime, kraj) values ('Briar Crest', 'Shatoujiao');
insert into kino (ime, kraj) values ('Pepper Wood', 'Semambung');
insert into kino (ime, kraj) values ('Loftsgordon', 'Al Aḩmadī');
insert into kino (ime, kraj) values ('Hayes', 'Obsharovka');
insert into kino (ime, kraj) values ('Trailsway', 'Marystown');
insert into kino (ime, kraj) values ('Forest', 'Sanhe');
insert into kino (ime, kraj) values ('New Castle', 'Binuangan');
insert into kino (ime, kraj) values ('Randy', 'Falkenberg');
insert into kino (ime, kraj) values ('Packers', 'Paris La Défense');
insert into kino (ime, kraj) values ('Petterle', 'Chicago');
insert into kino (ime, kraj) values ('Debra', 'Huangshanguan');
insert into kino (ime, kraj) values ('Green', 'Jiaodai');
insert into kino (ime, kraj) values ('Pine View', 'Bang Nam Priao');
insert into kino (ime, kraj) values ('Harbort', 'Candi');
insert into kino (ime, kraj) values ('Melby', 'Laï');
insert into kino (ime, kraj) values ('Stone Corner', 'Polos');
insert into kino (ime, kraj) values ('Carey', 'Nahāvand');
insert into kino (ime, kraj) values ('Iowa', 'Rucava');
insert into kino (ime, kraj) values ('Ridgeview', 'Wschowa');
insert into kino (ime, kraj) values ('Killdeer', 'Chugay');
insert into kino (ime, kraj) values ('Mariners Cove', 'Winburg');
insert into kino (ime, kraj) values ('Beilfuss', 'Turka');
insert into kino (ime, kraj) values ('Eagle Crest', 'Brejo Santo');
insert into kino (ime, kraj) values ('Jackson', 'San Juan de la Maguana');
insert into kino (ime, kraj) values ('Anniversary', 'Dzhetygara');
insert into kino (ime, kraj) values ('Buhler', 'Petrich');
insert into kino (ime, kraj) values ('Bultman', 'Dusun Tengah Cihaurbeuti');
insert into kino (ime, kraj) values ('Carberry', 'Plyeshchanitsy');
insert into kino (ime, kraj) values ('1st', 'Silab');
insert into kino (ime, kraj) values ('Canary', 'Hongxi');
insert into kino (ime, kraj) values ('Thierer', 'Galutu');
insert into kino (ime, kraj) values ('Fairfield', 'Bomomani');
insert into kino (ime, kraj) values ('Eliot', 'Épinal');
insert into kino (ime, kraj) values ('La Follette', 'Miastko');
insert into kino (ime, kraj) values ('Center', 'Bin Yauri');
insert into kino (ime, kraj) values ('Hudson', 'Koupéla');
insert into kino (ime, kraj) values ('Mariners Cove', 'Zhongjiapu');
insert into kino (ime, kraj) values ('Merrick', 'Jingzhou');
insert into kino (ime, kraj) values ('Elmside', 'Belverde');
insert into kino (ime, kraj) values ('Longview', 'Bentiu');
insert into kino (ime, kraj) values ('Thompson', 'Jincheng');
insert into kino (ime, kraj) values ('Dixon', 'Oromocto');
insert into kino (ime, kraj) values ('John Wall', 'Ibung');
insert into kino (ime, kraj) values ('Petterle', 'Ta’erqi');
insert into kino (ime, kraj) values ('Little Fleur', 'Mucllo');
insert into kino (ime, kraj) values ('Vermont', 'Shunhe');
insert into kino (ime, kraj) values ('Rigney', 'Haylaastay');
insert into kino (ime, kraj) values ('Hagan', 'Yarabamba');
insert into kino (ime, kraj) values ('Rutledge', 'Niška Banja');
insert into kino (ime, kraj) values ('Londonderry', 'Chebba');
insert into kino (ime, kraj) values ('Autumn Leaf', 'Keli');
insert into kino (ime, kraj) values ('Moland', 'San Cristóbal Verapaz');
insert into kino (ime, kraj) values ('Coleman', 'Boynton Beach');
insert into kino (ime, kraj) values ('Lotheville', 'Hénin-Beaumont');
insert into kino (ime, kraj) values ('Bayside', 'Koper');
insert into kino (ime, kraj) values ('Alpine', 'Reggada');
insert into kino (ime, kraj) values ('Meadow Valley', 'Baisangguan');
insert into kino (ime, kraj) values ('Sommers', 'Lebahseri');
insert into kino (ime, kraj) values ('Thackeray', 'Minshan');
insert into kino (ime, kraj) values ('Holy Cross', 'Malasin');
insert into kino (ime, kraj) values ('Mifflin', 'Gaoyi');
insert into kino (ime, kraj) values ('Lawn', 'Guadalupe');
insert into kino (ime, kraj) values ('Shelley', 'Maisons-Alfort');
insert into kino (ime, kraj) values ('Manitowish', 'Betong');
insert into kino (ime, kraj) values ('Lillian', 'Shypyntsi');
insert into kino (ime, kraj) values ('Fallview', 'Mamara');
insert into kino (ime, kraj) values ('Schlimgen', 'Las Higueras');
insert into kino (ime, kraj) values ('South', 'Dazhipo');
insert into kino (ime, kraj) values ('Westport', 'Guisijan');
insert into kino (ime, kraj) values ('Mifflin', 'El Ángel');
insert into kino (ime, kraj) values ('Northport', 'Shuyuan');
insert into kino (ime, kraj) values ('Lerdahl', 'Telmin Suma');
insert into kino (ime, kraj) values ('Blackbird', 'Dacudao');
insert into kino (ime, kraj) values ('Red Cloud', 'Taber');
insert into kino (ime, kraj) values ('Randy', 'Palencia');
insert into kino (ime, kraj) values ('Green', 'Chixi');
insert into kino (ime, kraj) values ('Algoma', 'Funan Chengguanzhen');
insert into kino (ime, kraj) values ('Evergreen', 'Klobuky');
insert into kino (ime, kraj) values ('Lyons', 'Burevestnik');
insert into kino (ime, kraj) values ('Fisk', 'Yaojiagou');
insert into kino (ime, kraj) values ('Ilene', 'Terbangan');
insert into kino (ime, kraj) values ('Moland', 'Angochi');
insert into kino (ime, kraj) values ('Jana', 'Cametá');
insert into kino (ime, kraj) values ('Parkside', 'Klenje');
insert into kino (ime, kraj) values ('Starling', 'Bochum');
insert into kino (ime, kraj) values ('Golf', 'Zavitinsk');
insert into kino (ime, kraj) values ('Bonner', 'Argel');
insert into kino (ime, kraj) values ('Porter', 'Marseille');
insert into kino (ime, kraj) values ('Meadow Valley', 'Helsingborg');
insert into kino (ime, kraj) values ('Talisman', 'Zhongshanlu');
insert into kino (ime, kraj) values ('Farmco', 'Neqāb');
insert into kino (ime, kraj) values ('Brentwood', 'Maoyang');
insert into kino (ime, kraj) values ('Holmberg', 'Birowo');
insert into kino (ime, kraj) values ('Fairview', 'Farīmān');
insert into kino (ime, kraj) values ('Luster', 'Tomado');
insert into kino (ime, kraj) values ('Sunbrook', 'Čakovec');
insert into kino (ime, kraj) values ('Jana', 'Puyan');
insert into kino (ime, kraj) values ('Tennessee', 'Bondo');
insert into kino (ime, kraj) values ('Ridge Oak', 'Zuocun');
insert into kino (ime, kraj) values ('Fairfield', 'Trubchevsk');
insert into kino (ime, kraj) values ('Brickson Park', 'Kislyakovskaya');
insert into kino (ime, kraj) values ('Packers', 'Psachná');
insert into kino (ime, kraj) values ('Merrick', 'Boco');
insert into kino (ime, kraj) values ('Novick', 'Leicheng');
insert into kino (ime, kraj) values ('Jackson', 'Santa Helena');
insert into kino (ime, kraj) values ('Warbler', 'Laoshawan');
insert into kino (ime, kraj) values ('Bobwhite', 'Oslo');
insert into kino (ime, kraj) values ('Towne', 'Jīroft');
insert into kino (ime, kraj) values ('Mallard', 'Lukovo');
insert into kino (ime, kraj) values ('Grim', 'Barão de São Miguel');
insert into kino (ime, kraj) values ('Myrtle', 'Tayu');
insert into kino (ime, kraj) values ('Mayer', 'Meiyuan');
insert into kino (ime, kraj) values ('Mariners Cove', 'Newark');
insert into kino (ime, kraj) values ('Express', 'Genteng');
insert into kino (ime, kraj) values ('Brickson Park', 'Puzi');
insert into kino (ime, kraj) values ('Twin Pines', 'Los Angeles');
insert into kino (ime, kraj) values ('Dawn', 'Jiamiao');
insert into kino (ime, kraj) values ('Buena Vista', 'Mooirivier');
insert into kino (ime, kraj) values ('Nobel', 'Kroonstad');
insert into kino (ime, kraj) values ('Esker', 'Baoluan');
insert into kino (ime, kraj) values ('Elka', 'Thongwa');
insert into kino (ime, kraj) values ('Twin Pines', 'Marseille');
insert into kino (ime, kraj) values ('Oxford', 'Orléans');
insert into kino (ime, kraj) values ('Lindbergh', 'Machikou');
insert into kino (ime, kraj) values ('Fieldstone', 'Monte de Fralães');
insert into kino (ime, kraj) values ('Anhalt', 'Keboireng');
insert into kino (ime, kraj) values ('Northview', 'Chornukhyne');
insert into kino (ime, kraj) values ('Magdeline', 'Rozsypne');
insert into kino (ime, kraj) values ('Eliot', 'Złotów');
insert into kino (ime, kraj) values ('Chinook', 'Yuguan');
insert into kino (ime, kraj) values ('Beilfuss', 'Saint-Claude');
insert into kino (ime, kraj) values ('Manufacturers', 'Skomlin');
insert into kino (ime, kraj) values ('Dwight', 'Ciénaga de Oro');
insert into kino (ime, kraj) values ('Toban', 'Thủ Thừa');
insert into kino (ime, kraj) values ('Ramsey', 'Ning’an');
insert into kino (ime, kraj) values ('Cordelia', 'Gândara');
insert into kino (ime, kraj) values ('Delaware', 'Kirovskiy');
insert into kino (ime, kraj) values ('Fieldstone', 'Betzdorf');
insert into kino (ime, kraj) values ('Rusk', 'Hostos');
insert into kino (ime, kraj) values ('Washington', 'Brovary');
insert into kino (ime, kraj) values ('Kedzie', 'Kemijärvi');
insert into kino (ime, kraj) values ('Lien', 'Cahuac');
insert into kino (ime, kraj) values ('Waxwing', 'Séléa');
insert into kino (ime, kraj) values ('Walton', 'Guaíba');
insert into kino (ime, kraj) values ('Ronald Regan', 'Vavoua');
insert into kino (ime, kraj) values ('South', 'Stockholm');
insert into kino (ime, kraj) values ('Erie', 'Sosnovyy Bor');
insert into kino (ime, kraj) values ('East', 'Buzdyak');
insert into kino (ime, kraj) values ('Maple Wood', 'Dulles');
insert into kino (ime, kraj) values ('Acker', 'Luthu');
insert into kino (ime, kraj) values ('Hansons', 'Annaka');
insert into kino (ime, kraj) values ('Hagan', 'Hengshi');
insert into kino (ime, kraj) values ('Magdeline', 'Xianglong');
insert into kino (ime, kraj) values ('4th', 'Engenho');
insert into kino (ime, kraj) values ('Village', 'Staraya Ladoga');
insert into kino (ime, kraj) values ('Lillian', 'Staropavlovskaya');
insert into kino (ime, kraj) values ('Mayfield', 'Suchań');
insert into kino (ime, kraj) values ('Ilene', 'Sikeshu');
insert into kino (ime, kraj) values ('Sheridan', 'Philadelphia');
insert into kino (ime, kraj) values ('Meadow Vale', 'Vanadjou');
insert into kino (ime, kraj) values ('Morningstar', 'Tagum');
insert into kino (ime, kraj) values ('New Castle', 'Póvoa');
insert into kino (ime, kraj) values ('Algoma', 'Ziway');
insert into kino (ime, kraj) values ('Farragut', 'Usquil');
insert into kino (ime, kraj) values ('Cardinal', 'Permas');
insert into kino (ime, kraj) values ('Sunnyside', 'Radojevo');
insert into kino (ime, kraj) values ('Hayes', 'Capanema');
insert into kino (ime, kraj) values ('Reinke', 'Salcedo');
insert into kino (ime, kraj) values ('Warbler', 'Chiscas');
insert into kino (ime, kraj) values ('Anniversary', 'Tomaševac');
insert into kino (ime, kraj) values ('Summit', 'Diên Khánh');
insert into kino (ime, kraj) values ('Reinke', 'Payabon');
insert into kino (ime, kraj) values ('Cascade', 'Minbu');
