insert into na_voljo (kino_ime, prigrizek_ime) values ('Schmedeman', 'Lambcasing');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Green', 'Maple Syrup');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Division', 'Fond - Neutral');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Glendale', 'Plate Foam Laminated 9in Blk');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Riverside', 'Soap - Pine Sol Floor Cleaner');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Basil', 'Lady Fingers');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Artisan', 'Sugar - White Packet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nelson', 'Guinea Fowl');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Graedel', 'Wine - Two Oceans Sauvignon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('South', 'Samosa - Veg');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bonner', 'Veal - Brisket, Provimi,bnls');
insert into na_voljo (kino_ime, prigrizek_ime) values ('6th', 'Ice Cream - Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('International', 'Lamb - Shoulder');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carberry', 'Calypso - Black Cherry Lemonade');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Reinke', 'Pails With Lids');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jenifer', 'Cookie - Oreo 100x2');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Union', 'Ecolab Silver Fusion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Colorado', 'Water - Mineral, Carbonated');
insert into na_voljo (kino_ime, prigrizek_ime) values ('South', 'Chicken - White Meat With Tender');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oneill', 'Sprite - 355 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Twin Pines', 'Cheese - Gouda Smoked');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sachtjen', 'Sauce - Soy Low Sodium - 3.87l');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dakota', 'Mushroom - Porcini, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sommers', 'Muffin - Mix - Bran And Maple 15l');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Blaine', 'Wine - White, Mosel Gold');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Coolidge', 'Juice - Lemon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mitchell', 'Nantucket Cranberry Juice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Texas', 'Juice - Cranberry, 341 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mcguire', 'Pineapple - Canned, Rings');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Prairieview', 'Water - Perrier');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golden Leaf', 'Sachet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Little Fleur', 'Coffee Cup 8oz 5338cd');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sachtjen', 'Cabbage Roll');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stang', 'Tuna - Salad Premix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carey', 'Soap - Mr.clean Floor Soap');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Porter', 'Veal - Slab Bacon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dennis', 'Chocolate - Chips Compound');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dapin', 'Soup - Campbells, Butternut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Linden', 'Cheese - Blue');
insert into na_voljo (kino_ime, prigrizek_ime) values ('North', 'Longos - Grilled Chicken With');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Green', 'Chocolate - Feathers');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lillian', 'Pepper - Roasted Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Armistice', 'Nut - Chestnuts, Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ridgeway', 'Oil - Sesame');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Namekagon', 'Tomatoes - Diced, Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('American', 'Nantucket - Carrot Orange');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Grayhawk', 'Wine - White, Cooking');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf', 'Beets - Mini Golden');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Reindahl', 'Wine - Piper Heidsieck Brut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kennedy', 'Soup - Cream Of Broccoli, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Amoth', 'Pastry - Apple Large');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ilene', 'Plate Pie Foil');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mesta', 'Soup Bowl Clear 8oz92008');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Center', 'Beer - Labatt Blue');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mcguire', 'Vanilla Beans');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jay', 'Flour - Corn, Fine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Center', 'Soup - Knorr, Chicken Gumbo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oxford', 'Bar - Sweet And Salty Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Browning', 'Cheese - Feta');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ryan', 'Hagen Daza - Dk Choocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Springview', 'Pineapple - Regular');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bowman', 'Coffee - Hazelnut Cream');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Utah', 'Wine - Winzer Krems Gruner');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Banding', 'Pie Filling - Cherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Del Sol', 'Petite Baguette');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Del Mar', 'Pasta - Orecchiette');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lunder', 'Rosemary - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('5th', 'Muffin Hinge 117n');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bartillon', 'Bread - Crusty Italian Poly');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Orin', 'Oil - Grapeseed Oil');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Canary', 'Dill - Primerba, Paste');
insert into na_voljo (kino_ime, prigrizek_ime) values ('New Castle', 'Spaghetti Squash');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Twin Pines', 'Chocolate Bar - Smarties');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brown', 'Coffee - 10oz Cup 92961');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fordem', 'Steampan - Half Size Shallow');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Manley', 'Pesto - Primerba, Paste');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Coleman', 'Food Colouring - Blue');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rigney', 'Liners - Banana, Paper');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Main', 'Cloves - Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bluejay', 'Cookie Dough - Peanut Butter');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Knutson', 'Oil - Olive Bertolli');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bunker Hill', 'Pasta - Spaghetti, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ruskin', 'Muffin Batt - Choc Chk');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moland', 'Sambuca - Opal Nera');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vidon', 'Muffin Carrot - Individual');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Thackeray', 'Chicken - Wings, Tip Off');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schurz', 'Sauce - Soya, Dark');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Redwing', 'Muffin Mix - Banana Nut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Blue Bill Park', 'Pear - Asian');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vermont', 'Beef Tenderloin Aaa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Texas', 'Wine - Barbera Alba Doc 2001');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Continental', 'Cheese - Fontina');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clyde Gallagher', 'Oven Mitts 17 Inch');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Drewry', 'Yeast - Fresh, Fleischman');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nova', 'Lamb - Loin Chops');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cottonwood', 'Apples - Spartan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Huxley', 'Coffee - Decaffeinato Coffee');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fallview', 'Coffee Cup 8oz 5338cd');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northfield', 'Sprouts - Onion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf Course', 'Sparkling Wine - Rose, Freixenet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hayes', 'Banana - Leaves');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northland', 'Wine - Beringer Founders Estate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lyons', 'Nantucket Apple Juice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('2nd', 'Cheese - Mozzarella');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Caliangt', 'Tart Shells - Sweet, 2');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Twin Pines', 'Boogies');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Colorado', 'Venison - Liver');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rusk', 'Veal - Sweetbread');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Barnett', 'Jameson Irish Whiskey');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westport', 'Couscous');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ilene', 'Aspic - Amber');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Randy', 'Sour Puss Sour Apple');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kinsman', 'Lettuce - Sea / Sea Asparagus');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hudson', 'Crush - Cream Soda');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Upham', 'Salt - Kosher');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gerald', 'Ecolab Silver Fusion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rutledge', 'Spice - Pepper Portions');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Autumn Leaf', 'Dried Peach');
insert into na_voljo (kino_ime, prigrizek_ime) values ('La Follette', 'Peppercorns - Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Glendale', 'Puree - Mango');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gerald', 'Yogurt - Raspberry, 175 Gr');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Norway Maple', 'Nantucket Orange Juice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fulton', 'Bagel - Whole White Sesame');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bobwhite', 'Corn - Cream, Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kings', 'Beef - Montreal Smoked Brisket');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gale', 'Lamb - Loin Chops');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eastwood', 'Coffee - Flavoured');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunnyside', 'Chef Hat 20cm');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shoshone', 'Wine La Vielle Ferme Cote Du');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oak Valley', 'Table Cloth 54x54 Colour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('South', 'Cheese - Cottage Cheese');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf', 'Kahlua');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Elmside', 'Compound - Orange');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Duke', 'Lychee');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Butternut', 'Wine - Acient Coast Caberne');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Linden', 'Lentils - Green, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anhalt', 'Soup - French Can Pea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Garrison', 'Hinge W Undercut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hoffman', 'Energy Drink');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carey', 'Vinegar - Rice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('American', 'Croissant, Raw - Mini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Leroy', 'Coffee - 10oz Cup 92961');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Michigan', 'Creme De Cacao Mcguines');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kensington', 'Bacon Strip Precooked');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Butternut', 'Plastic Arrow Stir Stick');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Artisan', 'Wine - Cave Springs Dry Riesling');
insert into na_voljo (kino_ime, prigrizek_ime) values ('8th', 'Towel - Roll White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oriole', 'Squid - Breaded');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dawn', 'Red Cod Fillets - 225g');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Reindahl', 'Horseradish Root');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waubesa', 'Yams');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Warbler', 'Coriander - Seed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bonner', 'Pork Casing');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moulton', 'Bread - Raisin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('East', 'Containter - 3oz Microwave Rect.');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hooker', 'Pomello');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Roxbury', 'Pepper - Red Chili');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Parkside', 'Eggroll');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Troy', 'Flour - Cake');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Charing Cross', 'Beans - Butter Lrg Lima');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Heath', 'Mushroom - Chantrelle, Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ludington', 'Crab - Imitation Flakes');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nevada', 'Papadam');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Old Shore', 'Muffin - Zero Transfat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dennis', 'Glove - Cutting');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maywood', 'Ham - Cooked Bayonne Tinned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nevada', 'Cheese - Cambozola');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Talisman', 'Coffee - French Vanilla Frothy');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Blackbird', 'Longos - Lasagna Veg');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fuller', 'Turnip - White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Leroy', 'Chicken - White Meat, No Tender');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crescent Oaks', 'Cheese - Grie Des Champ');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mockingbird', 'Nut - Almond, Blanched, Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Havey', 'Wine - Marlbourough Sauv Blanc');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dryden', 'Bar - Sweet And Salty Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Elgar', 'Nut - Pumpkin Seeds');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schmedeman', 'Muffin - Mix - Mango Sour Cherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maple', 'Wine - Pinot Noir Pond Haddock');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Macpherson', 'Pasta - Cappellini, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mosinee', 'Longos - Greek Salad');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Transport', 'Snails - Large Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schlimgen', 'Steampan Lid');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bunting', 'Cookies Oatmeal Raisin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Linden', 'Soup - Campbells, Beef Barley');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buena Vista', 'Caviar - Salmon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rowland', 'Mini - Vol Au Vents');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Barnett', 'V8 - Tropical Blend');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bowman', 'Soup - Campbells Chicken');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Springs', 'Sunflower Seed Raw');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Butternut', 'Flavouring - Orange');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vidon', 'Rolled Oats');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Chinook', 'Bread - Italian Corn Meal Poly');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakewood', 'Clam - Cherrystone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Thackeray', 'Glove - Cutting');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bartelt', 'Calypso - Lemonade');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Debs', 'Table Cloth 62x120 Colour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mallory', 'Pasta - Shells, Medium, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bunker Hill', 'Creme De Cacao White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dakota', 'Water - San Pellegrino');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Armistice', 'The Pop Shoppe Pinapple');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Warner', 'Ice Cream - Life Savers');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Independence', 'Papadam');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eagan', 'Crab - Dungeness, Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Onsgard', 'Onion - Dried');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Springs', 'Cabbage - Nappa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tomscot', 'Turnip - White, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hazelcrest', 'Beets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunnyside', 'Caviar - Salmon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Washington', 'Pork - Side Ribs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mcbride', 'Snapple - Mango Maddness');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Iowa', 'Wine - Magnotta - Cab Franc');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oriole', 'Beef - Salted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ridgeway', 'Bread Crumbs - Japanese Style');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hansons', 'Lettuce - Red Leaf');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Iowa', 'Energy - Boo - Koo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Delaware', 'Cake - Cheese Cake 9 Inch');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nova', 'Glaze - Apricot');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rutledge', 'Butter - Salted, Micro');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clemons', 'Soup Bowl Clear 8oz92008');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Myrtle', 'Pasta - Canelloni, Single Serve');
insert into na_voljo (kino_ime, prigrizek_ime) values ('2nd', 'Tomato - Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('8th', 'Wine - Shiraz Wolf Blass Premium');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merchant', 'Tea - Apple Green Tea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stephen', 'Chinese Foods - Chicken Wing');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brickson Park', 'Kale - Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westport', 'Dried Cherries');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Surrey', 'Chocolate Bar - Coffee Crisp');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kings', 'Rum - Spiced, Captain Morgan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Truax', 'Table Cloth 62x114 Colour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Park Meadow', 'Flour - Corn, Fine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pierstorff', 'Molasses - Fancy');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Canary', 'Oil - Avocado');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vidon', 'Crab - Back Fin Meat, Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pennsylvania', 'Beef - Ox Tongue, Pickled');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hovde', 'Bandage - Finger Cots');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scott', 'Schnappes Peppermint - Walker');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Grover', 'V8 Pet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ruskin', 'Lettuce - Belgian Endive');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Washington', 'Chicken - Wings, Tip Off');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Myrtle', 'Bread - Raisin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waubesa', 'Cheese - St. Andre');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dryden', 'Mints - Striped Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Russell', 'Quail - Whole, Bone - In');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pearson', 'Blueberries');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rowland', 'Wine - Stoneliegh Sauvignon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schiller', 'Tofu - Firm');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hagan', 'Cakes Assorted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buhler', 'Tomato Paste');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dwight', 'Cake - Cake Sheet Macaroon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Debra', 'Hold Up Tool Storage Rack');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kenwood', 'Sun - Dried Tomatoes');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Burrows', 'Miso Paste White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bowman', 'Juice - Cranberry, 341 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Holy Cross', 'Foam Dinner Plate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merry', 'Asparagus - Green, Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Express', 'Wine - Carmenere Casillero Del');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Spohn', 'Cheese - Roquefort Pappillon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ryan', 'Wine - Magnotta - Bel Paese White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Charing Cross', 'Tea - Decaf Lipton');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buell', 'Paste - Black Olive');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nova', 'Garam Marsala');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fisk', 'Allspice - Jamaican');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Springview', 'Beer - Guiness');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Browning', 'Plastic Wrap');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kingsford', 'Soup - Knorr, Chicken Noodle');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bunting', 'Vinegar - White Wine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oak', 'Cheese - Mozzarella');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Columbus', 'Green Tea Refresher');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakewood Gardens', 'Wine - Charddonnay Errazuriz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maryland', 'Wine - Trimbach Pinot Blanc');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northview', 'Coriander - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shopko', 'Parsnip');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Barby', 'Pie Pecan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mallory', 'Oil - Coconut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Heath', 'Tortillas - Flour, 10');
insert into na_voljo (kino_ime, prigrizek_ime) values ('South', 'Pepper - White, Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Michigan', 'Gloves - Goldtouch Disposable');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Glacier Hill', 'Apple - Delicious, Golden');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Marquette', 'Beans - Kidney White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crownhardt', 'Potatoes - Pei 10 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forster', 'Extract Vanilla Pure');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Independence', 'Muffin Chocolate Individual Wrap');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Main', 'Soup Campbells');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anhalt', 'Chef Hat 20cm');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Haas', 'Cherries - Maraschino,jar');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Prairieview', 'Oats Large Flake');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Walton', 'Nantucket Pine Orangebanana');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Redwing', 'Tomato - Plum With Basil');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest', 'Wine - White, Riesling, Semi - Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clarendon', 'Pie Filling - Cherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tennessee', 'Plaintain');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hansons', 'Pepper - Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crescent Oaks', 'Bread - White, Sliced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nevada', 'Breadfruit');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Charing Cross', 'Water - Spring Water 500ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Londonderry', 'Muffin - Mix - Strawberry Rhubarb');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Little Fleur', 'Pickle - Dill');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Victoria', 'Bread - Hamburger Buns');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waxwing', 'Creme De Menthe Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Straubel', 'Juice - Orange');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merchant', 'Lemonade - Natural, 591 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gerald', 'Turkey - Breast, Bone - In');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brown', 'Jicama');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Reindahl', 'Bread - Bagels, Plain');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Amoth', 'Beef - Baby, Liver');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dayton', 'Alize Gold Passion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakewood Gardens', 'Cheese - Boursin, Garlic / Herbs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cascade', 'Wine - White, Ej');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ryan', 'Cinnamon Rolls');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anderson', 'Maple Syrup');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Melrose', 'Sobe - Cranberry Grapefruit');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Wayridge', 'Potatoes - Pei 10 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bashford', 'Shrimp - 16/20, Iqf, Shell On');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Erie', 'Tea - Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hallows', 'Anchovy Paste - 56 G Tube');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Magdeline', 'Rice - Sushi');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hintze', 'Beer - Blue Light');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westerfield', 'Lamb - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Memorial', 'Pepper Squash');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mccormick', 'Lamb - Sausage Casings');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bluestem', 'Tuna - Yellowfin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Chinook', 'Ice Cream - Super Sandwich');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bowman', 'Soup - Campbells, Minestrone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Muir', 'Drambuie');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lerdahl', 'Wine - Manischewitz Concord');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fair Oaks', 'Trout - Rainbow, Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Paget', 'Lamb - Whole, Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fulton', 'Pasta - Agnolotti - Butternut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eastwood', 'Tea - Grapefruit Green Tea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Onsgard', 'Yukon Jack');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mcbride', 'Munchies Honey Sweet Trail Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Claremont', 'Cornish Hen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merchant', 'Wine - Blue Nun Qualitatswein');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Arrowood', 'Creme De Cacao White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northland', 'Milk - Skim');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cordelia', 'Bread - Raisin Walnut Pull');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Longview', 'Calypso - Black Cherry Lemonade');
insert into na_voljo (kino_ime, prigrizek_ime) values ('South', 'Vol Au Vents');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Corry', 'Wine - Red, Metus Rose');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunnyside', 'Appetizer - Veg Assortment');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Farmco', 'Wine - Rosso Del Veronese Igt');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Erie', 'Galliano');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sachs', 'Lid - 3oz Med Rec');
insert into na_voljo (kino_ime, prigrizek_ime) values ('American', 'Cheese - St. Andre');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buell', 'Lettuce - Baby Salad Greens');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Meadow Ridge', 'Sauce - Alfredo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('North', 'Shrimp - 16/20, Peeled Deviened');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Butternut', 'Pastry - Apple Large');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Park Meadow', 'Sugar - Brown');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eagle Crest', 'Wine - Chablis 2003 Champs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Parkside', 'Quail Eggs - Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carey', 'Appetizer - Crab And Brie');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Delladonna', 'Pancetta');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Warrior', 'Lettuce - Belgian Endive');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kropf', 'Corn - On The Cob');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dorton', 'Salmon - Atlantic, No Skin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Thierer', 'Pork Loin Bine - In Frenched');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Colorado', 'Wine - Chateau Bonnet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anthes', 'Tomatoes - Diced, Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Debs', 'Strawberries - California');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mccormick', 'Swiss Chard');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Donald', 'Turkey - Ground. Lean');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Drewry', 'Pepper - Scotch Bonnet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Elmside', 'Wine - Magnotta - Cab Franc');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cascade', 'Salsify, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kinsman', 'Ginger - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hauk', 'Steamers White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nova', 'Nut - Almond, Blanched, Sliced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oriole', 'Bar - Sweet And Salty Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Delaware', 'Tomatoes - Roma');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Talmadge', 'Bread - Corn Muffaleta Onion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Miller', 'Squash - Sunburst');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gale', 'Veal - Leg, Provimi - 50 Lb Max');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schmedeman', 'Pork - Bacon, Sliced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest', 'Beef Tenderloin Aaa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clove', 'Soup - Canadian Pea, Dry Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakewood', 'Madeira');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Riverside', 'Soup - Campbells, Butternut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Marcy', 'Cheese - Oka');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brickson Park', 'Wine - White, Schroder And Schyl');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fuller', 'Kolrabi');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Riverside', 'Cocoa Powder - Natural');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Novick', 'Turnip - Mini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bellgrove', 'Arizona - Plum Green Tea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eastlawn', 'Pastrami');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Talmadge', 'Bagels Poppyseed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Spenser', 'Wine - Red, Concha Y Toro');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Melby', 'Chinese Foods - Pepper Beef');
insert into na_voljo (kino_ime, prigrizek_ime) values ('International', 'Apricots - Dried');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Columbus', 'Sprite, Diet - 355ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Reindahl', 'Juice - Pineapple, 341 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Heath', 'Flour - Whole Wheat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Magdeline', 'Tea - Jasmin Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Homewood', 'Seaweed Green Sheets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sauthoff', 'Soup - Cream Of Broccoli, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kennedy', 'Glass - Wine, Plastic, Clear 5 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lindbergh', 'Scallop - St. Jaques');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kensington', 'Croissant, Raw - Mini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Service', 'Mousse - Banana Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dottie', 'Thyme - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('North', 'Vinegar - Cider');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hanson', 'Maple Syrup');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Coleman', 'Extract - Lemon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Haas', 'Pepsi - 600ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anniversary', 'Sugar - Icing');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shelley', 'Apples - Spartan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Claremont', 'Couscous');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Chinook', 'Ecolab - Ster Bac');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clyde Gallagher', 'Clementine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hollow Ridge', 'Initation Crab Meat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Logan', 'Syrup - Monin - Granny Smith');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lotheville', 'Wine - Riesling Alsace Ac 2001');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Linden', 'Beer - Creemore');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hagan', 'Squash - Guords');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Express', 'Blackberries');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pankratz', 'Seedlings - Buckwheat, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Macpherson', 'Longos - Penne With Pesto');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cascade', 'Alize Sunset');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northfield', 'Lettuce - Boston Bib - Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westerfield', 'Calypso - Strawberry Lemonade');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Prairie Rose', 'Creamers - 10%');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mallard', 'Vermacelli - Sprinkles, Assorted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Darwin', 'Shrimp - Black Tiger 26/30');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Leroy', 'Butter Ripple - Phillips');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Texas', 'Flower - Daisies');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northview', 'Pie Shells 10');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eggendart', 'Flour - Bread');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cherokee', 'Chef Hat 25cm');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Erie', 'Pork - Back, Short Cut, Boneless');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oakridge', 'Apple - Fuji');
insert into na_voljo (kino_ime, prigrizek_ime) values ('North', 'Flour Dark Rye');
insert into na_voljo (kino_ime, prigrizek_ime) values ('High Crossing', 'Tart Shells - Savory, 3');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stang', 'Wine - Prosecco Valdobiaddene');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Talmadge', 'Paper - Brown Paper Mini Cups');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Colorado', 'Beans - Black Bean, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Susan', 'Wine - Red, Colio Cabernet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Briar Crest', 'Cinnamon - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Parkside', 'Bar Special K');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Village', 'Bread Sour Rolls');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bultman', 'Maple Syrup');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dakota', 'Tea - Lemon Green Tea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stone Corner', 'Flavouring Vanilla Artificial');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Beilfuss', 'Wine - Jaboulet Cotes Du Rhone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Coolidge', 'Bread - Pullman, Sliced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westend', 'Bread - Kimel Stick Poly');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Quincy', 'Truffle Cups Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pleasure', 'Vacuum Bags 12x16');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Coolidge', 'Cookie Choc');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northport', 'Syrup - Golden, Lyles');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cordelia', 'Clams - Bay');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jenifer', 'Cognac - Courvaisier');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Meadow Ridge', 'Pastry - Chocolate Chip Muffin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Independence', 'Cheese - Valancey');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sutherland', 'Cheese - Valancey');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pearson', 'Beef Wellington');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dexter', 'Milk - Chocolate 500ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dapin', 'Tea - Camomele');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fulton', 'Petit Baguette');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Parkside', 'Nutmeg - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dwight', 'Yukon Jack');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carpenter', 'Halibut - Fletches');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hoepker', 'Split Peas - Green, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Truax', 'Pasta - Fusili Tri - Coloured');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Harbort', 'Muffin Batt - Carrot Spice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Veith', 'Numi - Assorted Teas');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Donald', 'Alize Red Passion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lake View', 'Sobe - Cranberry Grapefruit');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Upham', 'Truffle Cups - White Paper');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Huxley', 'Brandy Apricot');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clyde Gallagher', 'Island Oasis - Raspberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sheridan', 'Longos - Grilled Salmon With Bbq');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jenifer', 'Cream - 18%');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Veith', 'Bread - White Mini Epi');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Riverside', 'Jolt Cola - Electric Blue');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Derek', 'Tart - Butter Plain Squares');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vernon', 'Chevril');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Declaration', 'Flour - So Mix Cake White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Loftsgordon', 'Beans - Black Bean, Preserved');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mendota', 'Crackers - Soda / Saltins');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Troy', 'Wine - Kwv Chenin Blanc South');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Goodland', 'Sauce - Marinara');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Welch', 'Salt - Table');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mayer', 'Pasta - Orzo, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bellgrove', 'Rice - Aborio');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Springview', 'Foam Cup 6 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bowman', 'Chinese Foods - Pepper Beef');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Texas', 'Pepper - Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Transport', 'Beef - Chuck, Boneless');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunfield', 'Tea - Herbal I Love Lemon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lawn', 'Beer - Fruli');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rowland', 'Grapes - Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maple', 'Beef - Striploin Aa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dakota', 'Five Alive Citrus');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buhler', 'Milk - Homo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ludington', 'Cake - Mini Potato Pancake');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Comanche', 'Tomato Puree');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Warner', 'Arizona - Plum Green Tea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merrick', 'Cookies - Englishbay Chochip');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Riverside', 'Sour Puss - Tangerine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bowman', 'Rum - Light, Captain Morgan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northport', 'Wine - Sogrape Mateus Rose');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oxford', 'Wine - White, Ej Gallo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunnyside', 'Bowl 12 Oz - Showcase 92012');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Canary', 'Extract - Vanilla,artificial');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bunting', 'Stock - Veal, White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Independence', 'Muffin Puck Ww Carrot');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vera', 'Garlic - Peeled');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merrick', 'Wine - Cousino Macul Antiguas');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Almo', 'Bread - Corn Muffaletta');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hollow Ridge', 'Soy Protein');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Transport', 'Rabbit - Saddles');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Springview', 'Dc - Sakura Fu');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Starling', 'Otomegusa Dashi Konbu');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sugar', 'Carrots - Purple, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Goodland', 'Tomatoes - Diced, Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Elmside', 'Bread - Triangle White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mandrake', 'Table Cloth 120 Round White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northfield', 'Bonito Flakes - Toku Katsuo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('American', 'Cookie - Oreo 100x2');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Columbus', 'Eel - Smoked');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sauthoff', 'Chick Peas - Dried');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Harper', 'Kumquat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northfield', 'Chocolate - Feathers');
insert into na_voljo (kino_ime, prigrizek_ime) values ('New Castle', 'Grand Marnier');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Packers', 'Scallops - 20/30');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crownhardt', 'Chips - Miss Vickies');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Luster', 'Honey - Comb');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Coolidge', 'Chicken Giblets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Raven', 'Macaroons - Two Bite Choc');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Blaine', 'Truffle Cups - Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Steensland', 'Kiwano');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Norway Maple', 'Tart Shells - Sweet, 3');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hermina', 'Pork - Suckling Pig');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Annamark', 'Smoked Tongue');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Arkansas', 'Tea - Lemon Green Tea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunnyside', 'Stock - Beef, Brown');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Esch', 'Shrimp - Black Tiger 8 - 12');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sheridan', 'Cups 10oz Trans');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dexter', 'Carbonated Water - Cherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Leroy', 'Juice - Propel Sport');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Burrows', 'Grapefruit - White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forster', 'Pork - Caul Fat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Utah', 'Pepper - Julienne, Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lotheville', 'Egg - Salad Premix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hayes', 'Wine - Trimbach Pinot Blanc');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Steensland', 'Yokaline');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kropf', 'The Pop Shoppe Pinapple');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Meadow Ridge', 'Bread Roll Foccacia');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hooker', 'Bread - Burger');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Truax', 'Tuna - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pearson', 'Tobasco Sauce');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tennyson', 'Beef - Salted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Weeping Birch', 'Cheese - Oka');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Atwood', 'Shrimp - Black Tiger 13/15');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eastlawn', 'Island Oasis - Strawberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sycamore', 'Wine - Cabernet Sauvignon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Drewry', 'Smoked Tongue');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Annamark', 'Cup - 8oz Coffee Perforated');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Melvin', 'Salmon - Atlantic, Fresh, Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bluestem', 'Cake Slab');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Roth', 'Nut - Pumpkin Seeds');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Myrtle', 'Snapple - Mango Maddness');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Continental', 'Sobe - Berry Energy');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Doe Crossing', 'Oil - Olive');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brickson Park', 'Wine - Tribal Sauvignon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Doe Crossing', 'Sauce - Hoisin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Walton', 'Cinnamon Buns Sticky');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Menomonie', 'Veal - Inside, Choice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Summit', 'Tomatillo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Glendale', 'Truffle Cups Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Boyd', 'Ice Cream - Life Savers');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kipling', 'Rootbeer');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mariners Cove', 'Pickles - Gherkins');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fisk', 'Tofu - Firm');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Farmco', 'Marjoram - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scoville', 'Pasta - Rotini, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sage', 'Pate - Peppercorn');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sutherland', 'Cheese - Cheddar With Claret');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Atwood', 'Nut - Almond, Blanched, Sliced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shopko', 'Crackers - Trio');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Superior', 'Curry Powder');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Center', 'Bay Leaf Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lerdahl', 'Snapple Raspberry Tea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Homewood', 'Napkin White - Starched');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Calypso', 'Zucchini - Mini, Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sundown', 'Mushrooms - Black, Dried');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunnyside', 'Flavouring Vanilla Artificial');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Declaration', 'Chocolate - Milk, Callets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stoughton', 'Compound - Raspberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waywood', 'Sprouts - Alfalfa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eggendart', 'Mushroom - Crimini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dottie', 'Gingerale - Diet - Schweppes');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Warner', 'Chocolate Bar - Coffee Crisp');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maryland', 'Calypso - Strawberry Lemonade');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Spaight', 'Beef - Roasted, Cooked');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Prairie Rose', 'Longos - Lasagna Veg');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golden Leaf', 'Cheese - Montery Jack');
insert into na_voljo (kino_ime, prigrizek_ime) values ('East', 'Brandy - Bar');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tennessee', 'Potatoes - Idaho 100 Count');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waxwing', 'Beer - Camerons Auburn');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merchant', 'Veal - Insides, Grains');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Twin Pines', 'Squid U5 - Thailand');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schurz', 'Nestea - Ice Tea, Diet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Blaine', 'Ice Cream Bar - Drumstick');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Helena', 'Salmon - Sockeye Raw');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Milwaukee', 'Cheese - St. Andre');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Thackeray', 'Ice Cream Bar - Rolo Cone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Twin Pines', 'Olives - Green, Pitted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Melrose', 'Fish - Scallops, Cold Smoked');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Grayhawk', 'Eggplant Italian');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pine View', 'Club Soda - Schweppes, 355 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sachtjen', 'Bread Sour Rolls');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jay', 'Sobe - Liz Blizz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('North', 'Wine - Maipo Valle Cabernet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waxwing', 'Sauce - Caesar Dressing');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest Run', 'Bar - Sweet And Salty Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Saint Paul', 'Soup - French Onion, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Springview', 'Grapefruit - Pink');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Express', 'Butter - Salted, Micro');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Milwaukee', 'Chocolate - Chips Compound');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bay', 'Easy Off Oven Cleaner');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anzinger', 'Ice Cream - Vanilla');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Briar Crest', 'Nantucket Cranberry Juice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northview', 'V8 - Tropical Blend');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jenifer', 'Muffin Carrot - Individual');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mariners Cove', 'Longos - Lasagna Veg');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dixon', 'Sprite, Diet - 355ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Linden', 'Chickhen - Chicken Phyllo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schurz', 'Ice Cream Bar - Hagen Daz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bonner', 'Beans - Kidney, Red Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Spaight', 'Trout - Hot Smkd, Dbl Fillet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westridge', 'Table Cloth 54x54 Colour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Transport', 'Fish - Halibut, Cold Smoked');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Holmberg', 'Veal - Sweetbread');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Glendale', 'Quail - Eggs, Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Little Fleur', 'Beer - Fruli');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Granby', 'Pepper Squash');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dryden', 'Bread - Sour Sticks With Onion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Old Shore', 'Mangoes');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Morningstar', 'Soup - Knorr, Classic Can. Chili');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Chinook', 'Scotch - Queen Anne');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brickson Park', 'Basil - Primerba, Paste');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hintze', 'Rum - Spiced, Captain Morgan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bowman', 'Wine - Chianti Classico Riserva');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kropf', 'Coffee - Decafenated');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Victoria', 'Okra');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rieder', 'Bread - Pumpernickel');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Acker', 'Wine - Red, Gallo, Merlot');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Goodland', 'Wine - Shiraz Wolf Blass Premium');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stoughton', 'Juice - Happy Planet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eagan', 'Soup - Base Broth Chix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Briar Crest', 'Coffee - Egg Nog Capuccino');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakewood Gardens', 'Green Scrubbie Pad H.duty');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Southridge', 'Bread - Multigrain, Loaf');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Karstens', 'Soup - Campbells Beef Strogonoff');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tennyson', 'Beans - Kidney, Red Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mifflin', 'Wine - Baron De Rothschild');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fordem', 'Wine - Winzer Krems Gruner');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waywood', 'Silicone Paper 16.5x24');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Roxbury', 'Tea - Earl Grey');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cottonwood', 'Puree - Blackcurrant');
insert into na_voljo (kino_ime, prigrizek_ime) values ('High Crossing', 'Brandy Apricot');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ridge Oak', 'Crab Brie In Phyllo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fallview', 'Coffee - Beans, Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moose', 'Cream Of Tartar');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Heath', 'Ecolab - Mikroklene 4/4 L');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Loftsgordon', 'Wine - Tio Pepe Sherry Fino');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunnyside', 'Pork - Hock And Feet Attached');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Huxley', 'Kirsch - Schloss');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Chinook', 'Wanton Wrap');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf View', 'Wine - Red, Cooking');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sutherland', 'Nantucket Apple Juice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hanover', 'Straw - Regular');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dakota', 'Fond - Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hovde', 'Pears - Anjou');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lindbergh', 'Onions - Dried, Chopped');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Delaware', 'Hot Chocolate - Individual');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northfield', 'Chips Potato Salt Vinegar 43g');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moose', 'Syrup - Pancake');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cottonwood', 'Remy Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Basil', 'Pectin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pine View', 'Wine - White, Ej');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moland', 'Sauce - Demi Glace');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Burrows', 'Flour - Buckwheat, Dark');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pennsylvania', 'Chicken - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('2nd', 'Potatoes - Instant, Mashed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dexter', 'Pineapple - Golden');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Melvin', 'Beef - Short Ribs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fisk', 'Pastry - Apple Muffins - Mini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Arizona', 'Ice Cream Bar - Oreo Cone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Erie', 'Tea - Decaf 1 Cup');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Trailsway', 'Pernod');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waubesa', 'Mousse - Banana Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mockingbird', 'Pepper - Chili Powder');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Elmside', 'Wine - Chablis J Moreau Et Fils');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Continental', 'Island Oasis - Pina Colada');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brickson Park', 'V8 - Berry Blend');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Badeau', 'Juice - Prune');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Onsgard', 'Fib N9 - Prague Powder');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rutledge', 'Plasticspoonblack');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Homewood', 'Watercress');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Larry', 'Cheese - Brie, Triple Creme');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sugar', 'Veal - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hoffman', 'Blueberries');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Park Meadow', 'Potatoes - Fingerling 4 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Montana', 'Sage Ground Wiberg');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Grayhawk', 'Ham - Cooked Italian');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jay', 'Stock - Beef, White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Farmco', 'Chocolate - Compound Coating');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Elka', 'Soup Campbells Mexicali Tortilla');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Prairieview', 'Beer - Guiness');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Meadow Ridge', 'Lettuce - Radicchio');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Farwell', 'Shrimp - 16/20, Iqf, Shell On');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pawling', 'Butter - Salted, Micro');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schiller', 'Durian Fruit');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Basil', 'Burger Veggie');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dovetail', 'Salmon - Whole, 4 - 6 Pounds');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brentwood', 'Pepper - Pablano');
insert into na_voljo (kino_ime, prigrizek_ime) values ('American', 'Wine - Clavet Saint Emilion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Utah', 'Puree - Pear');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lyons', 'Cookies - Fortune');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mcguire', 'Tumeric');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Holmberg', 'Versatainer Nc - 9388');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carioca', 'Coffee - Ristretto Coffee Capsule');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Macpherson', 'Bandage - Finger Cots');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Utah', 'Beer - Paulaner Hefeweisse');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Leroy', 'Chicken - White Meat, No Tender');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westend', 'Lobak');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Russell', 'Potatoes - Pei 10 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crowley', 'Tuna - Loin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('La Follette', 'Bowl 12 Oz - Showcase 92012');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ryan', 'Assorted Desserts');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hazelcrest', 'Bar Bran Honey Nut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Miller', 'Cheese - Comte');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pierstorff', 'Cheese - Gouda Smoked');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Little Fleur', 'Orange Roughy 6/8 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mandrake', 'Pepper - Black, Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jay', 'Foam Cup 6 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kings', 'Sprouts - Peppercress');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Roth', 'Ice Cream Bar - Hagen Daz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Spohn', 'Onions - Cooking');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stephen', 'Celery');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brown', 'Tea - Grapefruit Green Tea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jackson', 'Pepper - Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northwestern', 'Lettuce - Belgian Endive');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Troy', 'Ecolab - Balanced Fusion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Birchwood', 'Bread - Frozen Basket Variety');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Knutson', 'Tomato - Peeled Italian Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Service', 'Mushroom - Trumpet, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Knutson', 'Cheese - Blue');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northview', 'Foam Dinner Plate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Drewry', 'Lamb - Leg, Diced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Basil', 'Cake - Box Window 10x10x2.5');
insert into na_voljo (kino_ime, prigrizek_ime) values ('International', 'Cheese - Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lukken', 'Pork - Shoulder');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scoville', 'Bandage - Flexible Neon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Delladonna', 'Pork - Kidney');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Butterfield', 'Pasta - Cappellini, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Transport', 'Tarts Assorted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carberry', 'Muffin Batt - Choc Chk');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Duke', 'Lamb - Pieces, Diced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('5th', 'Muffin Orange Individual');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stephen', 'Pepper - Red Thai');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gina', 'Cheese - Augre Des Champs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Onsgard', 'Turkey - Oven Roast Breast');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Morrow', 'Salsify, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Loeprich', 'Jack Daniels');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moland', 'Bacardi Raspberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Badeau', 'Celery Root');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Park Meadow', 'Cake - Night And Day Choclate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Laurel', 'Ice - Clear, 300 Lb For Carving');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Loftsgordon', 'Wine - Malbec Trapiche Reserve');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Southridge', 'Ecolab - Orange Frc, Cleaner');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ryan', 'Table Cloth 81x81 White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Washington', 'Filter - Coffee');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Thierer', 'Olives - Green, Pitted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Becker', 'Pork - Liver');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buena Vista', 'Dome Lid Clear P92008h');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stoughton', 'Napkin - Beverage 1 Ply');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fallview', 'Juice - Orange 1.89l');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Debs', 'Cheese - Goat With Herbs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest', 'Nut - Walnut, Chopped');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Claremont', 'Country Roll');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Grasskamp', 'Wine - Guy Sage Touraine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Texas', 'Chambord Royal');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fairview', 'Monkfish Fresh - Skin Off');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Village Green', 'Beer - Maudite');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monica', 'Stock - Veal, Brown');
insert into na_voljo (kino_ime, prigrizek_ime) values ('International', 'Trueblue - Blueberry 12x473ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Village', 'Coffee - Irish Cream');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carberry', 'Cheese - Cottage Cheese');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rockefeller', 'Milk - 1%');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Butterfield', 'Chilli Paste, Sambal Oelek');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Macpherson', 'Apple - Custard');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Morningstar', 'Stock - Fish');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bowman', 'Split Peas - Yellow, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eagle Crest', 'Sage - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Colorado', 'Beer - True North Strong Ale');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest Dale', 'Pasta - Cheese / Spinach Bauletti');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Novick', 'Beer - Corona');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Melvin', 'Sugar - White Packet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf', 'Sesame Seed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pennsylvania', 'Nectarines');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lawn', 'Cheese Cheddar Processed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Randy', 'Bread - Olive');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ronald Regan', 'Catfish - Fillets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Summer Ridge', 'Peas Snow');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monterey', 'Apricots Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crest Line', 'Beef - Outside, Round');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Park Meadow', 'Cactus Pads');
insert into na_voljo (kino_ime, prigrizek_ime) values ('8th', 'Bagel - Plain');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Huxley', 'Trueblue - Blueberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Magdeline', 'Soup Campbells Mexicali Tortilla');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Havey', 'Dc - Sakura Fu');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oak', 'Limes');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carey', 'Ice Cream - Strawberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gina', 'Beef - Cooked, Corned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fallview', 'Pork - Bacon Cooked Slcd');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Charing Cross', 'Dehydrated Kelp Kombo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Petterle', 'Pastry - Chocolate Marble Tea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hazelcrest', 'Pastry - Plain Baked Croissant');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Trailsway', 'Tray - 12in Rnd Blk');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Toban', 'Artichoke - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest Dale', 'Chocolate - Pistoles, White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nancy', 'Kiwano');
insert into na_voljo (kino_ime, prigrizek_ime) values ('School', 'Beets - Candy Cane, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oakridge', 'Mustard - Dijon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Caliangt', 'Beef - Prime Rib Aaa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clyde Gallagher', 'Lamb - Leg, Boneless');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eliot', 'Chicken - Tenderloin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Milwaukee', 'Wine - Cahors Ac 2000, Clos');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Springs', 'Carbonated Water - Blackcherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waywood', 'Chocolate Bar - Coffee Crisp');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scofield', 'Jam - Strawberry, 20 Ml Jar');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Evergreen', 'Gelatine Leaves - Bulk');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anzinger', 'Cheese - Swiss');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sutteridge', 'Apples - Spartan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carioca', 'Muffin Mix - Corn Harvest');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pepper Wood', 'Beef - Cow Feet Split');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Myrtle', 'Appetizer - Assorted Box');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dwight', 'Chips Potato Salt Vinegar 43g');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Twin Pines', 'Nantucket Orange Juice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bunker Hill', 'Milkettes - 2%');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mandrake', 'Veal - Inside, Choice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forster', 'Blueberries - Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Garrison', 'Beer - Upper Canada Light');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mallory', 'Pea - Snow');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Donald', 'Cheese - Comtomme');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Arkansas', 'Sausage - Andouille');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunnyside', 'Chinese Foods - Plain Fried Rice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Trailsway', 'Eggplant - Regular');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest', 'Table Cloth 54x54 Colour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lawn', 'Tea Leaves - Oolong');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monument', 'Chocolate Bar - Coffee Crisp');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merrick', 'Lamb - Bones');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Marquette', 'Chickhen - Chicken Phyllo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Delladonna', 'Bread - Multigrain, Loaf');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Glacier Hill', 'Calypso - Strawberry Lemonade');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Graceland', 'V8 - Tropical Blend');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cascade', 'Wine - Merlot Vina Carmen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moulton', 'Barramundi');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sachtjen', 'Potatoes - Mini White 3 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sugar', 'Duck - Breast');
insert into na_voljo (kino_ime, prigrizek_ime) values ('John Wall', 'Gatorade - Orange');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jay', 'Cheese - Romano, Grated');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Columbus', 'Fond - Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sommers', 'Chicken Breast Halal');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pierstorff', 'Lettuce - Escarole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kennedy', 'Sesame Seed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kipling', 'Quail - Eggs, Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ryan', 'Pork - Bones');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fremont', 'Cake - Cheese Cake 9 Inch');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Superior', 'Bacardi Limon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Surrey', 'Petit Baguette');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Green Ridge', 'Dragon Fruit');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lake View', 'Huck Towels White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Manley', 'Creme De Cacao Mcguines');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hooker', 'Banana');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunbrook', 'Beer - Blue Light');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Iowa', 'Pasta - Lasagna Noodle, Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shelley', 'Calypso - Strawberry Lemonade');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gale', 'Asparagus - White, Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rowland', 'Calypso - Black Cherry Lemonade');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nevada', 'Bagels Poppyseed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('New Castle', 'Pasta - Cheese / Spinach Bauletti');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Heath', 'Cleaner - Lime Away');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Esch', 'Capon - Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf', 'Table Cloth 81x81 White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hallows', 'Tomatoes - Cherry, Yellow');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mallory', 'Muffin - Mix - Mango Sour Cherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Iowa', 'Foil - 4oz Custard Cup');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dwight', 'Container - Clear 16 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Morrow', 'Cookies - Amaretto');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northridge', 'Lettuce - Belgian Endive');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eagan', 'Wine - Red, Pinot Noir, Chateau');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stephen', 'Chocolate Bar - Oh Henry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('6th', 'Broom And Broom Rack White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hooker', 'Curry Powder Madras');
insert into na_voljo (kino_ime, prigrizek_ime) values ('East', 'Beans - Black Bean, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northland', 'Rolled Oats');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Towne', 'Shrimp - Black Tiger 16/20');
insert into na_voljo (kino_ime, prigrizek_ime) values ('John Wall', 'Scrubbie - Scotchbrite Hand Pad');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clemons', 'Parsley Italian - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Morning', 'Juice - Happy Planet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mallory', 'Muskox - French Rack');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Main', 'Muffin Carrot - Individual');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lukken', 'Oxtail - Cut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jenifer', 'Smoked Paprika');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Everett', 'Bar Bran Honey Nut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maple', 'Bar Mix - Lemon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Old Gate', 'Dc Hikiage Hira Huba');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Messerschmidt', 'Container - Foam Dixie 12 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Leroy', 'Bread - 10 Grain Parisian');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cardinal', 'Tomato Puree');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Farragut', 'Amaretto');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bultman', 'Beef - Cow Feet Split');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hovde', 'Turkey Leg With Drum And Thigh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ludington', 'Broom - Push');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Reinke', 'Syrup - Monin, Irish Cream');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Drewry', 'Mace');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lake View', 'Beer - Creemore');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tennyson', 'Bag - Bread, White, Plain');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waxwing', 'Cream - 18%');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Summit', 'Bread - Granary Small Pull');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jay', 'Quail - Jumbo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anzinger', 'Carrots - Mini, Stem On');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maryland', 'Juice - Pineapple, 48 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rusk', 'Duck - Fat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Comanche', 'Salmon - Fillets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Susan', 'Cookie - Oatmeal');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dennis', 'The Pop Shoppe - Cream Soda');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Birchwood', 'Wine - Sogrape Mateus Rose');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Utah', 'Tart Shells - Sweet, 3');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cordelia', 'Tamarind Paste');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Center', 'Crab Meat Claw Pasteurise');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Coleman', 'Eggplant Italian');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Iowa', 'Rum - Spiced, Captain Morgan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Toban', 'Squash - Pattypan, Yellow');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Emmet', 'Tea - English Breakfast');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Welch', 'Garbage Bags - Black');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sommers', 'Tomato - Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westport', 'Tomato Paste');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Swallow', 'Anchovy In Oil');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anderson', 'Cheese - St. Paulin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Springs', 'Bananas');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Marcy', 'Bread - Roll, Italian');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Autumn Leaf', 'Sloe Gin - Mcguinness');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jana', 'Aspic - Clear');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lindbergh', 'Veal - Leg, Provimi - 50 Lb Max');
insert into na_voljo (kino_ime, prigrizek_ime) values ('5th', 'Southern Comfort');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Springs', 'Bread Base - Gold Formel');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tony', 'Potatoes - Mini Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maryland', 'Pastry - Chocolate Chip Muffin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stang', 'Tea - Lemon Scented');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Aberg', 'Lamb - Shoulder');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carberry', 'Tea - Black Currant');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monument', 'Waffle Stix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cottonwood', 'Pie Box - Cello Window 2.5');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Larry', 'Lamb Tenderloin Nz Fr');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merrick', 'Wine - Zonnebloem Pinotage');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lerdahl', 'Orange - Blood');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mifflin', 'Beef - Texas Style Burger');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Londonderry', 'Lemonade - Black Cherry, 591 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Colorado', 'Juice - Lemon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Harper', 'Wine - Sherry Dry Sack, William');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lillian', 'Bread - Pullman, Sliced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Village Green', 'Beer - Creemore');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Redwing', 'Lid - 3oz Med Rec');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Colorado', 'Bar Nature Valley');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waxwing', 'Broom - Corn');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ryan', 'Wine - White, Pelee Island');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Charing Cross', 'Chips Potato Reg 43g');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kinsman', 'Beef - Kobe Striploin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hollow Ridge', 'Soup - Campbells Bean Medley');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Harbort', 'Chocolate Bar - Coffee Crisp');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hooker', 'Beans - Long, Chinese');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Manufacturers', 'Rabbit - Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest', 'Barramundi');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anderson', 'Longos - Lasagna Veg');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scott', 'Samosa - Veg');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakeland', 'Muffin Mix - Morning Glory');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mayfield', 'Icecream - Dibs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sundown', 'Cookie Trail Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mccormick', 'Potatoes - Yukon Gold 5 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mccormick', 'Chips Potato Swt Chilli Sour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('American', 'Glycerine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Helena', 'Lettuce - Baby Salad Greens');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nova', 'Danishes - Mini Raspberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Charing Cross', 'Wine - Maipo Valle Cabernet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carioca', 'Sea Urchin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Old Shore', 'Cookies - Amaretto');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gina', 'Spice - Paprika');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Harper', 'Grenadillo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hollow Ridge', 'Hipnotiq Liquor');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scoville', 'Eel Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Blue Bill Park', 'Pecan Raisin - Tarts');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pearson', 'Monkfish - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kedzie', 'Beef - Striploin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golden Leaf', 'Veal - Inside, Choice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('2nd', 'Towel Multifold');
