insert into na_voljo (kino_ime, prigrizek_ime) values ('Tony', 'Jameson - Irish Whiskey');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sutteridge', 'Muffins - Assorted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bartillon', 'Nantucket - Orange Mango Cktl');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Milwaukee', 'Juice - Ocean Spray Cranberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Judy', 'Beans - Kidney White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mendota', 'Pasta - Lasagna, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sachtjen', 'Cheese - Augre Des Champs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Karstens', 'Container - Foam Dixie 12 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Randy', 'Munchies Honey Sweet Trail Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jana', 'Cloves - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Alpine', 'Salmon - Atlantic, Skin On');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bunker Hill', 'Sausage - Andouille');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Florence', 'Salami - Genova');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Daystar', 'Beer - Mcauslan Apricot');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Briar Crest', 'Tequila Rose Cream Liquor');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cardinal', 'Curry Paste - Green Masala');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Main', 'Pears - Bosc');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Division', 'Asparagus - Mexican');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hoard', 'Beef - Prime Rib Aaa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Quincy', 'Wine - Pinot Noir Stoneleigh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Washington', 'Flour - So Mix Cake White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mcbride', 'Roe - Lump Fish, Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moulton', 'Cheese - Swiss Sliced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Muir', 'Cakes Assorted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Welch', 'Coffee Swiss Choc Almond');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Truax', 'Muffin Hinge Container 6');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mesta', 'Bread - Sour Sticks With Onion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sycamore', 'Cheese - Pont Couvert');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hanover', 'Appetizer - Asian Shrimp Roll');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sycamore', 'Skirt - 24 Foot');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ludington', 'Bar Energy Chocchip');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moose', 'Stock - Beef, Brown');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Caliangt', 'Cabbage - Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sullivan', 'Sauerkraut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bartelt', 'Lettuce Romaine Chopped');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Spenser', 'Duck - Fat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mandrake', 'Vaccum Bag - 14x20');
insert into na_voljo (kino_ime, prigrizek_ime) values ('American', 'Goat - Leg');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sutteridge', 'Onion - Dried');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Linden', 'Syrup - Monin, Swiss Choclate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lillian', 'Lobak');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Reindahl', 'Peas - Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kingsford', 'Foam Dinner Plate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Montana', 'Shrimp - 16/20, Peeled Deviened');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest', 'Fondant - Icing');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Darwin', 'Wiberg Super Cure');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Wayridge', 'Mortadella');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vera', 'Monkfish - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Esch', 'Cape Capensis - Fillet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Raven', 'Pie Shell - 9');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dahle', 'Butter Balls Salted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Transport', 'Wine - Pinot Noir Latour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('David', 'Honey - Lavender');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Armistice', 'Contreau');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buena Vista', 'Salsify, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Iowa', 'Beef - Tongue, Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Erie', 'Flower - Commercial Spider');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ludington', 'Scallops - U - 10');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northland', 'Rum - Light, Captain Morgan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Parkside', 'Bread Crumbs - Panko');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stang', 'Pepper - White, Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bayside', 'Chocolate - Unsweetened');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cordelia', 'Stainless Steel Cleaner Vision');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Chive', 'Eggroll');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fairfield', 'Appetizer - Escargot Puff');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gerald', 'Beer - Labatt Blue');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schiller', 'Energy Drink - Redbull 355ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lerdahl', 'Capers - Pickled');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Toban', 'Syrup - Golden, Lyles');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stone Corner', 'Rabbit - Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Spaight', 'Doilies - 7, Paper');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Chinook', 'Pasta - Fusili Tri - Coloured');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Duke', 'Butter Ripple - Phillips');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Quincy', 'Bar - Sweet And Salty Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Coleman', 'Appetizer - Assorted Box');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hoard', 'Seedlings - Buckwheat, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Canary', 'Bar Special K');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cherokee', 'Bread - Crusty Italian Poly');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Straubel', 'Bacardi Raspberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Meadow Valley', 'Wine - Vovray Sec Domaine Huet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Norway Maple', 'Icecream - Dstk Super Cone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Division', 'Galliano');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nevada', 'Instant Coffee');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Aberg', 'Red Cod Fillets - 225g');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eastlawn', 'Flour - Whole Wheat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bartillon', 'Nantucket - Pomegranate Pear');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kedzie', 'Wine - White, French Cross');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mandrake', 'Table Cloth 62x120 White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schiller', 'Beef Wellington');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Morningstar', 'Cheese - Perron Cheddar');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Union', 'Yokaline');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northfield', 'Pancetta');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Packers', 'Turnip - Mini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Karstens', 'Shrimp - Baby, Cold Water');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fairfield', 'Soup - Campbells - Tomato');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jenna', 'Wine - Red, Black Opal Shiraz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ridgeview', 'Muffin - Mix - Mango Sour Cherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Colorado', 'Ham - Virginia');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Starling', 'Cheese - Romano, Grated');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mccormick', 'Bagelers - Cinn / Brown');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moose', 'Wine - Muscadet Sur Lie');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bunker Hill', 'Mint - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Grasskamp', 'Bread - Olive');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fisk', 'Momiji Oroshi Chili Sauce');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eastwood', 'Wine - Pinot Noir Mondavi Coastal');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dunning', 'Lettuce - Sea / Sea Asparagus');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sage', 'Absolut Citron');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Washington', 'Ecolab - Lime - A - Way 4/4 L');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stang', 'Chivas Regal - 12 Year Old');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ramsey', 'Five Alive Citrus');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hudson', 'Lemonade - Natural, 591 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bowman', 'Wine - Beringer Founders Estate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Esch', 'Ecolab - Medallion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Helena', 'Salmon - Sockeye Raw');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stoughton', 'Appetizer - Assorted Box');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lukken', 'Flour - Whole Wheat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Judy', 'Tomato - Plum With Basil');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buhler', 'Potatoes - Mini Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Melody', 'Pepper - Red Chili');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Reindahl', 'Beans - Butter Lrg Lima');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ronald Regan', 'Tea - Camomele');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mifflin', 'Cocoa Powder - Natural');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fairview', 'Beer - Blue');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Spenser', 'Beef - Ox Tongue, Pickled');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lukken', 'Rosemary - Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('North', 'Ecolab - Hobart Upr Prewash Arm');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Welch', 'Turnip - White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kropf', 'Juice - Apple, 1.36l');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Steensland', 'Bar Special K');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Morning', 'Ice Cream Bar - Oreo Cone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('American Ash', 'Liners - Baking Cups');
insert into na_voljo (kino_ime, prigrizek_ime) values ('East', 'Tart Shells - Sweet, 4');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Service', 'Barley - Pearl');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schurz', 'Bread - Bistro Sour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Katie', 'Basil - Pesto Sauce');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scofield', 'Coconut - Creamed, Pure');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oneill', 'Nantucket Cranberry Juice');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Johnson', 'Sage - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dawn', 'Syrup - Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Raven', 'Ice Cream Bar - Drumstick');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Thackeray', 'Pears - Fiorelle');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Graedel', 'Cookies - Fortune');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Manitowish', 'Basil - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Manitowish', 'Pasta - Detalini, White, Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Petterle', 'Munchies Honey Sweet Trail Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('4th', 'Bread Base - Toscano');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vernon', 'Oil - Olive Bertolli');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Claremont', 'Tuna - Loin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Beilfuss', 'Cheese - Gouda');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nova', 'Lobak');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tony', 'Bread - Corn Muffaleta Onion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Atwood', 'Chocolate Eclairs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Blaine', 'Beef - Prime Rib Aaa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cottonwood', 'Vodka - Lemon, Absolut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rigney', 'Yeast Dry - Fermipan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Porter', 'Snails - Large Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Blaine', 'Table Cloth 62x120 Colour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Farwell', 'Flour - Whole Wheat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lukken', 'Chivas Regal - 12 Year Old');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cardinal', 'Puree - Kiwi');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fallview', 'Fuji Apples');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Wayridge', 'Bread - Italian Sesame Poly');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mccormick', 'Chinese Foods - Thick Noodles');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Graceland', 'Cheese - Camembert');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pennsylvania', 'Mints - Striped Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mccormick', 'Cinnamon Buns Sticky');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Donald', 'Tart Shells - Barquettes, Savory');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Coolidge', 'Persimmons');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bunker Hill', 'Lettuce - Belgian Endive');
insert into na_voljo (kino_ime, prigrizek_ime) values ('John Wall', 'Salmon - Atlantic, No Skin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kipling', 'Appetizer - Mini Egg Roll, Shrimp');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rutledge', 'Cheese - Cheddar, Medium');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Granby', 'Lettuce - Spring Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Becker', 'Crush - Cream Soda');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jay', 'Pop - Club Soda Can');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Algoma', 'Hot Chocolate - Individual');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Norway Maple', 'Brocolinni - Gaylan, Chinese');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Duke', 'Rice - Long Grain');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hintze', 'Water - Tonic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dunning', 'Longos - Assorted Sandwich');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lighthouse Bay', 'Dc - Sakura Fu');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westport', 'Cinnamon - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Victoria', 'Longos - Assorted Sandwich');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gateway', 'Soup Campbells - Tomato Bisque');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Center', 'Puree - Mango');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hansons', 'Rolled Oats');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Welch', 'Chicken - White Meat With Tender');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Holmberg', 'V8 - Tropical Blend');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Meadow Valley', 'Soup - Beef, Base Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monica', 'Soup - Boston Clam Chowder');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hayes', 'Turkey Tenderloin Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Texas', 'Flower - Daisies');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ronald Regan', 'Wine - Sogrape Mateus Rose');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Weeping Birch', 'Marjoram - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Memorial', 'Bacardi Breezer - Tropical');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shasta', 'Lid - 16 Oz And 32 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pond', 'Muskox - French Rack');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Del Mar', 'Squid - Breaded');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Beilfuss', 'Oregano - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kedzie', 'Tomatoes - Cherry, Yellow');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Prairieview', 'Wine - Jackson Triggs Okonagan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Novick', 'Ice Cream - Vanilla');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hagan', 'Cinnamon - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Truax', 'Pastry - Carrot Muffin - Mini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stoughton', 'Muffin Mix - Corn Harvest');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bay', 'Flour Pastry Super Fine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Summit', 'Lemonade - Natural, 591 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hovde', 'Longan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anthes', 'Fennel - Seeds');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Elka', 'Rice Pilaf, Dry,package');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rusk', 'Compound - Raspberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Talmadge', 'Vinegar - Red Wine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stuart', 'Extract - Vanilla,artificial');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rowland', 'Cheese - Brie');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dayton', 'Tofu - Soft');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lake View', 'Pie Pecan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Annamark', 'Easy Off Oven Cleaner');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oak', 'Wine - White, Gewurtzraminer');
insert into na_voljo (kino_ime, prigrizek_ime) values ('High Crossing', 'Ice Cream - Vanilla');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Loomis', 'Olives - Stuffed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Becker', 'Five Alive Citrus');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hintze', 'Chocolate Bar - Smarties');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northland', 'Syrup - Monin, Amaretta');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Arizona', 'Butter - Salted, Micro');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Laurel', 'Towels - Paper / Kraft');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mockingbird', 'Soup - French Onion, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Transport', 'Coffee - Dark Roast');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Walton', 'Orange - Canned, Mandarin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schmedeman', 'Cheese - Havarti, Roasted Garlic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Glendale', 'Scallops - U - 10');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Union', 'Scallops - Live In Shell');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sutherland', 'Lamb Rack Frenched Australian');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hazelcrest', 'Wine - Merlot Vina Carmen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ryan', 'Table Cloth - 53x69 Colour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mockingbird', 'Juice - Ocean Spray Cranberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Summer Ridge', 'Jagermeister');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bellgrove', 'Energy Drink - Franks Pineapple');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Continental', 'Beans - Black Bean, Preserved');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anthes', 'Ice Cream - Strawberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Becker', 'Soup - Clam Chowder, Dry Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('8th', 'Beef - Tongue, Cooked');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Elmside', 'Wasabi Paste');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Towne', 'Sauce - Marinara');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Darwin', 'Leeks - Baby, White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('American Ash', 'Wine - German Riesling');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mandrake', 'Tea - Decaf 1 Cup');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cordelia', 'Compound - Pear');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brown', 'Sorrel - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Summer Ridge', 'Pastry - French Mini Assorted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Elgar', 'Squash - Guords');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lerdahl', 'Salmon Steak - Cohoe 8 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Riverside', 'Sour Puss Sour Apple');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dorton', 'Pork - Smoked Kassler');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hoard', 'Cake - Dulce De Leche');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Randy', 'Chips Potato Reg 43g');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oneill', 'Grapefruit - Pink');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schlimgen', 'Seedlings - Clamshell');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Summit', 'Egg - Salad Premix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buell', 'Beans - Long, Chinese');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Caliangt', 'Wine - German Riesling');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Straubel', 'Oil - Grapeseed Oil');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crest Line', 'Carbonated Water - Blackcherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northview', 'Beef Tenderloin Aaa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nelson', 'Island Oasis - Banana Daiquiri');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crownhardt', 'Rosemary - Primerba, Paste');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Red Cloud', 'Turkey - Oven Roast Breast');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dixon', 'Almonds Ground Blanched');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Steensland', 'Muffin Batt - Blueberry Passion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Blackbird', 'Sauce Tomato Pouch');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Autumn Leaf', 'Mousse - Mango');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf View', 'Steam Pan - Half Size Deep');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Derek', 'Soup - Beef, Base Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Chive', 'Goat - Leg');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fremont', 'Flour - Whole Wheat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Village', 'Longos - Chicken Wings');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rigney', 'Dill Weed - Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Comanche', 'Tart - Lemon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Londonderry', 'Garam Marsala');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Memorial', 'Plate Pie Foil');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Division', 'Sunflower Seed Raw');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bluejay', 'Bread - Petit Baguette');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ridge Oak', 'Crush - Grape, 355 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf View', 'Eggplant - Asian');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dunning', 'Potatoes - Yukon Gold 5 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sloan', 'Shrimp - Tiger 21/25');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest', 'Bread - Corn Muffaletta');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Service', 'Eel Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Michigan', 'Cheese - Boursin, Garlic / Herbs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Express', 'Chivas Regal - 12 Year Old');
insert into na_voljo (kino_ime, prigrizek_ime) values ('West', 'Orange Roughy 6/8 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Helena', 'Napkin - Dinner, White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stone Corner', 'Wine - Pinot Noir Latour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maywood', 'Shrimp, Dried, Small / Lb');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Darwin', 'Wine - Pinot Noir Pond Haddock');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf', 'Cheese - Mozzarella, Buffalo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Main', 'Cod - Salted, Boneless');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clyde Gallagher', 'Horseradish - Prepared');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anthes', 'Wine - Charddonnay Errazuriz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scoville', 'Oil - Shortening - All - Purpose');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scofield', 'Alize Gold Passion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Grover', 'Straw - Regular');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunfield', 'Pepsi - Diet, 355 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nobel', 'Tomatoes - Cherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Burning Wood', 'Cake Circle, Paprus');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dunning', 'Butter Sweet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('La Follette', 'Chicken - Whole Roasting');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Park Meadow', 'Eggwhite Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Meadow Vale', 'Yoplait - Strawbrasp Peac');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dunning', 'Icecream - Dstk Super Cone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('North', 'Cake Circle, Paprus');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Basil', 'Bread - Italian Sesame Poly');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Morningstar', 'Wine - Balbach Riverside');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cody', 'Truffle Cups - White Paper');
insert into na_voljo (kino_ime, prigrizek_ime) values ('La Follette', 'Appetizer - Escargot Puff');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunnyside', 'Wine - Conde De Valdemar');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Southridge', 'Chicken - Wieners');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Orin', 'Chutney Sauce - Mango');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Steensland', 'Wine - Red, Colio Cabernet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Little Fleur', 'Stock - Fish');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kim', 'Toamtoes 6x7 Select');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mayfield', 'Cookie Trail Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Veith', 'Beef - Top Sirloin - Aaa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waubesa', 'Whmis Spray Bottle Graduated');
insert into na_voljo (kino_ime, prigrizek_ime) values ('6th', 'Nut - Pine Nuts, Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mccormick', 'Kolrabi');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buhler', 'Veal - Inside');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merrick', 'Wine - Riesling Dr. Pauly');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Killdeer', 'Sausage - Chorizo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Myrtle', 'Cranberries - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carpenter', 'Asparagus - Mexican');
insert into na_voljo (kino_ime, prigrizek_ime) values ('International', 'Beans - Wax');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fallview', 'Water - San Pellegrino');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Namekagon', 'Water - Spring Water, 355 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Troy', 'Bread Crumbs - Japanese Style');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Marcy', 'Cookies Almond Hazelnut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Johnson', 'Oil - Olive Bertolli');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Londonderry', 'Cheese - Provolone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ridgeview', 'Cheese - Goat With Herbs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crescent Oaks', 'Soup - French Onion, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mayfield', 'Plasticforkblack');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vahlen', 'Sauce - Marinara');
insert into na_voljo (kino_ime, prigrizek_ime) values ('John Wall', 'Longos - Lasagna Veg');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bonner', 'Rum - Mount Gay Eclipes');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Michigan', 'Crush - Orange, 355ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Michigan', 'Pepper - Red Bell');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Troy', 'Beans - Black Bean, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Reinke', 'Gelatine Leaves - Bulk');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Continental', 'Oil - Olive Bertolli');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jenifer', 'Glaze - Clear');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scott', 'Spice - Paprika');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Duke', 'Wine - Touraine Azay - Le - Rideau');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clarendon', 'Steampan - Half Size Shallow');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dunning', 'Oats Large Flake');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brentwood', 'Bacon Strip Precooked');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stuart', 'Cauliflower');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rusk', 'Appetizer - Crab And Brie');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northfield', 'Piping Jelly - All Colours');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Swallow', 'Wiberg Super Cure');
insert into na_voljo (kino_ime, prigrizek_ime) values ('New Castle', 'Wine - Beringer Founders Estate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Coleman', 'Pork - Ham Hocks - Smoked');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rowland', 'Wine - Barossa Valley Estate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eastwood', 'Dome Lid Clear P92008h');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf Course', 'Wine - Red, Black Opal Shiraz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Loftsgordon', 'Muffin Chocolate Individual Wrap');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bluejay', 'Apple - Royal Gala');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sommers', 'Chicken - Leg, Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ridgeway', 'Sun - Dried Tomatoes');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Starling', 'Energy Drink');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shelley', 'Juice - Orange, 341 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merry', 'Foil Cont Round');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Darwin', 'Wine - Periguita Fonseca');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brentwood', 'Island Oasis - Raspberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fremont', 'Sardines');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakewood Gardens', 'Sage Ground Wiberg');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Starling', 'Irish Cream - Baileys');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eggendart', 'Sauce - Caesar Dressing');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tennessee', 'Cherries - Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Randy', 'Fireball Whisky');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shelley', 'Longos - Greek Salad');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Marquette', 'Amaretto');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Green', 'Straws - Cocktale');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fremont', 'Mushroom Morel Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gerald', 'Monkfish Fresh - Skin Off');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Loftsgordon', 'Nut - Almond, Blanched, Sliced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Macpherson', 'Soup - Campbells Chicken');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ridge Oak', 'Asparagus - Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Amoth', 'Beer - Blue');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Di Loreto', 'The Pop Shoppe - Root Beer');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunbrook', 'Arctic Char - Fillets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waubesa', 'Juice - Apple Cider');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ridge Oak', 'Icecream - Dstk Strw Chseck');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Warbler', 'Clementine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf Course', 'Spice - Peppercorn Melange');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hoepker', 'Banana Turning');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Atwood', 'Cheese Cloth');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mosinee', 'Butter Ripple - Phillips');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kingsford', 'Flower - Dish Garden');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kings', 'Cheese - Boursin, Garlic / Herbs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moland', 'Pork Loin Cutlets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Larry', 'Venison - Striploin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('John Wall', 'Bread - Malt');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ryan', 'Fish - Atlantic Salmon, Cold');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lerdahl', 'Bread - Crumbs, Bulk');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf', 'Muffin - Mix - Strawberry Rhubarb');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Orin', 'Puree - Kiwi');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sundown', 'Tomatoes - Grape');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fairfield', 'Swiss Chard');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Iowa', 'Red Cod Fillets - 225g');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Garrison', 'Banana Turning');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Melvin', 'Mushroom - Enoki, Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stone Corner', 'Wine - Pinot Noir Pond Haddock');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Melrose', 'Olives - Nicoise');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hintze', 'Sambuca - Opal Nera');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mccormick', 'Chinese Foods - Chicken');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Canary', 'Pork - Liver');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mockingbird', 'Wine - Valpolicella Masi');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fulton', 'Bag - Clear 7 Lb');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schmedeman', 'Yoplait - Strawbrasp Peac');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Canary', 'Bar Mix - Pina Colada, 355 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sheridan', 'Tomatoes');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kenwood', 'Soup - Knorr, Ministrone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westend', 'Cabbage - Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Namekagon', 'Versatainer Nc - 8288');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gina', 'Bread - French Stick');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northridge', 'Sauce - Hoisin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rowland', 'Sweet Pea Sprouts');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Coolidge', 'Bols Melon Liqueur');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Blackbird', 'Raspberries - Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anhalt', 'Soup - Beef Conomme, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Havey', 'Sobe - Tropical Energy');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest Run', 'Pomello');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waywood', 'Pepper - Red Thai');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monterey', 'Gherkin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oakridge', 'White Fish - Filets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mesta', 'Bread - White Epi Baguette');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Glacier Hill', 'Sage - Rubbed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gale', 'Flour - All Purpose');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Center', 'Wine - Segura Viudas Aria Brut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clarendon', 'Beef - Bresaola');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vernon', 'Soup - Campbells Tomato Ravioli');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bonner', 'Cake - Box Window 10x10x2.5');
insert into na_voljo (kino_ime, prigrizek_ime) values ('2nd', 'Muffin - Mix - Creme Brule 15l');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maple Wood', 'Shichimi Togarashi Peppeers');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oxford', 'Doilies - 7, Paper');
insert into na_voljo (kino_ime, prigrizek_ime) values ('2nd', 'Soup - Base Broth Beef');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anthes', 'Urban Zen Drinks');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jana', 'Pur Source');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cody', 'Bread - Pita');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nova', 'Chickensplit Half');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Derek', 'Cake - Mini Cheesecake');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waubesa', 'Lamb Leg - Bone - In Nz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Towne', 'Lettuce - Romaine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Granby', 'Wine - Redchard Merritt');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Corry', 'Pernod');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sycamore', 'Broom - Push');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sutherland', 'Pepperoni Slices');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Spaight', 'Oranges');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Center', 'Beef - Shank');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Towne', 'Pork - Inside');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Transport', 'Lettuce - Escarole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('International', 'Doilies - 10, Paper');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest Run', 'Chicken Breast Halal');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunbrook', 'Straw - Regular');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Badeau', 'Bread - Italian Roll With Herbs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ramsey', 'Wine - Pinot Noir Mondavi Coastal');
insert into na_voljo (kino_ime, prigrizek_ime) values ('John Wall', 'Container - Foam Dixie 12 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Towne', 'Wine - Red, Antinori Santa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maryland', 'Chicken Giblets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Beilfuss', 'Sobe - Tropical Energy');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fordem', 'Yeast Dry - Fermipan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mariners Cove', 'Carbonated Water - Strawberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Huxley', 'Kohlrabi');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dawn', 'Soup - Boston Clam Chowder');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf Course', 'Lobak');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Towne', 'Mangoes');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Milwaukee', 'Vinegar - Champagne');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jenna', 'Sage Derby');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Florence', 'Wine - Chablis 2003 Champs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Redwing', 'Sour Puss Sour Apple');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bashford', 'Mousse - Mango');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Acker', 'Sprouts - Onion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest Dale', 'Wine - White, Gewurtzraminer');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Glacier Hill', 'Tuna - Salad Premix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Knutson', 'Foam Espresso Cup Plain White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eastwood', 'Cheese - Cottage Cheese');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clove', 'Basil - Dry, Rubbed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Green Ridge', 'Artichoke - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schiller', 'Flour - Rye');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jenna', 'Onions - Vidalia');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mcguire', 'Bandage - Flexible Neon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mifflin', 'Chicken - Soup Base');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Havey', 'Extract - Vanilla,artificial');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scoville', 'Eggplant - Regular');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf View', 'Pants Custom Dry Clean');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Algoma', 'Straw - Regular');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moose', 'Rabbit - Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Riverside', 'Sprouts Dikon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Almo', 'Crab - Soft Shell');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mayfield', 'Bread - Dark Rye, Loaf');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hudson', 'Wine - Chateau Aqueria Tavel');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pearson', 'Nectarines');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sycamore', 'Arizona - Plum Green Tea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Caliangt', 'Sauce - Rosee');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maple Wood', 'Bread - Pumpernickle, Rounds');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dakota', 'Lighter - Bbq');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Surrey', 'Pork - Kidney');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Alpine', 'Momiji Oroshi Chili Sauce');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gulseth', 'Yogurt - Banana, 175 Gr');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lighthouse Bay', 'Ranchero - Primerba, Paste');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cherokee', 'Roe - Flying Fish');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sachs', 'Tart - Butter Plain Squares');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eggendart', 'Rice Pilaf, Dry,package');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Main', 'Soup Campbells Split Pea And Ham');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anderson', 'Beef Ground Medium');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monument', 'Beef - Short Ribs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rusk', 'Cheese - Cottage Cheese');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gale', 'Wine - Two Oceans Cabernet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Briar Crest', 'Laundry - Bag Cloth');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Basil', 'Stock - Veal, Brown');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mockingbird', 'Oil - Avocado');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Warbler', 'Extract - Rum');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Truax', 'Jam - Marmalade, Orange');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Thompson', 'Latex Rubber Gloves Size 9');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mosinee', 'Nestea - Iced Tea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Alpine', 'Veal - Leg, Provimi - 50 Lb Max');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dawn', 'Fudge - Cream Fudge');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Starling', 'Wooden Mop Handle');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carioca', 'Sugar - Palm');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Del Mar', 'Bread - White, Unsliced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kennedy', 'Cup - Paper 10oz 92959');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dixon', 'Cookies - Assorted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Annamark', 'Radish - Black, Winter, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mayer', 'Gatorade - Lemon Lime');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Barby', 'Potatoes - Idaho 80 Count');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Gulseth', 'Beets - Candy Cane, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Johnson', 'Carbonated Water - Raspberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Darwin', 'Beans - Kidney White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Independence', 'Wine - Port Late Bottled Vintage');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vermont', 'Chicken - Breast, 5 - 7 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Donald', 'Bread Country Roll');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brown', 'Creme De Cacao Mcguines');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Huxley', 'Pop - Club Soda Can');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Goodland', 'Papadam');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Porter', 'Container Clear 8 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anthes', 'Sprite, Diet - 355ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hoepker', 'Pate - Liver');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mariners Cove', 'Pickerel - Fillets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carpenter', 'Yogurt - Banana, 175 Gr');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Little Fleur', 'Mangostein');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dahle', 'Bread - Triangle White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Toban', 'Cheese - Parmesan Cubes');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Burning Wood', 'Mikes Hard Lemonade');
insert into na_voljo (kino_ime, prigrizek_ime) values ('North', 'Grapefruit - White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anderson', 'Lobster - Base');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dottie', 'Coffee Cup 8oz 5338cd');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Norway Maple', 'Tea - Darjeeling, Azzura');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oriole', 'Sugar - White Packet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunbrook', 'Sage - Rubbed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakewood Gardens', 'Beer - Upper Canada Light');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vermont', 'Garlic - Peeled');
insert into na_voljo (kino_ime, prigrizek_ime) values ('East', 'Tendrils - Baby Pea, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Florence', 'Wine - Magnotta, Merlot Sr Vqa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oakridge', 'Sugar - Cubes');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fallview', 'Magnotta - Bel Paese White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('3rd', 'Snapple - Iced Tea Peach');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Arapahoe', 'Kellogs Special K Cereal');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Doe Crossing', 'Lychee - Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carpenter', 'Wood Chips - Regular');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kropf', 'Beef - Striploin Aa');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shopko', 'Pork Salted Bellies');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Drewry', 'Pheasants - Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Park Meadow', 'Bread - Roll, Whole Wheat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sachs', 'Cookies - Fortune');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vera', 'Vermacelli - Sprinkles, Assorted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pepper Wood', 'Gooseberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dakota', 'Table Cloth 81x81 Colour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bonner', 'Silicone Parch. 16.3x24.3');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stoughton', 'Pasta - Lasagne, Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Manufacturers', 'Puree - Blackcurrant');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mockingbird', 'Longos - Chicken Cordon Bleu');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lindbergh', 'Table Cloth 62x114 White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Glendale', 'Gatorade - Orange');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Algoma', 'Scallops - 20/30');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Burrows', 'Pate - Liver');
insert into na_voljo (kino_ime, prigrizek_ime) values ('West', 'Wine - Jaboulet Cotes Du Rhone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Portage', 'Duck - Fat');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Coleman', 'Oil - Canola');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Arrowood', 'Lamb Rack Frenched Australian');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fieldstone', 'Veal - Shank, Pieces');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dryden', 'Island Oasis - Banana Daiquiri');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waywood', 'Beans - Black Bean, Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Florence', 'Crush - Cream Soda');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Roth', 'Fish - Artic Char, Cold Smoked');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bayside', 'Apple - Granny Smith');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Thackeray', 'Wine - Red, Cooking');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kennedy', 'Godiva White Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Independence', 'Tea - Earl Grey');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kensington', 'Roe - White Fish');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eastlawn', 'Cheese - Gorgonzola');
insert into na_voljo (kino_ime, prigrizek_ime) values ('West', 'Chocolate - Semi Sweet, Calets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westridge', 'Cod - Salted, Boneless');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scoville', 'Pail - 15l White, With Handle');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clove', 'Beer - Creemore');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Becker', 'Oil - Margarine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ryan', 'Wine - Stoneliegh Sauvignon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mosinee', 'Halibut - Steaks');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Thompson', 'Croissant, Raw - Mini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monterey', 'Wine - Red, Metus Rose');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sachtjen', 'Tarragon - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cascade', 'Wine - Cave Springs Dry Riesling');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crest Line', 'Croissants Thaw And Serve');
insert into na_voljo (kino_ime, prigrizek_ime) values ('2nd', 'Carbonated Water - Blackcherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Evergreen', 'Yogurt - Plain');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eagle Crest', 'Garbage Bags - Clear');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dawn', 'Ketchup - Tomato');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oakridge', 'Potatoes - Purple, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('High Crossing', 'Pur Value');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Muir', 'Transfer Sheets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cascade', 'Veal - Striploin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Leroy', 'Yogurt - Cherry, 175 Gr');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schiller', 'Tomatoes - Vine Ripe, Yellow');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dahle', 'Potatoes - Idaho 80 Count');
insert into na_voljo (kino_ime, prigrizek_ime) values ('1st', 'Pork - Smoked Kassler');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Huxley', 'Tamarillo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('La Follette', 'Raspberries - Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Declaration', 'Devonshire Cream');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dakota', 'Vodka - Hot, Lnferno');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Myrtle', 'Pastry - Lemon Danish - Mini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Farwell', 'Rum - White, Gg White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Doe Crossing', 'Cookie Choc');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cascade', 'Pasta - Cheese / Spinach Bauletti');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buena Vista', 'Nut - Peanut, Roasted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest Dale', 'Butter Sweet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sherman', 'Ginger - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hauk', 'Flour - So Mix Cake White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Esch', 'Compound - Rum');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kenwood', 'Juice - Orange, 341 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Corry', 'Shrimp - Black Tiger 16/20');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Loeprich', 'Dasheen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Barnett', 'Longos - Chicken Caeser Salad');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Susan', 'Appetizer - Smoked Salmon / Dill');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monument', 'French Pastry - Mini Chocolate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Walton', 'Tomatoes Tear Drop');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clarendon', 'Capers - Pickled');
insert into na_voljo (kino_ime, prigrizek_ime) values ('American', 'Longos - Chicken Curried');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Village Green', 'Quail - Jumbo Boneless');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Acker', 'Arctic Char - Fillets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hintze', 'Butter - Pod');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Derek', 'Syrup - Monin, Amaretta');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waywood', 'Clams - Littleneck, Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('3rd', 'Chips Potato Salt Vinegar 43g');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waxwing', 'Yeast Dry - Fermipan');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Service', 'Toothpick Frilled');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vermont', 'Soup Campbells');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Arizona', 'Table Cloth 62x120 Colour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Marcy', 'Vaccum Bag 10x13');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lotheville', 'Tomatoes Tear Drop Yellow');
insert into na_voljo (kino_ime, prigrizek_ime) values ('East', 'Coffee Decaf Colombian');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Arizona', 'Hinge W Undercut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Debs', 'Pepper - Jalapeno');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Becker', 'Wine - Semi Dry Riesling Vineland');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakeland', 'Muffin Mix - Morning Glory');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bay', 'Muffin Batt - Blueberry Passion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fisk', 'Compound - Raspberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eagan', 'Chef Hat 25cm');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Homewood', 'Cheese - Brie');
insert into na_voljo (kino_ime, prigrizek_ime) values ('7th', 'Rolled Oats');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Erie', 'Cheese - Parmigiano Reggiano');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vernon', 'Lemonade - Mandarin, 591 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shelley', 'Beef - Ox Tail, Frozen');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mallory', 'Bread - Sticks, Thin, Plain');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Marquette', 'Flour - Bread');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf', 'Wine - Barossa Valley Estate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hoard', 'Honey - Comb');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kinsman', 'Pasta - Canelloni, Single Serve');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Manley', 'Juice - Orangina');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakeland', 'Calypso - Lemonade');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kensington', 'Papayas');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Florence', 'Chicken - Leg, Boneless');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Arizona', 'Ginger - Pickled');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oxford', 'Cactus Pads');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Corry', 'Cheese - Bocconcini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fordem', 'Jolt Cola - Red Eye');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Russell', 'Juice - Cranberry 284ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest Run', 'Wine - Pinot Noir Latour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Farmco', 'Rosemary - Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Esch', 'Cheese Cloth No 60');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Algoma', 'Bread - 10 Grain Parisian');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Magdeline', 'Syrup - Monin, Irish Cream');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hovde', 'Cod - Black Whole Fillet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Meadow Vale', 'Wine - Chardonnay South');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Village Green', 'Yogurt - Plain');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Randy', 'Beef - Salted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dottie', 'Bar Nature Valley');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maywood', 'Shichimi Togarashi Peppeers');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Atwood', 'Pepper - Black, Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clyde Gallagher', 'Olives - Green, Pitted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Delladonna', 'Mushroom - Portebello');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schlimgen', 'Wine - Bouchard La Vignee Pinot');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Spenser', 'Pate - Peppercorn');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brown', 'Cheese - Comte');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Garrison', 'Trueblue - Blueberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crescent Oaks', 'Shrimp, Dried, Small / Lb');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Glendale', 'Shrimp - Black Tiger 13/15');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Columbus', 'Beans - Soya Bean');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Elka', 'Sprite, Diet - 355ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dovetail', 'Chicken - Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pawling', 'Potatoes - Purple, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cordelia', 'Sauce - Cranberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tomscot', 'Carbonated Water - White Grape');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Vermont', 'Wine - Piper Heidsieck Brut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dapin', 'Pork - Side Ribs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hermina', 'Containter - 3oz Microwave Rect.');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bayside', 'Sauce - White, Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shoshone', 'Lemonade - Kiwi, 591 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fremont', 'Cloves - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schmedeman', 'Pastry - Cheese Baked Scones');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clarendon', 'Snapple - Iced Tea Peach');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Talisman', 'Cookies Oatmeal Raisin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('School', 'Scallops 60/80 Iqf');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eagan', 'Apples - Sliced / Wedge');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakewood Gardens', 'Wine - Mondavi Coastal Private');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lerdahl', 'Croissants Thaw And Serve');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dwight', 'Clementine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anniversary', 'Grapes - Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Erie', 'Onions - Vidalia');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fieldstone', 'Muffin Mix - Raisin Bran');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Melvin', 'Wine La Vielle Ferme Cote Du');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Londonderry', 'Curry Paste - Green Masala');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westend', 'Wine - Lou Black Shiraz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sloan', 'V8 - Tropical Blend');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Meadow Vale', 'Garbage Bags - Clear');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Loomis', 'Raspberries - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Corry', 'Appetizer - Crab And Brie');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Steensland', 'Chocolate - Dark');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Del Mar', 'Cheese - Cream Cheese');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Johnson', 'Tomatoes - Plum, Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eagle Crest', 'Milkettes - 2%');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Warner', 'Sausage - Chorizo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Chive', 'Honey - Lavender');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Brickson Park', 'Venison - Denver Leg Boneless');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Katie', 'Tomato - Peeled Italian Canned');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hooker', 'Eel Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sutteridge', 'Table Cloth 90x90 White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Steensland', 'Beer - Moosehead');
insert into na_voljo (kino_ime, prigrizek_ime) values ('West', 'Flour - Chickpea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Green', 'Apple - Granny Smith');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Old Gate', 'Maintenance Removal Charge');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Wayridge', 'Melon - Watermelon, Seedless');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lindbergh', 'Bread - Pullman, Sliced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('2nd', 'Tomatoes - Vine Ripe, Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Orin', 'Alize Gold Passion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monument', 'Island Oasis - Banana Daiquiri');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sachs', 'Bread - Bagels, Mini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Montana', 'Chickensplit Half');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Huxley', 'Lamb - Leg, Diced');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Laurel', 'Cookies - Assorted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('New Castle', 'Table Cloth 62x114 White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Express', 'Wine - Clavet Saint Emilion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Artisan', 'Wine - German Riesling');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Declaration', 'Basil - Dry, Rubbed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tennessee', 'Rum - Dark, Bacardi, Black');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Manley', 'Icecream - Dstk Super Cone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bashford', 'Pails With Lids');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Village Green', 'Beer - Upper Canada Light');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Marcy', 'Flavouring - Orange');
insert into na_voljo (kino_ime, prigrizek_ime) values ('West', 'Syrup - Golden, Lyles');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bultman', 'Thyme - Lemon, Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hanson', 'Spinach - Packaged');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Twin Pines', 'Carbonated Water - Cherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Utah', 'Red Snapper - Fillet, Skin On');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mifflin', 'Yukon Jack');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rigney', 'Gherkin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Delladonna', 'Truffle Paste');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mifflin', 'Bacardi Limon');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schlimgen', 'Stock - Veal, White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Loeprich', 'Scrubbie - Scotchbrite Hand Pad');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Warbler', 'Bananas');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Glendale', 'Bread - Pita');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hagan', 'Rice - Jasmine Sented');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northland', 'Chips - Miss Vickies');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tennyson', 'Coffee - Ristretto Coffee Capsule');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Wayridge', 'Champagne - Brights, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Veith', 'Plasticspoonblack');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Victoria', 'Hog / Sausage Casing - Pork');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Portage', 'Doilies - 10, Paper');
insert into na_voljo (kino_ime, prigrizek_ime) values ('David', 'Star Fruit');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fremont', 'Jicama');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Goodland', 'Coconut - Creamed, Pure');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clemons', 'Lemonade - Natural, 591 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shelley', 'Silicone Parch. 16.3x24.3');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Garrison', 'Sprite - 355 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf Course', 'White Baguette');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Algoma', 'Flour - Masa De Harina Mexican');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Messerschmidt', 'Stock - Chicken, White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Randy', 'Kale - Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Continental', 'Lettuce - California Mix');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Colorado', 'Tomato - Plum With Basil');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Donald', 'Steampan - Half Size Shallow');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Aberg', 'Beer - Alexander Kieths, Pale Ale');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carpenter', 'Pork Casing');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Goodland', 'Cheese - Cream Cheese');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northwestern', 'Carrots - Purple, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Washington', 'Coke - Diet, 355 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hollow Ridge', 'Dc - Sakura Fu');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pond', 'Pepsi, 355 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Judy', 'Pork - Back, Short Cut, Boneless');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monterey', 'Crab - Claws, 26 - 30');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waxwing', 'Bread - Hot Dog Buns');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sauthoff', 'Longos - Chicken Caeser Salad');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forster', 'Juice - Orange, Concentrate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Myrtle', 'Energy Drink Red Bull');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anderson', 'Longos - Lasagna Beef');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Welch', 'Wine - Rosso Toscano Igt');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nancy', 'Lemonade - Black Cherry, 591 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sheridan', 'Lettuce - Boston Bib - Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buena Vista', 'Wine - Zinfandel California 2002');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Arrowood', 'Onions - Pearl');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cody', 'Sugar - Monocystal / Rock');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kinsman', 'Cake - Box Window 10x10x2.5');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northport', 'Sprouts - China Rose');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Garrison', 'Pork - Kidney');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hauk', 'Beef - Inside Round');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fair Oaks', 'Bread - Rolls, Rye');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Swallow', 'Containter - 3oz Microwave Rect.');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forster', 'Snapple Raspberry Tea');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Holy Cross', 'Coffee Decaf Colombian');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Milwaukee', 'Tamarind Paste');
insert into na_voljo (kino_ime, prigrizek_ime) values ('New Castle', 'Chocolate Eclairs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Rowland', 'Wine - Magnotta - Pinot Gris Sr');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lerdahl', 'Beets - Pickled');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sullivan', 'Sugar - Crumb');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Meadow Vale', 'Wine - Marlbourough Sauv Blanc');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakeland', 'Bagel - Plain');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Artisan', 'Puree - Pear');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anthes', 'Cookie - Oreo 100x2');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Meadow Valley', 'Grapes - Black');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Granby', 'Pepper - Black, Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Twin Pines', 'Bread - Roll, Soft White Round');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stuart', 'Cardamon Seed / Pod');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Manley', 'Syrup - Monin - Blue Curacao');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pond', 'Vermouth - Sweet, Cinzano');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Riverside', 'Chicken - Leg / Back Attach');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Buell', 'Glass - Wine, Plastic, Clear 5 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westridge', 'Pasta - Spaghetti, Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Green', 'Sauce - Oyster');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Starling', 'Cake Circle, Foil, Scallop');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Blue Bill Park', 'Momiji Oroshi Chili Sauce');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stang', 'Star Fruit');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Declaration', 'Syrup - Pancake');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf View', 'Ice Cream Bar - Rolo Cone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waxwing', 'Chips Potato Swt Chilli Sour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Maywood', 'Juice - Prune');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mendota', 'Nut - Almond, Blanched, Whole');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Twin Pines', 'Shrimp - 31/40');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mallard', 'Green Tea Refresher');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kedzie', 'Cheese - Taleggio D.o.p.');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Surrey', 'Longos - Penne With Pesto');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pearson', 'Macaroons - Two Bite Choc');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Londonderry', 'Chocolate - Feathers');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest Run', 'Broom And Brush Rack Black');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Starling', 'Sprouts - Brussel');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anthes', 'Juice - Propel Sport');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Nova', 'Cookie - Oreo 100x2');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dexter', 'Sansho Powder');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Golf', 'Wine - Jafflin Bourgongone');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pond', 'Anisette - Mcguiness');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Burning Wood', 'Turkey Leg With Drum And Thigh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sherman', 'Bread - White Epi Baguette');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Namekagon', 'Pepper - Sorrano');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kingsford', 'Foam Dinner Plate');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ronald Regan', 'Wine - Hardys Bankside Shiraz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Luster', 'Steampan - Half Size Shallow');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Washington', 'Beef - Tenderloin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cottonwood', 'Plate Foam Laminated 9in Blk');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westridge', 'Bread - Hamburger Buns');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Grayhawk', 'Stock - Veal, White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hoffman', 'Cinnamon Rolls');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bayside', 'Rum - White, Gg White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kennedy', 'Energy Drink Red Bull');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Grim', 'Cheese - Pied De Vents');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cherokee', 'Olives - Stuffed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Acker', 'Country Roll');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Raven', 'Anisette - Mcguiness');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fallview', 'Tray - 16in Rnd Blk');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lighthouse Bay', 'Wine - Trimbach Pinot Blanc');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Anniversary', 'Tea - Decaf Lipton');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sugar', 'Chicken - Livers');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Huxley', 'Pepper - Scotch Bonnet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merchant', 'Nut - Walnut, Pieces');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tennyson', 'Pickles - Gherkins');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Westridge', 'Cookie Double Choco');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monterey', 'Plastic Wrap');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Jenna', 'Table Cloth 144x90 White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hoepker', 'Orange Roughy 6/8 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Boyd', 'Chips Potato Salt Vinegar 43g');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Mandrake', 'Chicken - Leg, Boneless');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cody', 'Milk - Chocolate 250 Ml');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Petterle', 'Chips Potato Salt Vinegar 43g');
insert into na_voljo (kino_ime, prigrizek_ime) values ('North', 'Rice - Basmati');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Upham', 'Venison - Striploin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Express', 'Pork Loin Cutlets');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Banding', 'Goulash Seasoning');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Manufacturers', 'Beef - Ox Tongue, Pickled');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Springview', 'Wine - Chianti Classico Riserva');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Summer Ridge', 'Tamarind Paste');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Stone Corner', 'Muffin - Mix - Mango Sour Cherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Scofield', 'Red Cod Fillets - 225g');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Katie', 'Cranberries - Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oneill', 'Bread - Onion Focaccia');
insert into na_voljo (kino_ime, prigrizek_ime) values ('David', 'Chocolate - Milk Coating');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oriole', 'Vinegar - White Wine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moose', 'Lemon Pepper');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Johnson', 'Flavouring Vanilla Artificial');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tomscot', 'Cloves - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('2nd', 'Lychee');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shelley', 'Tomatoes - Hot House');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Monterey', 'Rum - Coconut, Malibu');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Knutson', 'Orange - Canned, Mandarin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ohio', 'Sauce - Alfredo');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Commercial', 'Muskox - French Rack');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Riverside', 'Mushrooms - Honey');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crescent Oaks', 'Cheese - Brick With Onion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Moland', 'Veal Inside - Provimi');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Miller', 'Madeira');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Logan', 'Mackerel Whole Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kennedy', 'Bok Choy - Baby');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ludington', 'Pastry - Apple Muffins - Mini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Summerview', 'Rosemary - Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crowley', 'Curry Paste - Green Masala');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Toban', 'Cheese - Colby');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Pond', 'Beer - Heinekin');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Grim', 'Seedlings - Clamshell');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Transport', 'Brandy - Orange, Mc Guiness');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Norway Maple', 'Juice - Mango');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Novick', 'Beef Ground Medium');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Browning', 'Ecolab - Mikroklene 4/4 L');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Chive', 'Pepper - Red Chili');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Fremont', 'Appetizer - Cheese Bites');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Donald', 'Chocolate Liqueur - Godet White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Carey', 'Pepper - Green');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Shopko', 'Alize Red Passion');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Sunbrook', 'Apple - Delicious, Golden');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Michigan', 'Plums - Red');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Village', 'Compound - Mocha');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Melvin', 'Juice - V8, Tomato');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northwestern', 'Veal - Heart');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kedzie', 'Bread - Olive Dinner Roll');
insert into na_voljo (kino_ime, prigrizek_ime) values ('6th', 'Beef - Ground Lean Fresh');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Schmedeman', 'Wine - Cava Aria Estate Brut');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Tennessee', 'Thyme - Dried');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Eggendart', 'Pop - Club Soda Can');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ridgeway', 'Garbage Bags - Clear');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hanover', 'Table Cloth 90x90 Colour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Grayhawk', 'Sugar - Sweet N Low, Individual');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clarendon', 'Sugar Thermometer');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bonner', 'Mushroom - White Button');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bunker Hill', 'Silicone Paper 16.5x24');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Canary', 'Assorted Desserts');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Evergreen', 'Wine - Tio Pepe Sherry Fino');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Cascade', 'Cranberry Foccacia');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Ridgeway', 'Carbonated Water - Wildberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Oxford', 'V8 - Berry Blend');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Manley', 'Cheese - Brie Roitelet');
insert into na_voljo (kino_ime, prigrizek_ime) values ('2nd', 'Milk - Condensed');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Clove', 'Table Cloth 72x144 White');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Evergreen', 'Cumin - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Laurel', 'Salsify, Organic');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Comanche', 'Bread - Bagels, Mini');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Michigan', 'Island Oasis - Strawberry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kensington', 'Nantucket - Kiwi Berry Cktl.');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dapin', 'Grapes - Black');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hallows', 'Wine - Ice Wine');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Morning', 'Soap - Pine Sol Floor Cleaner');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Independence', 'Shrimp - 100 / 200 Cold Water');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forster', 'Beef - Bones, Cut - Up');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Northridge', 'Cinnamon - Stick');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Forest Run', 'Salmon Steak - Cohoe 6 Oz');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Springs', 'Syrup - Monin, Irish Cream');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Orin', 'Cheese - Augre Des Champs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Service', 'Muffins - Assorted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Crescent Oaks', 'Figs');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Thierer', 'Cake - Miini Cheesecake Cherry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Hanson', 'Wine - Pinot Noir Latour');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Raven', 'Yogurt - Assorted Pack');
insert into na_voljo (kino_ime, prigrizek_ime) values ('South', 'Onions Granulated');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Garrison', 'Cup - 8oz Coffee Perforated');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Steensland', 'Beer - Guiness');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Dennis', 'Ginger - Ground');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Prentice', 'Wine La Vielle Ferme Cote Du');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Waubesa', 'Chips - Assorted');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Bellgrove', 'Taro Leaves');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Browning', 'Wine - Red, Pelee Island Merlot');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Valley Edge', 'Cauliflower');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Park Meadow', 'Doilies - 7, Paper');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Merrick', 'Dc Hikiage Hira Huba');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Lakeland', 'Peach - Halves');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Kennedy', 'Dill Weed - Dry');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Old Gate', 'Fudge - Cream Fudge');
insert into na_voljo (kino_ime, prigrizek_ime) values ('Warrior', 'Shrimp - 21/25, Peel And Deviened');
