insert into prigrizek (ime, cena) values ('Mushroom - Morels, Dry', '€3,29');
insert into prigrizek (ime, cena) values ('Lettuce - Radicchio', '€3,35');
insert into prigrizek (ime, cena) values ('Bread Foccacia Whole', '€0,62');
insert into prigrizek (ime, cena) values ('Beans - Fine', '€3,86');
insert into prigrizek (ime, cena) values ('Soup - Campbells, Butternut', '€0,59');
insert into prigrizek (ime, cena) values ('Vodka - Hot, Lnferno', '€0,11');
insert into prigrizek (ime, cena) values ('Brownies - Two Bite, Chocolate', '€2,69');
insert into prigrizek (ime, cena) values ('Bread - Bistro Sour', '€4,82');
insert into prigrizek (ime, cena) values ('Ecolab - Mikroklene 4/4 L', '€2,57');
insert into prigrizek (ime, cena) values ('Dawn Professionl Pot And Pan', '€1,50');
insert into prigrizek (ime, cena) values ('Raspberries - Frozen', '€3,74');
insert into prigrizek (ime, cena) values ('Kaffir Lime Leaves', '€3,77');
insert into prigrizek (ime, cena) values ('Bacardi Mojito', '€2,50');
insert into prigrizek (ime, cena) values ('Oxtail - Cut', '€2,61');
insert into prigrizek (ime, cena) values ('Lady Fingers', '€2,82');
insert into prigrizek (ime, cena) values ('Roe - Flying Fish', '€3,31');
insert into prigrizek (ime, cena) values ('Glucose', '€1,54');
insert into prigrizek (ime, cena) values ('Lettuce - Lolla Rosa', '€3,62');
insert into prigrizek (ime, cena) values ('Tumeric', '€4,05');
insert into prigrizek (ime, cena) values ('Nut - Almond, Blanched, Ground', '€3,96');
insert into prigrizek (ime, cena) values ('Taro Root', '€4,95');
insert into prigrizek (ime, cena) values ('Pepper - Red Chili', '€4,21');
insert into prigrizek (ime, cena) values ('Pastrami', '€2,68');
insert into prigrizek (ime, cena) values ('Pepsi - 600ml', '€2,97');
insert into prigrizek (ime, cena) values ('Papadam', '€2,67');
insert into prigrizek (ime, cena) values ('Chocolate - Compound Coating', '€4,68');
insert into prigrizek (ime, cena) values ('Juice - Clamato, 341 Ml', '€2,95');
insert into prigrizek (ime, cena) values ('Orange Roughy 4/6 Oz', '€0,35');
insert into prigrizek (ime, cena) values ('Sole - Dover, Whole, Fresh', '€0,36');
insert into prigrizek (ime, cena) values ('Bread - Italian Sesame Poly', '€3,24');
insert into prigrizek (ime, cena) values ('Soup - Campbells, Spinach Crm', '€0,15');
insert into prigrizek (ime, cena) values ('Soup Campbells - Tomato Bisque', '€0,29');
insert into prigrizek (ime, cena) values ('Chips Potato All Dressed - 43g', '€4,44');
insert into prigrizek (ime, cena) values ('Tart Shells - Savory, 4', '€1,67');
insert into prigrizek (ime, cena) values ('Wine - Sherry Dry Sack, William', '€2,79');
insert into prigrizek (ime, cena) values ('Oil - Macadamia', '€4,09');
insert into prigrizek (ime, cena) values ('Ecolab - Solid Fusion', '€4,18');
insert into prigrizek (ime, cena) values ('Liqueur - Melon', '€2,80');
insert into prigrizek (ime, cena) values ('Wine - Chateauneuf Du Pape', '€2,98');
insert into prigrizek (ime, cena) values ('Broom Handle', '€0,86');
insert into prigrizek (ime, cena) values ('Jolt Cola - Electric Blue', '€0,56');
insert into prigrizek (ime, cena) values ('Chilli Paste, Sambal Oelek', '€1,53');
insert into prigrizek (ime, cena) values ('Grand Marnier', '€2,94');
insert into prigrizek (ime, cena) values ('Lettuce - Curly Endive', '€2,29');
insert into prigrizek (ime, cena) values ('Rambutan', '€0,11');
insert into prigrizek (ime, cena) values ('Vinegar - Raspberry', '€1,13');
insert into prigrizek (ime, cena) values ('Crab - Claws, 26 - 30', '€0,58');
insert into prigrizek (ime, cena) values ('Hot Chocolate - Individual', '€1,09');
insert into prigrizek (ime, cena) values ('Lentils - Red, Dry', '€3,80');
insert into prigrizek (ime, cena) values ('Icecream Bar - Del Monte', '€1,13');
insert into prigrizek (ime, cena) values ('Fish - Base, Bouillion', '€4,28');
insert into prigrizek (ime, cena) values ('Wine - Blue Nun Qualitatswein', '€4,21');
insert into prigrizek (ime, cena) values ('Eggplant Italian', '€2,31');
insert into prigrizek (ime, cena) values ('Toamtoes 6x7 Select', '€4,02');
insert into prigrizek (ime, cena) values ('Chick Peas - Canned', '€3,31');
insert into prigrizek (ime, cena) values ('Eel - Smoked', '€0,53');
insert into prigrizek (ime, cena) values ('Cardamon Ground', '€2,62');
insert into prigrizek (ime, cena) values ('Vinegar - Balsamic, White', '€4,42');
insert into prigrizek (ime, cena) values ('Flower - Carnations', '€4,46');
insert into prigrizek (ime, cena) values ('Wine - Muscadet Sur Lie', '€3,56');
insert into prigrizek (ime, cena) values ('Appetizer - Veg Assortment', '€2,61');
insert into prigrizek (ime, cena) values ('Venison - Ground', '€0,90');
insert into prigrizek (ime, cena) values ('Venison - Racks Frenched', '€0,26');
insert into prigrizek (ime, cena) values ('Cheese - Mix', '€0,33');
insert into prigrizek (ime, cena) values ('Water - San Pellegrino', '€1,12');
insert into prigrizek (ime, cena) values ('Soup - Verve - Chipotle Chicken', '€3,88');
insert into prigrizek (ime, cena) values ('Cream - 10%', '€0,97');
insert into prigrizek (ime, cena) values ('Table Cloth 81x81 Colour', '€4,53');
insert into prigrizek (ime, cena) values ('Chicken Thigh - Bone Out', '€0,64');
insert into prigrizek (ime, cena) values ('Appetizer - Seafood Assortment', '€1,78');
insert into prigrizek (ime, cena) values ('Pumpkin - Seed', '€2,61');
insert into prigrizek (ime, cena) values ('Chick Peas - Canned', '€4,28');
insert into prigrizek (ime, cena) values ('Sea Bass - Whole', '€0,43');
insert into prigrizek (ime, cena) values ('Cake - Night And Day Choclate', '€4,70');
insert into prigrizek (ime, cena) values ('Bread - Burger', '€0,57');
insert into prigrizek (ime, cena) values ('Water - Tonic', '€1,35');
insert into prigrizek (ime, cena) values ('Chocolate Bar - Smarties', '€0,62');
insert into prigrizek (ime, cena) values ('Mangostein', '€3,66');
insert into prigrizek (ime, cena) values ('Fish - Base, Bouillion', '€1,68');
insert into prigrizek (ime, cena) values ('Snapple - Iced Tea Peach', '€0,74');
insert into prigrizek (ime, cena) values ('Turkey - Breast, Bone - In', '€1,88');
insert into prigrizek (ime, cena) values ('Tofu - Soft', '€3,26');
insert into prigrizek (ime, cena) values ('Bar - Sweet And Salty Chocolate', '€2,25');
insert into prigrizek (ime, cena) values ('Parsley Italian - Fresh', '€2,87');
insert into prigrizek (ime, cena) values ('Bacon Strip Precooked', '€0,60');
insert into prigrizek (ime, cena) values ('Bar - Granola Trail Mix Fruit Nut', '€2,01');
insert into prigrizek (ime, cena) values ('Knife Plastic - White', '€0,26');
insert into prigrizek (ime, cena) values ('Cheese - Feta', '€3,75');
insert into prigrizek (ime, cena) values ('Flour - Strong Pizza', '€3,39');
insert into prigrizek (ime, cena) values ('Water - Spring 1.5lit', '€3,46');
insert into prigrizek (ime, cena) values ('Compound - Pear', '€4,07');
insert into prigrizek (ime, cena) values ('Lotus Rootlets - Canned', '€3,20');
insert into prigrizek (ime, cena) values ('Tea - Decaf Lipton', '€4,26');
insert into prigrizek (ime, cena) values ('Wild Boar - Tenderloin', '€4,96');
insert into prigrizek (ime, cena) values ('Lychee', '€2,27');
insert into prigrizek (ime, cena) values ('Vermouth - Sweet, Cinzano', '€3,63');
insert into prigrizek (ime, cena) values ('Bread - Olive Dinner Roll', '€4,81');
insert into prigrizek (ime, cena) values ('Cheese - Swiss Sliced', '€4,01');
insert into prigrizek (ime, cena) values ('Beans - Black Bean, Dry', '€4,56');
insert into prigrizek (ime, cena) values ('Pail - 4l White, With Handle', '€0,09');
insert into prigrizek (ime, cena) values ('Artichoke - Fresh', '€4,99');
insert into prigrizek (ime, cena) values ('Nut - Almond, Blanched, Whole', '€4,10');
insert into prigrizek (ime, cena) values ('Cassis', '€3,32');
insert into prigrizek (ime, cena) values ('Salsify, Organic', '€0,92');
insert into prigrizek (ime, cena) values ('Soho Lychee Liqueur', '€0,54');
insert into prigrizek (ime, cena) values ('Mayonnaise', '€2,79');
insert into prigrizek (ime, cena) values ('Oil - Sesame', '€2,87');
insert into prigrizek (ime, cena) values ('Chick Peas - Canned', '€1,57');
insert into prigrizek (ime, cena) values ('Pail With Metal Handle 16l White', '€2,54');
insert into prigrizek (ime, cena) values ('Compound - Mocha', '€3,74');
insert into prigrizek (ime, cena) values ('Yeast Dry - Fermipan', '€3,17');
insert into prigrizek (ime, cena) values ('Coffee - Cafe Moreno', '€2,97');
insert into prigrizek (ime, cena) values ('Coffee Cup 12oz 5342cd', '€0,44');
insert into prigrizek (ime, cena) values ('Crab - Imitation Flakes', '€0,57');
insert into prigrizek (ime, cena) values ('Bread - Malt', '€1,55');
insert into prigrizek (ime, cena) values ('Pork - Sausage Casing', '€0,23');
insert into prigrizek (ime, cena) values ('Tuna - Salad Premix', '€0,54');
insert into prigrizek (ime, cena) values ('Chocolate - Semi Sweet, Calets', '€3,89');
insert into prigrizek (ime, cena) values ('Soup - Campbells Beef Strogonoff', '€4,38');
insert into prigrizek (ime, cena) values ('Wine - Red, Gamay Noir', '€2,29');
insert into prigrizek (ime, cena) values ('Strawberries', '€2,68');
insert into prigrizek (ime, cena) values ('Roe - Flying Fish', '€3,99');
insert into prigrizek (ime, cena) values ('Pizza Pizza Dough', '€1,82');
insert into prigrizek (ime, cena) values ('Squash - Pattypan, Yellow', '€0,71');
insert into prigrizek (ime, cena) values ('Bread - Crusty Italian Poly', '€4,18');
insert into prigrizek (ime, cena) values ('Petite Baguette', '€2,65');
insert into prigrizek (ime, cena) values ('Liqueur Banana, Ramazzotti', '€3,32');
insert into prigrizek (ime, cena) values ('Bread - 10 Grain', '€4,99');
insert into prigrizek (ime, cena) values ('Cherries - Bing, Canned', '€3,18');
insert into prigrizek (ime, cena) values ('Wine - Peller Estates Late', '€4,05');
insert into prigrizek (ime, cena) values ('Fib N9 - Prague Powder', '€4,38');
insert into prigrizek (ime, cena) values ('Table Cloth 81x81 White', '€1,29');
insert into prigrizek (ime, cena) values ('Ice Cream - Strawberry', '€3,04');
insert into prigrizek (ime, cena) values ('Radish - Pickled', '€3,80');
insert into prigrizek (ime, cena) values ('Sage Ground Wiberg', '€0,50');
insert into prigrizek (ime, cena) values ('Lotus Rootlets - Canned', '€4,69');
insert into prigrizek (ime, cena) values ('Bay Leaf Ground', '€0,84');
insert into prigrizek (ime, cena) values ('Cheese - Brie Roitelet', '€4,99');
insert into prigrizek (ime, cena) values ('Wine - Red, Mouton Cadet', '€4,46');
insert into prigrizek (ime, cena) values ('Garbag Bags - Black', '€2,78');
insert into prigrizek (ime, cena) values ('Beets', '€4,82');
insert into prigrizek (ime, cena) values ('Goat - Whole Cut', '€1,73');
insert into prigrizek (ime, cena) values ('Grapes - Green', '€4,45');
insert into prigrizek (ime, cena) values ('Lettuce - Escarole', '€1,06');
insert into prigrizek (ime, cena) values ('Wine - Vineland Estate Semi - Dry', '€4,17');
insert into prigrizek (ime, cena) values ('Puree - Passion Fruit', '€4,29');
insert into prigrizek (ime, cena) values ('Fish - Artic Char, Cold Smoked', '€4,14');
insert into prigrizek (ime, cena) values ('White Fish - Filets', '€3,66');
insert into prigrizek (ime, cena) values ('Tart Shells - Sweet, 4', '€4,17');
insert into prigrizek (ime, cena) values ('Dawn Professionl Pot And Pan', '€2,60');
insert into prigrizek (ime, cena) values ('Onions - Red', '€0,97');
insert into prigrizek (ime, cena) values ('Pork - Tenderloin, Frozen', '€2,15');
insert into prigrizek (ime, cena) values ('Pineapple - Canned, Rings', '€3,83');
insert into prigrizek (ime, cena) values ('Corn Meal', '€1,11');
insert into prigrizek (ime, cena) values ('Yoplait - Strawbrasp Peac', '€4,13');
insert into prigrizek (ime, cena) values ('Pastry - Carrot Muffin - Mini', '€4,63');
insert into prigrizek (ime, cena) values ('Cheese - Gorgonzola', '€2,72');
insert into prigrizek (ime, cena) values ('Coconut - Whole', '€0,13');
insert into prigrizek (ime, cena) values ('Honey - Comb', '€2,72');
insert into prigrizek (ime, cena) values ('Oil - Safflower', '€2,13');
insert into prigrizek (ime, cena) values ('Chocolate Bar - Oh Henry', '€4,04');
insert into prigrizek (ime, cena) values ('Ice Cream - Super Sandwich', '€1,86');
insert into prigrizek (ime, cena) values ('Wine - Alicanca Vinho Verde', '€2,89');
insert into prigrizek (ime, cena) values ('Veal - Inside, Choice', '€1,39');
insert into prigrizek (ime, cena) values ('Quiche Assorted', '€4,69');
insert into prigrizek (ime, cena) values ('Spinach - Frozen', '€4,00');
insert into prigrizek (ime, cena) values ('Island Oasis - Sweet And Sour Mix', '€2,15');
insert into prigrizek (ime, cena) values ('Wine - Prosecco Valdobienne', '€4,75');
insert into prigrizek (ime, cena) values ('Chocolate Bar - Reese Pieces', '€1,29');
insert into prigrizek (ime, cena) values ('Pepper - Yellow Bell', '€0,10');
insert into prigrizek (ime, cena) values ('Rum - Mount Gay Eclipes', '€2,79');
insert into prigrizek (ime, cena) values ('Tofu - Soft', '€4,40');
insert into prigrizek (ime, cena) values ('Kaffir Lime Leaves', '€3,14');
insert into prigrizek (ime, cena) values ('Wine - Prem Select Charddonany', '€1,24');
insert into prigrizek (ime, cena) values ('Pepper - Chillies, Crushed', '€1,03');
insert into prigrizek (ime, cena) values ('Sauce - White, Mix', '€2,09');
insert into prigrizek (ime, cena) values ('Salt - Sea', '€3,52');
insert into prigrizek (ime, cena) values ('Cape Capensis - Fillet', '€4,47');
insert into prigrizek (ime, cena) values ('White Baguette', '€4,03');
insert into prigrizek (ime, cena) values ('Salmon - Atlantic, No Skin', '€3,95');
insert into prigrizek (ime, cena) values ('Beans - Butter Lrg Lima', '€4,84');
insert into prigrizek (ime, cena) values ('Poppy Seed', '€4,84');
insert into prigrizek (ime, cena) values ('Lettuce - Sea / Sea Asparagus', '€4,96');
insert into prigrizek (ime, cena) values ('Pasta - Fettuccine, Egg, Fresh', '€2,88');
insert into prigrizek (ime, cena) values ('Ecolab - Lime - A - Way 4/4 L', '€3,32');
insert into prigrizek (ime, cena) values ('Cassis', '€4,62');
insert into prigrizek (ime, cena) values ('Tomatoes - Heirloom', '€4,91');
insert into prigrizek (ime, cena) values ('Cake - Mini Cheesecake', '€0,78');
insert into prigrizek (ime, cena) values ('Skirt - 24 Foot', '€2,19');
insert into prigrizek (ime, cena) values ('Pails With Lids', '€2,36');
insert into prigrizek (ime, cena) values ('Berry Brulee', '€2,60');
insert into prigrizek (ime, cena) values ('Wine - White, French Cross', '€3,58');
insert into prigrizek (ime, cena) values ('Sprouts - Corn', '€1,49');
insert into prigrizek (ime, cena) values ('Plastic Wrap', '€3,20');
insert into prigrizek (ime, cena) values ('Huck White Towels', '€4,06');
insert into prigrizek (ime, cena) values ('Cranberry Foccacia', '€4,70');
insert into prigrizek (ime, cena) values ('Flavouring - Raspberry', '€2,35');
insert into prigrizek (ime, cena) values ('Syrup - Monin - Granny Smith', '€0,53');
insert into prigrizek (ime, cena) values ('Cheese - Comte', '€2,81');
insert into prigrizek (ime, cena) values ('Coffee Swiss Choc Almond', '€3,25');
insert into prigrizek (ime, cena) values ('Table Cloth 62x120 Colour', '€2,32');
insert into prigrizek (ime, cena) values ('Heavy Duty Dust Pan', '€0,02');
insert into prigrizek (ime, cena) values ('Glycerine', '€0,63');
insert into prigrizek (ime, cena) values ('Puff Pastry - Sheets', '€4,33');
insert into prigrizek (ime, cena) values ('Bread Base - Toscano', '€2,35');
insert into prigrizek (ime, cena) values ('Wine - Tio Pepe Sherry Fino', '€4,19');
insert into prigrizek (ime, cena) values ('Milk - 2%', '€2,89');
insert into prigrizek (ime, cena) values ('Pepper - Orange', '€1,60');
insert into prigrizek (ime, cena) values ('Pie Shell - 5', '€4,06');
insert into prigrizek (ime, cena) values ('Tart Shells - Barquettes, Savory', '€2,01');
insert into prigrizek (ime, cena) values ('Kellogs Special K Cereal', '€2,62');
insert into prigrizek (ime, cena) values ('Juice - Lime', '€1,36');
insert into prigrizek (ime, cena) values ('Icecream Cone - Areo Chocolate', '€4,71');
insert into prigrizek (ime, cena) values ('Dried Peach', '€1,14');
insert into prigrizek (ime, cena) values ('Tea - Honey Green Tea', '€0,85');
insert into prigrizek (ime, cena) values ('Soup - Campbells Bean Medley', '€2,37');
insert into prigrizek (ime, cena) values ('Glaze - Clear', '€0,47');
insert into prigrizek (ime, cena) values ('Lettuce - California Mix', '€2,47');
insert into prigrizek (ime, cena) values ('Mince Meat - Filling', '€2,48');
insert into prigrizek (ime, cena) values ('Milk - Condensed', '€1,85');
insert into prigrizek (ime, cena) values ('Juice - Apple Cider', '€0,70');
insert into prigrizek (ime, cena) values ('Bread - French Stick', '€2,74');
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Pinot Gris Sr', '€2,26');
insert into prigrizek (ime, cena) values ('Cherries - Fresh', '€0,88');
insert into prigrizek (ime, cena) values ('Otomegusa Dashi Konbu', '€3,99');
insert into prigrizek (ime, cena) values ('Grenadine', '€0,38');
insert into prigrizek (ime, cena) values ('Juice - Happy Planet', '€3,67');
insert into prigrizek (ime, cena) values ('Compound - Mocha', '€3,74');
insert into prigrizek (ime, cena) values ('Lettuce - Boston Bib', '€4,27');
insert into prigrizek (ime, cena) values ('Lentils - Green, Dry', '€4,12');
insert into prigrizek (ime, cena) values ('Glaze - Apricot', '€4,98');
insert into prigrizek (ime, cena) values ('Beer - Blue', '€4,14');
insert into prigrizek (ime, cena) values ('Cake - Lemon Chiffon', '€1,64');
insert into prigrizek (ime, cena) values ('Veal - Striploin', '€0,80');
insert into prigrizek (ime, cena) values ('The Pop Shoppe - Lime Rickey', '€1,50');
insert into prigrizek (ime, cena) values ('Pike - Frozen Fillet', '€2,50');
insert into prigrizek (ime, cena) values ('Appetizer - Cheese Bites', '€3,46');
insert into prigrizek (ime, cena) values ('Praline Paste', '€2,77');
insert into prigrizek (ime, cena) values ('Cake - Pancake', '€3,09');
insert into prigrizek (ime, cena) values ('Doilies - 10, Paper', '€3,48');
insert into prigrizek (ime, cena) values ('Onions Granulated', '€2,78');
insert into prigrizek (ime, cena) values ('Napkin - Beverage 1 Ply', '€0,52');
insert into prigrizek (ime, cena) values ('Cream Of Tartar', '€0,88');
insert into prigrizek (ime, cena) values ('Coffee Caramel Biscotti', '€2,48');
insert into prigrizek (ime, cena) values ('Rabbit - Legs', '€2,22');
insert into prigrizek (ime, cena) values ('Soup - Campbells Mushroom', '€1,14');
insert into prigrizek (ime, cena) values ('Mix Pina Colada', '€1,87');
insert into prigrizek (ime, cena) values ('Peach - Fresh', '€1,57');
insert into prigrizek (ime, cena) values ('Shopper Bag - S - 4', '€1,58');
insert into prigrizek (ime, cena) values ('Juice - Orange', '€0,33');
insert into prigrizek (ime, cena) values ('Wine - Beringer Founders Estate', '€4,02');
insert into prigrizek (ime, cena) values ('Jam - Blackberry, 20 Ml Jar', '€3,61');
insert into prigrizek (ime, cena) values ('Clams - Canned', '€0,35');
insert into prigrizek (ime, cena) values ('Maintenance Removal Charge', '€2,46');
insert into prigrizek (ime, cena) values ('Tobasco Sauce', '€1,49');
insert into prigrizek (ime, cena) values ('Venison - Ground', '€3,97');
insert into prigrizek (ime, cena) values ('Scallops - U - 10', '€2,85');
insert into prigrizek (ime, cena) values ('Onion Powder', '€4,36');
insert into prigrizek (ime, cena) values ('Drambuie', '€3,85');
insert into prigrizek (ime, cena) values ('Pork - Loin, Center Cut', '€1,66');
insert into prigrizek (ime, cena) values ('Salt - Table', '€3,29');
insert into prigrizek (ime, cena) values ('Shrimp - 31/40', '€3,78');
insert into prigrizek (ime, cena) values ('Pasta - Lasagne, Fresh', '€2,35');
insert into prigrizek (ime, cena) values ('Muffin Batt - Blueberry Passion', '€0,37');
insert into prigrizek (ime, cena) values ('Soup - Campbells Tomato Ravioli', '€0,70');
insert into prigrizek (ime, cena) values ('Juice - Apple, 341 Ml', '€3,19');
insert into prigrizek (ime, cena) values ('Cake - French Pear Tart', '€2,35');
insert into prigrizek (ime, cena) values ('Mussels - Frozen', '€2,24');
insert into prigrizek (ime, cena) values ('Pork - Bacon,back Peameal', '€0,34');
insert into prigrizek (ime, cena) values ('Southern Comfort', '€3,19');
insert into prigrizek (ime, cena) values ('Gatorade - Fruit Punch', '€1,82');
insert into prigrizek (ime, cena) values ('Garam Marsala', '€4,11');
insert into prigrizek (ime, cena) values ('Mushroom - Shitake, Fresh', '€2,98');
insert into prigrizek (ime, cena) values ('Wine - Mondavi Coastal Private', '€3,90');
insert into prigrizek (ime, cena) values ('Sword Pick Asst', '€3,66');
insert into prigrizek (ime, cena) values ('Energy Drink', '€0,53');
insert into prigrizek (ime, cena) values ('Ecolab Crystal Fusion', '€1,36');
insert into prigrizek (ime, cena) values ('Coffee - 10oz Cup 92961', '€3,00');
insert into prigrizek (ime, cena) values ('Capon - Breast, Wing On', '€2,65');
insert into prigrizek (ime, cena) values ('Mushroom - Crimini', '€4,93');
insert into prigrizek (ime, cena) values ('Soup - Campbells, Butternut', '€1,07');
insert into prigrizek (ime, cena) values ('Teriyaki Sauce', '€4,54');
insert into prigrizek (ime, cena) values ('Corn Syrup', '€1,18');
insert into prigrizek (ime, cena) values ('Catfish - Fillets', '€2,74');
insert into prigrizek (ime, cena) values ('Pepper - Sorrano', '€4,86');
insert into prigrizek (ime, cena) values ('Sesame Seed', '€2,59');
insert into prigrizek (ime, cena) values ('Sprouts - Brussel', '€1,96');
insert into prigrizek (ime, cena) values ('Soup - Tomato Mush. Florentine', '€0,26');
insert into prigrizek (ime, cena) values ('Juice - Lime', '€1,75');
insert into prigrizek (ime, cena) values ('Milk - Skim', '€4,66');
insert into prigrizek (ime, cena) values ('Jam - Marmalade, Orange', '€0,30');
insert into prigrizek (ime, cena) values ('Wine - White, Pelee Island', '€4,41');
insert into prigrizek (ime, cena) values ('Wine - Ej Gallo Sonoma', '€5,00');
insert into prigrizek (ime, cena) values ('Bacardi Limon', '€3,77');
insert into prigrizek (ime, cena) values ('Wine - Red, Cabernet Sauvignon', '€2,32');
insert into prigrizek (ime, cena) values ('Beer - Mcauslan Apricot', '€0,20');
insert into prigrizek (ime, cena) values ('Alize Red Passion', '€4,25');
insert into prigrizek (ime, cena) values ('Wine - White, Cooking', '€0,37');
insert into prigrizek (ime, cena) values ('Cheese - Roquefort Pappillon', '€1,98');
insert into prigrizek (ime, cena) values ('Island Oasis - Sweet And Sour Mix', '€4,14');
insert into prigrizek (ime, cena) values ('Trout - Rainbow, Frozen', '€1,84');
insert into prigrizek (ime, cena) values ('Leeks - Large', '€2,83');
insert into prigrizek (ime, cena) values ('Pork Loin Cutlets', '€4,35');
insert into prigrizek (ime, cena) values ('Butter Balls Salted', '€3,79');
insert into prigrizek (ime, cena) values ('Tia Maria', '€0,31');
insert into prigrizek (ime, cena) values ('Mousse - Mango', '€4,34');
insert into prigrizek (ime, cena) values ('Lamb Shoulder Boneless Nz', '€1,16');
insert into prigrizek (ime, cena) values ('Onions - Red', '€4,38');
insert into prigrizek (ime, cena) values ('Vanilla Beans', '€0,81');
insert into prigrizek (ime, cena) values ('Cheese - Ricotta', '€0,71');
insert into prigrizek (ime, cena) values ('Ecolab Crystal Fusion', '€3,53');
insert into prigrizek (ime, cena) values ('Capers - Pickled', '€0,83');
insert into prigrizek (ime, cena) values ('Cheese - La Sauvagine', '€3,36');
insert into prigrizek (ime, cena) values ('Tarragon - Primerba, Paste', '€4,34');
insert into prigrizek (ime, cena) values ('Lamb - Shanks', '€3,69');
insert into prigrizek (ime, cena) values ('Bread Country Roll', '€4,36');
insert into prigrizek (ime, cena) values ('Wine - Placido Pinot Grigo', '€2,34');
insert into prigrizek (ime, cena) values ('Bar Mix - Lemon', '€0,34');
insert into prigrizek (ime, cena) values ('Lamb Rack - Ontario', '€2,43');
insert into prigrizek (ime, cena) values ('Veal - Tenderloin, Untrimmed', '€0,97');
insert into prigrizek (ime, cena) values ('Pepper - Red, Finger Hot', '€4,23');
insert into prigrizek (ime, cena) values ('Milk - Buttermilk', '€3,44');
insert into prigrizek (ime, cena) values ('Goat - Leg', '€0,63');
insert into prigrizek (ime, cena) values ('Graham Cracker Mix', '€2,75');
insert into prigrizek (ime, cena) values ('Salmon - Atlantic, Skin On', '€1,31');
insert into prigrizek (ime, cena) values ('Wine - Red, Black Opal Shiraz', '€2,10');
insert into prigrizek (ime, cena) values ('General Purpose Trigger', '€3,41');
insert into prigrizek (ime, cena) values ('Food Colouring - Red', '€4,37');
insert into prigrizek (ime, cena) values ('C - Plus, Orange', '€2,10');
insert into prigrizek (ime, cena) values ('Tea - Honey Green Tea', '€4,96');
insert into prigrizek (ime, cena) values ('Bread - Calabrese Baguette', '€1,07');
insert into prigrizek (ime, cena) values ('Cup - Paper 10oz 92959', '€0,14');
insert into prigrizek (ime, cena) values ('Sour Cream', '€0,40');
insert into prigrizek (ime, cena) values ('Mushroom - Lg - Cello', '€0,35');
insert into prigrizek (ime, cena) values ('Oil - Olive, Extra Virgin', '€1,83');
insert into prigrizek (ime, cena) values ('Cheese - Brie,danish', '€3,71');
insert into prigrizek (ime, cena) values ('Lemon Pepper', '€3,60');
insert into prigrizek (ime, cena) values ('Bread - Multigrain Oval', '€3,26');
insert into prigrizek (ime, cena) values ('Pepper - Red Bell', '€4,47');
insert into prigrizek (ime, cena) values ('Pepper - Roasted Red', '€0,44');
insert into prigrizek (ime, cena) values ('The Pop Shoppe - Lime Rickey', '€3,92');
insert into prigrizek (ime, cena) values ('Pastry - Banana Muffin - Mini', '€4,53');
insert into prigrizek (ime, cena) values ('Cardamon Ground', '€2,21');
insert into prigrizek (ime, cena) values ('Appetizer - Assorted Box', '€2,94');
insert into prigrizek (ime, cena) values ('Butter Balls Salted', '€4,94');
insert into prigrizek (ime, cena) values ('Pork Casing', '€4,10');
insert into prigrizek (ime, cena) values ('Mushrooms - Honey', '€4,58');
insert into prigrizek (ime, cena) values ('Longos - Lasagna Veg', '€1,99');
insert into prigrizek (ime, cena) values ('Plate Pie Foil', '€4,10');
insert into prigrizek (ime, cena) values ('Oil - Cooking Spray', '€1,54');
insert into prigrizek (ime, cena) values ('Shrimp, Dried, Small / Lb', '€2,81');
insert into prigrizek (ime, cena) values ('Iced Tea - Lemon, 460 Ml', '€0,33');
insert into prigrizek (ime, cena) values ('Oyster - In Shell', '€3,87');
insert into prigrizek (ime, cena) values ('Pie Shells 10', '€2,54');
insert into prigrizek (ime, cena) values ('Flour - Strong Pizza', '€3,11');
insert into prigrizek (ime, cena) values ('Beef - Bresaola', '€2,72');
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Cab Sauv', '€1,74');
insert into prigrizek (ime, cena) values ('Garlic', '€4,14');
insert into prigrizek (ime, cena) values ('Pepper - Paprika, Spanish', '€4,40');
insert into prigrizek (ime, cena) values ('Bread - Rolls, Rye', '€2,43');
insert into prigrizek (ime, cena) values ('Bag Stand', '€0,75');
insert into prigrizek (ime, cena) values ('Cheese Cloth No 100', '€0,13');
insert into prigrizek (ime, cena) values ('Oil - Margarine', '€3,21');
insert into prigrizek (ime, cena) values ('Tomatoes - Yellow Hot House', '€4,23');
insert into prigrizek (ime, cena) values ('Flour - Corn, Fine', '€3,98');
insert into prigrizek (ime, cena) values ('Fish - Halibut, Cold Smoked', '€3,47');
insert into prigrizek (ime, cena) values ('Coffee - 10oz Cup 92961', '€1,63');
insert into prigrizek (ime, cena) values ('Tamarind Paste', '€2,08');
insert into prigrizek (ime, cena) values ('Pepper - Cubanelle', '€0,29');
insert into prigrizek (ime, cena) values ('Crab - Claws, Snow 16 - 24', '€2,68');
insert into prigrizek (ime, cena) values ('Sherbet - Raspberry', '€0,46');
insert into prigrizek (ime, cena) values ('Soup - Campbells, Chix Gumbo', '€3,11');
insert into prigrizek (ime, cena) values ('Flour Pastry Super Fine', '€3,60');
insert into prigrizek (ime, cena) values ('Flower - Daisies', '€0,17');
insert into prigrizek (ime, cena) values ('Cornstarch', '€3,57');
insert into prigrizek (ime, cena) values ('Praline Paste', '€1,54');
insert into prigrizek (ime, cena) values ('Sugar - Brown', '€1,73');
insert into prigrizek (ime, cena) values ('Cauliflower', '€1,82');
insert into prigrizek (ime, cena) values ('Rosemary - Primerba, Paste', '€1,94');
insert into prigrizek (ime, cena) values ('Jameson - Irish Whiskey', '€0,02');
insert into prigrizek (ime, cena) values ('Lid - 0090 Clear', '€2,05');
insert into prigrizek (ime, cena) values ('Cake - Pancake', '€4,53');
insert into prigrizek (ime, cena) values ('Wine - Vineland Estate Semi - Dry', '€2,16');
insert into prigrizek (ime, cena) values ('Cactus Pads', '€4,01');
insert into prigrizek (ime, cena) values ('Soup Campbells Split Pea And Ham', '€4,61');
insert into prigrizek (ime, cena) values ('Lemonade - Island Tea, 591 Ml', '€2,18');
insert into prigrizek (ime, cena) values ('Wine - Saint Emilion Calvet', '€2,10');
insert into prigrizek (ime, cena) values ('Longos - Grilled Chicken With', '€3,66');
insert into prigrizek (ime, cena) values ('Shichimi Togarashi Peppeers', '€4,72');
insert into prigrizek (ime, cena) values ('Tomato - Peeled Italian Canned', '€0,24');
insert into prigrizek (ime, cena) values ('Coconut - Creamed, Pure', '€0,00');
insert into prigrizek (ime, cena) values ('Bols Melon Liqueur', '€0,36');
insert into prigrizek (ime, cena) values ('Vermouth - White, Cinzano', '€0,41');
insert into prigrizek (ime, cena) values ('Beer - Pilsner Urquell', '€2,16');
insert into prigrizek (ime, cena) values ('Grapefruit - White', '€1,91');
insert into prigrizek (ime, cena) values ('Wine - Chianti Classico Riserva', '€4,55');
insert into prigrizek (ime, cena) values ('French Kiss Vanilla', '€2,64');
insert into prigrizek (ime, cena) values ('Tomato Puree', '€3,87');
insert into prigrizek (ime, cena) values ('Muffin - Mix - Creme Brule 15l', '€1,17');
insert into prigrizek (ime, cena) values ('Browning Caramel Glace', '€1,91');
insert into prigrizek (ime, cena) values ('Wine - Ej Gallo Sierra Valley', '€0,86');
insert into prigrizek (ime, cena) values ('Cake Slab', '€1,01');
insert into prigrizek (ime, cena) values ('Nut - Almond, Blanched, Ground', '€2,70');
insert into prigrizek (ime, cena) values ('Garlic - Primerba, Paste', '€3,68');
insert into prigrizek (ime, cena) values ('Kellogs Raisan Bran Bars', '€2,11');
insert into prigrizek (ime, cena) values ('Soup - Campbells Mac N Cheese', '€0,51');
insert into prigrizek (ime, cena) values ('Sage - Fresh', '€0,89');
insert into prigrizek (ime, cena) values ('Foie Gras', '€1,62');
insert into prigrizek (ime, cena) values ('Tomatoes - Vine Ripe, Red', '€3,66');
insert into prigrizek (ime, cena) values ('Dried Cranberries', '€3,51');
insert into prigrizek (ime, cena) values ('Seaweed Green Sheets', '€3,50');
insert into prigrizek (ime, cena) values ('Ecolab - Hand Soap Form Antibac', '€0,90');
insert into prigrizek (ime, cena) values ('Chickensplit Half', '€3,29');
insert into prigrizek (ime, cena) values ('Sauce - Plum', '€0,87');
insert into prigrizek (ime, cena) values ('Soup - French Onion', '€3,83');
insert into prigrizek (ime, cena) values ('Glove - Cutting', '€4,99');
insert into prigrizek (ime, cena) values ('Lamb Rack - Ontario', '€4,09');
insert into prigrizek (ime, cena) values ('Absolut Citron', '€0,85');
insert into prigrizek (ime, cena) values ('Oil - Olive', '€0,15');
insert into prigrizek (ime, cena) values ('Vaccum Bag - 14x20', '€2,57');
insert into prigrizek (ime, cena) values ('Petit Baguette', '€1,08');
insert into prigrizek (ime, cena) values ('Cattail Hearts', '€1,33');
insert into prigrizek (ime, cena) values ('Jam - Apricot', '€1,95');
insert into prigrizek (ime, cena) values ('Garbage Bag - Clear', '€2,51');
insert into prigrizek (ime, cena) values ('Snapple - Iced Tea Peach', '€2,20');
insert into prigrizek (ime, cena) values ('Lady Fingers', '€4,00');
insert into prigrizek (ime, cena) values ('Strawberries', '€1,23');
insert into prigrizek (ime, cena) values ('Cookie Dough - Peanut Butter', '€0,60');
insert into prigrizek (ime, cena) values ('Soy Protein', '€2,09');
insert into prigrizek (ime, cena) values ('Soup - Campbells, Chix Gumbo', '€1,15');
insert into prigrizek (ime, cena) values ('Pasta - Cheese / Spinach Bauletti', '€4,77');
insert into prigrizek (ime, cena) values ('Ecolab Digiclean Mild Fm', '€0,02');
insert into prigrizek (ime, cena) values ('Wine - Rosso Toscano Igt', '€3,73');
insert into prigrizek (ime, cena) values ('Pork - Tenderloin, Frozen', '€0,18');
insert into prigrizek (ime, cena) values ('Muffins - Assorted', '€0,83');
insert into prigrizek (ime, cena) values ('Muffins - Assorted', '€4,75');
insert into prigrizek (ime, cena) values ('Wine - Manischewitz Concord', '€1,01');
insert into prigrizek (ime, cena) values ('Oats Large Flake', '€3,53');
insert into prigrizek (ime, cena) values ('Flavouring - Rum', '€2,62');
insert into prigrizek (ime, cena) values ('Spoon - Soup, Plastic', '€0,39');
insert into prigrizek (ime, cena) values ('Shrimp - Prawn', '€3,84');
insert into prigrizek (ime, cena) values ('Spinach - Frozen', '€3,17');
insert into prigrizek (ime, cena) values ('Wine - White, Chardonnay', '€0,13');
insert into prigrizek (ime, cena) values ('Onions - Dried, Chopped', '€0,88');
insert into prigrizek (ime, cena) values ('Longos - Cheese Tortellini', '€0,45');
insert into prigrizek (ime, cena) values ('Chambord Royal', '€3,60');
insert into prigrizek (ime, cena) values ('Ginger - Ground', '€3,09');
insert into prigrizek (ime, cena) values ('Jam - Apricot', '€3,85');
insert into prigrizek (ime, cena) values ('Nantucket Apple Juice', '€0,61');
insert into prigrizek (ime, cena) values ('Lamb - Whole Head Off,nz', '€1,72');
insert into prigrizek (ime, cena) values ('Thyme - Dried', '€1,48');
insert into prigrizek (ime, cena) values ('Pickles - Gherkins', '€2,96');
insert into prigrizek (ime, cena) values ('Ecolab - Orange Frc, Cleaner', '€3,60');
insert into prigrizek (ime, cena) values ('Chicken - White Meat With Tender', '€0,83');
insert into prigrizek (ime, cena) values ('Bagelers - Cinn / Brown Sugar', '€0,27');
insert into prigrizek (ime, cena) values ('Tea Leaves - Oolong', '€0,24');
insert into prigrizek (ime, cena) values ('Puree - Strawberry', '€2,48');
insert into prigrizek (ime, cena) values ('Salmon - Canned', '€1,85');
insert into prigrizek (ime, cena) values ('Veal - Bones', '€4,08');
insert into prigrizek (ime, cena) values ('Wine - Shiraz South Eastern', '€2,25');
insert into prigrizek (ime, cena) values ('Dooleys Toffee', '€1,04');
insert into prigrizek (ime, cena) values ('Relish', '€1,06');
insert into prigrizek (ime, cena) values ('Tabasco Sauce, 2 Oz', '€4,79');
insert into prigrizek (ime, cena) values ('Marsala - Sperone, Fine, D.o.c.', '€0,68');
insert into prigrizek (ime, cena) values ('Greens Mustard', '€2,73');
insert into prigrizek (ime, cena) values ('Soup - Campbells Asian Noodle', '€1,58');
insert into prigrizek (ime, cena) values ('Egg - Salad Premix', '€1,39');
insert into prigrizek (ime, cena) values ('Curry Paste - Green Masala', '€0,83');
insert into prigrizek (ime, cena) values ('Wine - Red, Gamay Noir', '€2,28');
insert into prigrizek (ime, cena) values ('Tea - Jasmin Green', '€4,51');
insert into prigrizek (ime, cena) values ('Lamb - Leg, Diced', '€2,57');
insert into prigrizek (ime, cena) values ('Muffin - Bran Ind Wrpd', '€1,35');
insert into prigrizek (ime, cena) values ('Beans - French', '€3,82');
insert into prigrizek (ime, cena) values ('Coconut - Whole', '€3,99');
insert into prigrizek (ime, cena) values ('Coconut - Shredded, Unsweet', '€3,09');
insert into prigrizek (ime, cena) values ('Soup - Campbells Asian Noodle', '€1,97');
insert into prigrizek (ime, cena) values ('Beer - Camerons Cream Ale', '€2,03');
insert into prigrizek (ime, cena) values ('Cups 10oz Trans', '€3,12');
insert into prigrizek (ime, cena) values ('Milk - Chocolate 250 Ml', '€3,11');
insert into prigrizek (ime, cena) values ('Carbonated Water - Wildberry', '€0,03');
insert into prigrizek (ime, cena) values ('Pepper - Orange', '€0,85');
insert into prigrizek (ime, cena) values ('Cheese - Brie,danish', '€2,95');
insert into prigrizek (ime, cena) values ('Sambuca - Ramazzotti', '€3,21');
insert into prigrizek (ime, cena) values ('Cumin - Ground', '€1,03');
insert into prigrizek (ime, cena) values ('Raisin - Dark', '€3,78');
insert into prigrizek (ime, cena) values ('Carbonated Water - Cherry', '€2,97');
insert into prigrizek (ime, cena) values ('Squash - Guords', '€4,98');
insert into prigrizek (ime, cena) values ('Dragon Fruit', '€0,39');
insert into prigrizek (ime, cena) values ('Tea Peppermint', '€1,67');
insert into prigrizek (ime, cena) values ('Cup - 6oz, Foam', '€1,74');
insert into prigrizek (ime, cena) values ('Cheese - Brie, Cups 125g', '€1,41');
insert into prigrizek (ime, cena) values ('Cookie - Oreo 100x2', '€2,75');
insert into prigrizek (ime, cena) values ('Cheese - Comte', '€3,82');
insert into prigrizek (ime, cena) values ('Veal - Brisket, Provimi,bnls', '€0,47');
insert into prigrizek (ime, cena) values ('Shrimp - Baby, Cold Water', '€1,73');
insert into prigrizek (ime, cena) values ('Cheese - Swiss', '€4,29');
insert into prigrizek (ime, cena) values ('Melon - Watermelon, Seedless', '€4,29');
insert into prigrizek (ime, cena) values ('Rappini - Andy Boy', '€4,61');
insert into prigrizek (ime, cena) values ('Pasta - Lasagna, Dry', '€3,00');
insert into prigrizek (ime, cena) values ('Food Colouring - Orange', '€4,29');
insert into prigrizek (ime, cena) values ('Mountain Dew', '€4,03');
insert into prigrizek (ime, cena) values ('Cheese - Cheddar, Old White', '€3,33');
insert into prigrizek (ime, cena) values ('Beer - Maudite', '€1,78');
insert into prigrizek (ime, cena) values ('Plastic Wrap', '€1,37');
insert into prigrizek (ime, cena) values ('Pasta - Rotini, Colour, Dry', '€3,58');
insert into prigrizek (ime, cena) values ('Straws - Cocktale', '€2,51');
insert into prigrizek (ime, cena) values ('Veal - Inside', '€1,79');
insert into prigrizek (ime, cena) values ('Sea Bass - Fillets', '€3,30');
insert into prigrizek (ime, cena) values ('Chicken Thigh - Bone Out', '€4,04');
insert into prigrizek (ime, cena) values ('Cauliflower', '€4,76');
insert into prigrizek (ime, cena) values ('Wine - Alicanca Vinho Verde', '€1,86');
insert into prigrizek (ime, cena) values ('Tuna - Loin', '€4,22');
insert into prigrizek (ime, cena) values ('Turkey - Ground. Lean', '€0,73');
insert into prigrizek (ime, cena) values ('Cheese - Brie,danish', '€1,62');
insert into prigrizek (ime, cena) values ('Flour - Corn, Fine', '€3,51');
insert into prigrizek (ime, cena) values ('Ginger - Fresh', '€3,26');
insert into prigrizek (ime, cena) values ('Cherries - Maraschino,jar', '€1,81');
insert into prigrizek (ime, cena) values ('Water - Mineral, Carbonated', '€2,62');
insert into prigrizek (ime, cena) values ('Wine - Fontanafredda Barolo', '€4,44');
insert into prigrizek (ime, cena) values ('Pastry - Mini French Pastries', '€4,18');
insert into prigrizek (ime, cena) values ('Sprouts - Onion', '€4,62');
insert into prigrizek (ime, cena) values ('Cup - 8oz Coffee Perforated', '€1,56');
insert into prigrizek (ime, cena) values ('Squash - Pepper', '€4,63');
insert into prigrizek (ime, cena) values ('Orange Roughy 6/8 Oz', '€0,44');
insert into prigrizek (ime, cena) values ('Soup - Base Broth Beef', '€1,30');
insert into prigrizek (ime, cena) values ('Cookie Dough - Oatmeal Rasin', '€1,08');
insert into prigrizek (ime, cena) values ('Pepper - White, Whole', '€1,46');
insert into prigrizek (ime, cena) values ('Wine - Redchard Merritt', '€0,90');
insert into prigrizek (ime, cena) values ('Chocolate - Pistoles, Lactee, Milk', '€3,41');
insert into prigrizek (ime, cena) values ('Juice - Ocean Spray Cranberry', '€4,95');
insert into prigrizek (ime, cena) values ('Sambuca - Opal Nera', '€4,10');
insert into prigrizek (ime, cena) values ('Calaloo', '€4,46');
insert into prigrizek (ime, cena) values ('Flower - Carnations', '€1,10');
insert into prigrizek (ime, cena) values ('The Pop Shoppe - Root Beer', '€0,17');
insert into prigrizek (ime, cena) values ('Godiva White Chocolate', '€4,90');
insert into prigrizek (ime, cena) values ('Salt - Celery', '€0,36');
insert into prigrizek (ime, cena) values ('Chinese Foods - Chicken Wing', '€2,18');
insert into prigrizek (ime, cena) values ('Mushrooms - Black, Dried', '€2,09');
insert into prigrizek (ime, cena) values ('Flower - Dish Garden', '€1,08');
insert into prigrizek (ime, cena) values ('Lamb - Whole, Frozen', '€2,22');
insert into prigrizek (ime, cena) values ('Nestea - Ice Tea, Diet', '€0,21');
insert into prigrizek (ime, cena) values ('Pasta - Tortellini, Fresh', '€3,33');
insert into prigrizek (ime, cena) values ('Bread - Olive Dinner Roll', '€4,84');
insert into prigrizek (ime, cena) values ('Tart - Raisin And Pecan', '€4,26');
insert into prigrizek (ime, cena) values ('Vanilla Beans', '€4,30');
insert into prigrizek (ime, cena) values ('Honey - Comb', '€4,18');
insert into prigrizek (ime, cena) values ('Milk - Homo', '€1,72');
insert into prigrizek (ime, cena) values ('Cheese - Cheddar, Mild', '€2,56');
insert into prigrizek (ime, cena) values ('Trueblue - Blueberry', '€0,04');
insert into prigrizek (ime, cena) values ('Turkey Leg With Drum And Thigh', '€2,04');
insert into prigrizek (ime, cena) values ('Thyme - Dried', '€3,35');
insert into prigrizek (ime, cena) values ('Lettuce - Treviso', '€3,81');
insert into prigrizek (ime, cena) values ('Grapes - Green', '€0,35');
insert into prigrizek (ime, cena) values ('Swiss Chard - Red', '€1,67');
insert into prigrizek (ime, cena) values ('Salt - Rock, Course', '€0,51');
insert into prigrizek (ime, cena) values ('Lettuce Romaine Chopped', '€0,23');
insert into prigrizek (ime, cena) values ('Yogurt - Strawberry, 175 Gr', '€1,96');
insert into prigrizek (ime, cena) values ('Tart - Lemon', '€0,19');
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Bel Paese White', '€3,97');
insert into prigrizek (ime, cena) values ('Pork - Sausage, Medium', '€1,18');
insert into prigrizek (ime, cena) values ('Cookies - Amaretto', '€2,64');
insert into prigrizek (ime, cena) values ('Coffee - Ristretto Coffee Capsule', '€3,30');
insert into prigrizek (ime, cena) values ('Corn - On The Cob', '€4,35');
insert into prigrizek (ime, cena) values ('Chocolate Eclairs', '€2,42');
insert into prigrizek (ime, cena) values ('Beer - Steamwhistle', '€2,01');
insert into prigrizek (ime, cena) values ('Huck Towels White', '€1,28');
insert into prigrizek (ime, cena) values ('Wine - Ej Gallo Sonoma', '€2,16');
insert into prigrizek (ime, cena) values ('Blouse / Shirt / Sweater', '€3,18');
insert into prigrizek (ime, cena) values ('Mushroom - Shitake, Fresh', '€0,94');
insert into prigrizek (ime, cena) values ('Cheese - Ricotta', '€4,23');
insert into prigrizek (ime, cena) values ('Blueberries', '€4,43');
insert into prigrizek (ime, cena) values ('Beans - French', '€0,83');
insert into prigrizek (ime, cena) values ('Crackers - Melba Toast', '€1,32');
insert into prigrizek (ime, cena) values ('Chocolate - Chips Compound', '€1,23');
insert into prigrizek (ime, cena) values ('Glaze - Apricot', '€4,64');
insert into prigrizek (ime, cena) values ('Neckerchief Blck', '€1,73');
insert into prigrizek (ime, cena) values ('Nantuket Peach Orange', '€3,44');
insert into prigrizek (ime, cena) values ('Artichokes - Knobless, White', '€1,66');
insert into prigrizek (ime, cena) values ('Pork - Back, Long Cut, Boneless', '€1,57');
insert into prigrizek (ime, cena) values ('Juice - Apple, 1.36l', '€1,47');
insert into prigrizek (ime, cena) values ('Rice - Sushi', '€3,27');
insert into prigrizek (ime, cena) values ('Soup - Campbellschix Stew', '€4,97');
insert into prigrizek (ime, cena) values ('Beans - Kidney White', '€3,02');
insert into prigrizek (ime, cena) values ('Cheese - Havarti, Roasted Garlic', '€4,88');
insert into prigrizek (ime, cena) values ('Chicken - Leg / Back Attach', '€3,52');
insert into prigrizek (ime, cena) values ('Sauce - Oyster', '€0,71');
insert into prigrizek (ime, cena) values ('Wine - Red, Black Opal Shiraz', '€3,57');
insert into prigrizek (ime, cena) values ('Tea - Green', '€4,32');
insert into prigrizek (ime, cena) values ('Ice - Clear, 300 Lb For Carving', '€3,10');
insert into prigrizek (ime, cena) values ('Soup - Verve - Chipotle Chicken', '€2,26');
insert into prigrizek (ime, cena) values ('Yokaline', '€2,34');
insert into prigrizek (ime, cena) values ('Wine - Harrow Estates, Vidal', '€0,58');
insert into prigrizek (ime, cena) values ('Yeast - Fresh, Fleischman', '€5,00');
insert into prigrizek (ime, cena) values ('Cumin - Ground', '€2,52');
insert into prigrizek (ime, cena) values ('Nantuket Peach Orange', '€1,26');
insert into prigrizek (ime, cena) values ('Kiwi Gold Zespri', '€2,26');
insert into prigrizek (ime, cena) values ('Ice Cream - Strawberry', '€0,58');
insert into prigrizek (ime, cena) values ('Rappini - Andy Boy', '€2,04');
insert into prigrizek (ime, cena) values ('Beef - Tender Tips', '€2,64');
insert into prigrizek (ime, cena) values ('Stock - Beef, Brown', '€4,15');
insert into prigrizek (ime, cena) values ('Cheese - Victor Et Berthold', '€0,48');
insert into prigrizek (ime, cena) values ('Kippers - Smoked', '€1,43');
insert into prigrizek (ime, cena) values ('Pork - Ground', '€0,51');
insert into prigrizek (ime, cena) values ('Nut - Hazelnut, Whole', '€4,57');
insert into prigrizek (ime, cena) values ('Gherkin', '€2,47');
insert into prigrizek (ime, cena) values ('The Pop Shoppe - Cream Soda', '€2,95');
insert into prigrizek (ime, cena) values ('Chips Potato All Dressed - 43g', '€1,40');
insert into prigrizek (ime, cena) values ('Pepper - Black, Ground', '€0,76');
insert into prigrizek (ime, cena) values ('Chicken - Whole', '€1,80');
insert into prigrizek (ime, cena) values ('Nut - Pecan, Halves', '€1,54');
insert into prigrizek (ime, cena) values ('Smirnoff Green Apple Twist', '€0,66');
insert into prigrizek (ime, cena) values ('Shrimp, Dried, Small / Lb', '€2,66');
insert into prigrizek (ime, cena) values ('Daves Island Stinger', '€2,34');
insert into prigrizek (ime, cena) values ('Lamb - Shoulder, Boneless', '€1,68');
insert into prigrizek (ime, cena) values ('Soup Campbells Mexicali Tortilla', '€3,24');
insert into prigrizek (ime, cena) values ('Bag - Clear 7 Lb', '€0,74');
insert into prigrizek (ime, cena) values ('Tumeric', '€1,88');
insert into prigrizek (ime, cena) values ('Creme De Cacao Mcguines', '€3,98');
insert into prigrizek (ime, cena) values ('Towel Multifold', '€2,82');
insert into prigrizek (ime, cena) values ('Trout - Hot Smkd, Dbl Fillet', '€3,61');
insert into prigrizek (ime, cena) values ('Wine - Crozes Hermitage E.', '€0,71');
insert into prigrizek (ime, cena) values ('Beer - Guiness', '€0,87');
insert into prigrizek (ime, cena) values ('Beef - Prime Rib Aaa', '€3,52');
insert into prigrizek (ime, cena) values ('The Pop Shoppe - Black Cherry', '€2,33');
insert into prigrizek (ime, cena) values ('Table Cloth 91x91 Colour', '€1,86');
insert into prigrizek (ime, cena) values ('Smoked Tongue', '€1,17');
insert into prigrizek (ime, cena) values ('Bagel - Everything Presliced', '€3,62');
insert into prigrizek (ime, cena) values ('Pork - Back Ribs', '€2,82');
insert into prigrizek (ime, cena) values ('Lid - High Heat, Super Clear', '€3,30');
insert into prigrizek (ime, cena) values ('Mushrooms - Black, Dried', '€1,70');
insert into prigrizek (ime, cena) values ('Flour Pastry Super Fine', '€0,52');
insert into prigrizek (ime, cena) values ('Ecolab Silver Fusion', '€2,87');
insert into prigrizek (ime, cena) values ('Piping Jelly - All Colours', '€1,59');
insert into prigrizek (ime, cena) values ('Longos - Chicken Wings', '€3,31');
insert into prigrizek (ime, cena) values ('Bread Base - Gold Formel', '€0,78');
insert into prigrizek (ime, cena) values ('Sprouts - Bean', '€0,78');
insert into prigrizek (ime, cena) values ('Soup Campbells Mexicali Tortilla', '€0,03');
insert into prigrizek (ime, cena) values ('Cheese - Brick With Onion', '€0,31');
insert into prigrizek (ime, cena) values ('Napkin - Beverage 1 Ply', '€4,07');
insert into prigrizek (ime, cena) values ('Appetizer - Asian Shrimp Roll', '€2,89');
insert into prigrizek (ime, cena) values ('Cheese - Brie, Triple Creme', '€4,90');
insert into prigrizek (ime, cena) values ('Tuna - Sushi Grade', '€0,89');
insert into prigrizek (ime, cena) values ('Extract - Rum', '€0,31');
insert into prigrizek (ime, cena) values ('Sugar - White Packet', '€4,66');
insert into prigrizek (ime, cena) values ('Bread - Pita', '€3,21');
insert into prigrizek (ime, cena) values ('Tart Shells - Savory, 4', '€0,10');
insert into prigrizek (ime, cena) values ('Wine - White, Antinore Orvieto', '€3,13');
insert into prigrizek (ime, cena) values ('Cheese - Victor Et Berthold', '€4,29');
insert into prigrizek (ime, cena) values ('Energy Drink Bawls', '€0,94');
insert into prigrizek (ime, cena) values ('Beef Flat Iron Steak', '€0,86');
insert into prigrizek (ime, cena) values ('Pasta - Lasagna, Dry', '€4,33');
insert into prigrizek (ime, cena) values ('Sauce Bbq Smokey', '€4,66');
insert into prigrizek (ime, cena) values ('Mushroom - King Eryingii', '€3,98');
insert into prigrizek (ime, cena) values ('Pears - Bosc', '€0,53');
insert into prigrizek (ime, cena) values ('Juice Peach Nectar', '€3,04');
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Belpaese', '€4,54');
insert into prigrizek (ime, cena) values ('Cauliflower', '€0,81');
insert into prigrizek (ime, cena) values ('Irish Cream - Butterscotch', '€4,10');
insert into prigrizek (ime, cena) values ('Huck White Towels', '€0,23');
insert into prigrizek (ime, cena) values ('Soup Campbells - Tomato Bisque', '€4,29');
insert into prigrizek (ime, cena) values ('Wine - George Duboeuf Rose', '€4,76');
insert into prigrizek (ime, cena) values ('Pork - European Side Bacon', '€4,21');
insert into prigrizek (ime, cena) values ('Fruit Mix - Light', '€1,79');
insert into prigrizek (ime, cena) values ('Macaroons - Homestyle Two Bit', '€4,23');
insert into prigrizek (ime, cena) values ('Lemonade - Strawberry, 591 Ml', '€4,58');
insert into prigrizek (ime, cena) values ('Icecream - Dibs', '€0,19');
insert into prigrizek (ime, cena) values ('Sauce - Oyster', '€3,34');
insert into prigrizek (ime, cena) values ('Compound - Pear', '€0,10');
insert into prigrizek (ime, cena) values ('Ranchero - Primerba, Paste', '€2,64');
insert into prigrizek (ime, cena) values ('Crab - Claws, 26 - 30', '€2,67');
insert into prigrizek (ime, cena) values ('Pork - Side Ribs', '€2,99');
insert into prigrizek (ime, cena) values ('Island Oasis - Banana Daiquiri', '€0,28');
insert into prigrizek (ime, cena) values ('Water - Evian 355 Ml', '€2,28');
insert into prigrizek (ime, cena) values ('Lettuce - Lolla Rosa', '€1,37');
insert into prigrizek (ime, cena) values ('Ice Cream - Chocolate', '€1,32');
insert into prigrizek (ime, cena) values ('Chocolate Bar - Oh Henry', '€1,67');
insert into prigrizek (ime, cena) values ('Nantucket - Pomegranate Pear', '€4,70');
insert into prigrizek (ime, cena) values ('Crab - Claws, Snow 16 - 24', '€0,16');
insert into prigrizek (ime, cena) values ('Wine - Remy Pannier Rose', '€0,60');
insert into prigrizek (ime, cena) values ('Cranberries - Dry', '€3,48');
insert into prigrizek (ime, cena) values ('Wine - Rosso Del Veronese Igt', '€2,81');
insert into prigrizek (ime, cena) values ('Ice Cream - Turtles Stick Bar', '€1,34');
insert into prigrizek (ime, cena) values ('Tortillas - Flour, 8', '€0,54');
insert into prigrizek (ime, cena) values ('Turkey - Breast, Bone - In', '€0,60');
insert into prigrizek (ime, cena) values ('Figs', '€1,18');
insert into prigrizek (ime, cena) values ('Kiwi Gold Zespri', '€3,52');
insert into prigrizek (ime, cena) values ('Cookie Chocolate Chip With', '€0,49');
insert into prigrizek (ime, cena) values ('Pork - Kidney', '€0,88');
insert into prigrizek (ime, cena) values ('Fish - Atlantic Salmon, Cold', '€0,97');
insert into prigrizek (ime, cena) values ('Calypso - Black Cherry Lemonade', '€2,96');
insert into prigrizek (ime, cena) values ('Longos - Chicken Wings', '€2,41');
insert into prigrizek (ime, cena) values ('Beer - Steamwhistle', '€3,97');
insert into prigrizek (ime, cena) values ('Ginsing - Fresh', '€1,75');
insert into prigrizek (ime, cena) values ('Ice Cream - Strawberry', '€0,55');
insert into prigrizek (ime, cena) values ('Star Anise, Whole', '€3,39');
insert into prigrizek (ime, cena) values ('Ecolab - Ster Bac', '€3,59');
insert into prigrizek (ime, cena) values ('Chocolate - Sugar Free Semi Choc', '€4,85');
insert into prigrizek (ime, cena) values ('Bay Leaf Ground', '€3,39');
insert into prigrizek (ime, cena) values ('Ice Cream - Strawberry', '€2,54');
insert into prigrizek (ime, cena) values ('Apricots - Halves', '€1,46');
insert into prigrizek (ime, cena) values ('Beans - Green', '€0,43');
insert into prigrizek (ime, cena) values ('Lemonade - Natural, 591 Ml', '€3,74');
insert into prigrizek (ime, cena) values ('Cup - 6oz, Foam', '€3,38');
insert into prigrizek (ime, cena) values ('Pie Shell - 5', '€1,18');
insert into prigrizek (ime, cena) values ('Glucose', '€4,29');
insert into prigrizek (ime, cena) values ('Wine - Blue Nun Qualitatswein', '€2,84');
insert into prigrizek (ime, cena) values ('Cocoa Powder - Natural', '€2,66');
insert into prigrizek (ime, cena) values ('Lettuce - California Mix', '€2,95');
insert into prigrizek (ime, cena) values ('Syrup - Kahlua Chocolate', '€2,97');
insert into prigrizek (ime, cena) values ('Soap - Pine Sol Floor Cleaner', '€1,27');
insert into prigrizek (ime, cena) values ('Soup V8 Roasted Red Pepper', '€0,00');
insert into prigrizek (ime, cena) values ('Flower - Leather Leaf Fern', '€4,54');
insert into prigrizek (ime, cena) values ('Stock - Beef, White', '€0,56');
insert into prigrizek (ime, cena) values ('Lobster - Base', '€0,29');
insert into prigrizek (ime, cena) values ('Tomatoes - Orange', '€0,23');
insert into prigrizek (ime, cena) values ('Sauce - Fish 25 Ozf Bottle', '€2,29');
insert into prigrizek (ime, cena) values ('Beef - Short Loin', '€3,12');
insert into prigrizek (ime, cena) values ('Red Cod Fillets - 225g', '€0,25');
insert into prigrizek (ime, cena) values ('Appetizer - Seafood Assortment', '€3,47');
insert into prigrizek (ime, cena) values ('Soap - Hand Soap', '€1,77');
insert into prigrizek (ime, cena) values ('Sardines', '€3,25');
insert into prigrizek (ime, cena) values ('Wine - Merlot Vina Carmen', '€0,92');
insert into prigrizek (ime, cena) values ('Shichimi Togarashi Peppeers', '€1,29');
insert into prigrizek (ime, cena) values ('Bread Sour Rolls', '€2,30');
insert into prigrizek (ime, cena) values ('Assorted Desserts', '€3,85');
insert into prigrizek (ime, cena) values ('Beans - Fava, Canned', '€2,93');
insert into prigrizek (ime, cena) values ('Salt - Seasoned', '€4,62');
insert into prigrizek (ime, cena) values ('Tomatoes Tear Drop Yellow', '€1,05');
insert into prigrizek (ime, cena) values ('Juice - Cranberry 284ml', '€1,17');
insert into prigrizek (ime, cena) values ('Pie Filling - Cherry', '€1,28');
insert into prigrizek (ime, cena) values ('Seedlings - Buckwheat, Organic', '€4,58');
insert into prigrizek (ime, cena) values ('Red Cod Fillets - 225g', '€4,46');
insert into prigrizek (ime, cena) values ('Sauce - Demi Glace', '€0,36');
insert into prigrizek (ime, cena) values ('Pasta - Rotini, Colour, Dry', '€3,51');
insert into prigrizek (ime, cena) values ('Soupcontfoam16oz 116con', '€2,28');
insert into prigrizek (ime, cena) values ('Cheese - Gouda', '€0,95');
insert into prigrizek (ime, cena) values ('Bread - Rolls, Rye', '€0,97');
insert into prigrizek (ime, cena) values ('Flour - Chickpea', '€1,18');
insert into prigrizek (ime, cena) values ('Halibut - Whole, Fresh', '€0,00');
insert into prigrizek (ime, cena) values ('Bread Base - Italian', '€1,08');
insert into prigrizek (ime, cena) values ('Myers Planters Punch', '€1,17');
insert into prigrizek (ime, cena) values ('Wine - Clavet Saint Emilion', '€4,84');
insert into prigrizek (ime, cena) values ('Wild Boar - Tenderloin', '€2,12');
insert into prigrizek (ime, cena) values ('Syrup - Pancake', '€2,64');
insert into prigrizek (ime, cena) values ('Nantucket - Orange Mango Cktl', '€0,21');
insert into prigrizek (ime, cena) values ('Syrup - Golden, Lyles', '€4,49');
insert into prigrizek (ime, cena) values ('Crush - Grape, 355 Ml', '€1,89');
insert into prigrizek (ime, cena) values ('Trout - Rainbow, Frozen', '€2,04');
insert into prigrizek (ime, cena) values ('Ecolab - Orange Frc, Cleaner', '€1,57');
insert into prigrizek (ime, cena) values ('Pepper - Red Chili', '€2,25');
insert into prigrizek (ime, cena) values ('Cake - Cake Sheet Macaroon', '€1,40');
insert into prigrizek (ime, cena) values ('Bag - Clear 7 Lb', '€0,21');
insert into prigrizek (ime, cena) values ('Cauliflower', '€3,50');
insert into prigrizek (ime, cena) values ('Hold Up Tool Storage Rack', '€1,97');
insert into prigrizek (ime, cena) values ('Beef - Tongue, Cooked', '€0,41');
insert into prigrizek (ime, cena) values ('Mini - Vol Au Vents', '€0,99');
insert into prigrizek (ime, cena) values ('Dried Apple', '€1,87');
insert into prigrizek (ime, cena) values ('Whmis - Spray Bottle Trigger', '€3,35');
insert into prigrizek (ime, cena) values ('Oven Mitts - 15 Inch', '€3,81');
insert into prigrizek (ime, cena) values ('Parsley Italian - Fresh', '€3,44');
insert into prigrizek (ime, cena) values ('Yeast - Fresh, Fleischman', '€1,47');
insert into prigrizek (ime, cena) values ('Beans - Soya Bean', '€2,95');
insert into prigrizek (ime, cena) values ('Carrots - Purple, Organic', '€0,92');
insert into prigrizek (ime, cena) values ('Grouper - Fresh', '€2,44');
insert into prigrizek (ime, cena) values ('Cherries - Bing, Canned', '€4,78');
insert into prigrizek (ime, cena) values ('Cream Of Tartar', '€2,79');
insert into prigrizek (ime, cena) values ('Puree - Passion Fruit', '€0,02');
insert into prigrizek (ime, cena) values ('Aspic - Amber', '€3,42');
insert into prigrizek (ime, cena) values ('Mustard Prepared', '€2,65');
insert into prigrizek (ime, cena) values ('Tomatoes Tear Drop', '€3,43');
insert into prigrizek (ime, cena) values ('Veal - Leg', '€4,45');
insert into prigrizek (ime, cena) values ('Canadian Emmenthal', '€1,45');
insert into prigrizek (ime, cena) values ('Pumpkin - Seed', '€0,44');
insert into prigrizek (ime, cena) values ('Lamb - Whole, Frozen', '€0,88');
insert into prigrizek (ime, cena) values ('Grenadillo', '€0,24');
insert into prigrizek (ime, cena) values ('Kaffir Lime Leaves', '€0,49');
insert into prigrizek (ime, cena) values ('Wanton Wrap', '€4,50');
insert into prigrizek (ime, cena) values ('Artichoke - Fresh', '€2,02');
insert into prigrizek (ime, cena) values ('Sauce - Balsamic Viniagrette', '€3,64');
insert into prigrizek (ime, cena) values ('Vinegar - Champagne', '€3,82');
insert into prigrizek (ime, cena) values ('Lettuce - Curly Endive', '€2,55');
insert into prigrizek (ime, cena) values ('Icecream Bar - Del Monte', '€2,65');
insert into prigrizek (ime, cena) values ('Lobster - Canned Premium', '€2,66');
insert into prigrizek (ime, cena) values ('Beer - Camerons Cream Ale', '€3,12');
insert into prigrizek (ime, cena) values ('Tea - Orange Pekoe', '€2,31');
insert into prigrizek (ime, cena) values ('Flower - Commercial Spider', '€2,70');
insert into prigrizek (ime, cena) values ('Russian Prince', '€2,30');
insert into prigrizek (ime, cena) values ('Capers - Pickled', '€2,60');
insert into prigrizek (ime, cena) values ('Sun - Dried Tomatoes', '€1,91');
insert into prigrizek (ime, cena) values ('Nut - Pecan, Pieces', '€0,57');
insert into prigrizek (ime, cena) values ('Cup - 3.5oz, Foam', '€3,16');
insert into prigrizek (ime, cena) values ('Muffin Batt - Blueberry Passion', '€0,34');
insert into prigrizek (ime, cena) values ('Wine - Pinot Noir Pond Haddock', '€0,31');
insert into prigrizek (ime, cena) values ('Beans - Fine', '€4,78');
insert into prigrizek (ime, cena) values ('Vanilla Beans', '€3,83');
insert into prigrizek (ime, cena) values ('Butter - Salted, Micro', '€0,69');
insert into prigrizek (ime, cena) values ('Fish - Soup Base, Bouillon', '€2,57');
insert into prigrizek (ime, cena) values ('Juice - Apple, 341 Ml', '€3,19');
insert into prigrizek (ime, cena) values ('Wasabi Powder', '€4,14');
insert into prigrizek (ime, cena) values ('Beef Dry Aged Tenderloin Aaa', '€4,40');
insert into prigrizek (ime, cena) values ('Asparagus - Green, Fresh', '€0,95');
insert into prigrizek (ime, cena) values ('Thyme - Dried', '€4,81');
insert into prigrizek (ime, cena) values ('Beer - Blue', '€3,08');
insert into prigrizek (ime, cena) values ('Soup Bowl Clear 8oz92008', '€2,03');
insert into prigrizek (ime, cena) values ('Instant Coffee', '€3,61');
insert into prigrizek (ime, cena) values ('Clam - Cherrystone', '€2,05');
insert into prigrizek (ime, cena) values ('Pepper - Red Bell', '€2,84');
insert into prigrizek (ime, cena) values ('Muffin - Carrot Individual Wrap', '€2,10');
insert into prigrizek (ime, cena) values ('Potatoes - Pei 10 Oz', '€3,05');
insert into prigrizek (ime, cena) values ('Beans - Yellow', '€2,58');
insert into prigrizek (ime, cena) values ('Catfish - Fillets', '€0,32');
insert into prigrizek (ime, cena) values ('Mushroom - White Button', '€0,52');
insert into prigrizek (ime, cena) values ('Fennel - Seeds', '€4,71');
insert into prigrizek (ime, cena) values ('Breadfruit', '€1,00');
insert into prigrizek (ime, cena) values ('Bread - Raisin', '€1,58');
insert into prigrizek (ime, cena) values ('Onions - Green', '€1,71');
insert into prigrizek (ime, cena) values ('Sauerkraut', '€3,22');
insert into prigrizek (ime, cena) values ('Jolt Cola', '€2,56');
insert into prigrizek (ime, cena) values ('Wine - Lou Black Shiraz', '€3,28');
insert into prigrizek (ime, cena) values ('Devonshire Cream', '€3,79');
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Cab Sauv', '€2,75');
insert into prigrizek (ime, cena) values ('V8 - Berry Blend', '€4,67');
insert into prigrizek (ime, cena) values ('Tomato Puree', '€3,08');
insert into prigrizek (ime, cena) values ('Glycerine', '€1,99');
insert into prigrizek (ime, cena) values ('Bandage - Flexible Neon', '€3,54');
insert into prigrizek (ime, cena) values ('Beef - Rib Eye Aaa', '€2,72');
insert into prigrizek (ime, cena) values ('Plasticforkblack', '€3,12');
insert into prigrizek (ime, cena) values ('Towel - Roll White', '€2,81');
insert into prigrizek (ime, cena) values ('Seedlings - Clamshell', '€2,42');
insert into prigrizek (ime, cena) values ('Ham Black Forest', '€0,32');
insert into prigrizek (ime, cena) values ('Potatoes - Parissienne', '€3,22');
insert into prigrizek (ime, cena) values ('Muffin Mix - Corn Harvest', '€4,09');
insert into prigrizek (ime, cena) values ('Rice Pilaf, Dry,package', '€1,15');
insert into prigrizek (ime, cena) values ('Garlic - Peeled', '€3,95');
insert into prigrizek (ime, cena) values ('Pastry - Banana Tea Loaf', '€2,19');
insert into prigrizek (ime, cena) values ('Bagelers', '€4,44');
insert into prigrizek (ime, cena) values ('Celery', '€0,10');
insert into prigrizek (ime, cena) values ('Juice - Clamato, 341 Ml', '€4,46');
insert into prigrizek (ime, cena) values ('Lid - 10,12,16 Oz', '€1,88');
insert into prigrizek (ime, cena) values ('Goldschalger', '€4,50');
insert into prigrizek (ime, cena) values ('Monkfish - Fresh', '€0,57');
insert into prigrizek (ime, cena) values ('Pastry - Mini French Pastries', '€0,59');
insert into prigrizek (ime, cena) values ('Pimento - Canned', '€3,14');
insert into prigrizek (ime, cena) values ('Peach - Halves', '€4,56');
insert into prigrizek (ime, cena) values ('Lamb - Leg, Boneless', '€0,78');
insert into prigrizek (ime, cena) values ('Pork - Back Ribs', '€4,08');
insert into prigrizek (ime, cena) values ('Bread - Ciabatta Buns', '€0,77');
insert into prigrizek (ime, cena) values ('Hickory Smoke, Liquid', '€0,10');
insert into prigrizek (ime, cena) values ('Wine - Maipo Valle Cabernet', '€4,13');
insert into prigrizek (ime, cena) values ('Chinese Foods - Chicken Wing', '€1,47');
insert into prigrizek (ime, cena) values ('Bread - Flat Bread', '€1,30');
insert into prigrizek (ime, cena) values ('Kiwano', '€3,76');
insert into prigrizek (ime, cena) values ('Squid - U 5', '€1,41');
insert into prigrizek (ime, cena) values ('Asparagus - Green, Fresh', '€4,85');
insert into prigrizek (ime, cena) values ('Pie Shell - 9', '€3,83');
insert into prigrizek (ime, cena) values ('Flower - Commercial Spider', '€4,67');
insert into prigrizek (ime, cena) values ('Asparagus - Green, Fresh', '€3,09');
insert into prigrizek (ime, cena) values ('Appetizer - Shrimp Puff', '€0,94');
insert into prigrizek (ime, cena) values ('Lamb - Whole Head Off', '€4,79');
insert into prigrizek (ime, cena) values ('Couscous', '€0,14');
insert into prigrizek (ime, cena) values ('Sauce - Alfredo', '€1,45');
insert into prigrizek (ime, cena) values ('Pork - Back, Long Cut, Boneless', '€0,97');
insert into prigrizek (ime, cena) values ('Truffle Shells - White Chocolate', '€4,29');
insert into prigrizek (ime, cena) values ('Wine - Remy Pannier Rose', '€4,10');
insert into prigrizek (ime, cena) values ('Radish - Black, Winter, Organic', '€3,06');
insert into prigrizek (ime, cena) values ('Appetizer - Sausage Rolls', '€0,51');
insert into prigrizek (ime, cena) values ('Pepper - Red Bell', '€0,48');
insert into prigrizek (ime, cena) values ('Sauce - Mint', '€1,45');
insert into prigrizek (ime, cena) values ('Cheese - St. Paulin', '€3,67');
insert into prigrizek (ime, cena) values ('Nut - Cashews, Whole, Raw', '€2,01');
insert into prigrizek (ime, cena) values ('Bread - White Epi Baguette', '€4,13');
insert into prigrizek (ime, cena) values ('Ham - Cooked', '€0,63');
insert into prigrizek (ime, cena) values ('Coffee Caramel Biscotti', '€4,78');
insert into prigrizek (ime, cena) values ('Nut - Almond, Blanched, Ground', '€0,67');
insert into prigrizek (ime, cena) values ('Transfer Sheets', '€1,76');
insert into prigrizek (ime, cena) values ('Wood Chips - Regular', '€0,19');
insert into prigrizek (ime, cena) values ('Rabbit - Whole', '€1,98');
insert into prigrizek (ime, cena) values ('Creme De Menth - White', '€2,72');
insert into prigrizek (ime, cena) values ('Soup - Cream Of Potato / Leek', '€1,73');
insert into prigrizek (ime, cena) values ('Muffin Hinge Container 6', '€3,83');
insert into prigrizek (ime, cena) values ('Flower - Commercial Bronze', '€2,49');
insert into prigrizek (ime, cena) values ('Salmon - Canned', '€0,24');
insert into prigrizek (ime, cena) values ('Tea Peppermint', '€1,76');
insert into prigrizek (ime, cena) values ('Sobe - Green Tea', '€4,46');
insert into prigrizek (ime, cena) values ('Container - Foam Dixie 12 Oz', '€0,79');
insert into prigrizek (ime, cena) values ('Pork - Back, Short Cut, Boneless', '€0,76');
insert into prigrizek (ime, cena) values ('Walkers Special Old Whiskey', '€1,85');
insert into prigrizek (ime, cena) values ('Chilli Paste, Ginger Garlic', '€2,84');
insert into prigrizek (ime, cena) values ('Wine - Sauvignon Blanc', '€1,63');
insert into prigrizek (ime, cena) values ('Soup - Clam Chowder, Dry Mix', '€2,57');
insert into prigrizek (ime, cena) values ('Towels - Paper / Kraft', '€1,59');
insert into prigrizek (ime, cena) values ('Island Oasis - Sweet And Sour Mix', '€2,23');
insert into prigrizek (ime, cena) values ('Corn Meal', '€1,69');
insert into prigrizek (ime, cena) values ('Beef - Short Loin', '€1,85');
insert into prigrizek (ime, cena) values ('Cloves - Whole', '€4,32');
insert into prigrizek (ime, cena) values ('Lambcasing', '€1,28');
insert into prigrizek (ime, cena) values ('Trout - Rainbow, Fresh', '€2,06');
insert into prigrizek (ime, cena) values ('Green Scrubbie Pad H.duty', '€3,51');
insert into prigrizek (ime, cena) values ('Wine - White, Mosel Gold', '€3,93');
insert into prigrizek (ime, cena) values ('Cake Circle, Foil, Scallop', '€4,03');
insert into prigrizek (ime, cena) values ('Napkin Colour', '€1,92');
insert into prigrizek (ime, cena) values ('Yogurt - French Vanilla', '€4,59');
insert into prigrizek (ime, cena) values ('Nantucket - Pomegranate Pear', '€0,32');
insert into prigrizek (ime, cena) values ('Maintenance Removal Charge', '€4,58');
insert into prigrizek (ime, cena) values ('Sausage - Andouille', '€0,47');
insert into prigrizek (ime, cena) values ('Cheese - Cottage Cheese', '€3,21');
insert into prigrizek (ime, cena) values ('Water Chestnut - Canned', '€2,82');
insert into prigrizek (ime, cena) values ('Wine - Two Oceans Cabernet', '€2,30');
insert into prigrizek (ime, cena) values ('C - Plus, Orange', '€1,36');
insert into prigrizek (ime, cena) values ('Flower - Carnations', '€3,12');
insert into prigrizek (ime, cena) values ('Wine - Beaujolais Villages', '€4,16');
insert into prigrizek (ime, cena) values ('Wine - Rubyport', '€3,42');
insert into prigrizek (ime, cena) values ('Wine - Acient Coast Caberne', '€2,94');
insert into prigrizek (ime, cena) values ('Marsala - Sperone, Fine, D.o.c.', '€3,58');
insert into prigrizek (ime, cena) values ('Olives - Nicoise', '€1,68');
insert into prigrizek (ime, cena) values ('Lamb - Whole, Frozen', '€1,49');
insert into prigrizek (ime, cena) values ('Cheese - Perron Cheddar', '€0,78');
insert into prigrizek (ime, cena) values ('Cheese - Brie,danish', '€0,19');
insert into prigrizek (ime, cena) values ('Cake - Cheese Cake 9 Inch', '€2,78');
insert into prigrizek (ime, cena) values ('Potatoes - Purple, Organic', '€4,07');
insert into prigrizek (ime, cena) values ('Carbonated Water - Lemon Lime', '€2,37');
insert into prigrizek (ime, cena) values ('Pepper - Red Chili', '€1,21');
insert into prigrizek (ime, cena) values ('Cheese - Provolone', '€1,08');
insert into prigrizek (ime, cena) values ('Soup - Campbells Pasta Fagioli', '€4,95');
insert into prigrizek (ime, cena) values ('Pork - Loin, Bone - In', '€0,06');
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Belpaese', '€3,56');
insert into prigrizek (ime, cena) values ('Cream - 10%', '€3,23');
insert into prigrizek (ime, cena) values ('Soup - Clam Chowder, Dry Mix', '€4,78');
insert into prigrizek (ime, cena) values ('Appetizer - Veg Assortment', '€4,05');
insert into prigrizek (ime, cena) values ('Bread Crumbs - Japanese Style', '€3,94');
insert into prigrizek (ime, cena) values ('Wine - Port Late Bottled Vintage', '€2,48');
insert into prigrizek (ime, cena) values ('Lobster - Tail 6 Oz', '€2,62');
insert into prigrizek (ime, cena) values ('Chicken - White Meat With Tender', '€2,17');
insert into prigrizek (ime, cena) values ('Puree - Guava', '€2,13');
insert into prigrizek (ime, cena) values ('Artichokes - Knobless, White', '€0,19');
insert into prigrizek (ime, cena) values ('Table Cloth - 53x69 Colour', '€1,33');
insert into prigrizek (ime, cena) values ('Nut - Pecan, Pieces', '€1,24');
insert into prigrizek (ime, cena) values ('Clams - Canned', '€3,78');
insert into prigrizek (ime, cena) values ('Garlic - Peeled', '€3,67');
insert into prigrizek (ime, cena) values ('Wine - Saint - Bris 2002, Sauv', '€4,69');
insert into prigrizek (ime, cena) values ('Fish - Bones', '€4,38');
insert into prigrizek (ime, cena) values ('Lamb Tenderloin Nz Fr', '€4,11');
insert into prigrizek (ime, cena) values ('Broom - Corn', '€1,95');
insert into prigrizek (ime, cena) values ('Trueblue - Blueberry 12x473ml', '€3,61');
insert into prigrizek (ime, cena) values ('Wine - Red, Gamay Noir', '€0,98');
insert into prigrizek (ime, cena) values ('Pastry - Banana Tea Loaf', '€3,23');
insert into prigrizek (ime, cena) values ('Longan', '€2,09');
insert into prigrizek (ime, cena) values ('Longos - Chicken Curried', '€0,62');
insert into prigrizek (ime, cena) values ('Gatorade - Fruit Punch', '€2,55');
insert into prigrizek (ime, cena) values ('Water - Tonic', '€3,40');
insert into prigrizek (ime, cena) values ('Catfish - Fillets', '€0,29');
insert into prigrizek (ime, cena) values ('Stock - Beef, Brown', '€3,95');
insert into prigrizek (ime, cena) values ('Salmon Steak - Cohoe 8 Oz', '€3,20');
insert into prigrizek (ime, cena) values ('Chocolate - Feathers', '€3,11');
insert into prigrizek (ime, cena) values ('Triple Sec - Mcguinness', '€4,28');
insert into prigrizek (ime, cena) values ('White Baguette', '€3,13');
insert into prigrizek (ime, cena) values ('Green Scrubbie Pad H.duty', '€1,82');
insert into prigrizek (ime, cena) values ('Sugar - Palm', '€0,53');
insert into prigrizek (ime, cena) values ('Sugar - Icing', '€5,00');
insert into prigrizek (ime, cena) values ('Pepper - Red, Finger Hot', '€0,82');
insert into prigrizek (ime, cena) values ('Rosemary - Fresh', '€3,99');
insert into prigrizek (ime, cena) values ('Wheat - Soft Kernal Of Wheat', '€2,26');
insert into prigrizek (ime, cena) values ('Cheese - Cream Cheese', '€2,42');
insert into prigrizek (ime, cena) values ('Wine - Fume Blanc Fetzer', '€4,41');
insert into prigrizek (ime, cena) values ('Bacon Strip Precooked', '€0,61');
insert into prigrizek (ime, cena) values ('Bread - Rye', '€3,95');
insert into prigrizek (ime, cena) values ('Pork - Caul Fat', '€2,30');
insert into prigrizek (ime, cena) values ('Vegetable - Base', '€2,58');
insert into prigrizek (ime, cena) values ('Bread Roll Foccacia', '€4,74');
insert into prigrizek (ime, cena) values ('Food Colouring - Green', '€4,24');
insert into prigrizek (ime, cena) values ('Shrimp - Black Tiger 26/30', '€4,21');
insert into prigrizek (ime, cena) values ('Container - Clear 32 Oz', '€0,69');
insert into prigrizek (ime, cena) values ('Yams', '€0,09');
insert into prigrizek (ime, cena) values ('Sage - Ground', '€0,69');
insert into prigrizek (ime, cena) values ('Wine - Prem Select Charddonany', '€4,87');
insert into prigrizek (ime, cena) values ('Bread Foccacia Whole', '€0,68');
insert into prigrizek (ime, cena) values ('Lamb - Rack', '€4,58');
insert into prigrizek (ime, cena) values ('Chocolate Bar - Coffee Crisp', '€2,77');
insert into prigrizek (ime, cena) values ('Jam - Marmalade, Orange', '€0,37');
insert into prigrizek (ime, cena) values ('Corn Meal', '€3,19');
insert into prigrizek (ime, cena) values ('Shopper Bag - S - 4', '€2,88');
insert into prigrizek (ime, cena) values ('Beef - Tenderloin - Aa', '€3,45');
insert into prigrizek (ime, cena) values ('Wine - Red, Concha Y Toro', '€4,81');
insert into prigrizek (ime, cena) values ('Ezy Change Mophandle', '€2,23');
insert into prigrizek (ime, cena) values ('Juice - Propel Sport', '€0,76');
insert into prigrizek (ime, cena) values ('Calaloo', '€1,04');
insert into prigrizek (ime, cena) values ('Longos - Penne With Pesto', '€4,31');
insert into prigrizek (ime, cena) values ('Pepper - Yellow Bell', '€3,99');
insert into prigrizek (ime, cena) values ('Ham - Cooked Bayonne Tinned', '€0,79');
insert into prigrizek (ime, cena) values ('Wine - Toasted Head', '€1,74');
insert into prigrizek (ime, cena) values ('Beef Cheek Fresh', '€2,42');
insert into prigrizek (ime, cena) values ('Pork - Sausage, Medium', '€0,29');
insert into prigrizek (ime, cena) values ('Flour - Rye', '€1,15');
insert into prigrizek (ime, cena) values ('Cookie Dough - Chunky', '€4,00');
insert into prigrizek (ime, cena) values ('Rum - Dark, Bacardi, Black', '€2,38');
insert into prigrizek (ime, cena) values ('Apple - Royal Gala', '€3,56');
insert into prigrizek (ime, cena) values ('Squeeze Bottle', '€2,28');
insert into prigrizek (ime, cena) values ('Spice - Onion Powder Granulated', '€2,71');
insert into prigrizek (ime, cena) values ('Gatorade - Lemon Lime', '€2,23');
insert into prigrizek (ime, cena) values ('Juice - Lemon', '€1,93');
