insert into prigrizek (ime, cena) values ('Sardines', 2.59);
insert into prigrizek (ime, cena) values ('Kaffir Lime Leaves', 6.11);
insert into prigrizek (ime, cena) values ('Cake Circle, Paprus', 7.7);
insert into prigrizek (ime, cena) values ('Muffin Hinge - 211n', 3.77);
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Red, Baco', 4.9);
insert into prigrizek (ime, cena) values ('Lettuce - Romaine, Heart', 1.41);
insert into prigrizek (ime, cena) values ('Wine - Shiraz South Eastern', 4.57);
insert into prigrizek (ime, cena) values ('Bread Ww Cluster', 2.83);
insert into prigrizek (ime, cena) values ('Mousse - Passion Fruit', 1.0);
insert into prigrizek (ime, cena) values ('Sauce - Vodka Blush', 4.72);
insert into prigrizek (ime, cena) values ('Tea - Decaf Lipton', 2.94);
insert into prigrizek (ime, cena) values ('Wine - Pinot Grigio Collavini', 1.68);
insert into prigrizek (ime, cena) values ('Chocolate - Unsweetened', 5.33);
insert into prigrizek (ime, cena) values ('Salt - Seasoned', 2.16);
insert into prigrizek (ime, cena) values ('Bread - Italian Corn Meal Poly', 3.96);
insert into prigrizek (ime, cena) values ('Cheese - Brie', 2.96);
insert into prigrizek (ime, cena) values ('Halibut - Whole, Fresh', 2.61);
insert into prigrizek (ime, cena) values ('Longos - Grilled Chicken With', 6.57);
insert into prigrizek (ime, cena) values ('Cinnamon - Stick', 2.22);
insert into prigrizek (ime, cena) values ('Pepper - Red Chili', 1.37);
insert into prigrizek (ime, cena) values ('Longos - Burritos', 7.6);
insert into prigrizek (ime, cena) values ('Water Chestnut - Canned', 3.61);
insert into prigrizek (ime, cena) values ('Pork - Suckling Pig', 7.51);
insert into prigrizek (ime, cena) values ('Pastry - Banana Tea Loaf', 4.12);
insert into prigrizek (ime, cena) values ('Salt - Rock, Course', 6.55);
insert into prigrizek (ime, cena) values ('Veal - Striploin', 3.94);
insert into prigrizek (ime, cena) values ('Appetizer - Mushroom Tart', 1.96);
insert into prigrizek (ime, cena) values ('Swiss Chard - Red', 1.95);
insert into prigrizek (ime, cena) values ('Mushroom - Porcini, Dry', 5.43);
insert into prigrizek (ime, cena) values ('Bagel - Ched Chs Presliced', 6.23);
insert into prigrizek (ime, cena) values ('Bouillion - Fish', 7.87);
insert into prigrizek (ime, cena) values ('Chinese Foods - Cantonese', 6.86);
insert into prigrizek (ime, cena) values ('Vinegar - Red Wine', 6.44);
insert into prigrizek (ime, cena) values ('Sambuca - Opal Nera', 6.42);
insert into prigrizek (ime, cena) values ('Assorted Desserts', 2.37);
insert into prigrizek (ime, cena) values ('Muffins - Assorted', 6.23);
insert into prigrizek (ime, cena) values ('Silicone Paper 16.5x24', 6.69);
insert into prigrizek (ime, cena) values ('Lychee', 2.32);
insert into prigrizek (ime, cena) values ('Brandy - Orange, Mc Guiness', 1.45);
insert into prigrizek (ime, cena) values ('Wine - Shiraz South Eastern', 5.25);
insert into prigrizek (ime, cena) values ('Rum - White, Gg White', 3.68);
insert into prigrizek (ime, cena) values ('Beef Ground Medium', 7.57);
insert into prigrizek (ime, cena) values ('Nutmeg - Ground', 6.85);
insert into prigrizek (ime, cena) values ('Scallops - 10/20', 2.98);
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Cab Franc', 1.77);
insert into prigrizek (ime, cena) values ('Roe - White Fish', 2.49);
insert into prigrizek (ime, cena) values ('Turkey - Breast, Boneless Sk On', 5.51);
insert into prigrizek (ime, cena) values ('Cheese - Taleggio D.o.p.', 4.9);
insert into prigrizek (ime, cena) values ('Honey - Comb', 3.35);
insert into prigrizek (ime, cena) values ('7up Diet, 355 Ml', 5.49);
insert into prigrizek (ime, cena) values ('Arctic Char - Fillets', 1.26);
insert into prigrizek (ime, cena) values ('Versatainer Nc - 9388', 7.02);
insert into prigrizek (ime, cena) values ('Wine - Red, Mouton Cadet', 6.06);
insert into prigrizek (ime, cena) values ('Mushroom Morel Fresh', 2.85);
insert into prigrizek (ime, cena) values ('Seabream Whole Farmed', 2.58);
insert into prigrizek (ime, cena) values ('Kellogs All Bran Bars', 3.32);
insert into prigrizek (ime, cena) values ('Pasta - Gnocchi, Potato', 5.94);
insert into prigrizek (ime, cena) values ('Wine - White, Lindemans Bin 95', 1.49);
insert into prigrizek (ime, cena) values ('Wine - Barbera Alba Doc 2001', 2.95);
insert into prigrizek (ime, cena) values ('Vinegar - Tarragon', 4.3);
insert into prigrizek (ime, cena) values ('Shrimp - Baby, Warm Water', 5.0);
insert into prigrizek (ime, cena) values ('Pork - Sausage, Medium', 1.64);
insert into prigrizek (ime, cena) values ('Chevril', 5.39);
insert into prigrizek (ime, cena) values ('Dried Cherries', 5.54);
insert into prigrizek (ime, cena) values ('Pepsi - 600ml', 4.37);
insert into prigrizek (ime, cena) values ('Wine - Alsace Riesling Reserve', 3.76);
insert into prigrizek (ime, cena) values ('Nut - Macadamia', 4.59);
insert into prigrizek (ime, cena) values ('Truffle Shells - White Chocolate', 1.08);
insert into prigrizek (ime, cena) values ('Wine - Chardonnay South', 4.49);
insert into prigrizek (ime, cena) values ('Wine - White, Gewurtzraminer', 5.63);
insert into prigrizek (ime, cena) values ('Oats Large Flake', 5.12);
insert into prigrizek (ime, cena) values ('Lettuce - Spring Mix', 2.75);
insert into prigrizek (ime, cena) values ('Bar Bran Honey Nut', 1.35);
insert into prigrizek (ime, cena) values ('Bread - Pumpernickle, Rounds', 6.66);
insert into prigrizek (ime, cena) values ('Wine - Blue Nun Qualitatswein', 3.94);
insert into prigrizek (ime, cena) values ('Bread - Calabrese Baguette', 6.06);
insert into prigrizek (ime, cena) values ('Table Cloth 54x72 White', 6.06);
insert into prigrizek (ime, cena) values ('Eggplant Oriental', 5.83);
insert into prigrizek (ime, cena) values ('Cookie - Oreo 100x2', 2.96);
insert into prigrizek (ime, cena) values ('Fiddlehead - Frozen', 7.19);
insert into prigrizek (ime, cena) values ('Lid Coffee Cup 8oz Blk', 6.29);
insert into prigrizek (ime, cena) values ('Table Cloth 54x72 Colour', 2.35);
insert into prigrizek (ime, cena) values ('Pepperoni Slices', 3.74);
insert into prigrizek (ime, cena) values ('Appetizer - Escargot Puff', 5.39);
insert into prigrizek (ime, cena) values ('Soup - Campbells Broccoli', 2.29);
insert into prigrizek (ime, cena) values ('Sauce - Demi Glace', 6.13);
insert into prigrizek (ime, cena) values ('Pickle - Dill', 3.02);
insert into prigrizek (ime, cena) values ('Bulgar', 7.76);
insert into prigrizek (ime, cena) values ('Ice Cream - Fudge Bars', 5.95);
insert into prigrizek (ime, cena) values ('Nut - Pecan, Halves', 2.95);
insert into prigrizek (ime, cena) values ('Flour - Semolina', 7.73);
insert into prigrizek (ime, cena) values ('Gherkin - Sour', 2.39);
insert into prigrizek (ime, cena) values ('Turkey - Breast, Smoked', 6.04);
insert into prigrizek (ime, cena) values ('Uniform Linen Charge', 3.38);
insert into prigrizek (ime, cena) values ('Initation Crab Meat', 1.82);
insert into prigrizek (ime, cena) values ('Eel Fresh', 6.87);
insert into prigrizek (ime, cena) values ('Wine - Niagara,vqa Reisling', 3.11);
insert into prigrizek (ime, cena) values ('Pineapple - Regular', 4.01);
insert into prigrizek (ime, cena) values ('Sherbet - Raspberry', 1.47);
insert into prigrizek (ime, cena) values ('Steam Pan - Half Size Deep', 6.51);
insert into prigrizek (ime, cena) values ('Crawfish', 4.49);
insert into prigrizek (ime, cena) values ('Extract - Rum', 7.92);
insert into prigrizek (ime, cena) values ('Sauce - Marinara', 4.27);
insert into prigrizek (ime, cena) values ('Wine - Wyndham Estate Bin 777', 5.38);
insert into prigrizek (ime, cena) values ('Doilies - 12, Paper', 1.13);
insert into prigrizek (ime, cena) values ('Parsley - Fresh', 2.18);
insert into prigrizek (ime, cena) values ('Soup - Knorr, Country Bean', 7.48);
insert into prigrizek (ime, cena) values ('Apple - Granny Smith', 3.44);
insert into prigrizek (ime, cena) values ('Red Pepper Paste', 4.25);
insert into prigrizek (ime, cena) values ('Veal - Chops, Split, Frenched', 6.8);
insert into prigrizek (ime, cena) values ('Pail - 15l White, With Handle', 6.38);
insert into prigrizek (ime, cena) values ('Mahi Mahi', 5.46);
insert into prigrizek (ime, cena) values ('Bread - Calabrese Baguette', 3.99);
insert into prigrizek (ime, cena) values ('Wine - Vineland Estate Semi - Dry', 3.53);
insert into prigrizek (ime, cena) values ('Island Oasis - Peach Daiquiri', 5.04);
insert into prigrizek (ime, cena) values ('Wine - Sicilia Igt Nero Avola', 5.96);
insert into prigrizek (ime, cena) values ('Venison - Racks Frenched', 1.11);
insert into prigrizek (ime, cena) values ('Juice - Mango', 5.65);
insert into prigrizek (ime, cena) values ('Lettuce - Arugula', 3.78);
insert into prigrizek (ime, cena) values ('Ecolab - Orange Frc, Cleaner', 1.96);
insert into prigrizek (ime, cena) values ('Figs', 6.81);
insert into prigrizek (ime, cena) values ('Cheese - Cheddar, Mild', 5.72);
insert into prigrizek (ime, cena) values ('Pepper - Green', 5.14);
insert into prigrizek (ime, cena) values ('Sobe - Cranberry Grapefruit', 5.08);
insert into prigrizek (ime, cena) values ('Chicken - Ground', 5.19);
insert into prigrizek (ime, cena) values ('Cheese - Asiago', 3.2);
insert into prigrizek (ime, cena) values ('Graham Cracker Mix', 2.76);
insert into prigrizek (ime, cena) values ('Duck - Whole', 7.62);
insert into prigrizek (ime, cena) values ('Juice - Apple, 1.36l', 6.87);
insert into prigrizek (ime, cena) values ('Milk - Condensed', 2.24);
insert into prigrizek (ime, cena) values ('Beans - Kidney, Red Dry', 2.25);
insert into prigrizek (ime, cena) values ('Pasta - Gnocchi, Potato', 1.41);
insert into prigrizek (ime, cena) values ('Flower - Carnations', 6.97);
insert into prigrizek (ime, cena) values ('Tortillas - Flour, 12', 3.01);
insert into prigrizek (ime, cena) values ('Pastry - Raisin Muffin - Mini', 7.99);
insert into prigrizek (ime, cena) values ('Sprouts - Corn', 4.47);
insert into prigrizek (ime, cena) values ('Hagen Daza - Dk Choocolate', 5.57);
insert into prigrizek (ime, cena) values ('Turnip - Mini', 4.39);
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Pinot Gris Sr', 1.86);
insert into prigrizek (ime, cena) values ('Plasticspoonblack', 5.62);
insert into prigrizek (ime, cena) values ('Coffee - Dark Roast', 5.68);
insert into prigrizek (ime, cena) values ('Wine - Rosso Del Veronese Igt', 3.39);
insert into prigrizek (ime, cena) values ('Veal - Osso Bucco', 5.02);
insert into prigrizek (ime, cena) values ('Curry Powder Madras', 5.72);
insert into prigrizek (ime, cena) values ('Pork - Inside', 3.78);
insert into prigrizek (ime, cena) values ('Glass - Wine, Plastic, Clear 5 Oz', 2.7);
insert into prigrizek (ime, cena) values ('Eggplant Italian', 5.06);
insert into prigrizek (ime, cena) values ('Wine - Crozes Hermitage E.', 3.4);
insert into prigrizek (ime, cena) values ('Chicken - Whole', 3.3);
insert into prigrizek (ime, cena) values ('Tomato - Peeled Italian Canned', 3.8);
insert into prigrizek (ime, cena) values ('Sausage - Andouille', 2.7);
insert into prigrizek (ime, cena) values ('Pasta - Orecchiette', 3.72);
insert into prigrizek (ime, cena) values ('Bag Clear 10 Lb', 6.85);
insert into prigrizek (ime, cena) values ('Raisin - Dark', 1.72);
insert into prigrizek (ime, cena) values ('Bread - Roll, Italian', 4.41);
insert into prigrizek (ime, cena) values ('Mangostein', 5.19);
insert into prigrizek (ime, cena) values ('Transfer Sheets', 3.54);
insert into prigrizek (ime, cena) values ('Lamb Shoulder Boneless Nz', 3.28);
insert into prigrizek (ime, cena) values ('Propel Sport Drink', 4.92);
insert into prigrizek (ime, cena) values ('Chocolate Eclairs', 2.94);
insert into prigrizek (ime, cena) values ('Pastry - Raisin Muffin - Mini', 4.59);
insert into prigrizek (ime, cena) values ('Grapefruit - Pink', 4.67);
insert into prigrizek (ime, cena) values ('Soup - Campbells Asian Noodle', 6.96);
insert into prigrizek (ime, cena) values ('Tomatoes - Vine Ripe, Yellow', 5.03);
insert into prigrizek (ime, cena) values ('Bread - Mini Hamburger Bun', 4.01);
insert into prigrizek (ime, cena) values ('Ecolab - Hobart Washarm End Cap', 5.21);
insert into prigrizek (ime, cena) values ('Pears - Anjou', 1.56);
insert into prigrizek (ime, cena) values ('Sage - Ground', 6.96);
insert into prigrizek (ime, cena) values ('Syrup - Monin - Passion Fruit', 1.08);
insert into prigrizek (ime, cena) values ('Onions - White', 2.02);
insert into prigrizek (ime, cena) values ('Blueberries - Frozen', 1.78);
insert into prigrizek (ime, cena) values ('Lamb - Leg, Diced', 2.25);
insert into prigrizek (ime, cena) values ('Table Cloth 72x144 White', 3.14);
insert into prigrizek (ime, cena) values ('Lidsoupcont Rp12dn', 2.23);
insert into prigrizek (ime, cena) values ('Wine - Cotes Du Rhone', 2.51);
insert into prigrizek (ime, cena) values ('Filter - Coffee', 7.22);
insert into prigrizek (ime, cena) values ('Vinegar - Balsamic', 5.51);
insert into prigrizek (ime, cena) values ('Yogurt - Cherry, 175 Gr', 7.44);
insert into prigrizek (ime, cena) values ('Syrup - Kahlua Chocolate', 5.24);
insert into prigrizek (ime, cena) values ('Appetizer - Sausage Rolls', 5.07);
insert into prigrizek (ime, cena) values ('Soup - Campbells', 7.77);
insert into prigrizek (ime, cena) values ('Beef - Striploin', 4.58);
insert into prigrizek (ime, cena) values ('Nantucket Pine Orangebanana', 1.06);
insert into prigrizek (ime, cena) values ('Fruit Mix - Light', 3.47);
insert into prigrizek (ime, cena) values ('Dome Lid Clear P92008h', 4.63);
insert into prigrizek (ime, cena) values ('Ecolab - Ster Bac', 6.5);
insert into prigrizek (ime, cena) values ('Bread - Pain Au Liat X12', 3.18);
insert into prigrizek (ime, cena) values ('Chocolate - Sugar Free Semi Choc', 7.45);
insert into prigrizek (ime, cena) values ('Wine - Barolo Fontanafredda', 1.12);
insert into prigrizek (ime, cena) values ('Icecream - Dibs', 2.57);
insert into prigrizek (ime, cena) values ('Cookies - Amaretto', 3.41);
insert into prigrizek (ime, cena) values ('Bananas', 2.9);
insert into prigrizek (ime, cena) values ('Island Oasis - Pina Colada', 7.53);
insert into prigrizek (ime, cena) values ('Sauce - White, Mix', 7.89);
insert into prigrizek (ime, cena) values ('Sour Puss - Tangerine', 7.05);
insert into prigrizek (ime, cena) values ('Sprouts - Alfalfa', 3.31);
insert into prigrizek (ime, cena) values ('Higashimaru Usukuchi Soy', 7.91);
insert into prigrizek (ime, cena) values ('Rabbit - Whole', 7.13);
insert into prigrizek (ime, cena) values ('The Pop Shoppe - Lime Rickey', 5.35);
insert into prigrizek (ime, cena) values ('Beer - Upper Canada Light', 1.04);
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Cab Sauv', 7.88);
insert into prigrizek (ime, cena) values ('Pail - 15l White, With Handle', 4.12);
insert into prigrizek (ime, cena) values ('Pie Filling - Pumpkin', 6.58);
insert into prigrizek (ime, cena) values ('Crab Meat Claw Pasteurise', 6.63);
insert into prigrizek (ime, cena) values ('Kaffir Lime Leaves', 5.77);
insert into prigrizek (ime, cena) values ('Cinnamon Rolls', 2.18);
insert into prigrizek (ime, cena) values ('Sauce - Salsa', 2.98);
insert into prigrizek (ime, cena) values ('Loaf Pan - 2 Lb, Foil', 3.78);
insert into prigrizek (ime, cena) values ('Scallops - 20/30', 5.56);
insert into prigrizek (ime, cena) values ('Chilli Paste, Hot Sambal Oelek', 6.89);
insert into prigrizek (ime, cena) values ('Cheese - Cheddar, Old White', 2.71);
insert into prigrizek (ime, cena) values ('Soup - Chicken And Wild Rice', 1.1);
insert into prigrizek (ime, cena) values ('Broom - Angled', 3.11);
insert into prigrizek (ime, cena) values ('Bread Sour Rolls', 1.85);
insert into prigrizek (ime, cena) values ('Water - San Pellegrino', 4.49);
insert into prigrizek (ime, cena) values ('Wine - Red, Marechal Foch', 7.59);
insert into prigrizek (ime, cena) values ('Soup - Chicken And Wild Rice', 1.29);
insert into prigrizek (ime, cena) values ('Nantucket - Carrot Orange', 7.04);
insert into prigrizek (ime, cena) values ('Peach - Fresh', 7.93);
insert into prigrizek (ime, cena) values ('Flour - Masa De Harina Mexican', 5.89);
insert into prigrizek (ime, cena) values ('Wine - Ice Wine', 4.42);
insert into prigrizek (ime, cena) values ('Coffee Guatemala Dark', 6.15);
insert into prigrizek (ime, cena) values ('Pastry - Mini French Pastries', 4.53);
insert into prigrizek (ime, cena) values ('Bread - Rolls, Rye', 5.71);
insert into prigrizek (ime, cena) values ('Foam Dinner Plate', 1.68);
insert into prigrizek (ime, cena) values ('Sour Puss - Tangerine', 7.75);
insert into prigrizek (ime, cena) values ('Veal - Shank, Pieces', 2.18);
insert into prigrizek (ime, cena) values ('Lettuce Romaine Chopped', 5.08);
insert into prigrizek (ime, cena) values ('French Kiss Vanilla', 4.66);
insert into prigrizek (ime, cena) values ('Gingerale - Schweppes, 355 Ml', 2.41);
insert into prigrizek (ime, cena) values ('Dawn Professionl Pot And Pan', 6.04);
insert into prigrizek (ime, cena) values ('Wine - White, Antinore Orvieto', 6.54);
insert into prigrizek (ime, cena) values ('Burger Veggie', 3.4);
insert into prigrizek (ime, cena) values ('Kirsch - Schloss', 7.27);
insert into prigrizek (ime, cena) values ('Artichoke - Hearts, Canned', 1.69);
insert into prigrizek (ime, cena) values ('Sauce Bbq Smokey', 4.3);
insert into prigrizek (ime, cena) values ('Peach - Halves', 1.68);
insert into prigrizek (ime, cena) values ('Wine - Niagara,vqa Reisling', 4.67);
insert into prigrizek (ime, cena) values ('Veal - Ground', 1.42);
insert into prigrizek (ime, cena) values ('Mortadella', 7.88);
insert into prigrizek (ime, cena) values ('Spinach - Spinach Leaf', 5.31);
insert into prigrizek (ime, cena) values ('Pea - Snow', 7.3);
insert into prigrizek (ime, cena) values ('Pop - Club Soda Can', 3.49);
insert into prigrizek (ime, cena) values ('Green Tea Refresher', 2.44);
insert into prigrizek (ime, cena) values ('Eggplant - Baby', 4.65);
insert into prigrizek (ime, cena) values ('Wine - Alsace Gewurztraminer', 2.02);
insert into prigrizek (ime, cena) values ('Sage - Ground', 1.1);
insert into prigrizek (ime, cena) values ('Muffin Mix - Oatmeal', 7.8);
insert into prigrizek (ime, cena) values ('Lamb - Shoulder, Boneless', 4.9);
insert into prigrizek (ime, cena) values ('Edible Flower - Mixed', 3.7);
insert into prigrizek (ime, cena) values ('Syrup - Monin - Granny Smith', 7.31);
insert into prigrizek (ime, cena) values ('Sugar - Crumb', 2.22);
insert into prigrizek (ime, cena) values ('Blue Curacao - Marie Brizard', 2.93);
insert into prigrizek (ime, cena) values ('Cheese - Roquefort Pappillon', 1.1);
insert into prigrizek (ime, cena) values ('Aspic - Amber', 5.29);
insert into prigrizek (ime, cena) values ('Chocolate Bar - Oh Henry', 2.55);
insert into prigrizek (ime, cena) values ('Juice - Clamato, 341 Ml', 6.26);
insert into prigrizek (ime, cena) values ('Jam - Raspberry,jar', 4.44);
insert into prigrizek (ime, cena) values ('Calypso - Black Cherry Lemonade', 7.66);
insert into prigrizek (ime, cena) values ('Pasta - Bauletti, Chicken White', 7.24);
insert into prigrizek (ime, cena) values ('Wine - Black Tower Qr', 3.07);
insert into prigrizek (ime, cena) values ('Galliano', 3.15);
insert into prigrizek (ime, cena) values ('Wine - Prem Select Charddonany', 2.92);
insert into prigrizek (ime, cena) values ('Bar Nature Valley', 4.99);
insert into prigrizek (ime, cena) values ('Sauce - Vodka Blush', 4.7);
insert into prigrizek (ime, cena) values ('Turkey - Breast, Bone - In', 5.8);
insert into prigrizek (ime, cena) values ('Arrowroot', 6.22);
insert into prigrizek (ime, cena) values ('Juice - Apple 284ml', 5.09);
insert into prigrizek (ime, cena) values ('Piping Jelly - All Colours', 4.26);
insert into prigrizek (ime, cena) values ('Lambcasing', 6.77);
insert into prigrizek (ime, cena) values ('Garbag Bags - Black', 4.32);
insert into prigrizek (ime, cena) values ('Ice Cream - Chocolate', 1.81);
insert into prigrizek (ime, cena) values ('Pan Grease', 3.12);
insert into prigrizek (ime, cena) values ('Liqueur Banana, Ramazzotti', 3.38);
insert into prigrizek (ime, cena) values ('Soup - Campbells, Spinach Crm', 5.84);
insert into prigrizek (ime, cena) values ('Tea - Orange Pekoe', 2.82);
insert into prigrizek (ime, cena) values ('Pineapple - Regular', 1.26);
insert into prigrizek (ime, cena) values ('Pastry - Lemon Danish - Mini', 1.28);
insert into prigrizek (ime, cena) values ('Puree - Mango', 1.19);
insert into prigrizek (ime, cena) values ('Roe - Flying Fish', 4.63);
insert into prigrizek (ime, cena) values ('Wine - Ej Gallo Sierra Valley', 4.75);
insert into prigrizek (ime, cena) values ('Shrimp - 31/40', 2.41);
insert into prigrizek (ime, cena) values ('Tea - Black Currant', 6.53);
insert into prigrizek (ime, cena) values ('Apple - Granny Smith', 3.29);
insert into prigrizek (ime, cena) values ('Wine - Domaine Boyar Royal', 4.75);
insert into prigrizek (ime, cena) values ('Pasta - Ravioli', 7.61);
insert into prigrizek (ime, cena) values ('Pears - Fiorelle', 2.31);
insert into prigrizek (ime, cena) values ('Pasta - Detalini, White, Fresh', 5.42);
insert into prigrizek (ime, cena) values ('Pepper - Red, Finger Hot', 2.47);
insert into prigrizek (ime, cena) values ('Wine - Merlot Vina Carmen', 3.41);
insert into prigrizek (ime, cena) values ('Chips - Assorted', 6.91);
insert into prigrizek (ime, cena) values ('Kirsch - Schloss', 5.29);
insert into prigrizek (ime, cena) values ('Wine - Malbec Trapiche Reserve', 7.17);
insert into prigrizek (ime, cena) values ('Fudge - Chocolate Fudge', 1.4);
insert into prigrizek (ime, cena) values ('Wine - Piper Heidsieck Brut', 2.04);
insert into prigrizek (ime, cena) values ('Neckerchief Blck', 1.58);
insert into prigrizek (ime, cena) values ('Cheese - Cheddar, Mild', 3.74);
insert into prigrizek (ime, cena) values ('Compound - Passion Fruit', 5.03);
insert into prigrizek (ime, cena) values ('Mussels - Cultivated', 4.01);
insert into prigrizek (ime, cena) values ('Cheese - Cheddar, Old White', 1.16);
insert into prigrizek (ime, cena) values ('Coffee Caramel Biscotti', 7.85);
insert into prigrizek (ime, cena) values ('Wine - White, Chardonnay', 1.02);
insert into prigrizek (ime, cena) values ('Pear - Packum', 4.68);
insert into prigrizek (ime, cena) values ('Walkers Special Old Whiskey', 6.25);
insert into prigrizek (ime, cena) values ('Tart - Raisin And Pecan', 5.27);
insert into prigrizek (ime, cena) values ('Egg Patty Fried', 1.9);
insert into prigrizek (ime, cena) values ('Seedlings - Buckwheat, Organic', 2.32);
insert into prigrizek (ime, cena) values ('Roe - White Fish', 1.62);
insert into prigrizek (ime, cena) values ('Vinegar - Sherry', 6.08);
insert into prigrizek (ime, cena) values ('Wine - Chablis 2003 Champs', 6.09);
insert into prigrizek (ime, cena) values ('Compound - Rum', 3.1);
insert into prigrizek (ime, cena) values ('Amaretto', 4.46);
insert into prigrizek (ime, cena) values ('Truffle Paste', 7.43);
insert into prigrizek (ime, cena) values ('Mustard Prepared', 6.26);
insert into prigrizek (ime, cena) values ('Vinegar - Raspberry', 2.12);
insert into prigrizek (ime, cena) values ('Tuna - Canned, Flaked, Light', 4.51);
insert into prigrizek (ime, cena) values ('Wine - Red, Concha Y Toro', 7.06);
insert into prigrizek (ime, cena) values ('Snapple - Iced Tea Peach', 2.02);
insert into prigrizek (ime, cena) values ('Bread - Multigrain, Loaf', 4.74);
insert into prigrizek (ime, cena) values ('Mix - Cocktail Ice Cream', 6.51);
insert into prigrizek (ime, cena) values ('Apples - Spartan', 4.78);
insert into prigrizek (ime, cena) values ('Wine - Two Oceans Sauvignon', 4.93);
insert into prigrizek (ime, cena) values ('Energy Drink - Franks Original', 2.63);
insert into prigrizek (ime, cena) values ('Soup - French Can Pea', 4.54);
insert into prigrizek (ime, cena) values ('Pork - Suckling Pig', 1.16);
insert into prigrizek (ime, cena) values ('Wine - Gewurztraminer Pierre', 2.13);
insert into prigrizek (ime, cena) values ('Petit Baguette', 4.5);
insert into prigrizek (ime, cena) values ('Ham - Virginia', 2.66);
insert into prigrizek (ime, cena) values ('Ice Cream - Strawberry', 3.08);
insert into prigrizek (ime, cena) values ('Lotus Rootlets - Canned', 5.71);
insert into prigrizek (ime, cena) values ('Wine - Barbera Alba Doc 2001', 3.44);
insert into prigrizek (ime, cena) values ('Cinnamon Buns Sticky', 6.47);
insert into prigrizek (ime, cena) values ('Lotus Leaves', 6.69);
insert into prigrizek (ime, cena) values ('Lamb - Racks, Frenched', 6.76);
insert into prigrizek (ime, cena) values ('Bread Base - Gold Formel', 1.32);
insert into prigrizek (ime, cena) values ('Veal - Insides, Grains', 7.15);
insert into prigrizek (ime, cena) values ('Chicken - Base', 4.53);
insert into prigrizek (ime, cena) values ('Puree - Mocha', 5.47);
insert into prigrizek (ime, cena) values ('Melon - Cantaloupe', 2.71);
insert into prigrizek (ime, cena) values ('Pesto - Primerba, Paste', 3.31);
insert into prigrizek (ime, cena) values ('Cape Capensis - Fillet', 7.51);
insert into prigrizek (ime, cena) values ('Vector Energy Bar', 7.54);
insert into prigrizek (ime, cena) values ('Pie Shell - 5', 6.1);
insert into prigrizek (ime, cena) values ('Lambcasing', 6.46);
insert into prigrizek (ime, cena) values ('Wine - Chateauneuf Du Pape', 2.09);
insert into prigrizek (ime, cena) values ('Kohlrabi', 6.81);
insert into prigrizek (ime, cena) values ('Shrimp - 100 / 200 Cold Water', 6.73);
insert into prigrizek (ime, cena) values ('Water - Spring Water, 355 Ml', 6.38);
insert into prigrizek (ime, cena) values ('Tea Leaves - Oolong', 5.72);
insert into prigrizek (ime, cena) values ('Pastry - Chocolate Chip Muffin', 2.79);
insert into prigrizek (ime, cena) values ('Goat - Whole Cut', 4.32);
insert into prigrizek (ime, cena) values ('Longos - Chicken Curried', 6.66);
insert into prigrizek (ime, cena) values ('Longos - Lasagna Veg', 1.11);
insert into prigrizek (ime, cena) values ('Nutmeg - Ground', 3.79);
insert into prigrizek (ime, cena) values ('Ecolab - Hand Soap Form Antibac', 5.69);
insert into prigrizek (ime, cena) values ('Wine - Jafflin Bourgongone', 7.04);
insert into prigrizek (ime, cena) values ('Lamb - Whole Head Off', 3.21);
insert into prigrizek (ime, cena) values ('Numi - Assorted Teas', 3.65);
insert into prigrizek (ime, cena) values ('Chicken - Tenderloin', 4.11);
insert into prigrizek (ime, cena) values ('Apple - Granny Smith', 5.63);
insert into prigrizek (ime, cena) values ('Bread - Rolls, Rye', 3.0);
insert into prigrizek (ime, cena) values ('Juice - V8 Splash', 5.09);
insert into prigrizek (ime, cena) values ('Pork - Loin, Boneless', 5.95);
insert into prigrizek (ime, cena) values ('Onion Powder', 6.6);
insert into prigrizek (ime, cena) values ('Leeks - Large', 2.26);
insert into prigrizek (ime, cena) values ('Lentils - Red, Dry', 7.55);
insert into prigrizek (ime, cena) values ('Cake - Mini Cheesecake', 2.87);
insert into prigrizek (ime, cena) values ('Bag - Clear 7 Lb', 4.65);
insert into prigrizek (ime, cena) values ('Remy Red Berry Infusion', 1.89);
insert into prigrizek (ime, cena) values ('Icecream Bar - Del Monte', 4.32);
insert into prigrizek (ime, cena) values ('Longos - Burritos', 2.5);
insert into prigrizek (ime, cena) values ('Pastry - Plain Baked Croissant', 3.79);
insert into prigrizek (ime, cena) values ('Hot Choc Vending', 3.77);
insert into prigrizek (ime, cena) values ('Oneshot Automatic Soap System', 3.57);
insert into prigrizek (ime, cena) values ('Bulgar', 7.77);
insert into prigrizek (ime, cena) values ('Longos - Penne With Pesto', 7.49);
insert into prigrizek (ime, cena) values ('Pork - Smoked Back Bacon', 3.79);
insert into prigrizek (ime, cena) values ('Nantucket - Pomegranate Pear', 4.13);
insert into prigrizek (ime, cena) values ('Pepperoni Slices', 4.45);
insert into prigrizek (ime, cena) values ('Napkin - Beverage 1 Ply', 7.74);
insert into prigrizek (ime, cena) values ('Beans - Navy, Dry', 2.68);
insert into prigrizek (ime, cena) values ('Bread - Focaccia Quarter', 2.53);
insert into prigrizek (ime, cena) values ('Cheese - Ricotta', 2.21);
insert into prigrizek (ime, cena) values ('Apple - Delicious, Golden', 5.23);
insert into prigrizek (ime, cena) values ('Soup Campbells Split Pea And Ham', 5.34);
insert into prigrizek (ime, cena) values ('Longos - Lasagna Veg', 5.92);
insert into prigrizek (ime, cena) values ('Pate - Liver', 4.94);
insert into prigrizek (ime, cena) values ('Compound - Passion Fruit', 4.84);
insert into prigrizek (ime, cena) values ('Lamb Leg - Bone - In Nz', 3.87);
insert into prigrizek (ime, cena) values ('Beans - Soya Bean', 1.43);
insert into prigrizek (ime, cena) values ('Melon - Honey Dew', 6.96);
insert into prigrizek (ime, cena) values ('Juice - Orange, Concentrate', 3.51);
insert into prigrizek (ime, cena) values ('Muffin Mix - Oatmeal', 3.66);
insert into prigrizek (ime, cena) values ('Crab - Meat', 6.02);
insert into prigrizek (ime, cena) values ('Melon - Watermelon Yellow', 2.97);
insert into prigrizek (ime, cena) values ('Muffin - Bran Ind Wrpd', 7.92);
insert into prigrizek (ime, cena) values ('Sage Derby', 5.03);
insert into prigrizek (ime, cena) values ('Cheese - Cheddar, Old White', 7.67);
insert into prigrizek (ime, cena) values ('Sugar - Sweet N Low, Individual', 2.31);
insert into prigrizek (ime, cena) values ('Coke - Diet, 355 Ml', 5.24);
insert into prigrizek (ime, cena) values ('Currants', 4.32);
insert into prigrizek (ime, cena) values ('Steamers White', 3.72);
insert into prigrizek (ime, cena) values ('Gherkin', 2.53);
insert into prigrizek (ime, cena) values ('Sprite - 355 Ml', 5.31);
insert into prigrizek (ime, cena) values ('Nantuket Peach Orange', 5.31);
insert into prigrizek (ime, cena) values ('Lamb Shoulder Boneless Nz', 7.7);
insert into prigrizek (ime, cena) values ('Squid - U - 10 Thailand', 2.97);
insert into prigrizek (ime, cena) values ('Pasta - Fettuccine, Dry', 2.22);
insert into prigrizek (ime, cena) values ('Pate Pans Yellow', 4.97);
insert into prigrizek (ime, cena) values ('Bag - Bread, White, Plain', 1.06);
insert into prigrizek (ime, cena) values ('Lotus Rootlets - Canned', 1.95);
insert into prigrizek (ime, cena) values ('Ecolab - Orange Frc, Cleaner', 7.61);
insert into prigrizek (ime, cena) values ('Lobster - Tail 6 Oz', 6.26);
insert into prigrizek (ime, cena) values ('Soup - Campbells - Chicken Noodle', 4.27);
insert into prigrizek (ime, cena) values ('7up Diet, 355 Ml', 2.09);
insert into prigrizek (ime, cena) values ('Cherries - Maraschino,jar', 3.15);
insert into prigrizek (ime, cena) values ('Wine - White Cab Sauv.on', 3.86);
insert into prigrizek (ime, cena) values ('Amarula Cream', 5.6);
insert into prigrizek (ime, cena) values ('Chestnuts - Whole,canned', 6.39);
insert into prigrizek (ime, cena) values ('Parsley Italian - Fresh', 3.48);
insert into prigrizek (ime, cena) values ('Beef - Prime Rib Aaa', 5.13);
insert into prigrizek (ime, cena) values ('Wine - Sicilia Igt Nero Avola', 3.89);
insert into prigrizek (ime, cena) values ('Muffin - Mix - Creme Brule 15l', 4.22);
insert into prigrizek (ime, cena) values ('Lamb - Leg, Boneless', 2.8);
insert into prigrizek (ime, cena) values ('Bread Base - Goodhearth', 7.92);
insert into prigrizek (ime, cena) values ('Cafe Royale', 1.24);
insert into prigrizek (ime, cena) values ('Chevere Logs', 3.33);
insert into prigrizek (ime, cena) values ('Flower - Commercial Bronze', 6.7);
insert into prigrizek (ime, cena) values ('Goulash Seasoning', 7.22);
insert into prigrizek (ime, cena) values ('V8 - Vegetable Cocktail', 1.52);
insert into prigrizek (ime, cena) values ('Wine - Mondavi Coastal Private', 7.46);
insert into prigrizek (ime, cena) values ('Black Currants', 5.23);
insert into prigrizek (ime, cena) values ('Beef - Tenderlion, Center Cut', 5.57);
insert into prigrizek (ime, cena) values ('Wine La Vielle Ferme Cote Du', 6.99);
insert into prigrizek (ime, cena) values ('Beef - Top Butt Aaa', 6.08);
insert into prigrizek (ime, cena) values ('Water - Spring Water, 355 Ml', 6.16);
insert into prigrizek (ime, cena) values ('Soup - Campbells Chicken', 2.51);
insert into prigrizek (ime, cena) values ('Rabbit - Whole', 3.69);
insert into prigrizek (ime, cena) values ('Wine - Red, Mouton Cadet', 7.42);
insert into prigrizek (ime, cena) values ('Pie Shell - 5', 1.42);
insert into prigrizek (ime, cena) values ('Icecream - Dstk Super Cone', 2.82);
insert into prigrizek (ime, cena) values ('Sugar - Cubes', 4.95);
insert into prigrizek (ime, cena) values ('Sherry - Dry', 5.76);
insert into prigrizek (ime, cena) values ('Grenadine', 7.22);
insert into prigrizek (ime, cena) values ('Wine - Sherry Dry Sack, William', 5.7);
insert into prigrizek (ime, cena) values ('Wine - Chardonnay South', 7.73);
insert into prigrizek (ime, cena) values ('Lamb Tenderloin Nz Fr', 3.3);
insert into prigrizek (ime, cena) values ('Wine - Chianti Classico Riserva', 7.89);
insert into prigrizek (ime, cena) values ('Wine - White, Chardonnay', 5.07);
insert into prigrizek (ime, cena) values ('Veal - Bones', 6.43);
insert into prigrizek (ime, cena) values ('Soup - Base Broth Chix', 2.12);
insert into prigrizek (ime, cena) values ('Sauce - Roasted Red Pepper', 3.23);
insert into prigrizek (ime, cena) values ('Peas - Frozen', 3.05);
insert into prigrizek (ime, cena) values ('Emulsifier', 2.06);
insert into prigrizek (ime, cena) values ('Tandoori Curry Paste', 1.66);
insert into prigrizek (ime, cena) values ('Coffee - Cafe Moreno', 5.85);
insert into prigrizek (ime, cena) values ('Cream - 10%', 7.39);
insert into prigrizek (ime, cena) values ('Bouq All Italian - Primerba', 2.49);
insert into prigrizek (ime, cena) values ('Pork - Back, Long Cut, Boneless', 4.45);
insert into prigrizek (ime, cena) values ('Wine - Casillero Del Diablo', 4.69);
insert into prigrizek (ime, cena) values ('Mustard - Individual Pkg', 1.63);
insert into prigrizek (ime, cena) values ('Turkey - Breast, Bone - In', 5.76);
insert into prigrizek (ime, cena) values ('Sprouts Dikon', 4.05);
insert into prigrizek (ime, cena) values ('Pomegranates', 4.27);
insert into prigrizek (ime, cena) values ('Remy Red Berry Infusion', 6.15);
insert into prigrizek (ime, cena) values ('Tomato Paste', 7.42);
insert into prigrizek (ime, cena) values ('Beef - Top Sirloin', 2.53);
insert into prigrizek (ime, cena) values ('Wine - Red, Black Opal Shiraz', 7.07);
insert into prigrizek (ime, cena) values ('Easy Off Oven Cleaner', 7.96);
insert into prigrizek (ime, cena) values ('Hinge W Undercut', 4.71);
insert into prigrizek (ime, cena) values ('Beer - Rickards Red', 4.64);
insert into prigrizek (ime, cena) values ('Tea - Lemon Scented', 7.42);
insert into prigrizek (ime, cena) values ('Oregano - Fresh', 3.32);
insert into prigrizek (ime, cena) values ('Garam Masala Powder', 5.18);
insert into prigrizek (ime, cena) values ('Cake - Cheese Cake 9 Inch', 3.29);
insert into prigrizek (ime, cena) values ('Appetizer - Mini Egg Roll, Shrimp', 3.39);
insert into prigrizek (ime, cena) values ('Cake - Night And Day Choclate', 5.11);
insert into prigrizek (ime, cena) values ('Sponge Cake Mix - Vanilla', 4.64);
insert into prigrizek (ime, cena) values ('Trout - Rainbow, Frozen', 6.02);
insert into prigrizek (ime, cena) values ('Radish', 5.28);
insert into prigrizek (ime, cena) values ('Pasta - Canelloni', 1.86);
insert into prigrizek (ime, cena) values ('Wine - Mondavi Coastal Private', 3.51);
insert into prigrizek (ime, cena) values ('Lemonade - Strawberry, 591 Ml', 6.34);
insert into prigrizek (ime, cena) values ('Molasses - Fancy', 5.51);
insert into prigrizek (ime, cena) values ('Snapple Raspberry Tea', 4.6);
insert into prigrizek (ime, cena) values ('Oil - Olive Bertolli', 7.89);
insert into prigrizek (ime, cena) values ('Pur Source', 2.32);
insert into prigrizek (ime, cena) values ('Pheasants - Whole', 3.42);
insert into prigrizek (ime, cena) values ('Food Colouring - Pink', 2.37);
insert into prigrizek (ime, cena) values ('Olives - Green, Pitted', 1.64);
insert into prigrizek (ime, cena) values ('Strawberries', 3.85);
insert into prigrizek (ime, cena) values ('Cheese - Havarti, Salsa', 7.79);
insert into prigrizek (ime, cena) values ('Bread - Dark Rye', 3.69);
insert into prigrizek (ime, cena) values ('Bread - Burger', 3.73);
insert into prigrizek (ime, cena) values ('Cake - Night And Day Choclate', 4.44);
insert into prigrizek (ime, cena) values ('Sprouts - Onion', 5.23);
insert into prigrizek (ime, cena) values ('Ginger - Fresh', 4.56);
insert into prigrizek (ime, cena) values ('Tortillas - Flour, 12', 4.89);
insert into prigrizek (ime, cena) values ('Dill Weed - Dry', 6.14);
insert into prigrizek (ime, cena) values ('Chilli Paste, Ginger Garlic', 6.28);
insert into prigrizek (ime, cena) values ('Extract - Vanilla,artificial', 3.51);
insert into prigrizek (ime, cena) values ('Pie Shell - 5', 1.89);
insert into prigrizek (ime, cena) values ('Miso - Soy Bean Paste', 1.76);
insert into prigrizek (ime, cena) values ('Goulash Seasoning', 2.09);
insert into prigrizek (ime, cena) values ('Cassis', 5.55);
insert into prigrizek (ime, cena) values ('Beef - Montreal Smoked Brisket', 5.43);
insert into prigrizek (ime, cena) values ('Lemonade - Pineapple Passion', 4.82);
insert into prigrizek (ime, cena) values ('Wanton Wrap', 2.43);
insert into prigrizek (ime, cena) values ('Wine - Rioja Campo Viejo', 6.31);
insert into prigrizek (ime, cena) values ('Spice - Onion Powder Granulated', 7.4);
insert into prigrizek (ime, cena) values ('Puree - Strawberry', 2.49);
insert into prigrizek (ime, cena) values ('Plate Foam Laminated 9in Blk', 2.87);
insert into prigrizek (ime, cena) values ('Lettuce - Boston Bib', 3.78);
insert into prigrizek (ime, cena) values ('Salmon Steak - Cohoe 6 Oz', 2.83);
insert into prigrizek (ime, cena) values ('Veal - Chops, Split, Frenched', 6.95);
insert into prigrizek (ime, cena) values ('Tarragon - Fresh', 3.84);
insert into prigrizek (ime, cena) values ('Beef - Bones, Marrow', 4.3);
insert into prigrizek (ime, cena) values ('Cookie Choc', 4.22);
insert into prigrizek (ime, cena) values ('V8 Splash Strawberry Kiwi', 4.63);
insert into prigrizek (ime, cena) values ('Pumpkin - Seed', 5.38);
insert into prigrizek (ime, cena) values ('Tahini Paste', 3.88);
insert into prigrizek (ime, cena) values ('Grapefruit - White', 3.44);
insert into prigrizek (ime, cena) values ('Longos - Lasagna Veg', 2.87);
insert into prigrizek (ime, cena) values ('Iced Tea - Lemon, 460 Ml', 1.56);
insert into prigrizek (ime, cena) values ('Wine - Gewurztraminer Pierre', 1.22);
insert into prigrizek (ime, cena) values ('Squash - Butternut', 6.99);
insert into prigrizek (ime, cena) values ('Browning Caramel Glace', 7.85);
insert into prigrizek (ime, cena) values ('Chilli Paste, Sambal Oelek', 2.58);
insert into prigrizek (ime, cena) values ('Garlic - Primerba, Paste', 7.42);
insert into prigrizek (ime, cena) values ('Wiberg Cure', 1.21);
insert into prigrizek (ime, cena) values ('Bacardi Limon', 2.52);
insert into prigrizek (ime, cena) values ('Phyllo Dough', 3.51);
insert into prigrizek (ime, cena) values ('Yogurt - Plain', 2.59);
insert into prigrizek (ime, cena) values ('Ham - Procutinni', 6.1);
insert into prigrizek (ime, cena) values ('Sugar - Palm', 7.85);
insert into prigrizek (ime, cena) values ('Flower - Daisies', 4.09);
insert into prigrizek (ime, cena) values ('Sour Puss - Tangerine', 3.76);
insert into prigrizek (ime, cena) values ('Beef - Tongue, Fresh', 5.97);
insert into prigrizek (ime, cena) values ('Wine - Pinot Noir Stoneleigh', 2.39);
insert into prigrizek (ime, cena) values ('Lemonade - Kiwi, 591 Ml', 2.17);
insert into prigrizek (ime, cena) values ('Pie Pecan', 4.38);
insert into prigrizek (ime, cena) values ('Coffee - Egg Nog Capuccino', 2.76);
insert into prigrizek (ime, cena) values ('Cranberries - Frozen', 2.83);
insert into prigrizek (ime, cena) values ('Sproutsmustard Cress', 3.0);
insert into prigrizek (ime, cena) values ('Rice Pilaf, Dry,package', 1.64);
insert into prigrizek (ime, cena) values ('Turnip - Mini', 1.31);
insert into prigrizek (ime, cena) values ('Pepper - Red, Finger Hot', 6.31);
insert into prigrizek (ime, cena) values ('Plate - Foam, Bread And Butter', 4.52);
insert into prigrizek (ime, cena) values ('Numi - Assorted Teas', 2.28);
insert into prigrizek (ime, cena) values ('Compound - Passion Fruit', 5.04);
insert into prigrizek (ime, cena) values ('Chicken - Base', 1.77);
insert into prigrizek (ime, cena) values ('Container - Clear 32 Oz', 4.31);
insert into prigrizek (ime, cena) values ('Steel Wool S.o.s', 3.44);
insert into prigrizek (ime, cena) values ('Melon - Honey Dew', 6.0);
insert into prigrizek (ime, cena) values ('Lettuce - Curly Endive', 4.18);
insert into prigrizek (ime, cena) values ('Bread - Raisin', 5.82);
insert into prigrizek (ime, cena) values ('Olives - Black, Pitted', 3.57);
insert into prigrizek (ime, cena) values ('Pepper - Green', 2.29);
insert into prigrizek (ime, cena) values ('Cheese - Cambozola', 5.85);
insert into prigrizek (ime, cena) values ('Chicken - Diced, Cooked', 3.33);
insert into prigrizek (ime, cena) values ('Bread - Italian Roll With Herbs', 4.29);
insert into prigrizek (ime, cena) values ('Bread - White, Sliced', 3.05);
insert into prigrizek (ime, cena) values ('Oven Mitts - 15 Inch', 7.21);
insert into prigrizek (ime, cena) values ('Bread - Pullman, Sliced', 7.23);
insert into prigrizek (ime, cena) values ('Myers Planters Punch', 3.13);
insert into prigrizek (ime, cena) values ('Fish - Atlantic Salmon, Cold', 2.02);
insert into prigrizek (ime, cena) values ('Glaze - Apricot', 5.4);
insert into prigrizek (ime, cena) values ('Orange Roughy 6/8 Oz', 7.58);
insert into prigrizek (ime, cena) values ('Nut - Hazelnut, Whole', 4.73);
insert into prigrizek (ime, cena) values ('Sauce - Fish 25 Ozf Bottle', 3.39);
insert into prigrizek (ime, cena) values ('Cheese - Marble', 2.42);
insert into prigrizek (ime, cena) values ('Bread Cranberry Foccacia', 1.32);
insert into prigrizek (ime, cena) values ('Chilli Paste, Sambal Oelek', 7.77);
insert into prigrizek (ime, cena) values ('Celery Root', 1.87);
insert into prigrizek (ime, cena) values ('Pasta - Fettuccine, Egg, Fresh', 3.57);
insert into prigrizek (ime, cena) values ('Appetizer - Seafood Assortment', 7.58);
insert into prigrizek (ime, cena) values ('Juice - Orange', 1.48);
insert into prigrizek (ime, cena) values ('Table Cloth 53x53 White', 2.26);
insert into prigrizek (ime, cena) values ('Salmon - Smoked, Sliced', 4.34);
insert into prigrizek (ime, cena) values ('Vermouth - Sweet, Cinzano', 6.21);
insert into prigrizek (ime, cena) values ('Tuna - Fresh', 4.94);
insert into prigrizek (ime, cena) values ('Longos - Assorted Sandwich', 4.72);
insert into prigrizek (ime, cena) values ('Whmis - Spray Bottle Trigger', 5.82);
insert into prigrizek (ime, cena) values ('Cheese - Parmigiano Reggiano', 2.84);
insert into prigrizek (ime, cena) values ('Shichimi Togarashi Peppeers', 6.2);
insert into prigrizek (ime, cena) values ('Sorrel - Fresh', 6.81);
insert into prigrizek (ime, cena) values ('Longos - Grilled Chicken With', 7.7);
insert into prigrizek (ime, cena) values ('Pepper - Black, Crushed', 5.91);
insert into prigrizek (ime, cena) values ('Wine - Cotes Du Rhone Parallele', 1.5);
insert into prigrizek (ime, cena) values ('Water, Tap', 7.98);
insert into prigrizek (ime, cena) values ('Table Cloth 91x91 Colour', 3.41);
insert into prigrizek (ime, cena) values ('Sauce - Plum', 5.4);
insert into prigrizek (ime, cena) values ('Pie Shell - 5', 2.22);
insert into prigrizek (ime, cena) values ('Icecream - Dibs', 5.57);
insert into prigrizek (ime, cena) values ('Fond - Neutral', 5.99);
insert into prigrizek (ime, cena) values ('Wine - Taylors Reserve', 3.63);
insert into prigrizek (ime, cena) values ('Ice Cream - Chocolate', 1.76);
insert into prigrizek (ime, cena) values ('Orange - Blood', 7.87);
insert into prigrizek (ime, cena) values ('Carrots - Purple, Organic', 1.34);
insert into prigrizek (ime, cena) values ('Quail - Jumbo', 1.53);
insert into prigrizek (ime, cena) values ('Soup - Campbells Mac N Cheese', 5.07);
insert into prigrizek (ime, cena) values ('Wine - Periguita Fonseca', 6.19);
insert into prigrizek (ime, cena) values ('Lamb - Whole, Fresh', 1.01);
insert into prigrizek (ime, cena) values ('Munchies Honey Sweet Trail Mix', 3.44);
insert into prigrizek (ime, cena) values ('Bandage - Finger Cots', 7.62);
insert into prigrizek (ime, cena) values ('Pasta - Spaghetti, Dry', 3.2);
insert into prigrizek (ime, cena) values ('Parasol Pick Stir Stick', 3.8);
insert into prigrizek (ime, cena) values ('Banana', 2.48);
insert into prigrizek (ime, cena) values ('Radish - Pickled', 6.68);
insert into prigrizek (ime, cena) values ('Trout - Hot Smkd, Dbl Fillet', 7.22);
insert into prigrizek (ime, cena) values ('Tahini Paste', 5.13);
insert into prigrizek (ime, cena) values ('Wine - Crozes Hermitage E.', 2.47);
insert into prigrizek (ime, cena) values ('Mcgillicuddy Vanilla Schnap', 7.66);
insert into prigrizek (ime, cena) values ('Lamb - Leg, Diced', 1.56);
insert into prigrizek (ime, cena) values ('Soup - Knorr, Chicken Gumbo', 1.06);
insert into prigrizek (ime, cena) values ('Marsala - Sperone, Fine, D.o.c.', 1.41);
insert into prigrizek (ime, cena) values ('French Pastries', 5.2);
insert into prigrizek (ime, cena) values ('Wine - Clavet Saint Emilion', 1.01);
insert into prigrizek (ime, cena) values ('Corn Meal', 4.77);
insert into prigrizek (ime, cena) values ('Vinegar - Sherry', 2.82);
insert into prigrizek (ime, cena) values ('Oil - Olive Bertolli', 6.49);
insert into prigrizek (ime, cena) values ('Sproutsmustard Cress', 3.89);
insert into prigrizek (ime, cena) values ('Coffee - Espresso', 4.65);
insert into prigrizek (ime, cena) values ('Pepsi, 355 Ml', 2.56);
insert into prigrizek (ime, cena) values ('Bread - Multigrain', 5.64);
insert into prigrizek (ime, cena) values ('Truffle Cups - Brown', 4.15);
insert into prigrizek (ime, cena) values ('Cheese Cloth No 60', 4.15);
insert into prigrizek (ime, cena) values ('Bread - Assorted Rolls', 4.85);
insert into prigrizek (ime, cena) values ('Chocolate - Pistoles, Lactee, Milk', 7.8);
insert into prigrizek (ime, cena) values ('Salsify, Organic', 2.8);
insert into prigrizek (ime, cena) values ('The Pop Shoppe - Lime Rickey', 2.2);
insert into prigrizek (ime, cena) values ('Energy - Boo - Koo', 2.88);
insert into prigrizek (ime, cena) values ('Chocolate - Semi Sweet, Calets', 4.0);
insert into prigrizek (ime, cena) values ('Browning Caramel Glace', 2.09);
insert into prigrizek (ime, cena) values ('Bread - Dark Rye, Loaf', 3.89);
insert into prigrizek (ime, cena) values ('Sauce - Thousand Island', 1.6);
insert into prigrizek (ime, cena) values ('Water - Spring Water 500ml', 2.42);
insert into prigrizek (ime, cena) values ('Wine - Marlbourough Sauv Blanc', 2.59);
insert into prigrizek (ime, cena) values ('Monkfish Fresh - Skin Off', 2.13);
insert into prigrizek (ime, cena) values ('Wine - Ruffino Chianti Classico', 6.21);
insert into prigrizek (ime, cena) values ('Sea Bass - Fillets', 5.68);
insert into prigrizek (ime, cena) values ('Rum - Dark, Bacardi, Black', 2.58);
insert into prigrizek (ime, cena) values ('Langers - Cranberry Cocktail', 7.77);
insert into prigrizek (ime, cena) values ('Lentils - Red, Dry', 6.88);
insert into prigrizek (ime, cena) values ('Flower - Potmums', 1.63);
insert into prigrizek (ime, cena) values ('Monkfish Fresh - Skin Off', 6.87);
insert into prigrizek (ime, cena) values ('Wine - Red, Wolf Blass, Yellow', 6.8);
insert into prigrizek (ime, cena) values ('Pepper - Pablano', 4.28);
insert into prigrizek (ime, cena) values ('Soup - French Onion, Dry', 2.34);
insert into prigrizek (ime, cena) values ('Pork Loin Cutlets', 5.35);
insert into prigrizek (ime, cena) values ('Chocolate - Milk Coating', 1.77);
insert into prigrizek (ime, cena) values ('Coconut - Whole', 4.91);
insert into prigrizek (ime, cena) values ('Pop Shoppe Cream Soda', 4.04);
insert into prigrizek (ime, cena) values ('Soup - Campbells, Minestrone', 4.05);
insert into prigrizek (ime, cena) values ('Dried Apple', 3.82);
insert into prigrizek (ime, cena) values ('Ice Cream - Life Savers', 6.73);
insert into prigrizek (ime, cena) values ('Ice Cream Bar - Oreo Cone', 4.89);
insert into prigrizek (ime, cena) values ('Lettuce - Baby Salad Greens', 1.13);
insert into prigrizek (ime, cena) values ('Beer - Muskoka Cream Ale', 2.09);
insert into prigrizek (ime, cena) values ('Bagel - Everything Presliced', 4.38);
insert into prigrizek (ime, cena) values ('Pasta - Fett Alfredo, Single Serve', 7.62);
insert into prigrizek (ime, cena) values ('Ginger - Pickled', 4.89);
insert into prigrizek (ime, cena) values ('Beef Ground Medium', 5.51);
insert into prigrizek (ime, cena) values ('Shrimp - Black Tiger 26/30', 2.91);
insert into prigrizek (ime, cena) values ('Juice - Cranberry, 341 Ml', 6.81);
insert into prigrizek (ime, cena) values ('Pepper Squash', 3.0);
insert into prigrizek (ime, cena) values ('Crackers - Melba Toast', 5.85);
insert into prigrizek (ime, cena) values ('Spice - Montreal Steak Spice', 2.74);
insert into prigrizek (ime, cena) values ('Wine - Sauvignon Blanc Oyster', 7.17);
insert into prigrizek (ime, cena) values ('Puff Pastry - Sheets', 3.7);
insert into prigrizek (ime, cena) values ('Wine - Two Oceans Cabernet', 5.7);
insert into prigrizek (ime, cena) values ('Cream - 10%', 5.39);
insert into prigrizek (ime, cena) values ('Cookie Double Choco', 1.17);
insert into prigrizek (ime, cena) values ('Bar Mix - Lime', 4.71);
insert into prigrizek (ime, cena) values ('Stock - Veal, White', 2.44);
insert into prigrizek (ime, cena) values ('Wine - White, Riesling, Henry Of', 5.5);
insert into prigrizek (ime, cena) values ('Tamarillo', 6.47);
insert into prigrizek (ime, cena) values ('Soup - Campbells', 4.34);
insert into prigrizek (ime, cena) values ('Bagel - 12 Grain Preslice', 3.02);
insert into prigrizek (ime, cena) values ('Potatoes - Pei 10 Oz', 6.73);
insert into prigrizek (ime, cena) values ('Veal - Striploin', 6.89);
insert into prigrizek (ime, cena) values ('Veal - Leg', 3.16);
insert into prigrizek (ime, cena) values ('Silicone Parch. 16.3x24.3', 5.05);
insert into prigrizek (ime, cena) values ('Lamb - Bones', 5.5);
insert into prigrizek (ime, cena) values ('Lobster - Cooked', 2.69);
insert into prigrizek (ime, cena) values ('Chocolate Liqueur - Godet White', 2.05);
insert into prigrizek (ime, cena) values ('Yogurt - Strawberry, 175 Gr', 5.73);
insert into prigrizek (ime, cena) values ('Blackberries', 7.09);
insert into prigrizek (ime, cena) values ('Garlic - Primerba, Paste', 5.75);
insert into prigrizek (ime, cena) values ('Cake - Mini Cheesecake', 6.99);
insert into prigrizek (ime, cena) values ('Coffee - French Vanilla Frothy', 7.24);
insert into prigrizek (ime, cena) values ('Pasta - Lasagna Noodle, Frozen', 3.07);
insert into prigrizek (ime, cena) values ('Fondant - Icing', 3.08);
insert into prigrizek (ime, cena) values ('Tart Shells - Savory, 2', 6.55);
insert into prigrizek (ime, cena) values ('Tomato - Green', 4.97);
insert into prigrizek (ime, cena) values ('V8 - Vegetable Cocktail', 4.11);
insert into prigrizek (ime, cena) values ('Horseradish Root', 1.27);
insert into prigrizek (ime, cena) values ('Roe - White Fish', 5.26);
insert into prigrizek (ime, cena) values ('Nut - Walnut, Chopped', 3.3);
insert into prigrizek (ime, cena) values ('Fond - Neutral', 5.86);
insert into prigrizek (ime, cena) values ('Soup V8 Roasted Red Pepper', 5.98);
insert into prigrizek (ime, cena) values ('Chinese Foods - Thick Noodles', 1.37);
insert into prigrizek (ime, cena) values ('Juice - Lime', 1.05);
insert into prigrizek (ime, cena) values ('Melon - Cantaloupe', 3.64);
insert into prigrizek (ime, cena) values ('Pasta - Fusili, Dry', 6.49);
insert into prigrizek (ime, cena) values ('Butter - Unsalted', 6.91);
insert into prigrizek (ime, cena) values ('Wine - Prosecco Valdobienne', 6.97);
insert into prigrizek (ime, cena) values ('Scallops - 10/20', 2.63);
insert into prigrizek (ime, cena) values ('Bag - Regular Kraft 20 Lb', 5.28);
insert into prigrizek (ime, cena) values ('Pickerel - Fillets', 7.86);
insert into prigrizek (ime, cena) values ('Coffee Caramel Biscotti', 2.95);
insert into prigrizek (ime, cena) values ('Bandage - Finger Cots', 3.41);
insert into prigrizek (ime, cena) values ('Lettuce - Lolla Rosa', 3.65);
insert into prigrizek (ime, cena) values ('Beef - Eye Of Round', 1.07);
insert into prigrizek (ime, cena) values ('Salmon - Smoked, Sliced', 7.1);
insert into prigrizek (ime, cena) values ('Cheese - Ermite Bleu', 2.9);
insert into prigrizek (ime, cena) values ('Brandy Apricot', 6.46);
insert into prigrizek (ime, cena) values ('Sprouts - Alfalfa', 3.34);
insert into prigrizek (ime, cena) values ('Wine - Shiraz South Eastern', 5.01);
insert into prigrizek (ime, cena) values ('Liqueur Banana, Ramazzotti', 7.72);
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Bel Paese White', 2.94);
insert into prigrizek (ime, cena) values ('Chocolate - Feathers', 7.57);
insert into prigrizek (ime, cena) values ('Truffle Cups - White Paper', 3.03);
insert into prigrizek (ime, cena) values ('Soap - Pine Sol Floor Cleaner', 1.91);
insert into prigrizek (ime, cena) values ('Cookies - Englishbay Chochip', 3.26);
insert into prigrizek (ime, cena) values ('Rice - Aborio', 4.95);
insert into prigrizek (ime, cena) values ('Wine - Soave Folonari', 5.73);
insert into prigrizek (ime, cena) values ('Tart - Lemon', 7.39);
insert into prigrizek (ime, cena) values ('Pork - Bacon, Double Smoked', 2.98);
insert into prigrizek (ime, cena) values ('Chicken Giblets', 5.22);
insert into prigrizek (ime, cena) values ('Bread - Rolls, Corn', 2.83);
insert into prigrizek (ime, cena) values ('Soup - Tomato Mush. Florentine', 5.39);
insert into prigrizek (ime, cena) values ('Cake - Lemon Chiffon', 7.19);
insert into prigrizek (ime, cena) values ('Bols Melon Liqueur', 7.3);
insert into prigrizek (ime, cena) values ('Wine - Saint - Bris 2002, Sauv', 5.2);
insert into prigrizek (ime, cena) values ('Wine - Cava Aria Estate Brut', 7.59);
insert into prigrizek (ime, cena) values ('Beef Cheek Fresh', 2.63);
insert into prigrizek (ime, cena) values ('Rice Wine - Aji Mirin', 6.22);
insert into prigrizek (ime, cena) values ('Spinach - Spinach Leaf', 6.76);
insert into prigrizek (ime, cena) values ('Sauce - Bernaise, Mix', 3.38);
insert into prigrizek (ime, cena) values ('Salmon - Atlantic, No Skin', 7.87);
insert into prigrizek (ime, cena) values ('Beer - Maudite', 7.17);
insert into prigrizek (ime, cena) values ('Lid - High Heat, Super Clear', 1.07);
insert into prigrizek (ime, cena) values ('Pasta - Shells, Medium, Dry', 4.05);
insert into prigrizek (ime, cena) values ('Canada Dry', 4.84);
insert into prigrizek (ime, cena) values ('Cheese - Gouda', 3.14);
insert into prigrizek (ime, cena) values ('Fish - Base, Bouillion', 3.48);
insert into prigrizek (ime, cena) values ('Tuna - Loin', 1.43);
insert into prigrizek (ime, cena) values ('Muffin Mix - Raisin Bran', 3.12);
insert into prigrizek (ime, cena) values ('Chocolate - Chips Compound', 7.97);
insert into prigrizek (ime, cena) values ('Quiche Assorted', 5.77);
insert into prigrizek (ime, cena) values ('Vinegar - White Wine', 5.33);
insert into prigrizek (ime, cena) values ('Cheese - Brie,danish', 4.88);
insert into prigrizek (ime, cena) values ('Foil - Round Foil', 5.77);
insert into prigrizek (ime, cena) values ('Crab - Dungeness, Whole', 4.41);
insert into prigrizek (ime, cena) values ('Rosemary - Primerba, Paste', 3.34);
insert into prigrizek (ime, cena) values ('Muffin Hinge 117n', 7.76);
insert into prigrizek (ime, cena) values ('Pepper - Red Chili', 4.56);
insert into prigrizek (ime, cena) values ('Veal - Brisket, Provimi,bnls', 7.58);
insert into prigrizek (ime, cena) values ('Wine - Touraine Azay - Le - Rideau', 4.11);
insert into prigrizek (ime, cena) values ('Pesto - Primerba, Paste', 5.31);
insert into prigrizek (ime, cena) values ('Gelatine Powder', 3.61);
insert into prigrizek (ime, cena) values ('Spinach - Frozen', 2.85);
insert into prigrizek (ime, cena) values ('Oil - Avocado', 5.65);
insert into prigrizek (ime, cena) values ('Vinegar - Cider', 6.2);
insert into prigrizek (ime, cena) values ('Shrimp - 16/20, Peeled Deviened', 2.45);
insert into prigrizek (ime, cena) values ('Star Anise, Whole', 6.0);
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Cab Sauv', 2.09);
insert into prigrizek (ime, cena) values ('Eel - Smoked', 4.89);
insert into prigrizek (ime, cena) values ('Soup - Knorr, Ministrone', 4.74);
insert into prigrizek (ime, cena) values ('Cotton Wet Mop 16 Oz', 7.48);
insert into prigrizek (ime, cena) values ('Papadam', 1.71);
insert into prigrizek (ime, cena) values ('Gatorade - Orange', 6.56);
insert into prigrizek (ime, cena) values ('Muffin - Zero Transfat', 2.26);
insert into prigrizek (ime, cena) values ('Sauce - Fish 25 Ozf Bottle', 5.13);
insert into prigrizek (ime, cena) values ('Longos - Penne With Pesto', 4.34);
insert into prigrizek (ime, cena) values ('Rice - 7 Grain Blend', 7.64);
insert into prigrizek (ime, cena) values ('Green Scrubbie Pad H.duty', 3.67);
insert into prigrizek (ime, cena) values ('Bulgar', 5.85);
insert into prigrizek (ime, cena) values ('Soup - Cream Of Potato / Leek', 6.75);
insert into prigrizek (ime, cena) values ('Soup - Campbells, Butternut', 6.48);
insert into prigrizek (ime, cena) values ('Bagels Poppyseed', 7.77);
insert into prigrizek (ime, cena) values ('Bread - Wheat Baguette', 5.61);
insert into prigrizek (ime, cena) values ('Bread - Crumbs, Bulk', 4.0);
insert into prigrizek (ime, cena) values ('Table Cloth 81x81 White', 3.1);
insert into prigrizek (ime, cena) values ('Pastry - Butterscotch Baked', 7.58);
insert into prigrizek (ime, cena) values ('Wine - Merlot Vina Carmen', 3.3);
insert into prigrizek (ime, cena) values ('Durian Fruit', 4.6);
insert into prigrizek (ime, cena) values ('Wine - Chateauneuf Du Pape', 1.69);
insert into prigrizek (ime, cena) values ('Wine - White, Chardonnay', 7.02);
insert into prigrizek (ime, cena) values ('Cup - 4oz Translucent', 1.5);
insert into prigrizek (ime, cena) values ('Shiro Miso', 5.82);
insert into prigrizek (ime, cena) values ('Rye Special Old', 3.95);
insert into prigrizek (ime, cena) values ('English Muffin', 6.54);
insert into prigrizek (ime, cena) values ('Mushroom - Portebello', 3.99);
insert into prigrizek (ime, cena) values ('Bandage - Finger Cots', 1.43);
insert into prigrizek (ime, cena) values ('Cookie Dough - Oatmeal Rasin', 3.63);
insert into prigrizek (ime, cena) values ('Schnappes - Peach, Walkers', 1.7);
insert into prigrizek (ime, cena) values ('Bagelers - Cinn / Brown', 2.85);
insert into prigrizek (ime, cena) values ('Juice - Mango', 5.26);
insert into prigrizek (ime, cena) values ('Shrimp - Black Tiger 13/15', 4.39);
insert into prigrizek (ime, cena) values ('Cheese - Sheep Milk', 6.25);
insert into prigrizek (ime, cena) values ('Soupcontfoam16oz 116con', 7.34);
insert into prigrizek (ime, cena) values ('Foil - Round Foil', 3.23);
insert into prigrizek (ime, cena) values ('Salmon - Smoked, Sliced', 7.33);
insert into prigrizek (ime, cena) values ('Lemonade - Island Tea, 591 Ml', 3.1);
insert into prigrizek (ime, cena) values ('Coffee Cup 12oz 5342cd', 3.98);
insert into prigrizek (ime, cena) values ('Beer - Camerons Cream Ale', 4.95);
insert into prigrizek (ime, cena) values ('Carbonated Water - Blackcherry', 1.96);
insert into prigrizek (ime, cena) values ('Scampi Tail', 5.36);
insert into prigrizek (ime, cena) values ('Cassis', 7.69);
insert into prigrizek (ime, cena) values ('Cornish Hen', 1.8);
insert into prigrizek (ime, cena) values ('Muffin - Mix - Creme Brule 15l', 7.57);
insert into prigrizek (ime, cena) values ('Turkey - Oven Roast Breast', 7.98);
insert into prigrizek (ime, cena) values ('Tofu - Firm', 7.35);
insert into prigrizek (ime, cena) values ('Vinegar - Rice', 5.1);
insert into prigrizek (ime, cena) values ('Bar Special K', 6.56);
insert into prigrizek (ime, cena) values ('Aromat Spice / Seasoning', 2.03);
insert into prigrizek (ime, cena) values ('Ginger - Ground', 5.79);
insert into prigrizek (ime, cena) values ('Wine - Peller Estates Late', 5.78);
insert into prigrizek (ime, cena) values ('Sardines', 2.02);
insert into prigrizek (ime, cena) values ('Table Cloth 54x72 Colour', 7.8);
insert into prigrizek (ime, cena) values ('Crab - Dungeness, Whole, live', 4.65);
insert into prigrizek (ime, cena) values ('Muffin - Carrot Individual Wrap', 2.66);
insert into prigrizek (ime, cena) values ('Apple - Fuji', 3.8);
insert into prigrizek (ime, cena) values ('Wine - Red, Wolf Blass, Yellow', 2.2);
insert into prigrizek (ime, cena) values ('Wine - Red, Cabernet Sauvignon', 4.38);
insert into prigrizek (ime, cena) values ('Sprouts - Brussel', 3.65);
insert into prigrizek (ime, cena) values ('Oranges', 6.79);
insert into prigrizek (ime, cena) values ('Sprouts - Baby Pea Tendrils', 1.48);
insert into prigrizek (ime, cena) values ('Snapple Lemon Tea', 5.03);
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Belpaese', 5.44);
insert into prigrizek (ime, cena) values ('Wine - Penfolds Koonuga Hill', 5.9);
insert into prigrizek (ime, cena) values ('Lotus Root', 6.03);
insert into prigrizek (ime, cena) values ('Cake - Dulce De Leche', 4.39);
insert into prigrizek (ime, cena) values ('Onions - Green', 1.53);
insert into prigrizek (ime, cena) values ('Rum - Spiced, Captain Morgan', 4.82);
insert into prigrizek (ime, cena) values ('Stock - Fish', 6.9);
insert into prigrizek (ime, cena) values ('Star Fruit', 7.04);
insert into prigrizek (ime, cena) values ('Mushrooms - Honey', 4.98);
insert into prigrizek (ime, cena) values ('Nori Sea Weed', 1.08);
insert into prigrizek (ime, cena) values ('Sloe Gin - Mcguinness', 7.28);
insert into prigrizek (ime, cena) values ('Pan Grease', 1.23);
insert into prigrizek (ime, cena) values ('Coconut - Creamed, Pure', 7.99);
insert into prigrizek (ime, cena) values ('Oregano - Fresh', 5.77);
insert into prigrizek (ime, cena) values ('Syrup - Chocolate', 5.77);
insert into prigrizek (ime, cena) values ('Barley - Pearl', 5.12);
insert into prigrizek (ime, cena) values ('Crab Brie In Phyllo', 5.03);
insert into prigrizek (ime, cena) values ('Steam Pan Full Lid', 5.23);
insert into prigrizek (ime, cena) values ('Salmon - Whole, 4 - 6 Pounds', 4.42);
insert into prigrizek (ime, cena) values ('Mangoes', 5.77);
insert into prigrizek (ime, cena) values ('Basil - Thai', 7.36);
insert into prigrizek (ime, cena) values ('Beer - True North Lager', 3.35);
insert into prigrizek (ime, cena) values ('Chef Hat 25cm', 7.05);
insert into prigrizek (ime, cena) values ('Mint - Fresh', 5.01);
insert into prigrizek (ime, cena) values ('Appetizer - Tarragon Chicken', 3.6);
insert into prigrizek (ime, cena) values ('Jam - Strawberry, 20 Ml Jar', 5.75);
insert into prigrizek (ime, cena) values ('Daikon Radish', 1.96);
insert into prigrizek (ime, cena) values ('Pork - Bacon, Sliced', 3.12);
insert into prigrizek (ime, cena) values ('Jerusalem Artichoke', 7.77);
insert into prigrizek (ime, cena) values ('Eggroll', 3.29);
insert into prigrizek (ime, cena) values ('Wine - Tribal Sauvignon', 4.55);
insert into prigrizek (ime, cena) values ('Apple - Delicious, Red', 2.97);
insert into prigrizek (ime, cena) values ('Oil - Coconut', 1.41);
insert into prigrizek (ime, cena) values ('Pork - Shoulder', 5.29);
insert into prigrizek (ime, cena) values ('Horseradish Root', 2.34);
insert into prigrizek (ime, cena) values ('Soup Campbells - Italian Wedding', 5.13);
insert into prigrizek (ime, cena) values ('Ice Cream - Fudge Bars', 1.38);
insert into prigrizek (ime, cena) values ('Kahlua', 3.2);
insert into prigrizek (ime, cena) values ('Filling - Mince Meat', 4.97);
insert into prigrizek (ime, cena) values ('Oil - Hazelnut', 5.44);
insert into prigrizek (ime, cena) values ('Chocolate - Milk, Callets', 7.18);
insert into prigrizek (ime, cena) values ('Rum - Light, Captain Morgan', 7.73);
insert into prigrizek (ime, cena) values ('Dc - Frozen Momji', 7.2);
insert into prigrizek (ime, cena) values ('Radish', 3.84);
insert into prigrizek (ime, cena) values ('Wine - Red, Gamay Noir', 2.35);
insert into prigrizek (ime, cena) values ('Chef Hat 25cm', 2.12);
insert into prigrizek (ime, cena) values ('Beef - Tenderloin - Aa', 6.09);
insert into prigrizek (ime, cena) values ('Clams - Littleneck, Whole', 2.37);
insert into prigrizek (ime, cena) values ('Gherkin - Sour', 2.68);
insert into prigrizek (ime, cena) values ('Foil - 4oz Custard Cup', 4.86);
insert into prigrizek (ime, cena) values ('Appetizer - Veg Assortment', 7.1);
insert into prigrizek (ime, cena) values ('Sugar - Cubes', 6.25);
insert into prigrizek (ime, cena) values ('Truffle Paste', 6.05);
insert into prigrizek (ime, cena) values ('Truffle Cups - Brown', 7.72);
insert into prigrizek (ime, cena) values ('Lettuce - Escarole', 7.58);
insert into prigrizek (ime, cena) values ('Sauce Tomato Pouch', 4.11);
insert into prigrizek (ime, cena) values ('Raspberries - Frozen', 5.02);
insert into prigrizek (ime, cena) values ('Turkey - Breast, Smoked', 2.9);
insert into prigrizek (ime, cena) values ('Mace', 4.66);
insert into prigrizek (ime, cena) values ('Remy Red', 6.96);
insert into prigrizek (ime, cena) values ('Mortadella', 5.77);
insert into prigrizek (ime, cena) values ('Bread - Italian Sesame Poly', 7.15);
insert into prigrizek (ime, cena) values ('Cookie Dough - Double', 2.28);
insert into prigrizek (ime, cena) values ('Miso Paste White', 4.1);
insert into prigrizek (ime, cena) values ('Beans - Soya Bean', 2.6);
insert into prigrizek (ime, cena) values ('Hersey Shakes', 5.87);
insert into prigrizek (ime, cena) values ('Wine - Beaujolais Villages', 7.95);
insert into prigrizek (ime, cena) values ('Wine - Vovray Sec Domaine Huet', 3.44);
insert into prigrizek (ime, cena) values ('Lobster - Base', 1.5);
insert into prigrizek (ime, cena) values ('Cocoa Powder - Natural', 1.35);
insert into prigrizek (ime, cena) values ('Cranberries - Frozen', 1.26);
insert into prigrizek (ime, cena) values ('Napkin - Beverage 1 Ply', 3.2);
insert into prigrizek (ime, cena) values ('Wine - Red, Pinot Noir, Chateau', 7.41);
insert into prigrizek (ime, cena) values ('Lid - 0090 Clear', 3.22);
insert into prigrizek (ime, cena) values ('Beans - Black Bean, Canned', 3.57);
insert into prigrizek (ime, cena) values ('Wine - Gewurztraminer Pierre', 2.29);
insert into prigrizek (ime, cena) values ('Squash - Pepper', 5.7);
insert into prigrizek (ime, cena) values ('Rice - Jasmine Sented', 5.33);
insert into prigrizek (ime, cena) values ('Ham - Smoked, Bone - In', 4.57);
insert into prigrizek (ime, cena) values ('Rosemary - Fresh', 4.4);
insert into prigrizek (ime, cena) values ('Stock - Chicken, White', 2.35);
insert into prigrizek (ime, cena) values ('Fish - Atlantic Salmon, Cold', 1.28);
insert into prigrizek (ime, cena) values ('Bagel - Whole White Sesame', 7.41);
insert into prigrizek (ime, cena) values ('Chick Peas - Canned', 2.77);
insert into prigrizek (ime, cena) values ('Frangelico', 3.1);
insert into prigrizek (ime, cena) values ('Cheese - Ermite Bleu', 3.12);
insert into prigrizek (ime, cena) values ('Spinach - Spinach Leaf', 4.02);
insert into prigrizek (ime, cena) values ('Crab Meat Claw Pasteurise', 7.33);
insert into prigrizek (ime, cena) values ('Dried Cranberries', 7.38);
insert into prigrizek (ime, cena) values ('Squash - Pattypan, Yellow', 6.6);
insert into prigrizek (ime, cena) values ('Mahi Mahi', 7.47);
insert into prigrizek (ime, cena) values ('Mortadella', 6.72);
insert into prigrizek (ime, cena) values ('Garlic Powder', 3.51);
insert into prigrizek (ime, cena) values ('Bread Fig And Almond', 7.49);
insert into prigrizek (ime, cena) values ('Tart Shells - Savory, 3', 2.21);
insert into prigrizek (ime, cena) values ('Bacardi Mojito', 3.24);
insert into prigrizek (ime, cena) values ('Pork - Sausage Casing', 6.92);
insert into prigrizek (ime, cena) values ('Veal - Liver', 4.55);
insert into prigrizek (ime, cena) values ('Pear - Packum', 1.9);
insert into prigrizek (ime, cena) values ('Vinegar - Raspberry', 7.88);
insert into prigrizek (ime, cena) values ('Tea - Orange Pekoe', 7.74);
insert into prigrizek (ime, cena) values ('Wine - Barbera Alba Doc 2001', 3.04);
insert into prigrizek (ime, cena) values ('Chocolate - White', 3.27);
insert into prigrizek (ime, cena) values ('Versatainer Nc - 8288', 1.18);
insert into prigrizek (ime, cena) values ('Wine - Wyndham Estate Bin 777', 4.67);
insert into prigrizek (ime, cena) values ('Wine - Magnotta - Cab Franc', 7.23);
insert into prigrizek (ime, cena) values ('Bread - Focaccia Quarter', 6.99);
insert into prigrizek (ime, cena) values ('Coffee Caramel Biscotti', 4.23);
insert into prigrizek (ime, cena) values ('Wine - White, Chardonnay', 3.83);
insert into prigrizek (ime, cena) values ('Cilantro / Coriander - Fresh', 7.95);
insert into prigrizek (ime, cena) values ('Ezy Change Mophandle', 2.48);
insert into prigrizek (ime, cena) values ('Cheese Cheddar Processed', 1.87);
insert into prigrizek (ime, cena) values ('Soup - Campbells Broccoli', 7.76);
insert into prigrizek (ime, cena) values ('Beef - Sushi Flat Iron Steak', 6.64);
insert into prigrizek (ime, cena) values ('Pepper - Red, Finger Hot', 4.09);
insert into prigrizek (ime, cena) values ('Saskatoon Berries - Frozen', 6.46);
insert into prigrizek (ime, cena) values ('Melon - Honey Dew', 4.16);
insert into prigrizek (ime, cena) values ('Dill Weed - Dry', 4.66);
insert into prigrizek (ime, cena) values ('Bread - Bistro White', 5.99);
insert into prigrizek (ime, cena) values ('Pie Shell - 5', 5.67);
insert into prigrizek (ime, cena) values ('Skewers - Bamboo', 5.13);
insert into prigrizek (ime, cena) values ('Flavouring - Raspberry', 1.13);
insert into prigrizek (ime, cena) values ('Gatorade - Lemon Lime', 7.61);
insert into prigrizek (ime, cena) values ('Wine - Saint - Bris 2002, Sauv', 5.57);
insert into prigrizek (ime, cena) values ('Wine - Black Tower Qr', 3.73);
insert into prigrizek (ime, cena) values ('Oil - Truffle, White', 7.55);
insert into prigrizek (ime, cena) values ('Roe - Lump Fish, Black', 6.08);
insert into prigrizek (ime, cena) values ('Parsley - Fresh', 1.76);
insert into prigrizek (ime, cena) values ('Tea - Jasmin Green', 1.89);
insert into prigrizek (ime, cena) values ('Vanilla Beans', 2.67);
insert into prigrizek (ime, cena) values ('Vodka - Hot, Lnferno', 7.4);
insert into prigrizek (ime, cena) values ('Wine - Guy Sage Touraine', 1.04);
insert into prigrizek (ime, cena) values ('Veal - Osso Bucco', 4.85);
insert into prigrizek (ime, cena) values ('Spoon - Soup, Plastic', 3.74);
insert into prigrizek (ime, cena) values ('Beef - Short Ribs', 2.72);
insert into prigrizek (ime, cena) values ('Bread - Rolls, Rye', 5.62);
insert into prigrizek (ime, cena) values ('Tea Leaves - Oolong', 3.02);
insert into prigrizek (ime, cena) values ('Pasta - Fusili, Dry', 6.49);
insert into prigrizek (ime, cena) values ('Sauce - Chili', 3.55);
insert into prigrizek (ime, cena) values ('Lid Tray - 16in Dome', 2.95);
insert into prigrizek (ime, cena) values ('Foil Cont Round', 1.73);
insert into prigrizek (ime, cena) values ('Energy Drink Bawls', 5.74);
insert into prigrizek (ime, cena) values ('Ezy Change Mophandle', 2.67);
insert into prigrizek (ime, cena) values ('Noodles - Steamed Chow Mein', 1.23);
insert into prigrizek (ime, cena) values ('Container - Hngd Cll Blk 7x7x3', 6.74);
insert into prigrizek (ime, cena) values ('Bread - English Muffin', 1.17);
insert into prigrizek (ime, cena) values ('Wine - Semi Dry Riesling Vineland', 4.31);
insert into prigrizek (ime, cena) values ('Juice - Apple 284ml', 2.35);
insert into prigrizek (ime, cena) values ('Wine - Shiraz Wolf Blass Premium', 4.05);
insert into prigrizek (ime, cena) values ('Pastry - Mini French Pastries', 6.34);
insert into prigrizek (ime, cena) values ('Spring Roll Veg Mini', 4.56);
insert into prigrizek (ime, cena) values ('Melon - Honey Dew', 5.93);
insert into prigrizek (ime, cena) values ('Chickensplit Half', 4.22);
insert into prigrizek (ime, cena) values ('Bandage - Fexible 1x3', 3.32);
insert into prigrizek (ime, cena) values ('Wine - Montecillo Rioja Crianza', 3.63);
insert into prigrizek (ime, cena) values ('Wine - Charddonnay Errazuriz', 4.91);
insert into prigrizek (ime, cena) values ('Wine - Fat Bastard Merlot', 7.76);
insert into prigrizek (ime, cena) values ('Pecan Raisin - Tarts', 5.38);
insert into prigrizek (ime, cena) values ('Cod - Salted, Boneless', 7.72);
insert into prigrizek (ime, cena) values ('Oats Large Flake', 3.77);
insert into prigrizek (ime, cena) values ('Sprouts - Peppercress', 6.69);
insert into prigrizek (ime, cena) values ('Cup - 6oz, Foam', 2.78);
insert into prigrizek (ime, cena) values ('Ecolab Crystal Fusion', 1.94);
insert into prigrizek (ime, cena) values ('Wine - Hardys Bankside Shiraz', 7.76);
insert into prigrizek (ime, cena) values ('Clam - Cherrystone', 6.29);
insert into prigrizek (ime, cena) values ('Devonshire Cream', 1.34);
insert into prigrizek (ime, cena) values ('Juice - Clamato, 341 Ml', 1.51);
insert into prigrizek (ime, cena) values ('Corn - Mini', 4.03);
insert into prigrizek (ime, cena) values ('Fuji Apples', 5.55);
