insert into prodaja (kino_ime, karta_id) values ('Tony', 1);
insert into prodaja (kino_ime, karta_id) values ('Farmco', 2);
insert into prodaja (kino_ime, karta_id) values ('Merry', 3);
insert into prodaja (kino_ime, karta_id) values ('Kropf', 4);
insert into prodaja (kino_ime, karta_id) values ('Little Fleur', 5);
insert into prodaja (kino_ime, karta_id) values ('Spohn', 6);
insert into prodaja (kino_ime, karta_id) values ('Union', 7);
insert into prodaja (kino_ime, karta_id) values ('Schiller', 8);
insert into prodaja (kino_ime, karta_id) values ('Bartillon', 9);
insert into prodaja (kino_ime, karta_id) values ('Darwin', 10);
insert into prodaja (kino_ime, karta_id) values ('Gale', 11);
insert into prodaja (kino_ime, karta_id) values ('Sutteridge', 12);
insert into prodaja (kino_ime, karta_id) values ('Melby', 13);
insert into prodaja (kino_ime, karta_id) values ('Atwood', 14);
insert into prodaja (kino_ime, karta_id) values ('Westerfield', 15);
insert into prodaja (kino_ime, karta_id) values ('Havey', 16);
insert into prodaja (kino_ime, karta_id) values ('Orin', 17);
insert into prodaja (kino_ime, karta_id) values ('Waubesa', 18);
insert into prodaja (kino_ime, karta_id) values ('Bunting', 19);
insert into prodaja (kino_ime, karta_id) values ('Killdeer', 20);
insert into prodaja (kino_ime, karta_id) values ('Evergreen', 21);
insert into prodaja (kino_ime, karta_id) values ('Anthes', 22);
insert into prodaja (kino_ime, karta_id) values ('Green', 23);
insert into prodaja (kino_ime, karta_id) values ('Forest Dale', 24);
insert into prodaja (kino_ime, karta_id) values ('Luster', 25);
insert into prodaja (kino_ime, karta_id) values ('Northland', 26);
insert into prodaja (kino_ime, karta_id) values ('Drewry', 27);
insert into prodaja (kino_ime, karta_id) values ('Loeprich', 28);
insert into prodaja (kino_ime, karta_id) values ('Veith', 29);
insert into prodaja (kino_ime, karta_id) values ('Scofield', 30);
insert into prodaja (kino_ime, karta_id) values ('Hanson', 31);
insert into prodaja (kino_ime, karta_id) values ('Summer Ridge', 32);
insert into prodaja (kino_ime, karta_id) values ('Leroy', 33);
insert into prodaja (kino_ime, karta_id) values ('Loftsgordon', 34);
insert into prodaja (kino_ime, karta_id) values ('Portage', 35);
insert into prodaja (kino_ime, karta_id) values ('Grim', 36);
insert into prodaja (kino_ime, karta_id) values ('Daystar', 37);
insert into prodaja (kino_ime, karta_id) values ('Kropf', 38);
insert into prodaja (kino_ime, karta_id) values ('Michigan', 39);
insert into prodaja (kino_ime, karta_id) values ('Eastwood', 40);
insert into prodaja (kino_ime, karta_id) values ('Fremont', 41);
insert into prodaja (kino_ime, karta_id) values ('Moulton', 42);
insert into prodaja (kino_ime, karta_id) values ('Veith', 43);
insert into prodaja (kino_ime, karta_id) values ('Sutherland', 44);
insert into prodaja (kino_ime, karta_id) values ('Arkansas', 45);
insert into prodaja (kino_ime, karta_id) values ('Green', 46);
insert into prodaja (kino_ime, karta_id) values ('Sycamore', 47);
insert into prodaja (kino_ime, karta_id) values ('Independence', 48);
insert into prodaja (kino_ime, karta_id) values ('Mayfield', 49);
insert into prodaja (kino_ime, karta_id) values ('Rieder', 50);
insert into prodaja (kino_ime, karta_id) values ('Farmco', 51);
insert into prodaja (kino_ime, karta_id) values ('Welch', 52);
insert into prodaja (kino_ime, karta_id) values ('Jay', 53);
insert into prodaja (kino_ime, karta_id) values ('Dwight', 54);
insert into prodaja (kino_ime, karta_id) values ('Porter', 55);
insert into prodaja (kino_ime, karta_id) values ('Sachs', 56);
insert into prodaja (kino_ime, karta_id) values ('Sunbrook', 57);
insert into prodaja (kino_ime, karta_id) values ('Alpine', 58);
insert into prodaja (kino_ime, karta_id) values ('Fairview', 59);
insert into prodaja (kino_ime, karta_id) values ('Eastlawn', 60);
insert into prodaja (kino_ime, karta_id) values ('Schurz', 61);
insert into prodaja (kino_ime, karta_id) values ('Westridge', 62);
insert into prodaja (kino_ime, karta_id) values ('West', 63);
insert into prodaja (kino_ime, karta_id) values ('Melby', 64);
insert into prodaja (kino_ime, karta_id) values ('8th', 65);
insert into prodaja (kino_ime, karta_id) values ('Bay', 66);
insert into prodaja (kino_ime, karta_id) values ('Hagan', 67);
insert into prodaja (kino_ime, karta_id) values ('Vernon', 68);
insert into prodaja (kino_ime, karta_id) values ('Dayton', 69);
insert into prodaja (kino_ime, karta_id) values ('Cambridge', 70);
insert into prodaja (kino_ime, karta_id) values ('Sutherland', 71);
insert into prodaja (kino_ime, karta_id) values ('Del Sol', 72);
insert into prodaja (kino_ime, karta_id) values ('Parkside', 73);
insert into prodaja (kino_ime, karta_id) values ('American', 74);
insert into prodaja (kino_ime, karta_id) values ('Pankratz', 75);
insert into prodaja (kino_ime, karta_id) values ('Spaight', 76);
insert into prodaja (kino_ime, karta_id) values ('Loftsgordon', 77);
insert into prodaja (kino_ime, karta_id) values ('Sage', 78);
insert into prodaja (kino_ime, karta_id) values ('7th', 79);
insert into prodaja (kino_ime, karta_id) values ('Continental', 80);
insert into prodaja (kino_ime, karta_id) values ('Meadow Ridge', 81);
insert into prodaja (kino_ime, karta_id) values ('Oxford', 82);
insert into prodaja (kino_ime, karta_id) values ('New Castle', 83);
insert into prodaja (kino_ime, karta_id) values ('Donald', 84);
insert into prodaja (kino_ime, karta_id) values ('Judy', 85);
insert into prodaja (kino_ime, karta_id) values ('Towne', 86);
insert into prodaja (kino_ime, karta_id) values ('Melvin', 87);
insert into prodaja (kino_ime, karta_id) values ('Sugar', 88);
insert into prodaja (kino_ime, karta_id) values ('Anderson', 89);
insert into prodaja (kino_ime, karta_id) values ('Susan', 90);
insert into prodaja (kino_ime, karta_id) values ('Kinsman', 91);
insert into prodaja (kino_ime, karta_id) values ('Canary', 92);
insert into prodaja (kino_ime, karta_id) values ('Sage', 93);
insert into prodaja (kino_ime, karta_id) values ('Fairfield', 94);
insert into prodaja (kino_ime, karta_id) values ('Maple Wood', 95);
insert into prodaja (kino_ime, karta_id) values ('Northfield', 96);
insert into prodaja (kino_ime, karta_id) values ('Bultman', 97);
insert into prodaja (kino_ime, karta_id) values ('Anthes', 98);
insert into prodaja (kino_ime, karta_id) values ('Superior', 99);
insert into prodaja (kino_ime, karta_id) values ('La Follette', 100);
insert into prodaja (kino_ime, karta_id) values ('Duke', 101);
insert into prodaja (kino_ime, karta_id) values ('Merchant', 102);
insert into prodaja (kino_ime, karta_id) values ('Burning Wood', 103);
insert into prodaja (kino_ime, karta_id) values ('Mayfield', 104);
insert into prodaja (kino_ime, karta_id) values ('American Ash', 105);
insert into prodaja (kino_ime, karta_id) values ('Kropf', 106);
insert into prodaja (kino_ime, karta_id) values ('Mayfield', 107);
insert into prodaja (kino_ime, karta_id) values ('Mcguire', 108);
insert into prodaja (kino_ime, karta_id) values ('Golf View', 109);
insert into prodaja (kino_ime, karta_id) values ('Lillian', 110);
insert into prodaja (kino_ime, karta_id) values ('Springs', 111);
insert into prodaja (kino_ime, karta_id) values ('Kinsman', 112);
insert into prodaja (kino_ime, karta_id) values ('Mayer', 113);
insert into prodaja (kino_ime, karta_id) values ('South', 114);
insert into prodaja (kino_ime, karta_id) values ('Troy', 115);
insert into prodaja (kino_ime, karta_id) values ('Acker', 116);
insert into prodaja (kino_ime, karta_id) values ('Glendale', 117);
insert into prodaja (kino_ime, karta_id) values ('Sugar', 118);
insert into prodaja (kino_ime, karta_id) values ('Judy', 119);
insert into prodaja (kino_ime, karta_id) values ('Hooker', 120);
insert into prodaja (kino_ime, karta_id) values ('8th', 121);
insert into prodaja (kino_ime, karta_id) values ('Cherokee', 122);
insert into prodaja (kino_ime, karta_id) values ('Butternut', 123);
insert into prodaja (kino_ime, karta_id) values ('Clarendon', 124);
insert into prodaja (kino_ime, karta_id) values ('Debra', 125);
insert into prodaja (kino_ime, karta_id) values ('Porter', 126);
insert into prodaja (kino_ime, karta_id) values ('Manley', 127);
insert into prodaja (kino_ime, karta_id) values ('Swallow', 128);
insert into prodaja (kino_ime, karta_id) values ('Lakewood', 129);
insert into prodaja (kino_ime, karta_id) values ('Tomscot', 130);
insert into prodaja (kino_ime, karta_id) values ('Farragut', 131);
insert into prodaja (kino_ime, karta_id) values ('Dahle', 132);
insert into prodaja (kino_ime, karta_id) values ('Stang', 133);
insert into prodaja (kino_ime, karta_id) values ('Kings', 134);
insert into prodaja (kino_ime, karta_id) values ('Debra', 135);
insert into prodaja (kino_ime, karta_id) values ('Ridge Oak', 136);
insert into prodaja (kino_ime, karta_id) values ('Chive', 137);
insert into prodaja (kino_ime, karta_id) values ('Amoth', 138);
insert into prodaja (kino_ime, karta_id) values ('Melrose', 139);
insert into prodaja (kino_ime, karta_id) values ('Crest Line', 140);
insert into prodaja (kino_ime, karta_id) values ('Marcy', 141);
insert into prodaja (kino_ime, karta_id) values ('Miller', 142);
insert into prodaja (kino_ime, karta_id) values ('Meadow Valley', 143);
insert into prodaja (kino_ime, karta_id) values ('Mitchell', 144);
insert into prodaja (kino_ime, karta_id) values ('Loomis', 145);
insert into prodaja (kino_ime, karta_id) values ('Huxley', 146);
insert into prodaja (kino_ime, karta_id) values ('Chinook', 147);
insert into prodaja (kino_ime, karta_id) values ('Roth', 148);
insert into prodaja (kino_ime, karta_id) values ('Nelson', 149);
insert into prodaja (kino_ime, karta_id) values ('Meadow Vale', 150);
insert into prodaja (kino_ime, karta_id) values ('Hazelcrest', 151);
insert into prodaja (kino_ime, karta_id) values ('Bay', 152);
insert into prodaja (kino_ime, karta_id) values ('American Ash', 153);
insert into prodaja (kino_ime, karta_id) values ('Granby', 154);
insert into prodaja (kino_ime, karta_id) values ('Clarendon', 155);
insert into prodaja (kino_ime, karta_id) values ('Porter', 156);
insert into prodaja (kino_ime, karta_id) values ('Nova', 157);
insert into prodaja (kino_ime, karta_id) values ('Mcbride', 158);
insert into prodaja (kino_ime, karta_id) values ('Ludington', 159);
insert into prodaja (kino_ime, karta_id) values ('Sundown', 160);
insert into prodaja (kino_ime, karta_id) values ('Florence', 161);
insert into prodaja (kino_ime, karta_id) values ('3rd', 162);
insert into prodaja (kino_ime, karta_id) values ('John Wall', 163);
insert into prodaja (kino_ime, karta_id) values ('Brown', 164);
insert into prodaja (kino_ime, karta_id) values ('6th', 165);
insert into prodaja (kino_ime, karta_id) values ('Lyons', 166);
insert into prodaja (kino_ime, karta_id) values ('Stang', 167);
insert into prodaja (kino_ime, karta_id) values ('Kingsford', 168);
insert into prodaja (kino_ime, karta_id) values ('Melody', 169);
insert into prodaja (kino_ime, karta_id) values ('Meadow Vale', 170);
insert into prodaja (kino_ime, karta_id) values ('Northfield', 171);
insert into prodaja (kino_ime, karta_id) values ('Superior', 172);
insert into prodaja (kino_ime, karta_id) values ('Muir', 173);
insert into prodaja (kino_ime, karta_id) values ('Sage', 174);
insert into prodaja (kino_ime, karta_id) values ('Independence', 175);
insert into prodaja (kino_ime, karta_id) values ('Sugar', 176);
insert into prodaja (kino_ime, karta_id) values ('Havey', 177);
insert into prodaja (kino_ime, karta_id) values ('Maywood', 178);
insert into prodaja (kino_ime, karta_id) values ('Heath', 179);
insert into prodaja (kino_ime, karta_id) values ('Old Shore', 180);
insert into prodaja (kino_ime, karta_id) values ('Sunbrook', 181);
insert into prodaja (kino_ime, karta_id) values ('1st', 182);
insert into prodaja (kino_ime, karta_id) values ('Corry', 183);
insert into prodaja (kino_ime, karta_id) values ('Dottie', 184);
insert into prodaja (kino_ime, karta_id) values ('Eagle Crest', 185);
insert into prodaja (kino_ime, karta_id) values ('Cody', 186);
insert into prodaja (kino_ime, karta_id) values ('Beilfuss', 187);
insert into prodaja (kino_ime, karta_id) values ('Valley Edge', 188);
insert into prodaja (kino_ime, karta_id) values ('Marcy', 189);
insert into prodaja (kino_ime, karta_id) values ('Dennis', 190);
insert into prodaja (kino_ime, karta_id) values ('Hoepker', 191);
insert into prodaja (kino_ime, karta_id) values ('Starling', 192);
insert into prodaja (kino_ime, karta_id) values ('Hoard', 193);
insert into prodaja (kino_ime, karta_id) values ('Lien', 194);
insert into prodaja (kino_ime, karta_id) values ('Twin Pines', 195);
insert into prodaja (kino_ime, karta_id) values ('Tennyson', 196);
insert into prodaja (kino_ime, karta_id) values ('Fairview', 197);
insert into prodaja (kino_ime, karta_id) values ('Algoma', 198);
insert into prodaja (kino_ime, karta_id) values ('3rd', 199);
insert into prodaja (kino_ime, karta_id) values ('Columbus', 200);
insert into prodaja (kino_ime, karta_id) values ('Hermina', 201);
insert into prodaja (kino_ime, karta_id) values ('Dayton', 202);
insert into prodaja (kino_ime, karta_id) values ('New Castle', 203);
insert into prodaja (kino_ime, karta_id) values ('Hintze', 204);
insert into prodaja (kino_ime, karta_id) values ('Almo', 205);
insert into prodaja (kino_ime, karta_id) values ('Bowman', 206);
insert into prodaja (kino_ime, karta_id) values ('Bluejay', 207);
insert into prodaja (kino_ime, karta_id) values ('Muir', 208);
insert into prodaja (kino_ime, karta_id) values ('Donald', 209);
insert into prodaja (kino_ime, karta_id) values ('Mayer', 210);
insert into prodaja (kino_ime, karta_id) values ('Doe Crossing', 211);
insert into prodaja (kino_ime, karta_id) values ('Orin', 212);
insert into prodaja (kino_ime, karta_id) values ('Crescent Oaks', 213);
insert into prodaja (kino_ime, karta_id) values ('Valley Edge', 214);
insert into prodaja (kino_ime, karta_id) values ('Little Fleur', 215);
insert into prodaja (kino_ime, karta_id) values ('Maywood', 216);
insert into prodaja (kino_ime, karta_id) values ('Graedel', 217);
insert into prodaja (kino_ime, karta_id) values ('East', 218);
insert into prodaja (kino_ime, karta_id) values ('Stuart', 219);
insert into prodaja (kino_ime, karta_id) values ('Thierer', 220);
insert into prodaja (kino_ime, karta_id) values ('6th', 221);
insert into prodaja (kino_ime, karta_id) values ('Reinke', 222);
insert into prodaja (kino_ime, karta_id) values ('Packers', 223);
insert into prodaja (kino_ime, karta_id) values ('Meadow Vale', 224);
insert into prodaja (kino_ime, karta_id) values ('Milwaukee', 225);
insert into prodaja (kino_ime, karta_id) values ('Dahle', 226);
insert into prodaja (kino_ime, karta_id) values ('Blaine', 227);
insert into prodaja (kino_ime, karta_id) values ('Dovetail', 228);
insert into prodaja (kino_ime, karta_id) values ('Northview', 229);
insert into prodaja (kino_ime, karta_id) values ('Everett', 230);
insert into prodaja (kino_ime, karta_id) values ('Bultman', 231);
insert into prodaja (kino_ime, karta_id) values ('Sherman', 232);
insert into prodaja (kino_ime, karta_id) values ('Pond', 233);
insert into prodaja (kino_ime, karta_id) values ('School', 234);
insert into prodaja (kino_ime, karta_id) values ('Jenifer', 235);
insert into prodaja (kino_ime, karta_id) values ('Vermont', 236);
insert into prodaja (kino_ime, karta_id) values ('Mayfield', 237);
insert into prodaja (kino_ime, karta_id) values ('Menomonie', 238);
insert into prodaja (kino_ime, karta_id) values ('Summerview', 239);
insert into prodaja (kino_ime, karta_id) values ('Pawling', 240);
insert into prodaja (kino_ime, karta_id) values ('Crescent Oaks', 241);
insert into prodaja (kino_ime, karta_id) values ('Burrows', 242);
insert into prodaja (kino_ime, karta_id) values ('Dottie', 243);
insert into prodaja (kino_ime, karta_id) values ('2nd', 244);
insert into prodaja (kino_ime, karta_id) values ('Village', 245);
insert into prodaja (kino_ime, karta_id) values ('Upham', 246);
insert into prodaja (kino_ime, karta_id) values ('Banding', 247);
insert into prodaja (kino_ime, karta_id) values ('Roth', 248);
insert into prodaja (kino_ime, karta_id) values ('Butternut', 249);
insert into prodaja (kino_ime, karta_id) values ('Crescent Oaks', 250);
insert into prodaja (kino_ime, karta_id) values ('Iowa', 251);
insert into prodaja (kino_ime, karta_id) values ('Truax', 252);
insert into prodaja (kino_ime, karta_id) values ('Barnett', 253);
insert into prodaja (kino_ime, karta_id) values ('Summit', 254);
insert into prodaja (kino_ime, karta_id) values ('Troy', 255);
insert into prodaja (kino_ime, karta_id) values ('Anderson', 256);
insert into prodaja (kino_ime, karta_id) values ('Melrose', 257);
insert into prodaja (kino_ime, karta_id) values ('Erie', 258);
insert into prodaja (kino_ime, karta_id) values ('Gerald', 259);
insert into prodaja (kino_ime, karta_id) values ('Petterle', 260);
insert into prodaja (kino_ime, karta_id) values ('Hallows', 261);
insert into prodaja (kino_ime, karta_id) values ('Barby', 262);
insert into prodaja (kino_ime, karta_id) values ('Hintze', 263);
insert into prodaja (kino_ime, karta_id) values ('Bluestem', 264);
insert into prodaja (kino_ime, karta_id) values ('Orin', 265);
insert into prodaja (kino_ime, karta_id) values ('Cherokee', 266);
insert into prodaja (kino_ime, karta_id) values ('Memorial', 267);
insert into prodaja (kino_ime, karta_id) values ('Sunnyside', 268);
insert into prodaja (kino_ime, karta_id) values ('Longview', 269);
insert into prodaja (kino_ime, karta_id) values ('Fallview', 270);
insert into prodaja (kino_ime, karta_id) values ('Sloan', 271);
insert into prodaja (kino_ime, karta_id) values ('Saint Paul', 272);
insert into prodaja (kino_ime, karta_id) values ('Brown', 273);
insert into prodaja (kino_ime, karta_id) values ('Oriole', 274);
insert into prodaja (kino_ime, karta_id) values ('3rd', 275);
insert into prodaja (kino_ime, karta_id) values ('Tomscot', 276);
insert into prodaja (kino_ime, karta_id) values ('High Crossing', 277);
insert into prodaja (kino_ime, karta_id) values ('Harper', 278);
insert into prodaja (kino_ime, karta_id) values ('Schurz', 279);
insert into prodaja (kino_ime, karta_id) values ('Myrtle', 280);
insert into prodaja (kino_ime, karta_id) values ('Chive', 281);
insert into prodaja (kino_ime, karta_id) values ('Namekagon', 282);
insert into prodaja (kino_ime, karta_id) values ('Artisan', 283);
insert into prodaja (kino_ime, karta_id) values ('Longview', 284);
insert into prodaja (kino_ime, karta_id) values ('Aberg', 285);
insert into prodaja (kino_ime, karta_id) values ('Dryden', 286);
insert into prodaja (kino_ime, karta_id) values ('Mitchell', 287);
insert into prodaja (kino_ime, karta_id) values ('Cordelia', 288);
insert into prodaja (kino_ime, karta_id) values ('Ridge Oak', 289);
insert into prodaja (kino_ime, karta_id) values ('Saint Paul', 290);
insert into prodaja (kino_ime, karta_id) values ('Roxbury', 291);
insert into prodaja (kino_ime, karta_id) values ('Texas', 292);
insert into prodaja (kino_ime, karta_id) values ('Buell', 293);
insert into prodaja (kino_ime, karta_id) values ('Butternut', 294);
insert into prodaja (kino_ime, karta_id) values ('Red Cloud', 295);
insert into prodaja (kino_ime, karta_id) values ('Hanover', 296);
insert into prodaja (kino_ime, karta_id) values ('Transport', 297);
insert into prodaja (kino_ime, karta_id) values ('Tomscot', 298);
insert into prodaja (kino_ime, karta_id) values ('Heffernan', 299);
insert into prodaja (kino_ime, karta_id) values ('Fieldstone', 300);
insert into prodaja (kino_ime, karta_id) values ('Lukken', 301);
insert into prodaja (kino_ime, karta_id) values ('Arizona', 302);
insert into prodaja (kino_ime, karta_id) values ('Colorado', 303);
insert into prodaja (kino_ime, karta_id) values ('Kings', 304);
insert into prodaja (kino_ime, karta_id) values ('Holmberg', 305);
insert into prodaja (kino_ime, karta_id) values ('Prairie Rose', 306);
insert into prodaja (kino_ime, karta_id) values ('Esker', 307);
insert into prodaja (kino_ime, karta_id) values ('Portage', 308);
insert into prodaja (kino_ime, karta_id) values ('Waubesa', 309);
insert into prodaja (kino_ime, karta_id) values ('Hanson', 310);
insert into prodaja (kino_ime, karta_id) values ('Texas', 311);
insert into prodaja (kino_ime, karta_id) values ('Mayer', 312);
insert into prodaja (kino_ime, karta_id) values ('Forest Run', 313);
insert into prodaja (kino_ime, karta_id) values ('Arkansas', 314);
insert into prodaja (kino_ime, karta_id) values ('Riverside', 315);
insert into prodaja (kino_ime, karta_id) values ('Charing Cross', 316);
insert into prodaja (kino_ime, karta_id) values ('Tennessee', 317);
insert into prodaja (kino_ime, karta_id) values ('Eastlawn', 318);
insert into prodaja (kino_ime, karta_id) values ('Manufacturers', 319);
insert into prodaja (kino_ime, karta_id) values ('Luster', 320);
insert into prodaja (kino_ime, karta_id) values ('Farmco', 321);
insert into prodaja (kino_ime, karta_id) values ('Randy', 322);
insert into prodaja (kino_ime, karta_id) values ('Springview', 323);
insert into prodaja (kino_ime, karta_id) values ('Declaration', 324);
insert into prodaja (kino_ime, karta_id) values ('New Castle', 325);
insert into prodaja (kino_ime, karta_id) values ('Ridgeview', 326);
insert into prodaja (kino_ime, karta_id) values ('Sundown', 327);
insert into prodaja (kino_ime, karta_id) values ('Pankratz', 328);
insert into prodaja (kino_ime, karta_id) values ('Norway Maple', 329);
insert into prodaja (kino_ime, karta_id) values ('6th', 330);
insert into prodaja (kino_ime, karta_id) values ('Old Gate', 331);
insert into prodaja (kino_ime, karta_id) values ('Warner', 332);
insert into prodaja (kino_ime, karta_id) values ('Daystar', 333);
insert into prodaja (kino_ime, karta_id) values ('Northview', 334);
insert into prodaja (kino_ime, karta_id) values ('Barnett', 335);
insert into prodaja (kino_ime, karta_id) values ('Twin Pines', 336);
insert into prodaja (kino_ime, karta_id) values ('Butternut', 337);
insert into prodaja (kino_ime, karta_id) values ('Waywood', 338);
insert into prodaja (kino_ime, karta_id) values ('Butternut', 339);
insert into prodaja (kino_ime, karta_id) values ('Mayfield', 340);
insert into prodaja (kino_ime, karta_id) values ('Northfield', 341);
insert into prodaja (kino_ime, karta_id) values ('Cordelia', 342);
insert into prodaja (kino_ime, karta_id) values ('Shoshone', 343);
insert into prodaja (kino_ime, karta_id) values ('Express', 344);
insert into prodaja (kino_ime, karta_id) values ('Prentice', 345);
insert into prodaja (kino_ime, karta_id) values ('Anhalt', 346);
insert into prodaja (kino_ime, karta_id) values ('Cody', 347);
insert into prodaja (kino_ime, karta_id) values ('Stang', 348);
insert into prodaja (kino_ime, karta_id) values ('Grasskamp', 349);
insert into prodaja (kino_ime, karta_id) values ('Corscot', 350);
insert into prodaja (kino_ime, karta_id) values ('Caliangt', 351);
insert into prodaja (kino_ime, karta_id) values ('Elmside', 352);
insert into prodaja (kino_ime, karta_id) values ('Texas', 353);
insert into prodaja (kino_ime, karta_id) values ('Sunfield', 354);
insert into prodaja (kino_ime, karta_id) values ('Walton', 355);
insert into prodaja (kino_ime, karta_id) values ('Paget', 356);
insert into prodaja (kino_ime, karta_id) values ('Bonner', 357);
insert into prodaja (kino_ime, karta_id) values ('Lyons', 358);
insert into prodaja (kino_ime, karta_id) values ('Merrick', 359);
insert into prodaja (kino_ime, karta_id) values ('5th', 360);
insert into prodaja (kino_ime, karta_id) values ('Division', 361);
insert into prodaja (kino_ime, karta_id) values ('Troy', 362);
insert into prodaja (kino_ime, karta_id) values ('Moland', 363);
insert into prodaja (kino_ime, karta_id) values ('Buhler', 364);
insert into prodaja (kino_ime, karta_id) values ('Graedel', 365);
insert into prodaja (kino_ime, karta_id) values ('Memorial', 366);
insert into prodaja (kino_ime, karta_id) values ('Reindahl', 367);
insert into prodaja (kino_ime, karta_id) values ('Dixon', 368);
insert into prodaja (kino_ime, karta_id) values ('Schlimgen', 369);
insert into prodaja (kino_ime, karta_id) values ('Shasta', 370);
insert into prodaja (kino_ime, karta_id) values ('Riverside', 371);
insert into prodaja (kino_ime, karta_id) values ('Kedzie', 372);
insert into prodaja (kino_ime, karta_id) values ('Arizona', 373);
insert into prodaja (kino_ime, karta_id) values ('Fordem', 374);
insert into prodaja (kino_ime, karta_id) values ('Banding', 375);
insert into prodaja (kino_ime, karta_id) values ('Pankratz', 376);
insert into prodaja (kino_ime, karta_id) values ('Acker', 377);
insert into prodaja (kino_ime, karta_id) values ('Arrowood', 378);
insert into prodaja (kino_ime, karta_id) values ('Fordem', 379);
insert into prodaja (kino_ime, karta_id) values ('Huxley', 380);
insert into prodaja (kino_ime, karta_id) values ('Claremont', 381);
insert into prodaja (kino_ime, karta_id) values ('Elka', 382);
insert into prodaja (kino_ime, karta_id) values ('Luster', 383);
insert into prodaja (kino_ime, karta_id) values ('Gerald', 384);
insert into prodaja (kino_ime, karta_id) values ('Atwood', 385);
insert into prodaja (kino_ime, karta_id) values ('Bartelt', 386);
insert into prodaja (kino_ime, karta_id) values ('Sugar', 387);
insert into prodaja (kino_ime, karta_id) values ('Cottonwood', 388);
insert into prodaja (kino_ime, karta_id) values ('Brown', 389);
insert into prodaja (kino_ime, karta_id) values ('Everett', 390);
insert into prodaja (kino_ime, karta_id) values ('Nobel', 391);
insert into prodaja (kino_ime, karta_id) values ('Cascade', 392);
insert into prodaja (kino_ime, karta_id) values ('Tomscot', 393);
insert into prodaja (kino_ime, karta_id) values ('4th', 394);
insert into prodaja (kino_ime, karta_id) values ('Menomonie', 395);
insert into prodaja (kino_ime, karta_id) values ('Manufacturers', 396);
insert into prodaja (kino_ime, karta_id) values ('Ronald Regan', 397);
insert into prodaja (kino_ime, karta_id) values ('Randy', 398);
insert into prodaja (kino_ime, karta_id) values ('Schmedeman', 399);
insert into prodaja (kino_ime, karta_id) values ('Lyons', 400);
insert into prodaja (kino_ime, karta_id) values ('Schiller', 401);
insert into prodaja (kino_ime, karta_id) values ('Village', 402);
insert into prodaja (kino_ime, karta_id) values ('Florence', 403);
insert into prodaja (kino_ime, karta_id) values ('Maple', 404);
insert into prodaja (kino_ime, karta_id) values ('Golf View', 405);
insert into prodaja (kino_ime, karta_id) values ('Elka', 406);
insert into prodaja (kino_ime, karta_id) values ('Anderson', 407);
insert into prodaja (kino_ime, karta_id) values ('Grover', 408);
insert into prodaja (kino_ime, karta_id) values ('Moulton', 409);
insert into prodaja (kino_ime, karta_id) values ('Hanover', 410);
insert into prodaja (kino_ime, karta_id) values ('Bayside', 411);
insert into prodaja (kino_ime, karta_id) values ('Chive', 412);
insert into prodaja (kino_ime, karta_id) values ('Holmberg', 413);
insert into prodaja (kino_ime, karta_id) values ('Shelley', 414);
insert into prodaja (kino_ime, karta_id) values ('Buell', 415);
insert into prodaja (kino_ime, karta_id) values ('Crowley', 416);
insert into prodaja (kino_ime, karta_id) values ('Harbort', 417);
insert into prodaja (kino_ime, karta_id) values ('Montana', 418);
insert into prodaja (kino_ime, karta_id) values ('Jana', 419);
insert into prodaja (kino_ime, karta_id) values ('Swallow', 420);
insert into prodaja (kino_ime, karta_id) values ('Paget', 421);
insert into prodaja (kino_ime, karta_id) values ('Ridgeview', 422);
insert into prodaja (kino_ime, karta_id) values ('Mayer', 423);
insert into prodaja (kino_ime, karta_id) values ('Michigan', 424);
insert into prodaja (kino_ime, karta_id) values ('Dottie', 425);
insert into prodaja (kino_ime, karta_id) values ('Linden', 426);
insert into prodaja (kino_ime, karta_id) values ('Sunnyside', 427);
insert into prodaja (kino_ime, karta_id) values ('Vidon', 428);
insert into prodaja (kino_ime, karta_id) values ('Rockefeller', 429);
insert into prodaja (kino_ime, karta_id) values ('Ridge Oak', 430);
insert into prodaja (kino_ime, karta_id) values ('Sunbrook', 431);
insert into prodaja (kino_ime, karta_id) values ('Sommers', 432);
insert into prodaja (kino_ime, karta_id) values ('Charing Cross', 433);
insert into prodaja (kino_ime, karta_id) values ('Elmside', 434);
insert into prodaja (kino_ime, karta_id) values ('8th', 435);
insert into prodaja (kino_ime, karta_id) values ('Montana', 436);
insert into prodaja (kino_ime, karta_id) values ('Ryan', 437);
insert into prodaja (kino_ime, karta_id) values ('Bowman', 438);
insert into prodaja (kino_ime, karta_id) values ('Maple', 439);
insert into prodaja (kino_ime, karta_id) values ('Pine View', 440);
insert into prodaja (kino_ime, karta_id) values ('Spaight', 441);
insert into prodaja (kino_ime, karta_id) values ('Tennessee', 442);
insert into prodaja (kino_ime, karta_id) values ('Meadow Valley', 443);
insert into prodaja (kino_ime, karta_id) values ('Loeprich', 444);
insert into prodaja (kino_ime, karta_id) values ('Bunting', 445);
insert into prodaja (kino_ime, karta_id) values ('Bluejay', 446);
insert into prodaja (kino_ime, karta_id) values ('Kensington', 447);
insert into prodaja (kino_ime, karta_id) values ('Texas', 448);
insert into prodaja (kino_ime, karta_id) values ('Starling', 449);
insert into prodaja (kino_ime, karta_id) values ('Surrey', 450);
insert into prodaja (kino_ime, karta_id) values ('Sunbrook', 451);
insert into prodaja (kino_ime, karta_id) values ('Clove', 452);
insert into prodaja (kino_ime, karta_id) values ('Fairview', 453);
insert into prodaja (kino_ime, karta_id) values ('Merrick', 454);
insert into prodaja (kino_ime, karta_id) values ('Eagle Crest', 455);
insert into prodaja (kino_ime, karta_id) values ('Dorton', 456);
insert into prodaja (kino_ime, karta_id) values ('Carey', 457);
insert into prodaja (kino_ime, karta_id) values ('Columbus', 458);
insert into prodaja (kino_ime, karta_id) values ('Gina', 459);
insert into prodaja (kino_ime, karta_id) values ('Di Loreto', 460);
insert into prodaja (kino_ime, karta_id) values ('Kinsman', 461);
insert into prodaja (kino_ime, karta_id) values ('Butternut', 462);
insert into prodaja (kino_ime, karta_id) values ('Pawling', 463);
insert into prodaja (kino_ime, karta_id) values ('Carberry', 464);
insert into prodaja (kino_ime, karta_id) values ('Darwin', 465);
insert into prodaja (kino_ime, karta_id) values ('Corben', 466);
insert into prodaja (kino_ime, karta_id) values ('Dorton', 467);
insert into prodaja (kino_ime, karta_id) values ('Kingsford', 468);
insert into prodaja (kino_ime, karta_id) values ('Grover', 469);
insert into prodaja (kino_ime, karta_id) values ('Monica', 470);
insert into prodaja (kino_ime, karta_id) values ('Talmadge', 471);
insert into prodaja (kino_ime, karta_id) values ('Golf View', 472);
insert into prodaja (kino_ime, karta_id) values ('Anderson', 473);
insert into prodaja (kino_ime, karta_id) values ('Paget', 474);
insert into prodaja (kino_ime, karta_id) values ('Butternut', 475);
insert into prodaja (kino_ime, karta_id) values ('Gerald', 476);
insert into prodaja (kino_ime, karta_id) values ('Manufacturers', 477);
insert into prodaja (kino_ime, karta_id) values ('Golf View', 478);
insert into prodaja (kino_ime, karta_id) values ('Memorial', 479);
insert into prodaja (kino_ime, karta_id) values ('Fremont', 480);
insert into prodaja (kino_ime, karta_id) values ('Armistice', 481);
insert into prodaja (kino_ime, karta_id) values ('Heffernan', 482);
insert into prodaja (kino_ime, karta_id) values ('Sutherland', 483);
insert into prodaja (kino_ime, karta_id) values ('Hanson', 484);
insert into prodaja (kino_ime, karta_id) values ('Aberg', 485);
insert into prodaja (kino_ime, karta_id) values ('Red Cloud', 486);
insert into prodaja (kino_ime, karta_id) values ('Scofield', 487);
insert into prodaja (kino_ime, karta_id) values ('Sommers', 488);
insert into prodaja (kino_ime, karta_id) values ('Bellgrove', 489);
insert into prodaja (kino_ime, karta_id) values ('Farragut', 490);
insert into prodaja (kino_ime, karta_id) values ('Briar Crest', 491);
insert into prodaja (kino_ime, karta_id) values ('Summer Ridge', 492);
insert into prodaja (kino_ime, karta_id) values ('Hallows', 493);
insert into prodaja (kino_ime, karta_id) values ('Oneill', 494);
insert into prodaja (kino_ime, karta_id) values ('Mayfield', 495);
insert into prodaja (kino_ime, karta_id) values ('Summerview', 496);
insert into prodaja (kino_ime, karta_id) values ('Village', 497);
insert into prodaja (kino_ime, karta_id) values ('Pepper Wood', 498);
insert into prodaja (kino_ime, karta_id) values ('Green Ridge', 499);
insert into prodaja (kino_ime, karta_id) values ('Sage', 500);
insert into prodaja (kino_ime, karta_id) values ('Duke', 501);
insert into prodaja (kino_ime, karta_id) values ('Bobwhite', 502);
insert into prodaja (kino_ime, karta_id) values ('Bartelt', 503);
insert into prodaja (kino_ime, karta_id) values ('Main', 504);
insert into prodaja (kino_ime, karta_id) values ('Starling', 505);
insert into prodaja (kino_ime, karta_id) values ('Sunbrook', 506);
insert into prodaja (kino_ime, karta_id) values ('Havey', 507);
insert into prodaja (kino_ime, karta_id) values ('Heath', 508);
insert into prodaja (kino_ime, karta_id) values ('Packers', 509);
insert into prodaja (kino_ime, karta_id) values ('Mandrake', 510);
insert into prodaja (kino_ime, karta_id) values ('Nova', 511);
insert into prodaja (kino_ime, karta_id) values ('Sunfield', 512);
insert into prodaja (kino_ime, karta_id) values ('Arizona', 513);
insert into prodaja (kino_ime, karta_id) values ('Mayfield', 514);
insert into prodaja (kino_ime, karta_id) values ('Warner', 515);
insert into prodaja (kino_ime, karta_id) values ('Clemons', 516);
insert into prodaja (kino_ime, karta_id) values ('Mesta', 517);
insert into prodaja (kino_ime, karta_id) values ('Mockingbird', 518);
insert into prodaja (kino_ime, karta_id) values ('Northfield', 519);
insert into prodaja (kino_ime, karta_id) values ('Westend', 520);
insert into prodaja (kino_ime, karta_id) values ('Cottonwood', 521);
insert into prodaja (kino_ime, karta_id) values ('Lukken', 522);
insert into prodaja (kino_ime, karta_id) values ('Acker', 523);
insert into prodaja (kino_ime, karta_id) values ('Center', 524);
insert into prodaja (kino_ime, karta_id) values ('Arkansas', 525);
insert into prodaja (kino_ime, karta_id) values ('Shopko', 526);
insert into prodaja (kino_ime, karta_id) values ('Chive', 527);
insert into prodaja (kino_ime, karta_id) values ('Larry', 528);
insert into prodaja (kino_ime, karta_id) values ('Hollow Ridge', 529);
insert into prodaja (kino_ime, karta_id) values ('Dwight', 530);
insert into prodaja (kino_ime, karta_id) values ('Lotheville', 531);
insert into prodaja (kino_ime, karta_id) values ('Delladonna', 532);
insert into prodaja (kino_ime, karta_id) values ('Maple', 533);
insert into prodaja (kino_ime, karta_id) values ('Browning', 534);
insert into prodaja (kino_ime, karta_id) values ('Morrow', 535);
insert into prodaja (kino_ime, karta_id) values ('Mariners Cove', 536);
insert into prodaja (kino_ime, karta_id) values ('Green', 537);
insert into prodaja (kino_ime, karta_id) values ('Reinke', 538);
insert into prodaja (kino_ime, karta_id) values ('Hazelcrest', 539);
insert into prodaja (kino_ime, karta_id) values ('Heath', 540);
insert into prodaja (kino_ime, karta_id) values ('Ramsey', 541);
insert into prodaja (kino_ime, karta_id) values ('Springview', 542);
insert into prodaja (kino_ime, karta_id) values ('Golf View', 543);
insert into prodaja (kino_ime, karta_id) values ('Lindbergh', 544);
insert into prodaja (kino_ime, karta_id) values ('Utah', 545);
insert into prodaja (kino_ime, karta_id) values ('Redwing', 546);
insert into prodaja (kino_ime, karta_id) values ('Onsgard', 547);
insert into prodaja (kino_ime, karta_id) values ('Russell', 548);
insert into prodaja (kino_ime, karta_id) values ('Eastlawn', 549);
insert into prodaja (kino_ime, karta_id) values ('Mesta', 550);
insert into prodaja (kino_ime, karta_id) values ('Fieldstone', 551);
insert into prodaja (kino_ime, karta_id) values ('Sutherland', 552);
insert into prodaja (kino_ime, karta_id) values ('Anhalt', 553);
insert into prodaja (kino_ime, karta_id) values ('Waywood', 554);
insert into prodaja (kino_ime, karta_id) values ('Claremont', 555);
insert into prodaja (kino_ime, karta_id) values ('Hooker', 556);
insert into prodaja (kino_ime, karta_id) values ('Glacier Hill', 557);
insert into prodaja (kino_ime, karta_id) values ('Melby', 558);
insert into prodaja (kino_ime, karta_id) values ('Division', 559);
insert into prodaja (kino_ime, karta_id) values ('Nevada', 560);
insert into prodaja (kino_ime, karta_id) values ('Thompson', 561);
insert into prodaja (kino_ime, karta_id) values ('Bonner', 562);
insert into prodaja (kino_ime, karta_id) values ('Forest Dale', 563);
insert into prodaja (kino_ime, karta_id) values ('School', 564);
insert into prodaja (kino_ime, karta_id) values ('Almo', 565);
insert into prodaja (kino_ime, karta_id) values ('International', 566);
insert into prodaja (kino_ime, karta_id) values ('Gerald', 567);
insert into prodaja (kino_ime, karta_id) values ('Moland', 568);
insert into prodaja (kino_ime, karta_id) values ('Rigney', 569);
insert into prodaja (kino_ime, karta_id) values ('Esch', 570);
insert into prodaja (kino_ime, karta_id) values ('Artisan', 571);
insert into prodaja (kino_ime, karta_id) values ('Sachs', 572);
insert into prodaja (kino_ime, karta_id) values ('Bayside', 573);
insert into prodaja (kino_ime, karta_id) values ('Sundown', 574);
insert into prodaja (kino_ime, karta_id) values ('Melby', 575);
insert into prodaja (kino_ime, karta_id) values ('Union', 576);
insert into prodaja (kino_ime, karta_id) values ('Prentice', 577);
insert into prodaja (kino_ime, karta_id) values ('Logan', 578);
insert into prodaja (kino_ime, karta_id) values ('Bayside', 579);
insert into prodaja (kino_ime, karta_id) values ('Nancy', 580);
insert into prodaja (kino_ime, karta_id) values ('Fremont', 581);
insert into prodaja (kino_ime, karta_id) values ('Coolidge', 582);
insert into prodaja (kino_ime, karta_id) values ('Talisman', 583);
insert into prodaja (kino_ime, karta_id) values ('Service', 584);
insert into prodaja (kino_ime, karta_id) values ('Charing Cross', 585);
insert into prodaja (kino_ime, karta_id) values ('Claremont', 586);
insert into prodaja (kino_ime, karta_id) values ('Corben', 587);
insert into prodaja (kino_ime, karta_id) values ('Valley Edge', 588);
insert into prodaja (kino_ime, karta_id) values ('Mayfield', 589);
insert into prodaja (kino_ime, karta_id) values ('Logan', 590);
insert into prodaja (kino_ime, karta_id) values ('Debra', 591);
insert into prodaja (kino_ime, karta_id) values ('Kingsford', 592);
insert into prodaja (kino_ime, karta_id) values ('Lerdahl', 593);
insert into prodaja (kino_ime, karta_id) values ('Namekagon', 594);
insert into prodaja (kino_ime, karta_id) values ('Center', 595);
insert into prodaja (kino_ime, karta_id) values ('Erie', 596);
insert into prodaja (kino_ime, karta_id) values ('David', 597);
insert into prodaja (kino_ime, karta_id) values ('Pearson', 598);
insert into prodaja (kino_ime, karta_id) values ('Birchwood', 599);
insert into prodaja (kino_ime, karta_id) values ('Mendota', 600);
insert into prodaja (kino_ime, karta_id) values ('Reinke', 601);
insert into prodaja (kino_ime, karta_id) values ('Banding', 602);
insert into prodaja (kino_ime, karta_id) values ('Lyons', 603);
insert into prodaja (kino_ime, karta_id) values ('Debra', 604);
insert into prodaja (kino_ime, karta_id) values ('Rigney', 605);
insert into prodaja (kino_ime, karta_id) values ('Prentice', 606);
insert into prodaja (kino_ime, karta_id) values ('Porter', 607);
insert into prodaja (kino_ime, karta_id) values ('Farwell', 608);
insert into prodaja (kino_ime, karta_id) values ('Dunning', 609);
insert into prodaja (kino_ime, karta_id) values ('Fairview', 610);
insert into prodaja (kino_ime, karta_id) values ('Straubel', 611);
insert into prodaja (kino_ime, karta_id) values ('Crescent Oaks', 612);
insert into prodaja (kino_ime, karta_id) values ('Evergreen', 613);
insert into prodaja (kino_ime, karta_id) values ('Sachtjen', 614);
insert into prodaja (kino_ime, karta_id) values ('Kenwood', 615);
insert into prodaja (kino_ime, karta_id) values ('Hayes', 616);
insert into prodaja (kino_ime, karta_id) values ('Hoard', 617);
insert into prodaja (kino_ime, karta_id) values ('Trailsway', 618);
insert into prodaja (kino_ime, karta_id) values ('Ludington', 619);
insert into prodaja (kino_ime, karta_id) values ('Cordelia', 620);
insert into prodaja (kino_ime, karta_id) values ('Welch', 621);
insert into prodaja (kino_ime, karta_id) values ('Hazelcrest', 622);
insert into prodaja (kino_ime, karta_id) values ('Declaration', 623);
insert into prodaja (kino_ime, karta_id) values ('Hooker', 624);
insert into prodaja (kino_ime, karta_id) values ('Sage', 625);
insert into prodaja (kino_ime, karta_id) values ('Browning', 626);
insert into prodaja (kino_ime, karta_id) values ('Bultman', 627);
insert into prodaja (kino_ime, karta_id) values ('Dapin', 628);
insert into prodaja (kino_ime, karta_id) values ('Algoma', 629);
insert into prodaja (kino_ime, karta_id) values ('Nelson', 630);
insert into prodaja (kino_ime, karta_id) values ('Anderson', 631);
insert into prodaja (kino_ime, karta_id) values ('Ridgeway', 632);
insert into prodaja (kino_ime, karta_id) values ('Glendale', 633);
insert into prodaja (kino_ime, karta_id) values ('Hooker', 634);
insert into prodaja (kino_ime, karta_id) values ('Sycamore', 635);
insert into prodaja (kino_ime, karta_id) values ('Rieder', 636);
insert into prodaja (kino_ime, karta_id) values ('Dapin', 637);
insert into prodaja (kino_ime, karta_id) values ('Macpherson', 638);
insert into prodaja (kino_ime, karta_id) values ('Dawn', 639);
insert into prodaja (kino_ime, karta_id) values ('Colorado', 640);
insert into prodaja (kino_ime, karta_id) values ('Mitchell', 641);
insert into prodaja (kino_ime, karta_id) values ('Glacier Hill', 642);
insert into prodaja (kino_ime, karta_id) values ('Kensington', 643);
insert into prodaja (kino_ime, karta_id) values ('Ryan', 644);
insert into prodaja (kino_ime, karta_id) values ('Fair Oaks', 645);
insert into prodaja (kino_ime, karta_id) values ('Butterfield', 646);
insert into prodaja (kino_ime, karta_id) values ('Northland', 647);
insert into prodaja (kino_ime, karta_id) values ('Pine View', 648);
insert into prodaja (kino_ime, karta_id) values ('Melody', 649);
insert into prodaja (kino_ime, karta_id) values ('Spaight', 650);
insert into prodaja (kino_ime, karta_id) values ('Mendota', 651);
insert into prodaja (kino_ime, karta_id) values ('Sloan', 652);
insert into prodaja (kino_ime, karta_id) values ('Brentwood', 653);
insert into prodaja (kino_ime, karta_id) values ('American', 654);
insert into prodaja (kino_ime, karta_id) values ('Center', 655);
insert into prodaja (kino_ime, karta_id) values ('Cardinal', 656);
insert into prodaja (kino_ime, karta_id) values ('Mcbride', 657);
insert into prodaja (kino_ime, karta_id) values ('La Follette', 658);
insert into prodaja (kino_ime, karta_id) values ('Artisan', 659);
insert into prodaja (kino_ime, karta_id) values ('Pennsylvania', 660);
insert into prodaja (kino_ime, karta_id) values ('Pierstorff', 661);
insert into prodaja (kino_ime, karta_id) values ('Bartelt', 662);
insert into prodaja (kino_ime, karta_id) values ('Stephen', 663);
insert into prodaja (kino_ime, karta_id) values ('Meadow Valley', 664);
insert into prodaja (kino_ime, karta_id) values ('Esch', 665);
insert into prodaja (kino_ime, karta_id) values ('Farmco', 666);
insert into prodaja (kino_ime, karta_id) values ('Toban', 667);
insert into prodaja (kino_ime, karta_id) values ('Eastlawn', 668);
insert into prodaja (kino_ime, karta_id) values ('Homewood', 669);
insert into prodaja (kino_ime, karta_id) values ('Acker', 670);
insert into prodaja (kino_ime, karta_id) values ('Mayfield', 671);
insert into prodaja (kino_ime, karta_id) values ('Linden', 672);
insert into prodaja (kino_ime, karta_id) values ('Briar Crest', 673);
insert into prodaja (kino_ime, karta_id) values ('Grim', 674);
insert into prodaja (kino_ime, karta_id) values ('Sycamore', 675);
insert into prodaja (kino_ime, karta_id) values ('Service', 676);
insert into prodaja (kino_ime, karta_id) values ('Pepper Wood', 677);
insert into prodaja (kino_ime, karta_id) values ('Rutledge', 678);
insert into prodaja (kino_ime, karta_id) values ('Mandrake', 679);
insert into prodaja (kino_ime, karta_id) values ('Starling', 680);
insert into prodaja (kino_ime, karta_id) values ('Thompson', 681);
insert into prodaja (kino_ime, karta_id) values ('Melody', 682);
insert into prodaja (kino_ime, karta_id) values ('Ridgeview', 683);
insert into prodaja (kino_ime, karta_id) values ('Bartelt', 684);
insert into prodaja (kino_ime, karta_id) values ('Eliot', 685);
insert into prodaja (kino_ime, karta_id) values ('Fisk', 686);
insert into prodaja (kino_ime, karta_id) values ('Hollow Ridge', 687);
insert into prodaja (kino_ime, karta_id) values ('Lindbergh', 688);
insert into prodaja (kino_ime, karta_id) values ('David', 689);
insert into prodaja (kino_ime, karta_id) values ('Lunder', 690);
insert into prodaja (kino_ime, karta_id) values ('Loftsgordon', 691);
insert into prodaja (kino_ime, karta_id) values ('Novick', 692);
insert into prodaja (kino_ime, karta_id) values ('Old Gate', 693);
insert into prodaja (kino_ime, karta_id) values ('Killdeer', 694);
insert into prodaja (kino_ime, karta_id) values ('Memorial', 695);
insert into prodaja (kino_ime, karta_id) values ('Sutteridge', 696);
insert into prodaja (kino_ime, karta_id) values ('Heath', 697);
insert into prodaja (kino_ime, karta_id) values ('Longview', 698);
insert into prodaja (kino_ime, karta_id) values ('Declaration', 699);
insert into prodaja (kino_ime, karta_id) values ('Namekagon', 700);
insert into prodaja (kino_ime, karta_id) values ('Eggendart', 701);
insert into prodaja (kino_ime, karta_id) values ('Fisk', 702);
insert into prodaja (kino_ime, karta_id) values ('Fremont', 703);
insert into prodaja (kino_ime, karta_id) values ('Warner', 704);
insert into prodaja (kino_ime, karta_id) values ('Welch', 705);
insert into prodaja (kino_ime, karta_id) values ('Sunnyside', 706);
insert into prodaja (kino_ime, karta_id) values ('Utah', 707);
insert into prodaja (kino_ime, karta_id) values ('Westend', 708);
insert into prodaja (kino_ime, karta_id) values ('Rockefeller', 709);
insert into prodaja (kino_ime, karta_id) values ('Manley', 710);
insert into prodaja (kino_ime, karta_id) values ('Talmadge', 711);
insert into prodaja (kino_ime, karta_id) values ('Bultman', 712);
insert into prodaja (kino_ime, karta_id) values ('Arapahoe', 713);
insert into prodaja (kino_ime, karta_id) values ('Oxford', 714);
insert into prodaja (kino_ime, karta_id) values ('Coolidge', 715);
insert into prodaja (kino_ime, karta_id) values ('Melby', 716);
insert into prodaja (kino_ime, karta_id) values ('Roth', 717);
insert into prodaja (kino_ime, karta_id) values ('Messerschmidt', 718);
insert into prodaja (kino_ime, karta_id) values ('Nancy', 719);
insert into prodaja (kino_ime, karta_id) values ('Pierstorff', 720);
insert into prodaja (kino_ime, karta_id) values ('Washington', 721);
insert into prodaja (kino_ime, karta_id) values ('La Follette', 722);
insert into prodaja (kino_ime, karta_id) values ('Rowland', 723);
insert into prodaja (kino_ime, karta_id) values ('Elmside', 724);
insert into prodaja (kino_ime, karta_id) values ('Stang', 725);
insert into prodaja (kino_ime, karta_id) values ('Sauthoff', 726);
insert into prodaja (kino_ime, karta_id) values ('2nd', 727);
insert into prodaja (kino_ime, karta_id) values ('Cambridge', 728);
insert into prodaja (kino_ime, karta_id) values ('Carpenter', 729);
insert into prodaja (kino_ime, karta_id) values ('Buena Vista', 730);
insert into prodaja (kino_ime, karta_id) values ('Independence', 731);
insert into prodaja (kino_ime, karta_id) values ('Little Fleur', 732);
insert into prodaja (kino_ime, karta_id) values ('6th', 733);
insert into prodaja (kino_ime, karta_id) values ('North', 734);
insert into prodaja (kino_ime, karta_id) values ('Hintze', 735);
insert into prodaja (kino_ime, karta_id) values ('Bluejay', 736);
insert into prodaja (kino_ime, karta_id) values ('Graceland', 737);
insert into prodaja (kino_ime, karta_id) values ('Eagan', 738);
insert into prodaja (kino_ime, karta_id) values ('Onsgard', 739);
insert into prodaja (kino_ime, karta_id) values ('Old Shore', 740);
insert into prodaja (kino_ime, karta_id) values ('Ilene', 741);
insert into prodaja (kino_ime, karta_id) values ('Sutherland', 742);
insert into prodaja (kino_ime, karta_id) values ('Mariners Cove', 743);
insert into prodaja (kino_ime, karta_id) values ('Sherman', 744);
insert into prodaja (kino_ime, karta_id) values ('West', 745);
insert into prodaja (kino_ime, karta_id) values ('Jana', 746);
insert into prodaja (kino_ime, karta_id) values ('Hansons', 747);
insert into prodaja (kino_ime, karta_id) values ('Debra', 748);
insert into prodaja (kino_ime, karta_id) values ('Hanson', 749);
insert into prodaja (kino_ime, karta_id) values ('Donald', 750);
insert into prodaja (kino_ime, karta_id) values ('Northview', 751);
insert into prodaja (kino_ime, karta_id) values ('Gerald', 752);
insert into prodaja (kino_ime, karta_id) values ('Ridge Oak', 753);
insert into prodaja (kino_ime, karta_id) values ('Swallow', 754);
insert into prodaja (kino_ime, karta_id) values ('Oak', 755);
insert into prodaja (kino_ime, karta_id) values ('Namekagon', 756);
insert into prodaja (kino_ime, karta_id) values ('Straubel', 757);
insert into prodaja (kino_ime, karta_id) values ('Lawn', 758);
insert into prodaja (kino_ime, karta_id) values ('Dixon', 759);
insert into prodaja (kino_ime, karta_id) values ('Corben', 760);
insert into prodaja (kino_ime, karta_id) values ('Sycamore', 761);
insert into prodaja (kino_ime, karta_id) values ('Raven', 762);
insert into prodaja (kino_ime, karta_id) values ('Golf Course', 763);
insert into prodaja (kino_ime, karta_id) values ('Toban', 764);
insert into prodaja (kino_ime, karta_id) values ('Green Ridge', 765);
insert into prodaja (kino_ime, karta_id) values ('Towne', 766);
insert into prodaja (kino_ime, karta_id) values ('Waywood', 767);
insert into prodaja (kino_ime, karta_id) values ('Buena Vista', 768);
insert into prodaja (kino_ime, karta_id) values ('Swallow', 769);
insert into prodaja (kino_ime, karta_id) values ('Brentwood', 770);
insert into prodaja (kino_ime, karta_id) values ('Porter', 771);
insert into prodaja (kino_ime, karta_id) values ('Veith', 772);
insert into prodaja (kino_ime, karta_id) values ('Hollow Ridge', 773);
insert into prodaja (kino_ime, karta_id) values ('Evergreen', 774);
insert into prodaja (kino_ime, karta_id) values ('Colorado', 775);
insert into prodaja (kino_ime, karta_id) values ('Susan', 776);
insert into prodaja (kino_ime, karta_id) values ('Fisk', 777);
insert into prodaja (kino_ime, karta_id) values ('Stoughton', 778);
insert into prodaja (kino_ime, karta_id) values ('Oxford', 779);
insert into prodaja (kino_ime, karta_id) values ('Lawn', 780);
insert into prodaja (kino_ime, karta_id) values ('Nelson', 781);
insert into prodaja (kino_ime, karta_id) values ('Alpine', 782);
insert into prodaja (kino_ime, karta_id) values ('Fallview', 783);
insert into prodaja (kino_ime, karta_id) values ('Vidon', 784);
insert into prodaja (kino_ime, karta_id) values ('Knutson', 785);
insert into prodaja (kino_ime, karta_id) values ('Moose', 786);
insert into prodaja (kino_ime, karta_id) values ('Anzinger', 787);
insert into prodaja (kino_ime, karta_id) values ('Melody', 788);
insert into prodaja (kino_ime, karta_id) values ('Myrtle', 789);
insert into prodaja (kino_ime, karta_id) values ('Melody', 790);
insert into prodaja (kino_ime, karta_id) values ('Comanche', 791);
insert into prodaja (kino_ime, karta_id) values ('Dahle', 792);
insert into prodaja (kino_ime, karta_id) values ('Bowman', 793);
insert into prodaja (kino_ime, karta_id) values ('Sundown', 794);
insert into prodaja (kino_ime, karta_id) values ('Westerfield', 795);
insert into prodaja (kino_ime, karta_id) values ('Oak', 796);
insert into prodaja (kino_ime, karta_id) values ('Anhalt', 797);
insert into prodaja (kino_ime, karta_id) values ('Namekagon', 798);
insert into prodaja (kino_ime, karta_id) values ('Eastlawn', 799);
insert into prodaja (kino_ime, karta_id) values ('Spohn', 800);
insert into prodaja (kino_ime, karta_id) values ('Lighthouse Bay', 801);
insert into prodaja (kino_ime, karta_id) values ('Sundown', 802);
insert into prodaja (kino_ime, karta_id) values ('Heath', 803);
insert into prodaja (kino_ime, karta_id) values ('Reindahl', 804);
insert into prodaja (kino_ime, karta_id) values ('Thackeray', 805);
insert into prodaja (kino_ime, karta_id) values ('Haas', 806);
insert into prodaja (kino_ime, karta_id) values ('6th', 807);
insert into prodaja (kino_ime, karta_id) values ('Bayside', 808);
insert into prodaja (kino_ime, karta_id) values ('Mitchell', 809);
insert into prodaja (kino_ime, karta_id) values ('Green', 810);
insert into prodaja (kino_ime, karta_id) values ('Beilfuss', 811);
insert into prodaja (kino_ime, karta_id) values ('Mallory', 812);
insert into prodaja (kino_ime, karta_id) values ('Sauthoff', 813);
insert into prodaja (kino_ime, karta_id) values ('Thompson', 814);
insert into prodaja (kino_ime, karta_id) values ('Corry', 815);
insert into prodaja (kino_ime, karta_id) values ('Hallows', 816);
insert into prodaja (kino_ime, karta_id) values ('Sycamore', 817);
insert into prodaja (kino_ime, karta_id) values ('Vermont', 818);
insert into prodaja (kino_ime, karta_id) values ('David', 819);
insert into prodaja (kino_ime, karta_id) values ('Dawn', 820);
insert into prodaja (kino_ime, karta_id) values ('Laurel', 821);
insert into prodaja (kino_ime, karta_id) values ('Buena Vista', 822);
insert into prodaja (kino_ime, karta_id) values ('Susan', 823);
insert into prodaja (kino_ime, karta_id) values ('Lyons', 824);
insert into prodaja (kino_ime, karta_id) values ('Anzinger', 825);
insert into prodaja (kino_ime, karta_id) values ('Eagan', 826);
insert into prodaja (kino_ime, karta_id) values ('La Follette', 827);
insert into prodaja (kino_ime, karta_id) values ('Welch', 828);
insert into prodaja (kino_ime, karta_id) values ('Dixon', 829);
insert into prodaja (kino_ime, karta_id) values ('Manley', 830);
insert into prodaja (kino_ime, karta_id) values ('Carioca', 831);
insert into prodaja (kino_ime, karta_id) values ('Norway Maple', 832);
insert into prodaja (kino_ime, karta_id) values ('Basil', 833);
insert into prodaja (kino_ime, karta_id) values ('Tennessee', 834);
insert into prodaja (kino_ime, karta_id) values ('Norway Maple', 835);
insert into prodaja (kino_ime, karta_id) values ('Stephen', 836);
insert into prodaja (kino_ime, karta_id) values ('Ridgeview', 837);
insert into prodaja (kino_ime, karta_id) values ('Barnett', 838);
insert into prodaja (kino_ime, karta_id) values ('Crest Line', 839);
insert into prodaja (kino_ime, karta_id) values ('Goodland', 840);
insert into prodaja (kino_ime, karta_id) values ('Anniversary', 841);
insert into prodaja (kino_ime, karta_id) values ('Maple', 842);
insert into prodaja (kino_ime, karta_id) values ('Erie', 843);
insert into prodaja (kino_ime, karta_id) values ('Dennis', 844);
insert into prodaja (kino_ime, karta_id) values ('Jana', 845);
insert into prodaja (kino_ime, karta_id) values ('Meadow Valley', 846);
insert into prodaja (kino_ime, karta_id) values ('Bay', 847);
insert into prodaja (kino_ime, karta_id) values ('Redwing', 848);
insert into prodaja (kino_ime, karta_id) values ('Monument', 849);
insert into prodaja (kino_ime, karta_id) values ('Moulton', 850);
insert into prodaja (kino_ime, karta_id) values ('Katie', 851);
insert into prodaja (kino_ime, karta_id) values ('Drewry', 852);
insert into prodaja (kino_ime, karta_id) values ('Kim', 853);
insert into prodaja (kino_ime, karta_id) values ('Lake View', 854);
insert into prodaja (kino_ime, karta_id) values ('Village Green', 855);
insert into prodaja (kino_ime, karta_id) values ('Derek', 856);
insert into prodaja (kino_ime, karta_id) values ('Michigan', 857);
insert into prodaja (kino_ime, karta_id) values ('Lyons', 858);
insert into prodaja (kino_ime, karta_id) values ('Derek', 859);
insert into prodaja (kino_ime, karta_id) values ('Karstens', 860);
insert into prodaja (kino_ime, karta_id) values ('Meadow Ridge', 861);
insert into prodaja (kino_ime, karta_id) values ('Jenifer', 862);
insert into prodaja (kino_ime, karta_id) values ('Karstens', 863);
insert into prodaja (kino_ime, karta_id) values ('Pepper Wood', 864);
insert into prodaja (kino_ime, karta_id) values ('Dahle', 865);
insert into prodaja (kino_ime, karta_id) values ('Cordelia', 866);
insert into prodaja (kino_ime, karta_id) values ('Reindahl', 867);
insert into prodaja (kino_ime, karta_id) values ('Algoma', 868);
insert into prodaja (kino_ime, karta_id) values ('Jana', 869);
insert into prodaja (kino_ime, karta_id) values ('Shelley', 870);
insert into prodaja (kino_ime, karta_id) values ('Rieder', 871);
insert into prodaja (kino_ime, karta_id) values ('Heath', 872);
insert into prodaja (kino_ime, karta_id) values ('Ohio', 873);
insert into prodaja (kino_ime, karta_id) values ('Columbus', 874);
insert into prodaja (kino_ime, karta_id) values ('Hintze', 875);
insert into prodaja (kino_ime, karta_id) values ('Fairview', 876);
insert into prodaja (kino_ime, karta_id) values ('Fisk', 877);
insert into prodaja (kino_ime, karta_id) values ('Roth', 878);
insert into prodaja (kino_ime, karta_id) values ('Doe Crossing', 879);
insert into prodaja (kino_ime, karta_id) values ('Ridgeview', 880);
insert into prodaja (kino_ime, karta_id) values ('Hauk', 881);
insert into prodaja (kino_ime, karta_id) values ('Golf', 882);
insert into prodaja (kino_ime, karta_id) values ('Melody', 883);
insert into prodaja (kino_ime, karta_id) values ('Dexter', 884);
insert into prodaja (kino_ime, karta_id) values ('Spohn', 885);
insert into prodaja (kino_ime, karta_id) values ('Pond', 886);
insert into prodaja (kino_ime, karta_id) values ('Farwell', 887);
insert into prodaja (kino_ime, karta_id) values ('Manitowish', 888);
insert into prodaja (kino_ime, karta_id) values ('Warbler', 889);
insert into prodaja (kino_ime, karta_id) values ('Packers', 890);
insert into prodaja (kino_ime, karta_id) values ('Reinke', 891);
insert into prodaja (kino_ime, karta_id) values ('Twin Pines', 892);
insert into prodaja (kino_ime, karta_id) values ('Larry', 893);
insert into prodaja (kino_ime, karta_id) values ('Dixon', 894);
insert into prodaja (kino_ime, karta_id) values ('Lyons', 895);
insert into prodaja (kino_ime, karta_id) values ('Londonderry', 896);
insert into prodaja (kino_ime, karta_id) values ('Lunder', 897);
insert into prodaja (kino_ime, karta_id) values ('Lindbergh', 898);
insert into prodaja (kino_ime, karta_id) values ('Corben', 899);
insert into prodaja (kino_ime, karta_id) values ('Hooker', 900);
insert into prodaja (kino_ime, karta_id) values ('Leroy', 901);
insert into prodaja (kino_ime, karta_id) values ('Transport', 902);
insert into prodaja (kino_ime, karta_id) values ('Fremont', 903);
insert into prodaja (kino_ime, karta_id) values ('Grasskamp', 904);
insert into prodaja (kino_ime, karta_id) values ('Lakewood Gardens', 905);
insert into prodaja (kino_ime, karta_id) values ('School', 906);
insert into prodaja (kino_ime, karta_id) values ('Mallard', 907);
insert into prodaja (kino_ime, karta_id) values ('La Follette', 908);
insert into prodaja (kino_ime, karta_id) values ('Gerald', 909);
insert into prodaja (kino_ime, karta_id) values ('Valley Edge', 910);
insert into prodaja (kino_ime, karta_id) values ('Hauk', 911);
insert into prodaja (kino_ime, karta_id) values ('Carpenter', 912);
insert into prodaja (kino_ime, karta_id) values ('5th', 913);
insert into prodaja (kino_ime, karta_id) values ('Dunning', 914);
insert into prodaja (kino_ime, karta_id) values ('Schmedeman', 915);
insert into prodaja (kino_ime, karta_id) values ('Londonderry', 916);
insert into prodaja (kino_ime, karta_id) values ('Tony', 917);
insert into prodaja (kino_ime, karta_id) values ('Rockefeller', 918);
insert into prodaja (kino_ime, karta_id) values ('Corben', 919);
insert into prodaja (kino_ime, karta_id) values ('Bunting', 920);
insert into prodaja (kino_ime, karta_id) values ('Harbort', 921);
insert into prodaja (kino_ime, karta_id) values ('Forest Run', 922);
insert into prodaja (kino_ime, karta_id) values ('Lindbergh', 923);
insert into prodaja (kino_ime, karta_id) values ('Crest Line', 924);
insert into prodaja (kino_ime, karta_id) values ('Crescent Oaks', 925);
insert into prodaja (kino_ime, karta_id) values ('Stephen', 926);
insert into prodaja (kino_ime, karta_id) values ('Monterey', 927);
insert into prodaja (kino_ime, karta_id) values ('Northridge', 928);
insert into prodaja (kino_ime, karta_id) values ('Everett', 929);
insert into prodaja (kino_ime, karta_id) values ('Clarendon', 930);
insert into prodaja (kino_ime, karta_id) values ('Dexter', 931);
insert into prodaja (kino_ime, karta_id) values ('Corben', 932);
insert into prodaja (kino_ime, karta_id) values ('Helena', 933);
insert into prodaja (kino_ime, karta_id) values ('Maple', 934);
insert into prodaja (kino_ime, karta_id) values ('Daystar', 935);
insert into prodaja (kino_ime, karta_id) values ('Southridge', 936);
insert into prodaja (kino_ime, karta_id) values ('Bowman', 937);
insert into prodaja (kino_ime, karta_id) values ('Clove', 938);
insert into prodaja (kino_ime, karta_id) values ('Menomonie', 939);
insert into prodaja (kino_ime, karta_id) values ('Laurel', 940);
insert into prodaja (kino_ime, karta_id) values ('Hauk', 941);
insert into prodaja (kino_ime, karta_id) values ('Riverside', 942);
insert into prodaja (kino_ime, karta_id) values ('American', 943);
insert into prodaja (kino_ime, karta_id) values ('Del Mar', 944);
insert into prodaja (kino_ime, karta_id) values ('Goodland', 945);
insert into prodaja (kino_ime, karta_id) values ('Bellgrove', 946);
insert into prodaja (kino_ime, karta_id) values ('Gateway', 947);
insert into prodaja (kino_ime, karta_id) values ('Raven', 948);
insert into prodaja (kino_ime, karta_id) values ('Tennyson', 949);
insert into prodaja (kino_ime, karta_id) values ('Paget', 950);
insert into prodaja (kino_ime, karta_id) values ('Stone Corner', 951);
insert into prodaja (kino_ime, karta_id) values ('Sherman', 952);
insert into prodaja (kino_ime, karta_id) values ('Del Sol', 953);
insert into prodaja (kino_ime, karta_id) values ('Nobel', 954);
insert into prodaja (kino_ime, karta_id) values ('Spenser', 955);
insert into prodaja (kino_ime, karta_id) values ('Hooker', 956);
insert into prodaja (kino_ime, karta_id) values ('Lighthouse Bay', 957);
insert into prodaja (kino_ime, karta_id) values ('Village Green', 958);
insert into prodaja (kino_ime, karta_id) values ('Cambridge', 959);
insert into prodaja (kino_ime, karta_id) values ('Tony', 960);
insert into prodaja (kino_ime, karta_id) values ('Northwestern', 961);
insert into prodaja (kino_ime, karta_id) values ('Dexter', 962);
insert into prodaja (kino_ime, karta_id) values ('Spenser', 963);
insert into prodaja (kino_ime, karta_id) values ('Prairie Rose', 964);
insert into prodaja (kino_ime, karta_id) values ('Reinke', 965);
insert into prodaja (kino_ime, karta_id) values ('Briar Crest', 966);
insert into prodaja (kino_ime, karta_id) values ('Kensington', 967);
insert into prodaja (kino_ime, karta_id) values ('Tennessee', 968);
insert into prodaja (kino_ime, karta_id) values ('Shopko', 969);
insert into prodaja (kino_ime, karta_id) values ('Hallows', 970);
insert into prodaja (kino_ime, karta_id) values ('Little Fleur', 971);
insert into prodaja (kino_ime, karta_id) values ('Truax', 972);
insert into prodaja (kino_ime, karta_id) values ('Dakota', 973);
insert into prodaja (kino_ime, karta_id) values ('Kings', 974);
insert into prodaja (kino_ime, karta_id) values ('Melody', 975);
insert into prodaja (kino_ime, karta_id) values ('Canary', 976);
insert into prodaja (kino_ime, karta_id) values ('Clyde Gallagher', 977);
insert into prodaja (kino_ime, karta_id) values ('Ridgeway', 978);
insert into prodaja (kino_ime, karta_id) values ('Logan', 979);
insert into prodaja (kino_ime, karta_id) values ('Walton', 980);
insert into prodaja (kino_ime, karta_id) values ('Kipling', 981);
insert into prodaja (kino_ime, karta_id) values ('Independence', 982);
insert into prodaja (kino_ime, karta_id) values ('Lillian', 983);
insert into prodaja (kino_ime, karta_id) values ('Eastlawn', 984);
insert into prodaja (kino_ime, karta_id) values ('Prairie Rose', 985);
insert into prodaja (kino_ime, karta_id) values ('Mitchell', 986);
insert into prodaja (kino_ime, karta_id) values ('Hintze', 987);
insert into prodaja (kino_ime, karta_id) values ('Arizona', 988);
insert into prodaja (kino_ime, karta_id) values ('Hanover', 989);
insert into prodaja (kino_ime, karta_id) values ('Continental', 990);
insert into prodaja (kino_ime, karta_id) values ('Washington', 991);
insert into prodaja (kino_ime, karta_id) values ('Pennsylvania', 992);
insert into prodaja (kino_ime, karta_id) values ('Kedzie', 993);
insert into prodaja (kino_ime, karta_id) values ('Oxford', 994);
insert into prodaja (kino_ime, karta_id) values ('Hanson', 995);
insert into prodaja (kino_ime, karta_id) values ('Arizona', 996);
insert into prodaja (kino_ime, karta_id) values ('Monument', 997);
insert into prodaja (kino_ime, karta_id) values ('Mallard', 998);
insert into prodaja (kino_ime, karta_id) values ('Pearson', 999);
insert into prodaja (kino_ime, karta_id) values ('Sloan', 1000);
